/* =====================================================================
   CYBORG-LABOR · arten5.js · Inhalte 2.0, zweiter Schub (Teil 3)
   Neon-Arkade, Plüsch, Bernstein, Dino-Fabrik, Kaufhaus, Funkturm und
   Magnetbahn bekommen je sechs Fische und sechs Insekten dazu.
   ===================================================================== */
(()=>{
  const{planet,fish,bug}=ARTEN3;const{stripes,dots,grid,patch,glowDots}=NH.A2;

  /* ================= Neon-Arkade ================= */
  planet('neonarkade');
  fish('neonkardinal','Neon-Kardinal','Cardinal tetra','m','teich','S','nacht',1,170,'Sein blauer Streifen leuchtet wie eine Neonröhre.','Its blue stripe glows like a neon tube.','Der blaue Streifen des Kardinalsalmlers spiegelt Licht. So finden sich die Fische im dunklen Wasser im Schwarm wieder.','The blue stripe of the cardinal tetra reflects light. That helps the fish find each other in a school in dark water.',{H:.15,L:.45,back:'#2a6aff',belly:'#ff3a4a',tail:'fork',dorsal:'std',pat:stripes('#45e0ff',1,true)});
  fish('leuchthai','Leuchthai','Lanternshark','m','meer','M','nacht',4,2100,'Sein Bauch leuchtet im Dunkeln.','Its belly glows in the dark.','Laternenhaie haben Leuchtzellen am Bauch. Von unten sieht man sie dadurch vor dem hellen Wasser kaum.','Lanternsharks have light cells on their belly. From below, that makes them hard to see against the bright water.',{H:.13,L:.8,back:'#2a2a3a',belly:'#45e0ff',tail:'moon',dorsal:'tri',pat:glowDots('#7ff0ff')});
  fish('mandarinfisch','Mandarinfisch','Mandarinfish','m','meer','S','nacht',3,1100,'Er ist so bunt wie ein Spielautomat.','It is as colourful as an arcade machine.','Der Mandarinfisch hat keine Schuppen. Stattdessen schützt ihn eine dicke Schleimschicht, die Räubern nicht schmeckt.','The mandarinfish has no scales. Instead, it is protected by a thick layer of slime that predators do not like the taste of.',{H:.2,L:.5,W:1.1,back:'#3a7aff',belly:'#ff8a2a',tail:'round',dorsal:'hi',pat:(x,w,h)=>{x.strokeStyle='#ff8a2a';x.lineWidth=7;for(let i=0;i<7;i++){x.beginPath();x.moveTo(0,i*h/6);x.bezierCurveTo(w*.3,i*h/6+30,w*.7,i*h/6-30,w,i*h/6);x.stroke()}}});
  fish('taschenlampenfisch','Taschenlampenfisch','Flashlight fish','m','meer','S','nacht',3,980,'Unter seinen Augen hat er zwei kleine Lampen.','It has two little lamps under its eyes.','Der Taschenlampenfisch hat unter den Augen Leuchtorgane. Er kann sie mit einem Lid an- und ausknipsen.','The flashlight fish has light organs under its eyes. It can switch them on and off with a lid.',{H:.2,L:.5,back:'#1a1a2a',belly:'#3a3a4a',tail:'fork',dorsal:'std',eye:.07,pat:(x,w,h)=>{x.fillStyle='#c8fff0';x.fillRect(w*.13,h*.55,18,10);x.fillRect(w*.87-18,h*.55,18,10)}});
  fish('arcademuraene','Arcade-Muräne','Arcade moray','f','meer','L','nacht',3,1150,'Sie hat mich angeschaut wie ein Endgegner.','It looked at me like a final boss.','Muränen haben im Hals ein zweites Kiefer. Damit ziehen sie die Beute nach innen.','Moray eels have a second jaw in their throat. They use it to pull their food inside.',{H:.1,L:1.1,back:'#7a3aff',belly:'#ffd23f',tail:'none',dorsal:'long',dz:.1,ds:2.4,anal:'long',pect:false,pat:dots('#ffd23f',30,6)});
  fish('bonuspunktbarsch','Bonuspunkt-Barsch','Bonus-spot bass','m','teich','M','tag',2,440,'Auf seinem Schwanz hat er einen Bonuspunkt.','It has a bonus spot on its tail.','Der Pfauenaugenbarsch hat einen Augenfleck am Schwanz. Angreifer schnappen so oft nach dem falschen Ende.','The peacock bass has an eyespot on its tail, so attackers often snap at the wrong end.',{H:.2,L:.75,back:'#7ab83a',belly:'#ffd23f',fin:'#ff5a2a',tail:'round',dorsal:'spiky',pat:stripes('#2a3a1a',3)});
  bug('scheinwerferkaefer','Scheinwerfer-Schnellkäfer','Headlight beetle','m','luft','nacht',3,950,'Er hat zwei grüne Scheinwerfer auf dem Rücken.','It has two green headlights on its back.','Manche Schnellkäfer in Amerika haben zwei leuchtende Flecken auf dem Rücken, wie Scheinwerfer an einem Auto.','Some click beetles in America have two glowing spots on their back, like the headlights of a car.',['be','#3a3028',{len:1.3,s:.85,glow:'#7fff6a'}]);
  bug('uvskorpion','UV-Skorpion','UV scorpion','m','stein','nacht',4,2000,'Unter UV-Licht leuchtet er blaugrün.','Under UV light it glows blue-green.','Skorpione leuchten unter UV-Licht blaugrün. Warum, wissen die Forschenden noch nicht genau.','Scorpions glow blue-green under UV light. Scientists still do not know exactly why.',['kr','#45e0c8',{claw:.07}]);
  bug('leuchttausendfuesser','Leucht-Tausendfüsser','Glowing millipede','m','boden','nacht',3,880,'Er leuchtet im Dunkeln wie ein Leuchtstab.','It glows in the dark like a glow stick.','Ein Tausendfüsser aus Kalifornien leuchtet nachts grün. So warnt er Tiere, die ihn fressen wollen.','A millipede from California glows green at night. That warns animals that want to eat it.',['ra',['#7fff6a','#5ae84a'],8]);
  bug('atlasspinner','Atlasspinner','Atlas moth','m','luft','nacht',5,4200,'Seine Flügel sind so gross wie ein Teller.','Its wings are as big as a plate.','Der Atlasspinner ist einer der grössten Falter der Welt. Als Falter hat er keinen Mund und frisst nichts mehr.','The Atlas moth is one of the largest moths in the world. As a moth it has no mouth and eats nothing at all.',['bf','#c8602a','#a8502a','#6a3a2a',{fs:.75,hs:.62}]);
  bug('discospinne','Disco-Spinne','Disco spider','f','baum','nacht',4,1900,'Ihr Hinterleib glitzert wie eine Discokugel.','Its body sparkles like a disco ball.','Manche Spinnen haben silberne Flecken am Hinterleib, die glänzen wie kleine Spiegel.','Some spiders have silver patches on their body that shine like tiny mirrors.',['sp','#e8f4ff',{body:.13}]);
  bug('smaragdlibelle','Smaragdlibelle','Emerald dragonfly','f','luft','tag',2,420,'Ihre Augen leuchten grün wie Smaragde.','Its eyes shine green like emeralds.','Smaragdlibellen haben leuchtend grüne Augen. Sie fliegen oft lange Strecken an Ufern entlang.','Emerald dragonflies have bright green eyes. They often fly long distances along riverbanks.',['li','#1a8a5a','#e8fff4']);

  /* ================= Plüsch ================= */
  planet('pluesch');
  fish('plueschkugelfisch','Plüsch-Kugelfisch','Plush pufferfish','m','meer','S','tag',2,380,'Er ist rund und weich wie ein Kissen.','It is round and soft like a cushion.','Kugelfische pumpen sich bei Gefahr mit Wasser auf, bis sie rund wie ein Ball sind.','When in danger, pufferfish pump themselves full of water until they are as round as a ball.',{H:.34,L:.45,W:1,back:'#ffb8d0',belly:'#fff4f8',tail:'round',dorsal:'std',pat:dots('#ff7aa5',18,5)});
  fish('kuschelwels','Kuschelwels','Upside-down catfish','m','teich','M','nacht',2,460,'Er schwimmt gern auf dem Rücken, wie beim Kuscheln.','It likes to swim on its back, as if it is cuddling.','Der Rückenschwimmer-Wels aus Afrika schwimmt oft verkehrt herum und frisst Algen von der Unterseite von Blättern.','The upside-down catfish from Africa often swims upside down and eats algae from the underside of leaves.',{H:.18,L:.6,back:'#c8a080',belly:'#4a3a2a',tail:'fork',dorsal:'tri',pat:dots('#6a4a2a',20,6)});
  fish('wollhandkrabbe','Wollhandkrabbe','Mitten crab','f','fluss','M','nacht',3,900,'Sie trägt Fäustlinge aus Wolle an den Scheren.','It wears woolly mittens on its claws.','Die Wollhandkrabbe hat pelzige Scheren, die aussehen wie Handschuhe. Sie wandert zum Eierlegen ins Meer.','The mitten crab has furry claws that look like gloves. It travels to the sea to lay its eggs.',{H:.14,L:.45,W:2,back:'#8a7a5a',belly:'#e8dcc0',tail:'none',dorsal:'none',anal:false,ps:2.2,eyeY:.8});
  fish('kissenstern','Kissenstern','Cushion star','m','meer','M','immer',2,400,'Er ist dick und weich wie ein kleines Kissen.','It is chunky and soft like a little cushion.','Seesterne haben an der Spitze jedes Arms ein kleines Auge. Damit sehen sie hell und dunkel.','Starfish have a tiny eye at the tip of each arm. With it they can tell light from dark.',{H:.12,L:.45,W:2.6,back:'#ff8a3a',belly:'#ffd8a0',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,pat:dots('#ffd23f',26,6)});
  fish('fransenanglerfisch','Fransen-Anglerfisch','Hairy frogfish','m','meer','M','nacht',4,2000,'Er ist überall voller weicher Fransen.','It is covered all over in soft fringes.','Der Fransen-Anglerfisch ist mit haarähnlichen Fortsätzen bedeckt. Er lockt Beute mit einem kleinen Köder auf der Stirn an.','The hairy frogfish is covered in hair-like growths. It lures prey with a little bait on its forehead.',{H:.3,L:.5,W:1.1,back:'#e8c890',belly:'#f4e4c0',tail:'round',dorsal:'spiky',pat:stripes('#a07a4a',14,true)});
  fish('fetzenseedrache','Fetzen-Seedrache','Leafy seadragon','m','meer','L','tag',5,4600,'Er sieht aus wie ein Stück Seetang mit Gesicht.','It looks like a piece of seaweed with a face.','Der Fetzen-Seedrache hat blattartige Lappen am ganzen Körper. Im Seetang ist er fast unsichtbar.','The leafy seadragon has leaf-like flaps all over its body. In seaweed it is almost invisible.',{H:.1,L:.9,back:'#c8a040',belly:'#f4e0a0',tail:'none',dorsal:'spiky',ds:1.6,anal:'spiky',ps:1.8,beak:{len:.18,r:.025}});
  bug('pelzbiene','Pelzbiene','Hairy-footed flower bee','f','blume','tag',2,330,'Sie ist flauschig wie ein Wollknäuel.','It is as fluffy as a ball of wool.','Pelzbienen fliegen schon früh im Frühling. Ihr dichter Pelz hält sie warm.','Hairy-footed flower bees fly very early in spring. Their thick fur keeps them warm.',['hu','#c8a070','#a08050',{s:.9}]);
  bug('pudelmotte','Pudelmotte','Poodle moth','f','luft','nacht',4,2300,'Sie sieht aus wie ein kleiner Pudel mit Flügeln.','It looks like a tiny poodle with wings.','Die Pudelmotte wurde erst 2009 auf einem Foto entdeckt. Man weiss bis heute sehr wenig über sie.','The poodle moth was only discovered in a photo in 2009. Very little is known about it even today.',['hu','#fffdf4','#f4ecdc',{s:1}]);
  bug('wolllaus','Wolllaus','Woolly aphid','f','baum','immer',1,140,'Sie trägt einen weissen Wollmantel.','It wears a white woolly coat.','Wollläuse bedecken sich mit weissen Wachsfäden. Das sieht aus wie ein kleiner Wollmantel.','Woolly aphids cover themselves with white wax threads. It looks like a little woolly coat.',['hu','#f8f8f4','#e8e8e0',{s:.6}]);
  bug('pelzkaefer','Pelzkäfer','Fur beetle','m','boden','tag',1,160,'Er knabbert am liebsten an Wolle.','It likes to nibble on wool best.','Die Larven des Pelzkäfers fressen Wolle, Federn und Fell. Die Käfer selbst besuchen gern Blüten.','Fur beetle larvae eat wool, feathers and fur. The beetles themselves like to visit flowers.',['be','#2a2224',{s:.75,key:'pelz',pat:dots('#f4f0e8',3,10)}]);
  bug('teddybaerbiene','Teddybär-Biene','Teddy bear bee','f','blume','tag',3,900,'Sie ist golden und flauschig wie ein Teddy.','It is golden and fluffy like a teddy.','Die Teddybär-Biene aus Australien ist mit goldbraunem Pelz bedeckt. Nachts beisst sie sich zum Schlafen an einem Stängel fest.','The teddy bear bee from Australia is covered in golden brown fur. At night it holds onto a stem with its jaws to sleep.',['hu','#e8a040','#c8803a',{s:1.05}]);
  bug('hummelschwebfliege','Hummel-Schwebfliege','Bumblebee hoverfly','f','blume','tag',2,360,'Sie sieht aus wie eine Hummel, ist aber eine Fliege.','It looks like a bumblebee, but it is a fly.','Diese Schwebfliege ist pelzig wie eine Hummel. Sie hat aber nur zwei Flügel, Hummeln haben vier.','This hoverfly is furry like a bumblebee. But it has only two wings; bumblebees have four.',['hu','#2a2224','#f4e8c8',{s:.85}]);

  /* ================= Bernstein ================= */
  planet('bernstein');
  fish('bernsteinschnecke','Bernsteinschnecke','Amber snail','f','teich','S','immer',1,140,'Ihr Haus ist durchsichtig wie Bernstein.','Its shell is see-through like amber.','Bernsteinschnecken haben ein dünnes, honigfarbenes Haus. Sie leben gern an Pflanzen am Ufer.','Amber snails have a thin, honey-coloured shell. They like to live on plants along the shore.',{H:.28,L:.42,W:.9,back:'#e8a040',belly:'#ffd890',tail:'none',dorsal:'none',anal:false,pect:false,gloss:1.6,pat:stripes('#c8803a',5,true)});
  fish('honiggurami','Honiggurami','Honey gourami','m','teich','S','tag',2,380,'Er ist gelb wie ein Tropfen Honig.','It is yellow like a drop of honey.','Der Honiggurami ist einer der kleinsten Guramis. Er wird nur etwa vier Zentimeter lang.','The honey gourami is one of the smallest gouramis. It only grows to about four centimetres long.',{H:.24,L:.48,back:'#ffb030',belly:'#fff0c0',tail:'round',dorsal:'long',anal:'long'});
  fish('goldschleie','Goldschleie','Golden tench','f','teich','M','nacht',3,920,'Sie ist glitschig und golden.','It is slippery and golden.','Schleien sind sehr ruhige Fische. Im Winter liegen sie oft still im Schlamm am Grund.','Tench are very calm fish. In winter they often lie still in the mud on the bottom.',{H:.2,L:.7,back:'#e8b030',belly:'#fff0b0',fin:'#e8a020',tail:'round',dorsal:'std',gloss:1.4});
  fish('hornhecht','Hornhecht','Garfish','m','meer','L','tag',2,480,'Er hat einen langen, spitzen Schnabel.','It has a long, pointy beak.','Hornhechte haben grüne Knochen. Das ist ganz natürlich und kommt von einem Farbstoff.','Garfish have green bones. That is completely natural and comes from a colouring substance.',{H:.08,L:1.1,back:'#3a6a8a',belly:'#f0f8ff',tail:'fork',dorsal:'std',dz:.2,beak:{len:.35,r:.025}});
  fish('goldmakrele','Goldmakrele','Mahi-mahi','f','meer','L','tag',3,1150,'Sie glänzt golden, grün und blau.','It shines gold, green and blue.','Goldmakrelen wachsen sehr schnell. In einem Jahr können sie über einen Meter lang werden.','Mahi-mahi grow very fast. In one year they can grow longer than a metre.',{H:.22,L:.9,back:'#2ac87a',belly:'#ffd23f',tail:'fork',dorsal:'long',dz:.05,ds:2.2,pat:dots('#3a8aff',20,5)});
  fish('edelkrebs','Edelkrebs','Noble crayfish','m','fluss','M','nacht',3,1000,'Er hat rote Unterseiten an den Scheren.','It has red undersides on its claws.','Der Edelkrebs kann über 20 Jahre alt werden. Er braucht sauberes Wasser.','The noble crayfish can live for more than 20 years. It needs clean water.',{H:.14,L:.6,W:.9,back:'#6a4a3a',belly:'#e86a4a',tail:'fan',dorsal:'none',anal:false,ps:2.2,arms:2,armL:.9});
  bug('harzbiene','Harzbiene','Stingless bee','f','baum','tag',2,360,'Sie sammelt klebriges Harz statt Honig.','It collects sticky resin instead of honey.','Stachellose Bienen bauen ihre Nester mit Baumharz. Manche dieser Nester findet man später als Bernstein.','Stingless bees build their nests with tree resin. Some of these nests are later found as amber.',['hu','#3a2a1a','#c8803a',{s:.7}]);
  bug('harzwanze','Harzwanze','Resin bug','f','blume','tag',3,880,'Ihre Beine sind ganz klebrig.','Its legs are all sticky.','Harzwanzen schmieren sich Pflanzenharz an die Vorderbeine. Damit fangen sie andere Insekten.','Resin bugs smear plant resin on their front legs. They use it to catch other insects.',['be','#c8502a',{len:1.3,s:.85}]);
  bug('holzwespe','Holzwespe','Horntail','f','baum','tag',3,860,'Sie hat einen langen Legestachel, sticht aber nicht.','It has a long egg-laying tube, but it does not sting.','Holzwespen legen ihre Eier ins Holz von Nadelbäumen. Ihr langer Legebohrer ist kein Stachel.','Horntails lay their eggs in the wood of conifers. Their long egg-laying tube is not a stinger.',['li','#2a2224','#ffd890',{len:.6,ws:.15,tail:true,two:true}]);
  bug('kiefernprachtkaefer','Kiefernprachtkäfer','Fire-chaser beetle','m','baum','tag',4,2200,'Er glänzt wie poliertes Metall.','It shines like polished metal.','Manche Prachtkäfer spüren Waldbrände aus vielen Kilometern Entfernung. Im verbrannten Holz legen sie ihre Eier ab.','Some jewel beetles can sense forest fires from many kilometres away. They lay their eggs in the burnt wood.',['be','#1a3a2a',{len:1.4,s:.85,key:'kiefer',pat:dots('#c8a040',10,8)}]);
  bug('kiefernschwaermer','Kiefernschwärmer','Pine hawk-moth','m','luft','nacht',2,420,'Er ist grau gestreift wie Kiefernrinde.','It is striped grey like pine bark.','Schwärmer gehören zu den schnellsten fliegenden Insekten. Sie können in der Luft stehen bleiben.','Hawk-moths are among the fastest flying insects. They can hover in the air.',['bf','#8a8a80','#6a6a60','#5a5a50',{fs:.5,hs:.32,raise:.3}]);
  bug('rindenwanze','Rindenwanze','Flat bark bug','f','baum','nacht',1,150,'Sie ist so flach wie ein Blatt Papier.','It is as flat as a sheet of paper.','Rindenwanzen sind ganz flach und leben unter der Rinde von Bäumen. Dort fressen sie Pilze.','Flat bark bugs are very flat and live under the bark of trees. There they eat fungi.',['be','#6a4a30',{len:1.2,s:.95}]);

  /* ================= Dino-Fabrik ================= */
  planet('dinofabrik');
  fish('gummimosasaurier','Gummi-Mosasaurier','Rubber mosasaur','m','meer','XL','tag',5,4800,'Ein Meeressaurier aus weichem Gummi!','A sea reptile made of soft rubber!','Mosasaurier waren riesige Meeresreptilien. Sie hatten sogar am Gaumen eine zweite Reihe Zähne.','Mosasaurs were huge sea reptiles. They even had a second row of teeth on the roof of their mouth.',{H:.16,L:1.1,back:'#7ac83a',belly:'#e8ffc8',tail:'spade',dorsal:'none',ps:1.8,gloss:1.4,beak:{len:.2,r:.06,flat:1.3,col:'#7ac83a'}});
  fish('megalodonspielzeug','Megalodon-Spielzeug','Toy megalodon','n','meer','XL','nacht',4,3200,'Ein Riesenhai aus Plastik mit weichen Zähnen.','A giant plastic shark with soft teeth.','Der Megalodon war ein riesiger Hai der Urzeit. Seine Zähne waren so gross wie eine Hand.','Megalodon was a giant prehistoric shark. Its teeth were as big as a hand.',{H:.2,L:1.1,back:'#8a9aa8',belly:'#f4f8ff',tail:'moon',dorsal:'tri',ds:1.3,gloss:1.4});
  fish('spritzgusskarpfen','Spritzguss-Karpfen','Moulded carp','m','teich','M','immer',1,190,'An seiner Flosse hängt noch ein Plastik-Stückchen.','There is still a bit of plastic stuck to its fin.','Goldfische und Karpfen sehen mehr Farben als wir. Sie können sogar UV-Licht sehen.','Goldfish and carp see more colours than we do. They can even see UV light.',{H:.24,L:.7,back:'#ff9a45',belly:'#fff0d8',tail:'fork',dorsal:'long',gloss:1.4,pat:grid('#ffb070',36)});
  fish('gummikatzenhai','Gummi-Katzenhai','Rubber catshark','m','meer','M','nacht',2,460,'Er hat Katzenaugen und quietscht.','It has cat eyes and squeaks.','Katzenhaie legen Eier in Hüllen, die man Nixentäschchen nennt. Manchmal findet man sie am Strand.','Catsharks lay eggs in cases called mermaid\'s purses. Sometimes you find them on the beach.',{H:.12,L:.85,back:'#e8b070',belly:'#fff4e0',tail:'spade',dorsal:'std',dz:.3,gloss:1.3,pat:dots('#8a5a2a',24,6)});
  fish('plastikbarrakuda','Plastik-Barrakuda','Plastic barracuda','m','meer','L','tag',3,1050,'Er glänzt silbern wie frisch aus der Form.','It shines silver as if fresh out of the mould.','Junge Barrakudas schwimmen in Schwärmen. Die grossen jagen lieber allein.','Young barracudas swim in schools. The big ones prefer to hunt alone.',{H:.1,L:1.05,back:'#8a9aa8',belly:'#ffffff',tail:'fork',dorsal:'tri',dz:.3,gloss:1.6,pat:stripes('#5a6a78',8)});
  fish('kunststoffmolly','Kunststoff-Molly','Plastic molly','m','teich','S','tag',1,150,'Er ist schwarz und glänzt wie Lack.','It is black and shiny like paint.','Mollys können in Süsswasser und in Salzwasser leben. Das schaffen nur wenige Fische.','Mollies can live in fresh water and in salt water. Very few fish can do that.',{H:.22,L:.48,back:'#1a1a24',belly:'#2a2a34',tail:'round',dorsal:'sail',gloss:1.6});
  bug('lilienhaehnchen','Lilienhähnchen','Lily beetle','n','blume','tag',2,330,'Es hat gequietscht, als ich es gefangen habe!','It squeaked when I caught it!','Das Lilienhähnchen ist knallrot. Wenn man es anfasst, macht es ein leises Quietschgeräusch.','The lily beetle is bright red. When you touch it, it makes a soft squeaking sound.',['be','#ff2a2a',{s:.8,len:1.15}]);
  bug('moertelbiene','Mörtelbiene','Mason bee','f','stein','tag',3,880,'Sie baut ihr Nest aus Lehm und Spucke.','It builds its nest from mud and spit.','Mörtelbienen bauen steinharte Nester aus Lehm, Sand und Speichel an Felsen und Mauern.','Mason bees build rock-hard nests from mud, sand and saliva on rocks and walls.',['hu','#2a2a34','#3a3a44',{s:.85}]);
  bug('toepferwespe','Töpferwespe','Potter wasp','f','blume','tag',3,900,'Sie hat einen winzigen Topf aus Lehm gebaut.','It built a tiny pot out of clay.','Töpferwespen formen aus Lehm kleine Töpfchen. In jedes legen sie ein Ei.','Potter wasps shape little pots out of clay. They lay one egg in each.',['li','#2a2224','#ffd890',{len:.38,ws:.12,two:true}]);
  bug('mehlkaefer','Mehlkäfer','Darkling beetle','m','boden','nacht',1,140,'Er riecht ein bisschen nach Mehl.','It smells a little bit like flour.','Die Larven des Mehlkäfers heissen Mehlwürmer. Forschende haben entdeckt, dass sie sogar Styropor fressen können.','Darkling beetle larvae are called mealworms. Scientists discovered they can even eat styrofoam.',['be','#2a2224',{len:1.25,s:.8}]);
  bug('weberameise','Weberameise','Weaver ant','f','baum','tag',2,380,'Sie näht Blätter zusammen.','It sews leaves together.','Weberameisen kleben Blätter mit Seide zu Nestern zusammen. Die Seide kommt von ihren Larven.','Weaver ants glue leaves together into nests with silk. The silk comes from their larvae.',['ke',['#e8a040','#d8903a','#e8a040'],3,.06]);
  bug('nashornkaefer','Nashornkäfer','Rhinoceros beetle','m','boden','nacht',3,1100,'Er hat ein Horn wie ein Dino.','It has a horn like a dinosaur.','Nashornkäfer gehören zu den stärksten Tieren. Sie können ein Vielfaches ihres eigenen Gewichts tragen.','Rhinoceros beetles are among the strongest animals. They can carry many times their own weight.',['be','#5a3a1a',{horn:true,s:1.15,len:1.2}]);

  /* ================= Kaufhaus ================= */
  planet('kaufhaus');
  fish('schwerttraeger','Schwertträger','Swordtail','m','teich','S','tag',1,170,'Seine Schwanzflosse hat ein langes Schwert.','Its tail fin has a long sword.','Nur die Männchen des Schwertträgers haben die lange Spitze an der Schwanzflosse.','Only male swordtails have the long point on their tail fin.',{H:.17,L:.5,back:'#ff4a2a',belly:'#ffd8c8',tail:'fork',ts:1.4,dorsal:'std'});
  fish('platy','Platy','Platy','m','teich','S','immer',1,140,'Er ist bunt wie ein Bonbon.','It is as colourful as a sweet.','Platys gibt es durch Zucht in vielen Farben. Sie bringen lebende Junge zur Welt.','Through breeding, platies come in many colours. They give birth to live young.',{H:.22,L:.45,back:'#ffb030',belly:'#fff0c8',fin:'#ff4a2a',tail:'round',dorsal:'std'});
  fish('prachtschmerle','Prachtschmerle','Clown loach','f','teich','M','nacht',2,460,'Sie hat geklickt, als ich sie gefangen habe.','It clicked when I caught it.','Prachtschmerlen machen Klickgeräusche. Manchmal legen sie sich zum Ausruhen seitlich hin.','Clown loaches make clicking sounds. Sometimes they lie down on their side to rest.',{H:.18,L:.6,back:'#ff8a2a',belly:'#ffd8a0',fin:'#e8402a',tail:'fork',dorsal:'std',pat:stripes('#1a1a24',3)});
  fish('sumatrabarbe','Sumatrabarbe','Tiger barb','f','teich','S','tag',1,160,'Sie hat Streifen wie ein kleiner Tiger.','It has stripes like a little tiger.','Sumatrabarben sind sehr lebhaft. Sie schwimmen am liebsten in einer grossen Gruppe.','Tiger barbs are very lively. They like to swim in a big group.',{H:.25,L:.45,back:'#ffd890',belly:'#fff8e0',fin:'#ff4a2a',tail:'fork',dorsal:'std',pat:stripes('#1a1a24',4)});
  fish('fensterputzerwels','Fensterputzer-Wels','Bristlenose pleco','m','teich','M','nacht',2,420,'Er hat sich an meinem Eimer festgesaugt.','It sucked onto my bucket.','Antennenwelse haben ein Saugmaul. Damit raspeln sie Algen von Steinen und Aquarienscheiben.','Bristlenose plecos have a sucker mouth. They use it to scrape algae off stones and aquarium glass.',{H:.14,L:.6,W:1.4,back:'#5a5040',belly:'#a09078',tail:'fork',dorsal:'sail',pat:dots('#c8b898',30,4)});
  fish('rotkopfsalmler','Rotkopfsalmler','Rummy-nose tetra','m','teich','S','tag',2,360,'Sein Kopf ist knallrot.','Its head is bright red.','Ist das Wasser nicht gut, wird der rote Kopf des Rotkopfsalmlers blass. So merkt man es schnell.','If the water is not good, the rummy-nose tetra\'s red head turns pale. That way you notice quickly.',{H:.15,L:.45,back:'#c8c8b8',belly:'#f4f4f0',tail:'fork',dorsal:'std',pat:(x,w,h)=>{x.fillStyle='#ff2a2a';x.fillRect(0,0,w*.18,h);x.fillRect(w*.82,0,w*.18,h);x.fillStyle='#1a1a24';x.fillRect(w*.4,h*.3,w*.2,h*.12);x.fillRect(w*.4,h*.6,w*.2,h*.12)}});
  bug('diebkaefer','Diebkäfer','Spider beetle','m','boden','nacht',1,130,'Er sieht aus wie eine winzige Spinne.','It looks like a tiny spider.','Diebkäfer haben lange Beine und einen runden Körper. Darum hält man sie leicht für Spinnen.','Spider beetles have long legs and a round body. That is why people often think they are spiders.',['sp','#a0602a',{body:.09,leg:.18}]);
  bug('speckkaefer','Speckkäfer','Larder beetle','m','boden','tag',2,320,'Er hat einen hellen Gürtel um den Bauch.','It has a pale belt around its middle.','Museen nutzen Speckkäfer, um Tierskelette ganz sauber zu machen. Die Larven fressen alles, was noch daran ist.','Museums use larder beetles to clean animal skeletons. The larvae eat everything that is left on them.',['be','#2a2224',{s:.8,key:'speck',pat:(x,w,h)=>{x.fillStyle='#d8c8a0';x.fillRect(0,h*.55,w,h*.18)}}]);
  bug('fruchtfliege','Fruchtfliege','Fruit fly','f','luft','immer',1,100,'Sie hat rote Augen und liebt Bananen.','It has red eyes and loves bananas.','Fruchtfliegen werden in Laboren sehr viel erforscht. Durch sie weiss man viel über Gene.','Fruit flies are studied a lot in laboratories. Thanks to them, we know a lot about genes.',['li','#c8a060','#f0f8ff',{len:.2,ws:.1,two:true}]);
  bug('trauermuecke','Trauermücke','Fungus gnat','f','luft','nacht',1,110,'Sie wohnt im Blumentopf.','It lives in the flower pot.','Die Larven der Trauermücke leben in feuchter Blumenerde. Die Mücken selbst stechen nicht.','Fungus gnat larvae live in damp potting soil. The gnats themselves do not bite.',['li','#2a2224','#e0e8f0',{len:.22,ws:.09,two:true}]);
  bug('spinnmilbe','Spinnmilbe','Spider mite','f','blume','tag',2,300,'Sie spinnt feine Netze über die Blätter.','It spins fine webs over the leaves.','Spinnmilben sind winzig und rot. Sie spinnen feine Gespinste auf Pflanzen wie kleine Spinnen.','Spider mites are tiny and red. They spin fine webs on plants like little spiders.',['sp','#e83a2a',{body:.1,leg:.1}]);
  bug('schmierlaus','Schmierlaus','Mealybug','f','blume','immer',1,130,'Sie sieht aus wie ein Wattebausch.','It looks like a cotton ball.','Schmierläuse sind mit weissem Wachs bepudert. Sie sitzen gern an Zimmerpflanzen.','Mealybugs are dusted with white wax. They like to sit on houseplants.',['ra',['#f8f4ec','#f0ece4'],4]);

  /* ================= Funkturm ================= */
  planet('funkturm');
  fish('zitterwels','Zitterwels','Electric catfish','m','fluss','L','nacht',4,2000,'Es hat ein bisschen gekribbelt!','It tingled a little!','Der Zitterwels aus Afrika kann elektrische Schläge austeilen. Damit betäubt er seine Beute.','The electric catfish from Africa can give electric shocks. It uses them to stun its prey.',{H:.2,L:.85,back:'#b8a890',belly:'#f0e8d8',tail:'round',dorsal:'none',pat:dots('#4a3a2a',22,6)});
  fish('hammerhai','Hammerhai','Hammerhead shark','m','meer','XL','tag',5,4500,'Sein Kopf ist breit wie ein Hammer.','Its head is as wide as a hammer.','Der breite Kopf des Hammerhais ist voller Sinnesorgane. Damit findet er Beute, die im Sand versteckt ist.','The hammerhead\'s wide head is full of sense organs. It uses them to find prey hidden in the sand.',{H:.16,L:1.1,back:'#7a8a9a',belly:'#f0f4f8',tail:'moon',dorsal:'tri',ds:1.4,beak:{len:.06,r:.09,flat:3.6,col:'#7a8a9a'}});
  fish('fangschreckenkrebs','Fangschreckenkrebs','Mantis shrimp','m','meer','M','tag',4,2200,'Er ist bunter als ein Regenbogen.','It is more colourful than a rainbow.','Fangschreckenkrebse schlagen blitzschnell mit ihren Fangarmen zu. Ihre Augen sehen viel mehr Farben als unsere.','Mantis shrimp strike with lightning speed using their claws. Their eyes see many more colours than ours.',{H:.14,L:.7,back:'#2ac87a',belly:'#ff6fa5',tail:'fan',dorsal:'none',anal:false,eyeY:.8,eye:.065,pat:stripes('#45a0ff',7)});
  fish('rotlachs','Rotlachs','Sockeye salmon','m','fluss','L','tag',3,1200,'Er ist knallrot mit grünem Kopf.','It is bright red with a green head.','Lachse finden den Fluss, in dem sie geschlüpft sind, mit ihrem Geruchssinn wieder. Dort legen sie Eier.','Salmon find the river where they hatched again using their sense of smell. There they lay their eggs.',{H:.2,L:.9,back:'#e8302a',belly:'#ff8a6a',tail:'fork',dorsal:'std',pat:(x,w,h)=>{x.fillStyle='#4a8a3a';x.fillRect(0,0,w*.17,h);x.fillRect(w*.83,0,w*.17,h)}});
  fish('banjowels','Banjowels','Banjo catfish','m','teich','S','nacht',2,380,'Er sieht aus wie ein kleines Banjo.','It looks like a little banjo.','Der Banjowels hat einen breiten Kopf und einen dünnen Schwanz, wie ein Banjo. Er versteckt sich im Laub.','The banjo catfish has a wide head and a thin tail, like a banjo. It hides among fallen leaves.',{H:.16,L:.6,W:1.6,back:'#6a5040',belly:'#a08870',tail:'round',dorsal:'tri',pat:dots('#3a2a1a',20,6)});
  fish('signalkrebs','Signalkrebs','Signal crayfish','m','fluss','M','nacht',2,420,'An seinen Scheren hat er weisse Signalflecken.','It has white signal spots on its claws.','Der Signalkrebs hat weisse Flecken an den Scheren, wie kleine Signalflaggen. Daher hat er seinen Namen.','The signal crayfish has white spots on its claws like little signal flags. That is how it got its name.',{H:.14,L:.6,W:.9,back:'#6a5a4a',belly:'#e8c8b0',tail:'fan',dorsal:'none',anal:false,ps:2.2,arms:2,armL:.9});
  bug('alpenbock','Alpenbock','Rosalia longicorn','m','baum','tag',4,2100,'Er ist himmelblau mit schwarzen Flecken.','It is sky blue with black spots.','Der Alpenbock hat sehr lange Fühler und lebt in alten Buchen. Er ist selten und geschützt.','The Rosalia longicorn has very long antennae and lives in old beech trees. It is rare and protected.',['be','#7ab8e8',{len:1.4,s:.85,ant:.5,key:'alpen',pat:dots('#1a1a24',6,12)}]);
  bug('langhornbiene','Langhornbiene','Long-horned bee','f','blume','tag',3,880,'Ihre Fühler sind so lang wie sie selbst.','Its antennae are as long as it is.','Bei den Männchen der Langhornbiene sind die Fühler fast so lang wie der ganze Körper.','In male long-horned bees, the antennae are almost as long as the whole body.',['hu','#5a4a3a','#c8b090',{s:.8}]);
  bug('wespenspinne','Wespenspinne','Wasp spider','f','blume','tag',2,400,'Sie ist gestreift wie eine Wespe.','It is striped like a wasp.','Die Wespenspinne webt ein Zickzack-Band in ihr Netz. Wozu, ist noch nicht ganz klar.','The wasp spider weaves a zigzag band into its web. What it is for is not yet fully known.',['sp','#ffd23f',{body:.12}]);
  bug('rossameise','Rossameise','Carpenter ant','f','baum','nacht',2,330,'Sie ist eine der grössten Ameisen bei uns.','It is one of the biggest ants around here.','Rossameisen nagen ihre Nester ins Holz von Bäumen. Sie fressen das Holz aber nicht.','Carpenter ants gnaw their nests into tree wood. But they do not eat the wood.',['ke',['#2a2224','#5a2a24','#2a2224'],3,.075]);
  bug('ultraschallbaerenspinner','Ultraschall-Bärenspinner','Tiger moth','m','luft','nacht',4,2000,'Er hat leise geknackt wie ein Funkgerät.','It crackled softly like a radio.','Manche Bärenspinner machen Klickgeräusche im Ultraschall. Damit stören sie das Echolot von Fledermäusen.','Some tiger moths make clicking sounds in ultrasound. That jams the echolocation of bats.',['bf','#f4e8d0','#ff6a3a','#2a2224',{fs:.48,hs:.42}]);
  bug('schillerfalter','Schillerfalter','Purple emperor','m','baum','tag',3,1000,'Je nachdem, wie ich schaue, ist er braun oder lila.','Depending on how I look, it is brown or purple.','Beim Schillerfalter hängt die Farbe vom Blickwinkel ab. Von der Seite schimmert er lila.','The colour of the purple emperor depends on the angle you look from. From the side it shimmers purple.',['bf','#6a4ad8','#4a3a8a','#2a2224']);

  /* ================= Magnetbahn ================= */
  planet('magnetbahn');
  fish('glasaal','Glasaal','Glass eel','m','fluss','S','nacht',2,400,'Er ist durchsichtig wie Glas.','It is see-through like glass.','Junge Aale sind ganz durchsichtig. Man nennt sie Glasaale, wenn sie vom Meer in die Flüsse wandern.','Young eels are completely see-through. They are called glass eels when they travel from the sea into rivers.',{H:.06,L:.8,back:'#e8f4ff',belly:'#f8fcff',tail:'none',dorsal:'long',dz:.15,ds:2,anal:'long',pect:false,gloss:1.8});
  fish('sardine','Sardine','Sardine','f','meer','S','immer',1,120,'Sie war mit tausend Freundinnen unterwegs.','It was travelling with a thousand friends.','Sardinen ziehen in riesigen Schwärmen an der Küste Südafrikas entlang. Den Schwarm sieht man sogar aus Flugzeugen.','Sardines travel along the coast of South Africa in huge schools. You can even see the school from airplanes.',{H:.14,L:.55,back:'#3a6a9a',belly:'#f4f8ff',tail:'fork',dorsal:'std',gloss:1.5});
  fish('wahoo','Wahoo','Wahoo','m','meer','L','tag',4,2400,'Er schoss an mir vorbei wie ein Zug.','It shot past me like a train.','Der Wahoo ist einer der schnellsten Fische im Meer. Er hat einen langen, schlanken Körper.','The wahoo is one of the fastest fish in the sea. It has a long, slim body.',{H:.12,L:1.05,back:'#2a4a8a',belly:'#f0f4ff',tail:'moon',dorsal:'long',dz:.2,pat:stripes('#4a8ad8',10)});
  fish('blauhai','Blauhai','Blue shark','m','meer','XL','tag',4,2800,'Er ist blau wie das tiefe Meer.','It is blue like the deep sea.','Blauhaie schwimmen sehr weite Strecken. Manche durchqueren den ganzen Atlantik.','Blue sharks swim very long distances. Some cross the whole Atlantic.',{H:.13,L:1.1,back:'#2a5ad8',belly:'#f4f8ff',tail:'moon',dorsal:'tri',ps:1.8});
  fish('teufelsrochen','Teufelsrochen','Devil ray','m','meer','L','tag',3,1250,'Er ist aus dem Wasser geflogen!','It flew out of the water!','Teufelsrochen springen in grossen Gruppen aus dem Wasser und landen mit einem lauten Klatschen.','Devil rays leap out of the water in big groups and land with a loud splash.',{H:.08,L:.7,W:2.8,back:'#2a2a3a',belly:'#ffffff',tail:'spade',dorsal:'none',anal:false,arms:2,armL:.4});
  fish('stint','Stint','Smelt','m','fluss','S','nacht',1,140,'Er riecht nach frischer Gurke.','It smells like fresh cucumber.','Stinte riechen nach Gurke. Im Frühjahr wandern sie in grossen Schwärmen die Flüsse hinauf.','Smelt smell like cucumber. In spring they travel up rivers in big schools.',{H:.12,L:.5,back:'#a0b8a8',belly:'#f8fcf8',tail:'fork',dorsal:'std',gloss:1.6});
  bug('bogongfalter','Bogong-Falter','Bogong moth','m','luft','nacht',3,950,'Er findet den Weg mit den Sternen.','It finds its way using the stars.','Bogong-Falter in Australien wandern nachts über tausend Kilometer. Sie orientieren sich an den Sternen.','Bogong moths in Australia travel over a thousand kilometres at night. They find their way using the stars.',['bf','#6a5a4a','#8a7a6a','#3a2a24',{fs:.44,hs:.38}]);
  bug('treiberameise','Treiberameise','Army ant','f','boden','tag',3,880,'Sie läuft in einer langen Reihe wie ein Zug.','It walks in a long line like a train.','Treiberameisen haben kein festes Nest. Sie ziehen in riesigen Kolonnen durch den Wald.','Army ants have no fixed nest. They march through the forest in huge columns.',['ke',['#8a3a1a','#a04a2a','#8a3a1a'],3,.07]);
  bug('goldlaufkaefer','Goldlaufkäfer','Golden ground beetle','m','boden','tag',2,380,'Er rennt so schnell wie ein Schnellzug.','It runs as fast as an express train.','Laufkäfer können nicht gut fliegen, aber sehr schnell rennen. Der Goldlaufkäfer glänzt grün-golden.','Ground beetles cannot fly well, but they run very fast. The golden ground beetle shines green and gold.',['be','#5ac83a',{len:1.25,s:.9,key:'goldlauf',pat:stripes('#c8e040',6,true)}]);
  bug('radspinne','Radspinne','Wheel spider','f','boden','tag',4,2000,'Sie rollt sich wie ein Rad davon.','It rolls away like a wheel.','Eine Spinne aus der Wüste Marokkos macht bei Gefahr Radschläge und rollt so schnell davon.','A spider from the desert of Morocco does cartwheels when in danger and rolls away fast.',['sp','#e8c890',{body:.1,leg:.24}]);
  bug('stromhummel','Strom-Hummel','Static bumblebee','f','blume','tag',2,400,'Ihr Pelz knistert ein bisschen.','Its fur crackles a little.','Hummeln spüren die schwachen elektrischen Felder von Blüten. So merken sie, ob schon jemand Nektar geholt hat.','Bumblebees can feel the weak electric fields of flowers. That tells them whether someone has already taken the nectar.',['hu','#ffd23f','#2a2438',{s:.95}]);
  bug('prozessionsraupe','Prozessions-Raupe','Processionary caterpillar','f','baum','nacht',2,360,'Sie läuft mit ihren Geschwistern hintereinander wie ein Zug.','It walks nose to tail with its brothers and sisters like a train.','Prozessionsraupen wandern in einer langen Reihe, eine hinter der anderen. Ihre Haare sollte man nicht anfassen.','Processionary caterpillars travel in a long line, one behind the other. You should not touch their hairs.',['ra',['#8a8a7a','#a0a090','#6a6a5a'],7]);

  ARTEN3.done();
})();
