/* =====================================================================
   CYBORG-LABOR · arten2.js · Neue Fische und Insekten (Inhalte 2.0)
   Die vierzehn Planeten mit bisher nur drei Fischen und drei Insekten
   bekommen je drei Fische und drei Insekten dazu. Jedes Tier ist echt
   (oder ein Spielzeug-Verwandter eines echten Tieres) und hat einen
   wahren, kindgerechten Fakt.
   ===================================================================== */
(()=>{
  const{F,B,fishMeta,bugMeta,fishT,butterfly,shellDome,legs,feelers,bugFace,shade}=NH;
  /* Muster für Fischhaut (Canvas 256×256) */
  const stripes=(c,n,v)=>(x,w,h)=>{x.fillStyle=c;for(let i=0;i<n;i++)v?x.fillRect(0,(i+.3)*h/n,w,h/n*.35):x.fillRect((i+.3)*w/n,0,w/n*.35,h)};
  const dots=(c,n,r)=>(x,w,h)=>{x.fillStyle=c;for(let i=0;i<n;i++){x.beginPath();x.arc((i*67)%w,12+(i*41)%(h-24),r,0,TAU);x.fill()}};
  const grid=(c,s)=>(x,w,h)=>{x.strokeStyle=c;x.lineWidth=3;for(let i=0;i<w;i+=s){x.beginPath();x.moveTo(i,0);x.lineTo(i,h);x.stroke()}for(let j=0;j<h;j+=s){x.beginPath();x.moveTo(0,j);x.lineTo(w,j);x.stroke()}};
  const patch=(cs)=>(x,w,h)=>{cs.forEach((c,i)=>{x.fillStyle=c;x.fillRect((i*83)%w,(i*57)%h,60,46)});x.strokeStyle='#fff8';x.setLineDash([6,5]);x.lineWidth=3;cs.forEach((c,i)=>x.strokeRect((i*83)%w,(i*57)%h,60,46));x.setLineDash([])};
  const glowDots=(c)=>(x,w,h)=>{x.fillStyle=c;for(let i=0;i<10;i++){x.beginPath();x.arc(20+i*24,h*.62,5,0,TAU);x.fill()}};
  /* Insekten-Bausteine */
  function beetle(g,m,col,o){o=o||{};const k=m.c(o.leg||'#3b3450',{gloss:.8});
    const mat=o.pat?m.tex('a2-'+o.key,ctex('a2-'+o.key,128,128,(x,w,h)=>{x.fillStyle=col;x.fillRect(0,0,w,h);o.pat(x,w,h)}),{gloss:1.1,rim:.5}):null;
    shellDome(g,m,col,[0,.2,-.04],.26*(o.s||1),o.len||1.15,mat?{mat}:{});P(g,G.s(.13),k,[0,.17,.27],null,[1.1,.9,.9]);bugFace(g,m,[0,.17,.3],.12,.5,{mouth:false,er:o.er});
    legs(g,k,[[.16,.25,.06],[.02,.29,0],[-.12,.27,-.06]],.13);feelers(g,k,k,[.04,.22,.36],o.ant||.14,.08);
    if(o.horn)P(g,G.co(.035,.16,8),k,[0,.28,.38],[-1,0,0]);if(o.glow)P(g,G.s(.11),m.glow(o.glow,2.2),[0,.16,-.25],null,[1,.8,1]).userData.noOutline=true}
  function libelle(g,m,col,wcol,o){o=o||{};const b=m.c(col,{gloss:1,rim:.6});P(g,G.ca(.035,o.len||.55),b,[0,.25,-.12],[PI/2,0,0]);P(g,G.s(.07),b,[0,.26,.2]);bugFace(g,m,[0,.27,.22],.08,.7,{er:.4,mouth:false});
    const wm=m.c(wcol||'#e8f6ff',{opacity:.55});for(const z of(o.two?[.06]:[.1,.02]))for(const s of[-1,1]){const w=P(g,G.s(o.ws||.2),wm,[s*(o.ws||.2),.29,z],null,[1,.04,.22]);w.userData.noOutline=true}
    legs(g,b,[[.12,.12,.05,.03],[.04,.14,0,.03]],.22,.012);if(o.tail)P(g,G.cy(.012,.005,.2,6),b,[0,.32,-.48],[-.9,0,0])}
  function grille(g,m,col,o){o=o||{};const b=m.c(col,{gloss:.6,rim:.5});P(g,G.ca(.08,o.len||.22),b,[0,.16,0],[PI/2,0,0]);P(g,G.s(.09),b,[0,.19,.18]);bugFace(g,m,[0,.19,.21],.09,.55,{mouth:false});
    both(s=>P(g,G.tu([[s*.07,.16,-.02],[s*.13,.3,-.12],[s*.14,.04,-.22]],.025,.018),b));legs(g,b,[[.1,.16,.05,.04],[.02,.17,0,.04]],.12,.014);feelers(g,b,b,[.03,.22,.25],o.ant||.3,.12,.5);
    P(g,G.s(.1),m.c(o.wing||shade(col,.7),{gloss:.8}),[0,.22,-.04],null,[1,.35,1.6]);if(o.arms)both(s=>P(g,G.tu([[s*.05,.2,.12],[s*.08,.3,.22],[s*.05,.22,.3]],.02,.015),b))}
  function kette(g,m,cols,n,r){for(let i=0;i<n;i++){const z=.3-i*(r*1.5);P(g,G.s(r*(i===0?1.15:1)),m.c(cols[i%cols.length],{gloss:.9}),[0,r+.02,z]);if(i===0)bugFace(g,m,[0,r+.02,z],r,.55,{mouth:false})}
    const k=m.c(shade(cols[0],.6));const mz=.3-r*1.5;legs(g,k,[[mz+r*.8,r*2.6,.05,.03],[mz,r*2.8,0,.03],[mz-r*.8,r*2.6,-.05,.03]],r+.02,.012);feelers(g,k,k,[r*.4,r*1.5,.3+r*.8],.16,.08)}
  function spinne(g,m,col,o){o=o||{};const b=m.c(col,{gloss:.7,rim:.6});P(g,G.s(o.body||.1),b,[0,.14,-.06]);P(g,G.s(.07),b,[0,.13,.08]);
    if(o.eyes)for(const[x,y]of[[-.03,.17],[.03,.17],[-.06,.15],[.06,.15]])P(g,G.s(x===.03||x===-.03?.022:.014),m.c('#1a1a24',{gloss:1.6}),[x,y,.14]);else bugFace(g,m,[0,.13,.1],.07,.6,{mouth:false});
    for(let i=0;i<4;i++)both(s=>{const z=.1-i*.06,L=o.leg||.22;P(g,G.tu([[s*.05,.13,z],[s*(.05+L*.6),.13+L*.55,z+(i<2?.04:-.04)],[s*(.05+L),.01,z+(i<2?.1:-.1)]],.012,.008),b)})}
  function schnecke(g,m,col,band){const sk=m.c('#e8c8a0',{gloss:.9});P(g,G.ca(.06,.34),sk,[0,.06,0],[PI/2,0,0],[1.2,.8,1]);
    const sh=m.tex('a2-snail-'+col,ctex('a2-snail-'+col,64,64,(x,w,h)=>{x.fillStyle=col;x.fillRect(0,0,w,h);x.fillStyle=band;for(let i=0;i<4;i++)x.fillRect(0,i*16+5,w,5)}),{gloss:1.2,rim:.5});
    P(g,G.s(.15),sh,[0,.2,-.04],null,[.75,1,1]);both(s=>{P(g,G.cy(.01,.012,.12,6),sk,[s*.03,.14,.18],[.5,0,0]);P(g,G.s(.022),m.c('#3b3450'),[s*.03,.2,.21])})}
  const fish=(id,n,pl,wh,sz,tm,r,pr,tx,fa,o)=>F(id,fishMeta(n,pl,wh,sz,tm,r,pr,tx,fa),(g,m)=>fishT(g,m,Object.assign({id},o)));
  const bug=(id,n,pl,wh,tm,r,pr,tx,fa,b)=>B(id,bugMeta(n,pl,wh,tm,r,pr,tx,fa),b);

  /* ---------------- Neon-Arkade ---------------- */
  fish('joystickwels','Joystick-Wels','neonarkade','teich','M','nacht',2,380,'Ich hab einen Joystick-Wels gefangen! Seine Barteln wackeln in alle vier Richtungen.','Welse schmecken mit der ganzen Haut. Auf ihrem Körper sitzen viele Geschmacksknospen, besonders an den Barteln.',{H:.2,L:.8,back:'#6a3aa8',belly:'#ffd0f0',tail:'round',dorsal:'std',pat:dots('#ff6fd8',16,7)});
  fish('muenzkarpfen','Münzkarpfen','neonarkade','teich','S','immer',1,150,'Ich hab einen Münzkarpfen gefangen! Seine Schuppen klimpern wie Spielmarken.','Karpfen können sehr alt werden. Manche Koi haben über 50 Jahre lang in ihrem Teich gelebt.',{H:.22,L:.55,back:'#ffd23f',belly:'#fff6c0',tail:'fancy',dorsal:'hi',pat:dots('#ffb020',20,9)});
  fish('highscorehai','Highscore-Hai','neonarkade','meer','L','nacht',4,2400,'Ich hab einen Highscore-Hai gefangen! Neuer Rekord!','Haie verlieren ständig Zähne und bekommen immer neue. Manche Haie brauchen im Leben Tausende Zähne.',{H:.2,L:1.05,back:'#45e0ff',belly:'#e8fbff',tail:'moon',dorsal:'tri',pat:grid('#7ff0ff',32)});
  bug('bonuskaefer','Bonuskäfer','neonarkade','boden','tag',1,180,'Ich hab einen Bonuskäfer gefangen! Er blinkt, als gäbe es Extrapunkte.','Manche Käfer glänzen wie Metall. Das kommt nicht von Farbe, sondern von hauchdünnen Schichten im Panzer, die das Licht spiegeln.',(g,m)=>beetle(g,m,'#ffd23f',{key:'bonus',pat:(x,w,h)=>{x.fillStyle='#ff6fd8';x.font='bold 40px monospace';x.textAlign='center';x.fillText('1UP',w/2,h/2+14)}}));
  bug('tastengrille','Tastengrille','neonarkade','boden','nacht',2,400,'Ich hab eine Tastengrille gefangen! Sie zirpt im Takt der Automaten.','Grillen zirpen, indem sie ihre Flügel aneinanderreiben. Bei warmem Wetter zirpen sie schneller.',(g,m)=>grille(g,m,'#ff6fd8',{wing:'#45e0ff'}));
  bug('leuchtstablibelle','Leuchtstab-Libelle','neonarkade','luft','nacht',3,950,'Ich hab eine Leuchtstab-Libelle gefangen! Sie zieht einen bunten Lichtstreifen hinter sich her.','Libellen können in alle Richtungen fliegen, sogar rückwärts. Ihre vier Flügel bewegen sie unabhängig voneinander.',(g,m)=>libelle(g,m,'#7fff6a','#c8ffe8'));

  /* ---------------- Plüsch ---------------- */
  fish('knopfaugenbarsch','Knopfaugen-Barsch','pluesch','teich','S','tag',1,140,'Ich hab einen Knopfaugen-Barsch gefangen! Er hat Augen wie zwei Knöpfe.','Fische haben keine Augenlider. Sie können nicht blinzeln und schlafen mit offenen Augen.',{H:.22,L:.55,back:'#ff9ab8',belly:'#fff0f4',tail:'round',dorsal:'std',eye:.075,pat:stripes('#ffd0de',5)});
  fish('kuschelrochen','Kuschelrochen','pluesch','meer','L','immer',3,1100,'Ich hab einen Kuschelrochen gefangen! Er ist weich wie eine Decke.','Rochen sind mit Haien verwandt. Ihr Skelett ist nicht aus Knochen, sondern aus Knorpel, so wie unsere Ohren.',{H:.1,L:.8,W:2.4,back:'#9ab8ff',belly:'#f4f8ff',tail:'spade',dorsal:'none',anal:false,pat:dots('#c8d8ff',12,10)});
  fish('flickenfisch','Flickenfisch','pluesch','fluss','M','tag',2,360,'Ich hab einen Flickenfisch gefangen! Er ist aus lauter bunten Stoffresten genäht.','Forellen und ihre Verwandten mögen kühles, sauberes Wasser mit viel Sauerstoff. Wo sie leben, ist das Wasser meist gesund.',{H:.2,L:.75,back:'#c8945a',belly:'#fff2e0',tail:'fork',dorsal:'std',pat:patch(['#ff6fa5','#7fd34a','#45a0ff','#ffd23f','#c87aff','#ff9a45'])});
  bug('samtmilbe','Samtmilbe','pluesch','boden','tag',1,160,'Ich hab eine Samtmilbe gefangen! Rot und weich wie ein Kissen.','Rote Samtmilben sehen aus wie kleine Plüschtiere. Sie haben acht Beine und sind mit den Spinnen verwandt.',(g,m)=>spinne(g,m,'#e8304a',{body:.13,leg:.12}));
  bug('baerenspinner','Bärenspinner','pluesch','luft','nacht',2,450,'Ich hab einen Bärenspinner gefangen! Seine Raupe war ein haariger kleiner Teddy.','Die Raupen der Bärenspinner sind dicht behaart. Deshalb nennt man sie auch Bärenraupen.',(g,m)=>butterfly(g,m,'baerenspinner','#f4f0e8','#ff7a3a','#5a3a2a'));
  bug('schildwanze','Schildwanze','pluesch','baum','tag',2,300,'Ich hab eine Schildwanze gefangen! Sie sieht aus wie ein kleines grünes Kissen.','Viele Wanzen geben bei Gefahr einen Geruch ab. So lassen Vögel sie lieber in Ruhe.',(g,m)=>beetle(g,m,'#7fd34a',{len:1,s:1.1}));

  /* ---------------- Bernstein-Mond ---------------- */
  fish('lungenfisch','Lungenfisch','bernstein','teich','L','nacht',4,2200,'Ich hab einen Lungenfisch gefangen! Er schnappt an der Oberfläche nach Luft.','Lungenfische können Luft atmen. Trocknet ihr Teich aus, graben sie sich in den Schlamm und warten auf Regen.',{H:.15,L:1,back:'#8a7040',belly:'#e8d8b0',tail:'spade',dorsal:'long',dz:.25,ds:1.5,pat:dots('#5a4020',18,6)});
  fish('knochenhecht','Knochenhecht','bernstein','fluss','L','tag',3,1300,'Ich hab einen Knochenhecht gefangen! Seine Schuppen sind hart wie eine Rüstung.','Knochenhechte haben harte, glänzende Schuppen. Ihre Familie gibt es schon seit der Zeit der Dinosaurier.',{H:.13,L:1,back:'#a08a50',belly:'#f0e4c0',tail:'round',dorsal:'std',dz:.3,pat:grid('#7a6030',20)});
  fish('bernsteinguppy','Bernstein-Guppy','bernstein','teich','S','immer',1,150,'Ich hab einen Bernstein-Guppy gefangen! Er leuchtet honiggelb im Licht.','Guppys bringen lebende Junge zur Welt, statt Eier zu legen. Ein Weibchen kann über zwanzig Junge auf einmal haben.',{H:.16,L:.45,back:'#ffb030',belly:'#fff4d0',tail:'fancy',dorsal:'std',ts:1.3});
  bug('harzameise','Harz-Ameise','bernstein','baum','tag',1,170,'Ich hab eine Harz-Ameise gefangen! An ihren Füssen klebt noch ein bisschen Harz.','Ameisen gab es schon zur Zeit der Dinosaurier. Man hat sie in sehr altem Bernstein gefunden, versteinertem Baumharz.',(g,m)=>kette(g,m,['#c86a20','#a0501a','#c86a20'],3,.07));
  bug('skorpionsfliege','Skorpionsfliege','bernstein','luft','tag',2,420,'Ich hab eine Skorpionsfliege gefangen! Sie sieht gefährlich aus, ist aber ganz lieb.','Die Skorpionsfliege sieht wehrhaft aus, ist aber harmlos. Ihr gebogener Schwanz ist kein Stachel.',(g,m)=>libelle(g,m,'#c8501a','#f4e0b0',{len:.38,tail:true,ws:.16}));
  bug('kugelassel','Kugelassel','bernstein','boden','nacht',1,140,'Ich hab eine Kugelassel gefangen! Sie hat sich zu einer kleinen Kugel gerollt.','Kugelasseln rollen sich bei Gefahr zu einer Kugel zusammen. Sie sind Krebse, die an Land leben.',(g,m)=>{beetle(g,m,'#7a7a88',{key:'assel',len:1.3,pat:(x,w,h)=>{x.fillStyle='#5a5a68';for(let i=0;i<8;i++)x.fillRect(0,i*16,w,4)}})});

  /* ---------------- Dino-Fabrik ---------------- */
  fish('quietschfisch','Quietschfisch','dinofabrik','teich','S','tag',1,120,'Ich hab einen Quietschfisch gefangen! Er quietscht, wenn man ihn drückt.','Fische haben eine Seitenlinie. Damit spüren sie kleinste Bewegungen im Wasser, sogar im Dunkeln.',{H:.24,L:.5,back:'#ffd23f',belly:'#fff8d0',tail:'round',dorsal:'hi',gloss:1.6});
  fish('schraubenhecht','Schraubenhecht','dinofabrik','fluss','L','immer',3,1000,'Ich hab einen Schraubenhecht gefangen! Seine Streifen drehen sich wie ein Gewinde.','Hechte lauern ganz still zwischen Wasserpflanzen und schiessen dann blitzschnell los.',{H:.14,L:1,back:'#7fa85a',belly:'#f0f4d8',tail:'fork',dorsal:'std',dz:.25,pat:stripes('#4a6a30',9)});
  fish('lackfisch','Lackfisch','dinofabrik','meer','M','tag',2,380,'Ich hab einen Lackfisch gefangen! Er glänzt wie frisch lackiert.','Manche Fische können ihre Farbe ändern, zum Beispiel zur Tarnung oder um zu zeigen, wie es ihnen geht.',{H:.22,L:.7,back:'#e8457f',belly:'#ffe0ec',tail:'fork',dorsal:'sail',gloss:1.6});
  bug('nietenkaefer','Nietenkäfer','dinofabrik','boden','tag',1,170,'Ich hab einen Nietenkäfer gefangen! Sein Panzer ist mit kleinen Nieten besetzt.','Käfer sind die artenreichste Tiergruppe der Welt. Man kennt fast 400 000 verschiedene Käferarten.',(g,m)=>beetle(g,m,'#8a9ab8',{key:'niete',pat:(x,w,h)=>{x.fillStyle='#d8e0f0';for(let i=0;i<4;i++)for(let j=0;j<4;j++){x.beginPath();x.arc(16+i*32,16+j*32,6,0,TAU);x.fill()}}}));
  bug('farbkleckspfalter','Farbklecks-Falter','dinofabrik','luft','tag',2,400,'Ich hab einen Farbklecks-Falter gefangen! Er ist durch die Lackiererei geflogen.','Die Farben auf Schmetterlingsflügeln stammen von winzigen Schuppen. Deshalb bleibt bunter Staub an den Fingern, wenn man sie anfasst.',(g,m)=>butterfly(g,m,'farbklecks',x=>{x.fillStyle='#fff';x.fillRect(0,0,1,1);for(const[c,a,b]of[['#e8457f',.3,.4],['#45a0ff',.7,.6],['#ffd23f',.5,.85]]){x.fillStyle=c;x.beginPath();x.arc(a,b,.16,0,TAU);x.fill()}},'#7fd34a','#3b3450'));
  bug('fliessbandameise','Fliessband-Ameise','dinofabrik','boden','tag',2,320,'Ich hab eine Fliessband-Ameise gefangen! Sie trägt ein Zahnrad, das grösser ist als sie.','Ameisen können ein Vielfaches ihres eigenen Gewichts tragen.',(g,m)=>{kette(g,m,['#3b3450','#5a5070','#3b3450'],3,.07);P(g,G.to(.07,.022),m.steel(),[0,.2,.05],[PI/2,0,0])});

  /* ---------------- Kaufhaus ---------------- */
  fish('schaufensterguppy','Schaufenster-Guppy','kaufhaus','teich','S','immer',1,140,'Ich hab einen Schaufenster-Guppy gefangen! Er posiert, als wäre er im Prospekt.','Guppys gehören zu den beliebtesten Aquarienfischen. Die Männchen haben besonders bunte, grosse Schwanzflossen.',{H:.15,L:.42,back:'#45c8ff',belly:'#e8f8ff',tail:'fancy',dorsal:'std',ts:1.4,pat:dots('#ff6fd8',8,10)});
  fish('goldorfe','Goldorfe','kaufhaus','teich','M','tag',2,340,'Ich hab eine Goldorfe gefangen! Sie schwimmt immer ganz oben im Brunnen.','Goldorfen schwimmen gern in Gruppen dicht unter der Wasseroberfläche. Deshalb sieht man sie im Teich besonders gut.',{H:.17,L:.72,back:'#ff9a30',belly:'#fff0d0',tail:'fork',dorsal:'std'});
  fish('schmetterlingsfisch','Schmetterlingsfisch','kaufhaus','meer','M','tag',3,900,'Ich hab einen Schmetterlingsfisch gefangen! Er hat einen falschen Augenfleck am Schwanz.','Viele Schmetterlingsfische haben einen dunklen Fleck am Schwanz, der wie ein Auge aussieht. So verwirren sie Räuber.',{H:.32,L:.5,back:'#ffe45a',belly:'#fffbe0',tail:'round',dorsal:'sail',pat:(x,w,h)=>{x.fillStyle='#3b3450';x.beginPath();x.arc(w*.25,h*.4,14,0,TAU);x.fill();x.fillRect(w*.8,0,10,h)}});
  bug('kleidermotte','Kleidermotte','kaufhaus','luft','nacht',1,150,'Ich hab eine Kleidermotte gefangen! Sie wollte gerade in die Pulli-Abteilung.','Nicht die Motte selbst frisst Löcher in Pullover, sondern ihre Raupen. Die erwachsenen Kleidermotten fressen gar nichts mehr.',(g,m)=>butterfly(g,m,'kleidermotte','#e8d8a8','#d8c898','#a89060',{fs:.4,hs:.35,raise:.2}));
  bug('teppichkaefer','Teppichkäfer','kaufhaus','boden','tag',2,330,'Ich hab einen Teppichkäfer gefangen! Er ist gemustert wie ein kleiner Läufer.','Teppichkäfer sind winzig und gemustert wie ein Teppich. Die erwachsenen Käfer besuchen gern Blüten.',(g,m)=>beetle(g,m,'#5a3a2a',{key:'teppich',s:.8,pat:(x,w,h)=>{const c=['#f4f0e8','#e8a050','#5a3a2a'];for(let i=0;i<24;i++){x.fillStyle=c[i%3];x.fillRect((i*37)%w,(i*23)%h,14,10)}}}));
  bug('tagpfauenauge','Tagpfauenauge','kaufhaus','blume','tag',3,850,'Ich hab ein Tagpfauenauge gefangen! Auf jedem Flügel schaut mich ein Auge an.','Die Augenflecken des Tagpfauenauges erschrecken Vögel. Bei Gefahr klappt der Falter die Flügel plötzlich auf.',(g,m)=>butterfly(g,m,'pfauenauge',x=>{x.fillStyle='#c8302a';x.fillRect(0,0,1,1);x.fillStyle='#ffd23f';x.beginPath();x.arc(.72,.72,.2,0,TAU);x.fill();x.fillStyle='#3b6ad8';x.beginPath();x.arc(.72,.72,.12,0,TAU);x.fill();x.fillStyle='#1a1a24';x.beginPath();x.arc(.72,.72,.06,0,TAU);x.fill()},x=>{x.fillStyle='#8a2a24';x.fillRect(0,-1,1,1);x.fillStyle='#3b6ad8';x.beginPath();x.arc(.5,-.5,.12,0,TAU);x.fill()},'#3b3450'));

  /* ---------------- Funkturm ---------------- */
  fish('wellenbarsch','Wellenbarsch','funkturm','teich','S','tag',1,140,'Ich hab einen Wellenbarsch gefangen! Seine Streifen sehen aus wie Funkwellen.','Unter Wasser ist Schall mehr als viermal so schnell wie in der Luft. Fische hören deshalb sehr gut.',{H:.2,L:.55,back:'#5a8ad8',belly:'#e8f0ff',tail:'fork',dorsal:'spiky',pat:(x,w,h)=>{x.strokeStyle='#c8e0ff';x.lineWidth=5;for(let j=0;j<4;j++){x.beginPath();for(let i=0;i<=w;i+=8)x.lineTo(i,40+j*50+Math.sin(i/14)*10);x.stroke()}}});
  fish('ruesselfisch','Elefantenrüsselfisch','funkturm','fluss','M','nacht',4,2000,'Ich hab einen Elefantenrüsselfisch gefangen! Er sendet leise Signale wie ein Funkgerät.','Der Elefantenrüsselfisch erzeugt schwache elektrische Signale. Damit findet er im trüben Wasser Futter und verständigt sich mit anderen.',{H:.15,L:.75,back:'#5a4a5a',belly:'#c8b8c8',tail:'fork',dorsal:'std',dz:.3,mouth:'none'});
  fish('trommelfisch','Trommelfisch','funkturm','meer','M','immer',2,400,'Ich hab einen Trommelfisch gefangen! Er brummt mir etwas vor.','Trommelfische machen mit ihrer Schwimmblase laute Brumm- und Trommelgeräusche.',{H:.24,L:.75,back:'#b8a890',belly:'#f4f0e8',tail:'round',dorsal:'long',pat:stripes('#8a7860',6,true)});
  bug('langhornmotte','Langhornmotte','funkturm','luft','tag',2,380,'Ich hab eine Langhornmotte gefangen! Ihre Fühler sind länger als jede Antenne hier.','Die Fühler der Langhornmotten können viel länger sein als ihr ganzer Körper.',(g,m)=>{butterfly(g,m,'langhorn','#c8a050','#a08040','#3b3450',{fs:.42,hs:.36});feelers(g,m.c('#f4f0e8'),null,[.02,.36,.29],.7,.16,.8)});
  bug('kurzwellenzikade','Kurzwellen-Zikade','funkturm','baum','tag',3,900,'Ich hab eine Kurzwellen-Zikade gefangen! Sie hat den ganzen Sommer durchgesendet.','Zikaden gehören zu den lautesten Insekten. Ihr Gesang kann so laut sein wie ein Rasenmäher.',(g,m)=>libelle(g,m,'#4a6a3a','#d8f0e0',{len:.32,two:true,ws:.18}));
  bug('weberknecht','Weberknecht','funkturm','boden','nacht',1,130,'Ich hab einen Weberknecht gefangen! Seine Beine sind dünn wie Antennendrähte.','Weberknechte sind keine Spinnen, obwohl sie acht Beine haben. Netze spinnen können sie nicht.',(g,m)=>spinne(g,m,'#8a6a4a',{body:.08,leg:.42}));

  /* ---------------- Magnetbahn ---------------- */
  fish('kompassbarsch','Kompassbarsch','magnetbahn','teich','S','tag',1,150,'Ich hab einen Kompassbarsch gefangen! Seine Nase zeigt immer nach Norden.','Manche Fische spüren das Magnetfeld der Erde. Lachse finden so vermutlich den Weg zurück zu ihrem Heimatfluss.',{H:.2,L:.55,back:'#d84a4a',belly:'#f0f4ff',tail:'fork',dorsal:'spiky',pat:(x,w,h)=>{x.fillStyle='#4a6ad8';x.fillRect(0,0,w/2,h)}});
  fish('blitzthun','Blitz-Thun','magnetbahn','meer','L','tag',4,2200,'Ich hab einen Blitz-Thun gefangen! Der war schneller als der Zug.','Thunfische sind sehr schnelle Schwimmer. Auf kurzen Strecken schaffen sie über 70 Kilometer pro Stunde.',{H:.22,L:1,back:'#2a4a8a',belly:'#e8f0f8',tail:'moon',dorsal:'tri',pat:stripes('#ffd23f',6)});
  fish('fliegenderfisch','Fliegender Fisch','magnetbahn','meer','M','immer',3,900,'Ich hab einen Fliegenden Fisch gefangen! Er ist über die Schienen gesegelt.','Fliegende Fische springen aus dem Wasser und gleiten mit ihren grossen Brustflossen oft über 50 Meter weit.',{H:.14,L:.7,back:'#5a8ad8',belly:'#f4f8ff',tail:'fork',dorsal:'std',ps:2.6,pz:.6});
  bug('kompasstermite','Kompasstermite','magnetbahn','boden','tag',2,420,'Ich hab eine Kompasstermite gefangen! Sie baut nur Häuser, die nach Norden zeigen.','In Australien bauen Kompass-Termiten flache Hügel, die genau von Norden nach Süden zeigen. So werden sie mittags nicht zu heiss.',(g,m)=>kette(g,m,['#f4e8d0','#e8d8b8','#d8c8a0'],3,.07));
  bug('wanderheuschrecke','Wanderheuschrecke','magnetbahn','luft','tag',2,380,'Ich hab eine Wanderheuschrecke gefangen! Sie ist mit dem Zug gereist.','Wanderheuschrecken fliegen in riesigen Schwärmen und legen dabei Hunderte Kilometer zurück.',(g,m)=>grille(g,m,'#b8a040',{len:.3,ant:.18}));
  bug('sandlaufkaefer','Sandlaufkäfer','magnetbahn','boden','tag',3,1000,'Ich hab einen Sandlaufkäfer gefangen! Er rennt fast so schnell wie die Bahn.','Sandlaufkäfer gehören zu den schnellsten Läufern unter den Insekten. Sie rennen so schnell, dass sie kurz anhalten müssen, um wieder etwas zu sehen.',(g,m)=>beetle(g,m,'#2a8a5a',{key:'sandlauf',len:1.3,s:.85,pat:(x,w,h)=>{x.fillStyle='#f4f0d0';for(const[a,b]of[[30,40],[98,40],[30,90],[98,90]]){x.beginPath();x.arc(a,b,9,0,TAU);x.fill()}}}));

  /* ---------------- Rechenzentrum ---------------- */
  fish('kuehlwassertetra','Kühlwasser-Tetra','rechenzentrum','teich','S','immer',1,140,'Ich hab einen Kühlwasser-Tetra gefangen! Er mag es kühl, genau wie die Server.','Salmler haben oft eine kleine extra Flosse zwischen Rückenflosse und Schwanz. Man nennt sie Fettflosse.',{H:.16,L:.45,back:'#4a8ad8',belly:'#f0f4ff',tail:'fork',dorsal:'std',pat:stripes('#7fffd8',3,true)});
  fish('propellerfisch','Propellerfisch','rechenzentrum','fluss','M','tag',2,360,'Ich hab einen Propellerfisch gefangen! Sein Schwanz dreht sich wie ein Lüfter.','Fische schwimmen vor allem mit der Schwanzflosse. Die anderen Flossen helfen beim Lenken und Bremsen.',{H:.2,L:.68,back:'#8a9aa8',belly:'#e8f0f8',tail:'moon',dorsal:'std',ts:1.3,pat:grid('#a8b8c8',24)});
  fish('zitterrochen','Zitterrochen','rechenzentrum','meer','L','nacht',4,2300,'Ich hab einen Zitterrochen gefangen! Es hat kurz gekribbelt.','Zitterrochen haben zwei elektrische Organe im Körper. Sie funktionieren ein bisschen wie Batterien.',{H:.1,L:.7,W:2.6,back:'#c8a870',belly:'#f8f0e0',tail:'round',dorsal:'none',anal:false,pat:dots('#8a6a40',10,8)});
  bug('fehlermotte','Fehlermotte','rechenzentrum','luft','nacht',3,1200,'Ich hab eine Fehlermotte gefangen! Kein Wunder, dass der Server gehustet hat.','1947 fand man in einem grossen Computer eine echte Motte, die einen Fehler ausgelöst hatte. Sie wurde ins Logbuch geklebt.',(g,m)=>butterfly(g,m,'fehlermotte','#a89880','#8a7a6a','#5a4a3a',{raise:.3}));
  bug('springspinne','Springspinne','rechenzentrum','boden','tag',2,400,'Ich hab eine Springspinne gefangen! Sie hat mich mit acht Augen angeschaut.','Springspinnen haben acht Augen und sehen sehr scharf. Sie springen ein Vielfaches ihrer Körperlänge weit.',(g,m)=>spinne(g,m,'#3b3450',{eyes:true,body:.09,leg:.14}));
  bug('leuchtkaefer','Leuchtkäfer','rechenzentrum','luft','nacht',2,450,'Ich hab einen Leuchtkäfer gefangen! Er blinkt wie eine Status-LED.','Leuchtkäfer erzeugen Licht fast ohne Wärme. Beinahe die ganze Energie wird zu Licht.',(g,m)=>beetle(g,m,'#5a4a3a',{s:.8,glow:'#c8ff5a'}));

  /* ---------------- Tiefsee ---------------- */
  fish('schwarzerschlinger','Schwarzer Schlinger','tiefsee','meer','M','nacht',4,2000,'Ich hab einen Schwarzen Schlinger gefangen! Sein Bauch ist wie ein Ballon.','Der Schwarze Schlinger kann Fische verschlucken, die grösser sind als er selbst. Sein Magen dehnt sich wie ein Ballon.',{H:.24,L:.6,back:'#2a2a3a',belly:'#4a4a5a',tail:'round',dorsal:'std',eye:.04});
  fish('pelikanaal','Pelikanaal','tiefsee','meer','L','immer',3,1200,'Ich hab einen Pelikanaal gefangen! Sein Maul ist so gross wie ein Kescher.','Der Pelikanaal hat ein riesiges Maul, das er wie ein Netz aufklappen kann.',{H:.1,L:1.1,back:'#1a1a2a',belly:'#3a3a5a',tail:'none',dorsal:'long',ds:1.6,dz:.2,eye:.03,pat:glowDots('#ff6fd8')});
  fish('drachenfisch','Drachenfisch','tiefsee','meer','M','nacht',4,2600,'Ich hab einen Drachenfisch gefangen! Er leuchtet heimlich rot.','Drachenfische leuchten rot. Die meisten Tiefseetiere sehen rotes Licht nicht, also ist es ihre geheime Taschenlampe.',{H:.13,L:.85,back:'#1a1a24',belly:'#2a2a3a',tail:'fork',dorsal:'std',dz:.2,pat:glowDots('#ff3a3a')});
  bug('gelbrandkaefer','Gelbrandkäfer','tiefsee','wasser','tag',2,420,'Ich hab einen Gelbrandkäfer gefangen! Er hatte eine Luftblase unter dem Panzer.','Der Gelbrandkäfer nimmt unter seinen Flügeldecken eine Luftblase mit und taucht damit wie mit einer Sauerstoffflasche.',(g,m)=>beetle(g,m,'#2a3a2a',{key:'gelbrand',len:1.25,pat:(x,w,h)=>{x.strokeStyle='#ffd23f';x.lineWidth=10;x.strokeRect(0,0,w,h)}}));
  bug('wasserskorpion','Wasserskorpion','tiefsee','wasser','nacht',3,900,'Ich hab einen Wasserskorpion gefangen! Er atmet durch einen Schnorchel.','Der Wasserskorpion atmet durch ein langes Rohr am Hinterleib, wie durch einen Schnorchel.',(g,m)=>{grille(g,m,'#6a5a3a',{arms:true,ant:.08});P(g,G.cy(.008,.006,.3,6),m.c('#6a5a3a'),[0,.18,-.36],[PI/2,0,0])});
  bug('strandfloh','Strandfloh','tiefsee','boden','nacht',1,120,'Ich hab einen Strandfloh gefangen! Er hüpft wie verrückt.','Strandflöhe sind kleine Krebse. Wenn man am Strand Seetang anhebt, springen sie weit davon.',(g,m)=>grille(g,m,'#d8c8a8',{len:.16,ant:.2}));

  /* ---------------- Wetterwerk ---------------- */
  fish('groppe','Groppe','wetterwerk','fluss','S','tag',1,150,'Ich hab eine Groppe gefangen! Sie hüpft am Grund von Stein zu Stein.','Die Groppe hat keine Schwimmblase. Deshalb hüpft sie am Gewässergrund von Stein zu Stein.',{H:.2,L:.55,back:'#7a6a5a',belly:'#e8e0d0',tail:'round',dorsal:'long',dz:.4,pat:dots('#5a4a3a',14,8)});
  fish('sonnenbarsch','Sonnenbarsch','wetterwerk','teich','S','tag',2,330,'Ich hab einen Sonnenbarsch gefangen! Er strahlt wie ein Sonnentag.','Sonnenbarsche bauen am Grund kleine Nestmulden. Das Männchen bewacht die Eier.',{H:.28,L:.5,back:'#5ab8a8',belly:'#ffb040',tail:'round',dorsal:'spiky',pat:(x,w,h)=>{x.fillStyle='#ff6a3a';x.beginPath();x.arc(w*.2,h*.35,12,0,TAU);x.fill()}});
  fish('wolkenmanta','Wolken-Manta','wetterwerk','meer','XL','immer',4,3000,'Ich hab einen Wolken-Manta gefangen! Er ist so gross wie eine Gewitterwolke.','Mantarochen gehören zu den grössten Fischen. Ihre Flossen können von Spitze zu Spitze über sieben Meter breit sein.',{H:.12,L:.9,W:3,back:'#4a5a7a',belly:'#f4f8ff',tail:'none',dorsal:'none',anal:false,pat:dots('#e8f0ff',8,14)});
  bug('schnake','Schnake','wetterwerk','luft','tag',1,120,'Ich hab eine Schnake gefangen! Sie sieht aus wie eine Riesenmücke.','Schnaken sehen aus wie riesige Mücken, stechen aber nicht.',(g,m)=>{libelle(g,m,'#a08a6a','#f0f0f0',{len:.35,two:true,ws:.14});for(let i=0;i<3;i++)both(s=>P(g,G.tu([[s*.03,.24,.05-i*.06],[s*.2,.3,.05-i*.08],[s*.32,0,.05-i*.1]],.008,.006),m.c('#a08a6a')))});
  bug('baenderschnecke','Bänderschnecke','wetterwerk','boden','immer',1,140,'Ich hab eine Bänderschnecke gefangen! Bei Regen kommt sie raus.','Bänderschnecken gibt es in vielen Farben, von Gelb bis Rosa, mit oder ohne dunkle Streifen.',(g,m)=>schnecke(g,m,'#ffe45a','#5a3a2a'));
  bug('taumelkaefer','Taumelkäfer','wetterwerk','wasser','tag',2,400,'Ich hab einen Taumelkäfer gefangen! Er dreht auf dem Wasser Kreise.','Taumelkäfer haben geteilte Augen. Sie sehen gleichzeitig über und unter Wasser.',(g,m)=>beetle(g,m,'#1a2a3a',{s:.8,er:.36}));

  /* ---------------- Nachtmarkt ---------------- */
  fish('medaka','Medaka','nachtmarkt','teich','S','immer',1,150,'Ich hab einen Medaka gefangen! So ein kleiner Reisfisch.','Medakas sind kleine Reisfische aus Japan. 1994 flogen sie ins Weltall und bekamen dort sogar Junge.',{H:.13,L:.42,back:'#f4c870',belly:'#fff8e8',tail:'round',dorsal:'std',dz:.25,eye:.065});
  fish('igelfisch','Igelfisch','nachtmarkt','meer','M','nacht',3,1000,'Ich hab einen Igelfisch gefangen! Er hat sich zu einer Stachelkugel aufgepumpt.','Bei Gefahr pumpt sich der Igelfisch mit Wasser auf, und seine Stacheln stellen sich auf wie bei einem Igel.',{H:.34,L:.55,W:.9,back:'#c8a870',belly:'#fffbe8',tail:'round',dorsal:'none',pat:dots('#5a4020',30,4)});
  fish('schleierschwanz','Schleierschwanz','nachtmarkt','teich','M','tag',2,420,'Ich hab einen Schleierschwanz gefangen! Seine Flossen wehen wie Seidenschals.','Schleierschwänze sind gezüchtete Goldfische mit langen, wehenden Flossen. Sie schwimmen eher gemütlich.',{H:.26,L:.5,back:'#ff6a3a',belly:'#fff0e0',tail:'fancy',ts:1.8,dorsal:'sail'});
  bug('seidenspinner','Seidenspinner','nachtmarkt','baum','nacht',3,950,'Ich hab einen Seidenspinner gefangen! Er ist weiss und flauschig.','Die Raupe des Seidenspinners spinnt ihren Kokon aus einem einzigen Faden. Er kann mehrere hundert Meter lang sein.',(g,m)=>butterfly(g,m,'seidenspinner','#f8f4ec','#ece4d8','#e8e0d0',{raise:.35}));
  bug('nachtpfauenauge','Nachtpfauenauge','nachtmarkt','luft','nacht',4,1800,'Ich hab ein Nachtpfauenauge gefangen! Seine Fühler sehen aus wie Federn.','Ein männliches Nachtpfauenauge riecht ein Weibchen mit seinen gefiederten Fühlern aus mehreren Kilometern Entfernung.',(g,m)=>butterfly(g,m,'nachtpfau',x=>{x.fillStyle='#a8907a';x.fillRect(0,0,1,1);x.fillStyle='#3b3450';x.beginPath();x.arc(.6,.6,.14,0,TAU);x.fill();x.fillStyle='#ffd8a0';x.beginPath();x.arc(.6,.6,.06,0,TAU);x.fill()},x=>{x.fillStyle='#8a7a6a';x.fillRect(0,-1,1,1);x.fillStyle='#3b3450';x.beginPath();x.arc(.5,-.5,.12,0,TAU);x.fill()},'#6a5a4a'));
  bug('ohrwurm','Ohrwurm','nachtmarkt','boden','nacht',1,130,'Ich hab einen Ohrwurm gefangen! Keine Sorge, der will nicht in mein Ohr.','Ohrwürmer krabbeln nicht in Ohren. Die Mütter kümmern sich liebevoll um ihre Eier und putzen sie.',(g,m)=>{kette(g,m,['#8a4a2a','#a05a30','#8a4a2a','#a05a30'],4,.055);both(s=>P(g,G.co(.015,.12,6),m.c('#5a2a1a'),[s*.025,.06,-.05],[-PI/2,0,s*.2]))});

  /* ---------------- Bauklotz ---------------- */
  fish('kofferfisch','Kofferfisch','bauklotz','meer','M','tag',2,420,'Ich hab einen Kofferfisch gefangen! Er ist eckig wie ein Bauklotz.','Der Kofferfisch hat einen festen, eckigen Panzer. Nach seinem Vorbild haben Ingenieure sogar ein Auto entworfen.',{H:.24,L:.55,W:.95,back:'#ffd23f',belly:'#fff8d0',tail:'round',dorsal:'none',pat:dots('#3b3450',22,6)});
  fish('elritze','Elritze','bauklotz','teich','S','immer',1,130,'Ich hab eine Elritze gefangen! Sie war im Schwarm ganz vorne.','Elritzen schwimmen in Schwärmen. Wird eine verletzt, gibt sie einen Schreckstoff ab, der die anderen warnt.',{H:.14,L:.45,back:'#6a8a5a',belly:'#ffd0b0',tail:'fork',dorsal:'std',pat:stripes('#3a5a3a',8)});
  fish('maulbrueter','Maulbrüter','bauklotz','fluss','M','tag',3,950,'Ich hab einen Maulbrüter gefangen! Er trägt seine Kinder im Mund herum.','Manche Buntbarsche tragen ihre Eier und Jungen im Maul, um sie zu beschützen.',{H:.24,L:.6,back:'#45a0ff',belly:'#fff4c0',tail:'round',dorsal:'long',pat:stripes('#2a6ad8',5)});
  bug('koecherfliege','Köcherfliege','bauklotz','wasser','nacht',2,380,'Ich hab eine Köcherfliege gefangen! Als Larve hat sie sich ein Haus aus Steinchen gebaut.','Die Larven der Köcherfliege bauen sich aus Steinchen und Stöckchen ein schützendes Haus.',(g,m)=>butterfly(g,m,'koecher','#a8906a','#c8b090','#6a5a4a',{raise:.15,fs:.45,hs:.38}));
  bug('mauerbiene','Mauerbiene','bauklotz','blume','tag',1,170,'Ich hab eine Mauerbiene gefangen! Sie baut mit Lehm, genau wie ich mit Klötzen.','Mauerbienen bauen ihre Nester in kleine Löcher und Ritzen und mauern sie mit Lehm zu.',(g,m)=>{P(g,G.s(.13),m.c('#c8642a',{gloss:.3,rim:1.2,rimColor:'#ffd0a0'}),[0,.18,-.04],null,[1,1,1.2]);P(g,G.s(.09),m.c('#3b3450'),[0,.19,.14]);bugFace(g,m,[0,.19,.17],.09,.55,{mouth:false});for(const s of[-1,1])P(g,G.s(.12),m.c('#e8f6ff',{opacity:.5}),[s*.13,.26,0],null,[1,.08,.5]).userData.noOutline=true});
  bug('pillendreher','Pillendreher','bauklotz','boden','nacht',3,1100,'Ich hab einen Pillendreher gefangen! Er rollt eine Kugel, viel grösser als er.','Pillendreher rollen Kugeln, die viel schwerer sind als sie selbst. Nachts orientieren sie sich an der Milchstrasse.',(g,m)=>{beetle(g,m,'#2a2a3a',{s:.85});P(g,G.s(.16),m.c('#8a6a4a',{gloss:.2}),[0,.16,-.42])});

  /* ---------------- Bildschirmschoner ---------------- */
  fish('schlaflippfisch','Schlaf-Lippfisch','schoner','meer','M','nacht',3,950,'Ich hab einen Schlaf-Lippfisch gefangen! Er hat schon den Schlafanzug an.','Manche Lippfische graben sich nachts in den Sand oder hüllen sich in eine Schleimhülle und schlafen.',{H:.18,L:.7,back:'#5a6ad8',belly:'#e8ecff',tail:'round',dorsal:'long',pat:stripes('#ffd8f0',4,true)});
  fish('zebrabaerbling','Zebrabärbling','schoner','teich','S','immer',1,140,'Ich hab einen Zebrabärbling gefangen! Er ist gestreift wie ein Ladebalken.','Zebrabärblinge können verletzte Teile ihres Herzens wieder nachwachsen lassen.',{H:.13,L:.45,back:'#3a4aa8',belly:'#f0f0ff',tail:'fork',dorsal:'std',pat:stripes('#e8f0ff',5,true)});
  fish('schlummerwels','Schlummerwels','schoner','fluss','M','nacht',2,400,'Ich hab einen Schlummerwels gefangen! Er hat gegähnt.','Viele Welse sind nachtaktiv. Tagsüber verstecken sie sich unter Steinen und Wurzeln.',{H:.16,L:.8,back:'#3a3a5a',belly:'#a8a8c8',tail:'round',dorsal:'std',pat:dots('#7a7aa8',14,6)});
  bug('taubenschwaenzchen','Taubenschwänzchen','schoner','blume','tag',3,1000,'Ich hab ein Taubenschwänzchen gefangen! Es stand in der Luft wie ein Mini-Kolibri.','Das Taubenschwänzchen steht beim Trinken in der Luft wie ein Kolibri und saugt mit einem langen Rüssel Nektar.',(g,m)=>{butterfly(g,m,'taubenschw','#7a6a5a','#ff9a45','#6a5a4a',{fs:.42,hs:.3,raise:.4});P(g,G.cy(.006,.004,.2,6),m.c('#3b3450'),[0,.3,.38],[PI/2,0,0])});
  bug('florfliege','Florfliege','schoner','luft','nacht',1,150,'Ich hab eine Florfliege gefangen! Ihre Augen glänzen golden.','Florfliegen haben grüne, durchsichtige Flügel und goldene Augen. Ihre Larven fressen Blattläuse.',(g,m)=>libelle(g,m,'#9ae85a','#d8ffd0',{len:.3,ws:.17}));
  bug('stabschrecke','Stabschrecke','schoner','baum','immer',2,420,'Ich hab eine Stabschrecke gefangen! Ich dachte erst, das ist ein Zweig.','Stabschrecken sehen aus wie kleine Zweige. Manche wiegen sich im Wind, damit sie noch echter wirken.',(g,m)=>{const b=m.c('#8a7a4a',{gloss:.3});P(g,G.cy(.018,.014,.7,6),b,[0,.12,0],[PI/2,0,0]);for(let i=0;i<3;i++)both(s=>P(g,G.tu([[s*.01,.12,.15-i*.15],[s*.14,.2,.18-i*.15],[s*.2,0,.22-i*.15]],.008,.006),b));feelers(g,b,b,[.01,.13,.35],.2,.05,.2)});

  /* ---------------- Honigwabe ---------------- */
  fish('lavendelschmerle','Lavendel-Schmerle','honigwabe','teich','S','immer',1,140,'Ich hab eine Lavendel-Schmerle gefangen! Sie duftet fast ein bisschen.','Schmerlen haben Barteln am Maul und suchen damit im Sand nach Futter.',{H:.12,L:.55,back:'#a890d8',belly:'#f4f0ff',tail:'round',dorsal:'std',dz:.4,pat:dots('#7a60a8',16,6)});
  fish('bitterling','Bitterling','honigwabe','teich','S','tag',2,360,'Ich hab einen Bitterling gefangen! Er schillert in allen Farben.','Der Bitterling legt seine Eier in eine Muschel. Dort wachsen die Jungen sicher auf.',{H:.22,L:.42,back:'#c8a8d8',belly:'#ffe8f0',tail:'fork',dorsal:'std',pat:stripes('#5ac8e8',1,true)});
  fish('kaiserfisch','Kaiserfisch','honigwabe','meer','M','tag',3,1000,'Ich hab einen Kaiserfisch gefangen! Er trägt Streifen wie ein Königsmantel.','Junge Kaiserfische sehen ganz anders aus als die erwachsenen. Früher hielt man sie sogar für verschiedene Arten.',{H:.3,L:.55,back:'#3a5ad8',belly:'#ffd23f',tail:'round',dorsal:'sail',pat:(x,w,h)=>{x.strokeStyle='#ffd23f';x.lineWidth=5;for(let i=0;i<7;i++){x.beginPath();x.arc(w*.5,h*1.4,40+i*22,0,TAU);x.stroke()}}});
  bug('holzbiene','Holzbiene','honigwabe','blume','tag',2,420,'Ich hab eine Holzbiene gefangen! Sie schimmert blauschwarz.','Die Blauschwarze Holzbiene ist eine der grössten Bienen Europas. Sie nagt ihre Nester in totes Holz.',(g,m)=>{P(g,G.s(.15),m.c('#2a2a4a',{gloss:1,rim:1,rimColor:'#8a7aff'}),[0,.18,-.04],null,[1,.9,1.25]);P(g,G.s(.1),m.c('#2a2a4a'),[0,.19,.16]);bugFace(g,m,[0,.19,.19],.1,.55,{mouth:false});for(const s of[-1,1])P(g,G.s(.14),m.c('#6a5aa8',{opacity:.6}),[s*.15,.27,0],null,[1,.08,.5]).userData.noOutline=true});
  bug('wachsmotte','Wachsmotte','honigwabe','luft','nacht',1,160,'Ich hab eine Wachsmotte gefangen! Sie riecht ein bisschen nach Kerze.','Die Raupen der Wachsmotte können sogar Plastiktüten anknabbern. Forschende untersuchen, ob das beim Aufräumen helfen kann.',(g,m)=>butterfly(g,m,'wachsmotte','#c8b090','#b8a080','#8a7a5a',{raise:.2,fs:.45,hs:.38}));
  bug('rosenkaefer','Rosenkäfer','honigwabe','blume','tag',3,900,'Ich hab einen Rosenkäfer gefangen! Er glänzt grün wie ein Edelstein.','Der Rosenkäfer kann fliegen, ohne die Flügeldecken ganz aufzuklappen. Er schiebt die Flügel einfach seitlich heraus.',(g,m)=>beetle(g,m,'#3ac87a',{key:'rose',pat:(x,w,h)=>{x.fillStyle='#e8fff0';for(const[a,b]of[[40,80],[90,60],[70,100]])x.fillRect(a,b,10,4)}}));
})();
