/* =====================================================================
   CYBORG-LABOR · arten7.js · Inhalte 2.0, zweiter Schub (Teil 5)
   Die fünf kleinen Monde (Keim, Kassette, Glühwurm, Drachen, Pixel)
   bekommen je fünf Fische und fünf Insekten dazu, passend zum Thema.
   ===================================================================== */
(()=>{
  const{planet,fish,bug}=ARTEN3;const{stripes,dots,grid,patch,glowDots}=NH.A2;

  /* ================= Keim-Mond (Samen) ================= */
  planet('keim');
  fish('tambaqui','Tambaqui','Tambaqui','m','teich','L','tag',3,1050,'Er hat eine Nuss im Maul.','It has a nut in its mouth.','Der Tambaqui frisst Früchte, die in den überfluteten Wald fallen. Mit seinem Kot verteilt er die Samen weit weg.','The tambaqui eats fruit that falls into the flooded forest. It spreads the seeds far away in its droppings.',{H:.3,L:.75,back:'#4a5a5a',belly:'#2a2a2a',tail:'fork',dorsal:'std'});
  fish('moderlieschen','Moderlieschen','Sunbleak','n','teich','S','immer',1,120,'Es ist winzig und glitzert silbern.','It is tiny and glitters silver.','Das Moderlieschen klebt seine Eier in einem Ring um Pflanzenstängel. Das Männchen bewacht sie.','The sunbleak sticks its eggs in a ring around plant stems. The male guards them.',{H:.14,L:.42,back:'#7a9a8a',belly:'#ffffff',tail:'fork',dorsal:'std',gloss:1.5});
  fish('lotuskarpfen','Lotus-Karpfen','Lotus carp','m','teich','M','tag',2,420,'Er hat ein Lotusblatt auf dem Rücken.','It has a lotus leaf on its back.','Lotussamen können mehr als tausend Jahre lang keimfähig bleiben. Man hat sehr alte Samen wieder zum Wachsen gebracht.','Lotus seeds can stay able to sprout for more than a thousand years. People have grown plants from very old seeds.',{H:.22,L:.7,back:'#ff9ab0',belly:'#fff0f4',tail:'fancy',dorsal:'long',pat:dots('#ffffff',14,8)});
  fish('mangrovenkaerpfling','Mangroven-Kärpfling','Mangrove killifish','m','teich','S','nacht',3,880,'Er wohnte in einem feuchten Ast.','It was living inside a damp branch.','Der Mangroven-Kärpfling kann wochenlang ausserhalb des Wassers in feuchten Ästen überleben. Er atmet dann durch die Haut.','The mangrove killifish can survive for weeks out of water inside damp branches. It breathes through its skin then.',{H:.12,L:.55,back:'#a07a4a',belly:'#f4e4c8',tail:'round',dorsal:'std',dz:.3,pat:dots('#6a4a2a',18,4)});
  fish('feenkrebs','Feenkrebs','Fairy shrimp','m','teich','S','tag',2,360,'Er schwimmt auf dem Rücken und winkt mit vielen Beinen.','It swims on its back and waves lots of legs.','Feenkrebse schwimmen auf dem Rücken. Ihre Eier überstehen Trockenheit wie Samenkörner und schlüpfen beim nächsten Regen.','Fairy shrimp swim on their backs. Their eggs survive dry times like seeds and hatch with the next rain.',{H:.1,L:.5,W:.8,back:'#ffb890',belly:'#fff0e0',tail:'fork',dorsal:'none',anal:'spiky',eyeY:.7,gloss:1.4});
  bug('samenkaefer','Samenkäfer','Bean weevil','m','boden','immer',1,140,'Er hat in einer Erbse gewohnt.','It was living inside a pea.','Die Larven des Samenkäfers wachsen in einem Samenkorn heran. Wenn sie fertig sind, fressen sie ein rundes Türchen hinaus.','Bean weevil larvae grow up inside a seed. When they are ready, they chew a round little door to get out.',['be','#8a7a5a',{s:.7,len:1.1}]);
  bug('eichelbohrer','Eichelbohrer','Acorn weevil','m','baum','tag',2,380,'Seine Nase ist so lang wie sein Körper.','Its nose is as long as its body.','Das Weibchen des Eichelbohrers bohrt mit seinem langen Rüssel ein Loch in eine Eichel und legt ein Ei hinein.','The female acorn weevil drills a hole into an acorn with its long snout and lays an egg inside.',['be','#a07a4a',{horn:true,s:.8,len:1.2}]);
  bug('ernteameise','Ernteameise','Harvester ant','f','boden','tag',2,330,'Sie trägt ein Samenkorn nach Hause.','It is carrying a seed home.','Ernteameisen sammeln Samen und lagern sie in Kammern in ihrem Nest, wie in einer Scheune.','Harvester ants collect seeds and store them in chambers in their nest, like in a barn.',['ke',['#c84a2a','#b83a1a','#c84a2a'],3,.065]);
  bug('tomatenhummel','Tomaten-Hummel','Tomato bumblebee','f','blume','tag',2,380,'Sie brummt ganz laut an der Tomatenblüte.','It buzzes very loudly on the tomato flower.','Hummeln schütteln Tomatenblüten mit einem lauten Brummen. Dabei fällt der Pollen heraus, und es wachsen Tomaten.','Bumblebees shake tomato flowers with a loud buzz. That makes the pollen fall out, and tomatoes can grow.',['hu','#ffd23f','#e8402a',{s:.95}]);
  bug('gallwespe','Gallwespe','Gall wasp','f','baum','tag',3,860,'Sie hat einen Galläpfel an das Eichenblatt gezaubert.','It magicked an oak apple onto the oak leaf.','Gallwespen legen ihre Eier in Eichenblätter. Der Baum bildet darum eine Kugel, den Gallapfel, in der die Larve wohnt.','Gall wasps lay their eggs in oak leaves. The tree grows a ball around them, the oak apple, where the larva lives.',['li','#5a3a2a','#f0f4ff',{len:.25,ws:.11,two:true}]);

  /* ================= Kassetten-Mond (Musik) ================= */
  planet('kassette');
  fish('riemenfisch','Riemenfisch','Oarfish','m','teich','XL','nacht',5,4500,'Er ist lang wie ein ausgerolltes Tonband.','It is as long as an unrolled tape.','Der Riemenfisch ist der längste Knochenfisch der Welt. Er schwimmt senkrecht im Wasser und wird nur selten gesehen.','The oarfish is the longest bony fish in the world. It swims upright in the water and is only rarely seen.',{H:.08,L:1.15,back:'#d8dce8',belly:'#ffffff',fin:'#ff3a4a',tail:'none',dorsal:'long',dz:.05,ds:2.6,anal:false,gloss:1.6,pat:dots('#6a7a9a',30,3)});
  fish('walkmanwels','Walkman-Wels','Headphone catfish','m','teich','M','nacht',2,440,'Er hört gerade Musik.','It is listening to music right now.','Welse hören sehr gut. Kleine Knöchelchen verbinden ihre Schwimmblase mit dem Ohr und verstärken so den Schall.','Catfish hear very well. Tiny bones link their swim bladder to the ear and make sounds louder.',{H:.17,L:.7,back:'#5a5a6a',belly:'#c8c8d0',tail:'round',dorsal:'tri',pat:stripes('#ffd23f',1,true)});
  fish('bandsalatqualle','Bandsalat-Qualle','Tape-tangle jellyfish','f','teich','L','nacht',3,1100,'Ihre Fäden sind verknotet wie Bandsalat.','Its threads are knotted like a tangled tape.','Die Löwenmähnenqualle hat die längsten Fangfäden aller Quallen. Sie können länger sein als ein Blauwal.','The lion\'s mane jellyfish has the longest tentacles of any jellyfish. They can be longer than a blue whale.',{H:.3,L:.35,W:1,back:'#c87a3a',belly:'#e8a060',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,arms:10,armL:1.2,armCol:'#8a5a2a'});
  fish('leierfisch','Leierfisch','Dragonet','m','teich','S','tag',2,400,'Seine Flosse sieht aus wie eine Leier.','Its fin looks like a lyre.','Leierfisch-Männchen spreizen ihre grossen bunten Flossen weit auf, um den Weibchen zu gefallen.','Male dragonets spread their big colourful fins wide to impress the females.',{H:.14,L:.6,W:1.3,back:'#e8a050',belly:'#fff0d8',tail:'round',dorsal:'sail',ds:1.6,pat:dots('#45a0ff',20,4)});
  fish('synthiesalmler','Synthie-Salmler','Synth tetra','m','teich','S','immer',1,150,'Er schimmert wie ein Synthesizer-Licht.','It shimmers like a synthesizer light.','Viele Salmler haben eine kleine Fettflosse zwischen Rückenflosse und Schwanz. Wozu sie dient, ist noch nicht ganz klar.','Many tetras have a small fatty fin between the back fin and the tail. What it is for is not yet fully known.',{H:.18,L:.45,back:'#c83aff',belly:'#ffd0ff',tail:'fork',dorsal:'std',pat:stripes('#45e0ff',1,true)});
  bug('zwitscherschrecke','Zwitscherschrecke','Upland green bush-cricket','f','baum','nacht',2,360,'Sie zwitschert wie ein kleiner Vogel.','It twitters like a little bird.','Die Zwitscherschrecke singt abends in Büschen und Bäumen sehr laut. Man hört sie oft, sieht sie aber kaum.','The upland green bush-cricket sings very loudly in bushes and trees in the evening. You often hear it but hardly ever see it.',['gr','#5ab83a',{len:.28,ant:.4,wing:'#4a9a2a'}]);
  bug('tanzfliege','Tanzfliege','Dance fly','f','luft','tag',2,330,'Sie tanzt in der Luft zur Musik.','It dances in the air to the music.','Manche Tanzfliegen-Männchen schenken dem Weibchen ein Geschenk, eingewickelt in Seide.','Some male dance flies give the female a present wrapped in silk.',['li','#3a3a44','#f0f4ff',{len:.3,ws:.12,two:true}]);
  bug('lauschereule','Lauscher-Eule','Listening moth','f','luft','nacht',2,380,'Sie hat Ohren am Körper und hört alles.','It has ears on its body and hears everything.','Eulenfalter haben Ohren an der Brust. Damit hören sie die Rufe von Fledermäusen und können ausweichen.','Owlet moths have ears on their chest. They hear the calls of bats and can dodge them.',['bf','#8a7a6a','#a09080','#5a4a3a',{fs:.46,hs:.4}]);
  bug('zirpameise','Zirp-Ameise','Squeaking ant','f','boden','immer',1,140,'Sie quietscht leise, wenn sie Hilfe braucht.','It squeaks softly when it needs help.','Viele Ameisen können leise zirpen, indem sie Teile ihres Hinterleibs aneinanderreiben. So rufen sie Hilfe.','Many ants can chirp quietly by rubbing parts of their body together. That is how they call for help.',['ke',['#3a2a24','#4a3a34','#3a2a24'],3,.06]);
  bug('garnspulenraupe','Garnspulen-Raupe','Spool caterpillar','f','baum','tag',3,880,'Sie spult einen Faden auf wie ein Tonband.','It winds up a thread like a tape.','Eine Seidenraupe spinnt ihren Kokon aus einem einzigen Faden. Er kann fast einen Kilometer lang sein.','A silkworm spins its cocoon from one single thread. It can be almost a kilometre long.',['ra',['#f4f0e8','#e8e0d0'],6]);

  /* ================= Glühwurm-Mond (Leuchten) ================= */
  planet('gluehwurm');
  fish('pinienzapfenfisch','Pinienzapfenfisch','Pineconefish','m','teich','S','nacht',3,950,'Er sieht aus wie ein Tannenzapfen mit Licht.','It looks like a pinecone with a light.','Der Pinienzapfenfisch hat harte Schuppen wie ein Zapfen und kleine Leuchtorgane am Kiefer.','The pineconefish has hard scales like a pinecone and little light organs on its jaw.',{H:.24,L:.45,back:'#ffd23f',belly:'#fff4c0',tail:'round',dorsal:'spiky',pat:grid('#1a1a24',18)});
  fish('ponyfisch','Ponyfisch','Ponyfish','m','teich','S','nacht',2,380,'Sein Bauch schimmert wie Mondlicht.','Its belly shimmers like moonlight.','Ponyfische haben leuchtende Bakterien im Hals. Ihr Licht strahlt durch den Bauch nach unten.','Ponyfish have glowing bacteria in their throat. Their light shines down through the belly.',{H:.28,L:.45,W:.6,back:'#c8d0d8',belly:'#e8fff0',tail:'fork',dorsal:'std',gloss:1.6,pat:glowDots('#c8ffd8')});
  fish('leuchtgarnele','Leucht-Garnele','Glowing shrimp','f','teich','S','immer',2,420,'Sie hat eine leuchtende Wolke gepustet.','It puffed out a glowing cloud.','Manche Garnelen spucken bei Gefahr eine leuchtende Wolke aus. Der Räuber ist geblendet, und die Garnele entkommt.','Some shrimp spit out a glowing cloud when in danger. The predator is dazzled, and the shrimp escapes.',{H:.14,L:.5,W:.7,back:'#e8402a',belly:'#ff8a6a',tail:'fan',dorsal:'none',anal:false,arms:2,armL:1,pat:glowDots('#7ab8ff')});
  fish('kristallqualle','Kristallqualle','Crystal jelly','f','teich','M','nacht',4,2000,'Ihr Rand leuchtet grün.','Its edge glows green.','Aus der Kristallqualle stammt ein grün leuchtender Stoff, mit dem Forschende Zellen unter dem Mikroskop sichtbar machen.','A green glowing substance from the crystal jelly helps scientists see cells under the microscope.',{H:.3,L:.3,W:1,back:'#f0fff4',belly:'#ffffff',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,gloss:1.8,arms:12,armL:.8,armCol:'#c8ffd0',pat:stripes('#7aff8a',12,true)});
  fish('leuchtkrill','Leuchtkrill','Glowing krill','m','teich','S','nacht',1,130,'Er blinkt wie ein winziges Lämpchen.','It blinks like a tiny lamp.','Krill sind kleine Krebse, die in riesigen Schwärmen leben. Sie haben Leuchtorgane und sind Futter für Wale.','Krill are small crustaceans that live in huge swarms. They have light organs and are food for whales.',{H:.12,L:.45,W:.6,back:'#ff9a8a',belly:'#fff0ec',tail:'fork',dorsal:'none',eye:.06,arms:2,armL:.8,gloss:1.4});
  bug('leuchtregenwurm','Leucht-Regenwurm','Glowing earthworm','m','boden','nacht',3,880,'Er hinterlässt eine leuchtende Spur.','It leaves a glowing trail.','Einige Regenwürmer geben bei Gefahr einen leuchtenden Schleim ab. Er glimmt im Dunkeln grünlich.','Some earthworms give off glowing slime when in danger. It glows greenish in the dark.',['ra',['#c87a7a','#d88a8a'],8]);
  bug('leuchtspringschwanz','Leucht-Springschwanz','Glowing springtail','m','boden','nacht',2,340,'Er leuchtet beim Hüpfen.','It glows when it hops.','Einige Springschwänze leuchten im Dunkeln. Sie leben im Laub und im Boden.','Some springtails glow in the dark. They live in leaf litter and soil.',['gr','#c8ffe0',{len:.16,wing:'#7affb0'}]);
  bug('eisenbahnwurm','Eisenbahnwurm','Railroad worm','m','boden','nacht',4,2200,'Er leuchtet wie ein Zug mit roten Scheinwerfern.','It glows like a train with red headlights.','Die Larve eines Käfers aus Südamerika leuchtet vorn rot und an den Seiten grün, wie ein Zug in der Nacht.','The larva of a beetle from South America glows red at the front and green along its sides, like a train at night.',['ra',['#ff3a2a','#7aff6a','#7aff6a','#7aff6a'],8]);
  bug('kleinerleuchtkaefer','Kleiner Leuchtkäfer','Lesser glow-worm','m','luft','nacht',2,400,'Er leuchtet beim Fliegen.','It glows while it flies.','Beim Kleinen Leuchtkäfer leuchten auch die Männchen im Flug. Die Weibchen warten leuchtend im Gras.','In the lesser glow-worm, the males also glow while flying. The females wait in the grass, glowing.',['be','#4a4030',{s:.75,len:1.2,glow:'#d8ff6a'}]);
  bug('lunafalter','Luna-Falter','Luna moth','m','luft','nacht',4,2100,'Er ist blassgrün wie der Mond.','It is pale green like the moon.','Der Luna-Falter hat lange Schwänzchen an den Hinterflügeln. Als Falter lebt er nur etwa eine Woche.','The Luna moth has long tails on its hind wings. As a moth it lives for only about a week.',['bf','#c8f0b0','#b8e8a0','#f4f0e8',{fs:.56,hs:.5}]);

  /* ================= Drachen-Mond (Wind und Drachen) ================= */
  planet('drachen');
  fish('drachenkopf','Drachenkopf','Scorpionfish','m','meer','M','nacht',3,1000,'Er sieht aus wie ein bunter Stein mit Stacheln.','It looks like a colourful stone with spines.','Der Drachenkopf ist perfekt getarnt. Er liegt still am Grund, bis ein Fisch nah genug kommt.','The scorpionfish is perfectly camouflaged. It lies still on the bottom until a fish comes close enough.',{H:.24,L:.55,W:1.1,back:'#c8603a',belly:'#f4c8a8',tail:'round',dorsal:'spiky',ds:1.3,ps:1.6,pat:dots('#8a3a2a',22,7)});
  fish('drachenmuraene','Drachenmuräne','Dragon moray','f','meer','L','nacht',4,2300,'Sie hat Hörner wie ein Drache.','It has horns like a dragon.','Die Drachenmuräne hat kleine Röhren über den Augen, die wie Hörner aussehen. Damit riecht sie.','The dragon moray has little tubes above its eyes that look like horns. It uses them to smell.',{H:.1,L:1.05,back:'#ff7a2a',belly:'#fff0e0',tail:'none',dorsal:'long',dz:.1,ds:2.4,anal:'long',pect:false,pat:dots('#ffffff',30,5)});
  fish('seemotte','Seemotte','Sea moth','f','meer','S','tag',3,920,'Sie hat Flossen wie kleine Drachenflügel.','It has fins like little kite wings.','Die Seemotte geht mit ihren Flossen über den Meeresgrund. Ihre grossen Brustflossen sehen aus wie Flügel.','The sea moth walks across the sea floor on its fins. Its big chest fins look like wings.',{H:.12,L:.45,W:1.4,back:'#c8a080',belly:'#f4e8d8',tail:'round',dorsal:'none',ps:2.6,beak:{len:.12,r:.03}});
  fish('kuhnasenrochen','Kuhnasenrochen','Cownose ray','m','meer','L','tag',3,1100,'Er hat eine Nase wie eine Kuh.','It has a nose like a cow.','Kuhnasenrochen wandern in riesigen Gruppen von Tausenden Tieren durch das Meer, wie ein Schwarm Drachen am Himmel.','Cownose rays travel through the sea in huge groups of thousands, like a flock of kites in the sky.',{H:.08,L:.7,W:2.8,back:'#a08a6a',belly:'#ffffff',tail:'spade',dorsal:'none',anal:false});
  fish('flugkalmar','Flugkalmar','Flying squid','m','meer','M','tag',3,980,'Er ist aus dem Wasser gesegelt!','It sailed out of the water!','Manche Kalmare schiessen mit einem Wasserstrahl aus dem Meer und gleiten mit ausgebreiteten Flossen durch die Luft.','Some squid shoot out of the sea with a jet of water and glide through the air with their fins spread.',{H:.12,L:.75,back:'#e88a6a',belly:'#fff0e8',tail:'spade',ts:1.4,dorsal:'none',anal:false,pect:false,eye:.07,arms:8,armL:.8});
  bug('flugdrache','Flugdrache','Flying dragon','m','baum','tag',4,2400,'Er ist von Baum zu Baum gesegelt.','It glided from tree to tree.','Der Flugdrache ist eine kleine Echse. Er spannt Hautflügel zwischen seinen Rippen auf und gleitet von Baum zu Baum.','The flying dragon is a small lizard. It spreads skin wings between its ribs and glides from tree to tree.',['li','#8a7a4a','#ff8a3a',{len:.55,ws:.24,two:true}]);
  bug('seidenfadenraupe','Seidenfaden-Raupe','Thread caterpillar','f','baum','tag',1,150,'Sie hängt an einem Faden wie ein Drachen.','It hangs on a thread like a kite.','Viele Raupen lassen sich an einem Seidenfaden vom Baum herunter. Bei Gefahr klettern sie den Faden wieder hoch.','Many caterpillars lower themselves from trees on a silk thread. When in danger, they climb back up.',['ra',['#7ab83a','#8ac84a'],6]);
  bug('kaiserlibelle','Grosse Königslibelle','Emperor dragonfly','f','luft','tag',3,950,'Sie fliegt schnell und hoch wie ein Drachen.','It flies fast and high like a kite.','Die Grosse Königslibelle ist eine der grössten Libellen Europas. Sie frisst sogar im Flug.','The emperor dragonfly is one of the largest dragonflies in Europe. It even eats while flying.',['li','#3a8aff','#e8f4ff',{len:.65,ws:.24}]);
  bug('flugameise','Flug-Ameise','Flying ant','f','luft','tag',1,130,'Sie hat Flügel, obwohl sie eine Ameise ist.','It has wings even though it is an ant.','An warmen Sommertagen fliegen junge Königinnen und Männchen mit Flügeln aus dem Nest. Danach gründen die Königinnen neue Völker.','On warm summer days, young queens and males fly out of the nest with wings. Afterwards the queens start new colonies.',['li','#3a2a24','#f0f4ff',{len:.3,ws:.13}]);
  bug('waldbrettspiel','Waldbrettspiel','Speckled wood','n','baum','tag',2,330,'Es tanzt im Sonnenfleck zwischen den Bäumen.','It dances in the sunspot between the trees.','Die Männchen des Waldbrettspiels verteidigen kleine Sonnenflecken im Wald gegen andere Falter.','Male speckled woods defend little sunspots in the forest against other butterflies.',['bf','#6a5a3a','#5a4a2a','#3a2a24',{fs:.44,hs:.38}]);

  /* ================= Pixel-Mond (Raster und Rätsel) ================= */
  planet('pixelmond');
  fish('schachbrettbuntbarsch','Schachbrett-Buntbarsch','Checkerboard cichlid','m','teich','S','tag',2,400,'Er ist gemustert wie ein Schachbrett.','It is patterned like a chessboard.','Der Schachbrett-Buntbarsch lebt in weichem, dunklem Wasser in Südamerika. Sein Muster wird bei Aufregung kräftiger.','The checkerboard cichlid lives in soft, dark water in South America. Its pattern gets stronger when it is excited.',{H:.2,L:.55,back:'#c8c0b0',belly:'#f4f0e8',tail:'fancy',dorsal:'long',pat:(x,w,h)=>{x.fillStyle='#2a2a2a';for(let i=0;i<8;i++)for(let j=0;j<8;j++)if((i+j)%2)x.fillRect(i*w/8,j*h/8,w/8,h/8)}});
  fish('wuerfelkofferfisch','Würfel-Kofferfisch','Cube boxfish','m','teich','S','immer',2,420,'Er ist eckig wie ein Pixel.','It is square like a pixel.','Junge Gelbe Kofferfische sind fast würfelförmig und leuchtend gelb mit schwarzen Punkten.','Young yellow boxfish are almost cube-shaped and bright yellow with black dots.',{H:.3,L:.35,W:1.05,back:'#ffe020',belly:'#fff4a0',tail:'round',dorsal:'std',pat:dots('#1a1a24',30,5)});
  fish('zebramuraene','Zebra-Muräne','Zebra moray','f','teich','L','nacht',3,1050,'Sie ist gestreift wie eine Bildschirmzeile.','It is striped like a screen line.','Die Zebra-Muräne hat flache, runde Zähne. Damit knackt sie Krebse und Muscheln.','The zebra moray has flat, round teeth. It uses them to crack crabs and shellfish.',{H:.09,L:1.05,back:'#2a2a2a',belly:'#f4f4f4',tail:'none',dorsal:'long',dz:.1,ds:2.4,anal:'long',pect:false,pat:stripes('#f4f4f4',14)});
  fish('harlekinsuesslippe','Harlekin-Süsslippe','Harlequin sweetlips','f','teich','M','tag',3,960,'Sie wackelt beim Schwimmen wie eine Spielfigur.','It wobbles when it swims like a game piece.','Junge Harlekin-Süsslippen schwimmen wackelig wie ein giftiger Plattwurm. So lassen Räuber sie in Ruhe.','Young harlequin sweetlips swim wobbly like a poisonous flatworm. That way predators leave them alone.',{H:.22,L:.6,back:'#f4f0e8',belly:'#ffffff',fin:'#ff8a3a',tail:'round',dorsal:'long',pat:(x,w,h)=>{x.fillStyle='#4a3a2a';for(let i=0;i<9;i++){x.beginPath();x.ellipse((i*61)%w,(i*43)%h,22,16,0,0,TAU);x.fill()}}});
  fish('schachbrettlippfisch','Schachbrett-Lippfisch','Checkerboard wrasse','m','teich','S','nacht',2,380,'Er hat sich zum Schlafen im Sand vergraben.','It had buried itself in the sand to sleep.','Viele Lippfische vergraben sich nachts zum Schlafen im Sand. Morgens kommen sie wieder heraus.','Many wrasses bury themselves in the sand to sleep at night. In the morning they come out again.',{H:.15,L:.6,back:'#7ab8a0',belly:'#f4fcf8',tail:'round',dorsal:'long',pat:grid('#2a5a4a',20)});
  bug('mosaikjungfer','Mosaikjungfer','Hawker dragonfly','f','luft','tag',2,420,'Ihr Körper ist ein Mosaik aus bunten Flecken.','Its body is a mosaic of colourful patches.','Mosaikjungfern haben ein Muster wie ein Mosaik aus kleinen Steinchen. Sie jagen oft bis in die Dämmerung.','Hawker dragonflies have a pattern like a mosaic of little stones. They often hunt until dusk.',['li','#3a8a5a','#e8fff0',{len:.6}]);
  bug('schachbrettfalter','Schachbrettfalter','Marbled white','m','blume','tag',2,360,'Er ist schwarz-weiss wie ein Schachbrett.','It is black and white like a chessboard.','Der Schachbrettfalter hat ein schwarz-weisses Muster. Er besucht am liebsten lila Blüten.','The marbled white has a black and white pattern. It likes to visit purple flowers best.',['bf',x=>{x.fillStyle='#f8f8f4';x.fillRect(0,-1,1,2);x.fillStyle='#2a2a2a';for(let i=0;i<5;i++)for(let j=0;j<10;j++)if((i+j)%2)x.fillRect(i*.2,-1+j*.2,.2,.2)},x=>{x.fillStyle='#f8f8f4';x.fillRect(0,-1,1,2);x.fillStyle='#2a2a2a';for(let i=0;i<5;i++)for(let j=0;j<10;j++)if((i+j)%2)x.fillRect(i*.2,-1+j*.2,.2,.2)},'#2a2a2a']);
  bug('punktmarienkaefer','22-Punkt-Marienkäfer','22-spot ladybird','m','blume','tag',1,160,'Er hat genau 22 Punkte wie Pixel.','It has exactly 22 spots like pixels.','Der 22-Punkt-Marienkäfer ist gelb und frisst keine Läuse, sondern Mehltau-Pilze auf Blättern.','The 22-spot ladybird is yellow and does not eat aphids, but mildew fungus on leaves.',['be','#ffe020',{s:.7,len:.95,key:'punkt22',pat:dots('#1a1a24',22,6)}]);
  bug('gitterwanze','Gitterwanze','Lace bug','f','blume','tag',2,330,'Ihre Flügel sehen aus wie ein feines Gitter.','Its wings look like a fine grid.','Gitterwanzen haben Flügel mit einem Muster wie Spitze oder ein feines Gitter.','Lace bugs have wings with a pattern like lace or a fine grid.',['be','#f0ece0',{s:.75,len:1.1,key:'gitter',pat:grid('#a09880',12)}]);
  bug('zartschrecke','Punktierte Zartschrecke','Speckled bush-cricket','f','baum','nacht',2,350,'Ihr Lied ist so hoch, dass ich es kaum höre.','Its song is so high I can hardly hear it.','Die Punktierte Zartschrecke singt so hoch und leise, dass viele Erwachsene sie gar nicht hören können.','The speckled bush-cricket sings so high and softly that many adults cannot hear it at all.',['gr','#7ac83a',{len:.2,ant:.38,wing:'#6ab82a'}]);

  ARTEN3.done();
})();
