/* =====================================================================
   CYBORG-LABOR · arten6.js · Inhalte 2.0, zweiter Schub (Teil 4)
   Rechenzentrum, Tiefsee, Wetterwerk, Nachtmarkt, Bauklotz, Schoner und
   Honigwabe bekommen je sechs Fische und sechs Insekten dazu.
   ===================================================================== */
(()=>{
  const{planet,fish,bug}=ARTEN3;const{stripes,dots,grid,patch,glowDots}=NH.A2;

  /* ================= Rechenzentrum ================= */
  planet('rechenzentrum');
  fish('glasbarsch','Glasbarsch','Glassfish','m','teich','S','immer',1,160,'Ich kann seine Gräten sehen wie Kabel in einem Gehäuse.','I can see its bones like cables inside a case.','Glasbarsche sind fast durchsichtig. Man kann ihre Wirbelsäule und Gräten von aussen sehen.','Glassfish are almost see-through. You can see their spine and bones from the outside.',{H:.24,L:.45,back:'#e8f4f0',belly:'#f8fffc',tail:'fork',dorsal:'spiky',gloss:1.8,pat:stripes('#c8d8d0',10)});
  fish('roehrenaal','Röhrenaal','Garden eel','m','meer','M','tag',2,420,'Er steckte im Sand wie ein Kabel.','It was sticking out of the sand like a cable.','Röhrenaale leben in grossen Kolonien im Sand. Sie strecken nur den Vorderkörper heraus und schnappen Plankton.','Garden eels live in big colonies in the sand. They stick out only the front of their body and snap up plankton.',{H:.06,L:1,back:'#f4f0e8',belly:'#ffffff',tail:'none',dorsal:'none',anal:false,pect:false,pat:dots('#2a2a2a',30,4)});
  fish('kabeljau','Kabeljau','Cod','m','meer','L','nacht',2,480,'Kabel-jau! Der Name passt hier perfekt.','Cod! The German name sounds like cable, which fits perfectly here.','Ein grosses Kabeljau-Weibchen kann in einem Jahr Millionen Eier legen.','A big female cod can lay millions of eggs in one year.',{H:.18,L:.9,back:'#8a8a6a',belly:'#f4f4e8',tail:'round',dorsal:'std',pat:dots('#5a5a3a',30,5)});
  fish('putzgarnele','Putz-Garnele','Algae shrimp','f','teich','S','tag',1,150,'Sie hat sofort angefangen, meinen Eimer zu putzen.','It started cleaning my bucket straight away.','Manche Garnelen fressen den ganzen Tag Algen. In Aquarien halten sie die Scheiben sauber.','Some shrimp eat algae all day long. In aquariums they keep the glass clean.',{H:.14,L:.45,W:.7,back:'#d8e8e0',belly:'#f4fcf8',tail:'fan',dorsal:'none',anal:false,arms:2,armL:.6,pat:dots('#8aa898',20,3)});
  fish('saugschmerle','Saugschmerle','Hillstream loach','f','fluss','S','tag',2,380,'Sie klebt am Stein wie ein Saugnapf.','It sticks to the stone like a sucker.','Saugschmerlen leben in sehr schnellen Bächen. Mit ihrem flachen Körper halten sie sich an Steinen fest.','Hillstream loaches live in very fast streams. They hold on to stones with their flat body.',{H:.07,L:.5,W:2,back:'#8a7a5a',belly:'#e8dcc0',tail:'round',dorsal:'std',ps:2.2,pat:dots('#3a3020',30,4)});
  fish('leuchtaugenfisch','Leuchtaugenfisch','Lampeye','m','teich','S','nacht',2,360,'Seine Augen leuchten blau wie LEDs.','Its eyes glow blue like LEDs.','Der Leuchtaugenfisch hat Augen, die im Licht blau glänzen. Im Schwarm sieht das aus wie viele kleine Lämpchen.','The lampeye has eyes that shine blue in the light. In a school it looks like lots of tiny lamps.',{H:.14,L:.42,back:'#c8c0a0',belly:'#f8f4e8',tail:'round',dorsal:'std',eye:.06,pat:glowDots('#7ab8ff')});
  bug('kabelameise','Kabelameise','Crazy ant','f','boden','immer',2,320,'Sie krabbelt am liebsten in Steckdosen.','It likes crawling into sockets best.','Manche Ameisen werden von elektrischen Geräten angezogen und krabbeln in Schaltkästen hinein.','Some ants are attracted to electrical equipment and crawl into switch boxes.',['ke',['#8a5a2a','#a06a3a','#8a5a2a'],3,.055]);
  bug('baertierchen','Bärtierchen','Water bear','n','boden','immer',5,4000,'Es ist winzig und sieht aus wie ein Gummibär mit acht Beinen.','It is tiny and looks like a gummy bear with eight legs.','Bärtierchen leben im Moos. Sie können austrocknen und Jahre später wieder aufwachen. Sie haben sogar eine Reise ins Weltall überlebt.','Water bears live in moss. They can dry out and wake up again years later. They even survived a trip into space.',['ra',['#e8c8a0','#f0d8b0','#e8c8a0'],4]);
  bug('kupferstecher','Kupferstecher','Engraver beetle','m','baum','tag',2,340,'Er hat ein Muster in die Rinde geritzt.','It scratched a pattern into the bark.','Die Gänge des Kupferstechers unter der Rinde sehen aus wie ein Sternmuster, wie bei einem Kupferstich.','The engraver beetle\'s tunnels under the bark look like a star pattern, like an old copper engraving.',['be','#6a3a20',{s:.7,len:1.2}]);
  bug('platinenwanze','Platinen-Wanze','Circuit stink bug','f','baum','tag',1,180,'Ihr Rücken sieht aus wie eine Platine.','Its back looks like a circuit board.','Baumwanzen haben Duftdrüsen. Bei Gefahr verbreiten sie einen Geruch, den Vögel nicht mögen.','Shield bugs have scent glands. When in danger, they spread a smell that birds do not like.',['be','#2a8a4a',{len:1,s:1.05,key:'platine',pat:grid('#c8ffc0',20)}]);
  bug('bombardierkaefer','Bombardierkäfer','Bombardier beetle','m','boden','nacht',3,950,'Puff! Er hat eine kleine Wolke abgeschossen.','Pop! It fired off a little cloud.','Der Bombardierkäfer mischt in seinem Hinterleib zwei Stoffe. Bei Gefahr spritzt er mit einem Knall eine heisse Wolke ab.','The bombardier beetle mixes two substances in its body. When in danger, it squirts a hot cloud with a pop.',['be','#3a5ad8',{s:.85,key:'bomb',pat:(x,w,h)=>{x.fillStyle='#ff7a2a';x.fillRect(0,0,w,h*.25)}}]);
  bug('gespinstmotte','Gespinstmotte','Ermine moth','f','baum','nacht',2,330,'Ihre Raupen haben einen ganzen Busch eingesponnen.','Its caterpillars spun a whole bush into silk.','Die Raupen der Gespinstmotte überziehen ganze Büsche mit Seide wie mit Kabeln. Dem Busch wachsen danach neue Blätter.','Ermine moth caterpillars cover whole bushes in silk, like cables. Afterwards the bush grows new leaves.',['bf','#f8f8f4','#f0f0ec','#e8e8e0',{fs:.38,hs:.3,raise:.25}]);

  /* ================= Tiefsee ================= */
  planet('tiefsee');
  fish('vampirtintenfisch','Vampirtintenfisch','Vampire squid','m','meer','M','nacht',4,2300,'Er sieht unheimlich aus, ist aber ganz harmlos.','It looks spooky, but it is totally harmless.','Der Vampirtintenfisch ist kein Vampir. Er frisst Flocken, die von oben herabsinken, und kann blau leuchten.','The vampire squid is no vampire. It eats flakes that sink down from above and can glow blue.',{H:.2,L:.5,W:1.1,back:'#6a1a2a',belly:'#8a2a3a',tail:'none',dorsal:'none',anal:false,ps:1.8,eye:.08,arms:8,armL:.8,pat:glowDots('#7ab8ff')});
  fish('dumbooktopus','Dumbo-Oktopus','Dumbo octopus','m','meer','M','immer',4,2200,'Er wedelt mit Flossen, die aussehen wie Ohren.','It flaps fins that look like ears.','Dumbo-Oktopusse leben tiefer im Meer als alle anderen Kraken. Sie schwimmen mit ohrenähnlichen Flossen.','Dumbo octopuses live deeper in the sea than any other octopus. They swim with ear-like fins.',{H:.3,L:.4,W:1,back:'#ffb8c8',belly:'#fff0f4',tail:'none',dorsal:'none',anal:false,ps:2.4,eye:.07,arms:8,armL:.5});
  fish('riesenassel','Riesenassel','Giant isopod','f','meer','L','nacht',3,1150,'Sie ist so gross wie eine Katze.','It is as big as a cat.','Die Riesenassel lebt am dunklen Meeresgrund. Sie kann sehr lange ohne Futter auskommen.','The giant isopod lives on the dark sea floor. It can go a very long time without food.',{H:.14,L:.7,W:1.8,back:'#c8b8a0',belly:'#e8dcc8',tail:'fan',dorsal:'none',anal:false,eyeY:.6,pat:stripes('#a0907a',8)});
  fish('tonnenaugenfisch','Tonnenaugenfisch','Barreleye','m','meer','S','nacht',5,4400,'Sein Kopf ist durchsichtig wie eine Glaskuppel.','Its head is see-through like a glass dome.','Der Tonnenaugenfisch hat einen durchsichtigen Kopf. Durch ihn hindurch schauen seine grünen Augen nach oben.','The barreleye has a see-through head. Its green eyes look upwards through it.',{H:.18,L:.55,back:'#3a3a4a',belly:'#6a6a7a',tail:'fork',dorsal:'std',eye:.07,eyeY:.9,beak:{len:.12,r:.08,col:'#d8f0ff',y:.05}});
  fish('blobfisch','Blobfisch','Blobfish','m','meer','M','nacht',3,1000,'Er sieht aus wie ein müder Pudding.','It looks like a tired pudding.','Der Blobfisch sieht nur an Land so schlaff aus. In der Tiefsee hält ihn der Wasserdruck in Form.','The blobfish only looks so floppy on land. In the deep sea, the water pressure keeps it in shape.',{H:.28,L:.55,W:1.2,back:'#ffc8c0',belly:'#fff0ec',tail:'round',dorsal:'none',eye:.05,gloss:1.3});
  fish('rippenqualle','Rippenqualle','Comb jelly','f','meer','S','nacht',2,420,'An ihr laufen Regenbogenlichter entlang.','Rainbow lights run along it.','Rippenquallen schwimmen mit winzigen Wimpern. Die brechen das Licht und sehen aus wie laufende Regenbogen.','Comb jellies swim with tiny hairs. These break up light and look like running rainbows.',{H:.3,L:.45,W:1,back:'#e8f4ff',belly:'#ffffff',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,gloss:1.8,pat:stripes('#c87aff',8,true)});
  bug('wasserspinne','Wasserspinne','Diving bell spider','f','wasser','immer',3,950,'Sie wohnt in einer Luftblase unter Wasser.','It lives in an air bubble under water.','Die Wasserspinne baut unter Wasser eine Glocke aus Seide und füllt sie mit Luft. Darin lebt sie.','The diving bell spider builds a bell of silk under water and fills it with air. It lives inside.',['sp','#5a4a3a',{body:.11}]);
  bug('wassermilbe','Wassermilbe','Water mite','f','wasser','tag',1,130,'Sie ist rot wie eine kleine Beere.','It is red like a little berry.','Wassermilben sind winzige rote Spinnentiere. Sie schwimmen mit acht Beinen durch Teiche.','Water mites are tiny red arachnids. They swim through ponds with eight legs.',['sp','#e8302a',{body:.1,leg:.12}]);
  bug('leuchtschnecke','Leucht-Schnecke','Glowing sea snail','f','boden','nacht',3,900,'Ihr Haus leuchtet grün im Dunkeln.','Its shell glows green in the dark.','Eine kleine Meeresschnecke kann ihr ganzes Haus zum Leuchten bringen. So erschreckt sie Angreifer.','A small sea snail can make its whole shell glow. That startles attackers.',['sn','#c8ffc0','#7ae86a']);
  bug('yetikrabbe','Yetikrabbe','Yeti crab','f','boden','immer',4,2400,'Sie hat haarige Arme wie ein Yeti.','It has hairy arms like a yeti.','Die Yetikrabbe lebt an heissen Quellen in der Tiefsee. Auf ihren haarigen Armen züchtet sie Bakterien, die sie frisst.','The yeti crab lives near hot springs in the deep sea. It grows bacteria on its hairy arms and eats them.',['kr','#f4f0e8',{claw:.08}]);
  bug('pompejiwurm','Pompeji-Wurm','Pompeii worm','m','boden','immer',4,2100,'Er wohnt neben einem heissen Schlot.','It lives next to a hot vent.','Der Pompeji-Wurm lebt an heissen Quellen am Meeresgrund. Er hält mehr Hitze aus als fast jedes andere Tier.','The Pompeii worm lives near hot springs on the sea floor. It can take more heat than almost any other animal.',['ra',['#ff8a8a','#f4e8d8','#ff8a8a'],7]);
  bug('schuppenfussschnecke','Schuppenfuss-Schnecke','Scaly-foot snail','f','boden','nacht',5,4300,'Sie trägt eine Rüstung aus Eisen.','It wears armour made of iron.','Die Schuppenfuss-Schnecke lebt in der Tiefsee. Ihr Haus und ihr Fuss sind mit Eisen gepanzert.','The scaly-foot snail lives in the deep sea. Its shell and foot are armoured with iron.',['sn','#3a3a44','#6a6a74']);

  /* ================= Wetterwerk ================= */
  planet('wetterwerk');
  fish('wolkenkardinal','Wolkenkardinal','White Cloud minnow','m','teich','S','immer',1,150,'Er kommt vom Weisse-Wolken-Berg.','It comes from the White Cloud Mountain.','Der Kardinalfisch stammt vom Weisse-Wolken-Berg in China. Er mag kühles Wasser.','This little fish comes from White Cloud Mountain in China. It likes cool water.',{H:.15,L:.45,back:'#8a7a5a',belly:'#f4ecd8',fin:'#ff4a2a',tail:'fork',dorsal:'std',pat:stripes('#ffd23f',1,true)});
  fish('barometerbarsch','Barometer-Barsch','Barometer perch','m','teich','M','tag',2,400,'Er weiss vor mir, dass es regnen wird.','It knows before I do that it is going to rain.','Viele Fische spüren Änderungen im Luftdruck mit ihrer Schwimmblase, zum Beispiel vor einem Gewitter.','Many fish can feel changes in air pressure with their swim bladder, for example before a storm.',{H:.2,L:.6,back:'#5a8a5a',belly:'#f0f8e8',fin:'#ff7a3a',tail:'fork',dorsal:'spiky',pat:(x,w,h)=>{x.strokeStyle='#2a4a2a';x.lineWidth=3;x.beginPath();x.arc(w*.5,h*.5,30,0,TAU);x.moveTo(w*.5,h*.5);x.lineTo(w*.5+20,h*.5-14);x.stroke()}});
  fish('schirmqualle','Schirmqualle','Moon jellyfish','f','meer','M','immer',2,380,'Sie sieht aus wie ein durchsichtiger Regenschirm.','It looks like a see-through umbrella.','Ohrenquallen haben kein Gehirn und kein Herz. Trotzdem schwimmen sie seit Millionen Jahren durchs Meer.','Moon jellyfish have no brain and no heart. Even so, they have been swimming through the sea for millions of years.',{H:.32,L:.3,W:1,back:'#e8f0ff',belly:'#f8fcff',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,gloss:1.6,arms:6,armL:.7,armCol:'#e8f0ff',pat:(x,w,h)=>{x.strokeStyle='#c8a8ff';x.lineWidth=5;for(let i=0;i<4;i++){x.beginPath();x.arc(w*(.2+i*.2),h*.5,14,0,TAU);x.stroke()}}});
  fish('schneeflockenmuraene','Schneeflocken-Muräne','Snowflake moray','f','meer','L','nacht',3,1100,'Sie hat Flecken wie Schneeflocken.','It has spots like snowflakes.','Die Schneeflocken-Muräne frisst vor allem Krebse. Sie hat stumpfe Zähne, mit denen sie Panzer knackt.','The snowflake moray mainly eats crabs. It has blunt teeth for cracking shells.',{H:.09,L:1.05,back:'#f4f0e8',belly:'#ffffff',tail:'none',dorsal:'long',dz:.1,ds:2.4,anal:'long',pect:false,pat:(x,w,h)=>{x.fillStyle='#2a2a2a';for(let i=0;i<24;i++){const a=(i*67)%w,b=(i*41)%h;x.fillRect(a-8,b-2,16,4);x.fillRect(a-2,b-8,4,16)}}});
  fish('sonnenuntergangslippfisch','Sonnenuntergangs-Lippfisch','Sunset wrasse','m','meer','M','tag',2,440,'Er hat alle Farben eines Sonnenuntergangs.','It has all the colours of a sunset.','Manche Lippfische wechseln im Laufe ihres Lebens vom Weibchen zum Männchen und bekommen dann neue Farben.','Some wrasses change from female to male during their life and then get new colours.',{H:.15,L:.7,back:'#ff8a3a',belly:'#ffe060',tail:'moon',dorsal:'long',pat:stripes('#ff4a8a',3,true)});
  fish('schlangenkopf','Schlangenkopffisch','Snakehead','m','teich','L','nacht',3,1050,'Er hat einen Kopf wie eine kleine Schlange.','It has a head like a little snake.','Schlangenkopffische atmen Luft. Nach Regen können sie sogar ein Stück über feuchtes Land kriechen.','Snakeheads breathe air. After rain, they can even wriggle a short way across damp land.',{H:.13,L:.95,back:'#5a5a3a',belly:'#d8d0b0',tail:'round',dorsal:'long',dz:.1,ds:2.2,anal:'long',pat:dots('#2a2a1a',18,9)});
  bug('regenbogenblattkaefer','Regenbogen-Blattkäfer','Rainbow leaf beetle','m','blume','tag',4,2100,'Er hat Streifen in allen Regenbogenfarben.','It has stripes in every colour of the rainbow.','Der Regenbogen-Blattkäfer lebt in den Bergen und ist sehr selten. Er schimmert grün, rot, blau und golden.','The rainbow leaf beetle lives in the mountains and is very rare. It shimmers green, red, blue and gold.',['be','#2ac87a',{s:.8,key:'regenbogen',pat:(x,w,h)=>{['#ff3a3a','#ffd23f','#2ac87a','#3a7aff','#9a3aff'].forEach((c,i)=>{x.fillStyle=c;x.fillRect(i*w/5,0,w/5,h)})}}]);
  bug('schneeschnake','Schnee-Schnake','Snow fly','f','boden','tag',3,880,'Sie hat keine Flügel und läuft über den Schnee.','It has no wings and walks across the snow.','Die Schnee-Schnake hat keine Flügel. Sie ist im Winter aktiv und krabbelt sogar bei Frost über den Schnee.','The snow fly has no wings. It is active in winter and crawls over the snow even when it is freezing.',['sp','#3a3a44',{body:.07,leg:.3}]);
  bug('regenmuecke','Regenmücke','Rain midge','f','luft','tag',1,110,'Sie fliegt sogar im Regen herum.','It flies around even in the rain.','Mücken überleben es, wenn ein Regentropfen sie trifft. Sie sind so leicht, dass der Tropfen sie einfach mitnimmt.','Midges survive being hit by a raindrop. They are so light that the drop just carries them along.',['li','#6a6a5a','#e8f4ff',{len:.24,ws:.1,two:true}]);
  bug('heidelibelle','Sonnen-Heidelibelle','Red darter','f','luft','tag',2,360,'Sie sonnt sich auf einem warmen Stein.','It is sunbathing on a warm rock.','Heidelibellen sitzen gern in der Sonne, um sich aufzuwärmen. Erst wenn sie warm sind, fliegen sie gut.','Darters like to sit in the sun to warm up. Only once they are warm can they fly well.',['li','#e8402a','#fff4e8',{len:.45}]);
  bug('rotewegschnecke','Rote Wegschnecke','Red slug','f','boden','nacht',1,130,'Nach dem Regen kommt sie heraus.','It comes out after the rain.','Nacktschnecken brauchen Feuchtigkeit. Darum sieht man sie vor allem nach dem Regen.','Slugs need moisture. That is why you mostly see them after the rain.',['ra',['#e85a2a','#f06a3a','#e85a2a'],6]);
  bug('oedlandschrecke','Blauflügel-Ödlandschrecke','Blue-winged grasshopper','f','stein','tag',2,380,'Beim Fliegen blitzen blaue Flügel auf.','Blue wings flash when it flies.','Die Blauflügel-Ödlandschrecke ist auf Steinen fast unsichtbar. Im Flug zeigt sie leuchtend blaue Flügel.','The blue-winged grasshopper is almost invisible on stones. In flight it shows bright blue wings.',['gr','#8a8070',{wing:'#3a8ad8'}]);

  /* ================= Nachtmarkt ================= */
  planet('nachtmarkt');
  fish('loewenkopfgoldfisch','Löwenkopf-Goldfisch','Lionhead goldfish','m','teich','S','nacht',2,420,'Er hat eine Mähne wie ein kleiner Löwe.','It has a mane like a little lion.','Der Löwenkopf ist ein gezüchteter Goldfisch ohne Rückenflosse. Auf seinem Kopf wächst eine weiche Haube.','The lionhead is a bred goldfish with no back fin. A soft hood grows on its head.',{H:.28,L:.45,back:'#ff6a2a',belly:'#fff0d8',tail:'fancy',dorsal:'none',ts:1.2,pat:dots('#ff9a5a',20,7)});
  fish('blasenauge','Blasenauge','Bubble-eye goldfish','n','teich','S','nacht',3,900,'Es hat zwei Blasen unter den Augen.','It has two bubbles under its eyes.','Das Blasenauge ist ein gezüchteter Goldfisch mit weichen Wasserblasen unter den Augen.','The bubble-eye is a bred goldfish with soft water bubbles under its eyes.',{H:.24,L:.45,back:'#ffb030',belly:'#fff4d8',tail:'fancy',dorsal:'none',eye:.09,eyeY:.6});
  fish('kampffisch','Siamesischer Kampffisch','Siamese fighting fish','m','teich','S','tag',2,460,'Seine Flossen wehen wie ein Seidenkleid.','Its fins flow like a silk dress.','Kampffisch-Männchen haben lange, bunte Flossen. Sie atmen zusätzlich Luft an der Oberfläche.','Male Siamese fighting fish have long, colourful fins. They also breathe air at the surface.',{H:.16,L:.5,back:'#3a3aff',belly:'#c83aff',tail:'fancy',ts:1.6,dorsal:'sail',anal:'long',as:1.6});
  fish('ayu','Ayu','Ayu','m','fluss','M','tag',2,400,'Er riecht ein bisschen nach Melone.','It smells a little like melon.','Der Ayu lebt nur ein Jahr. Er frisst Algen von Steinen und riecht ein bisschen nach Melone.','The ayu lives for only one year. It eats algae off stones and smells a little like melon.',{H:.14,L:.7,back:'#7a8a5a',belly:'#f4f4e0',tail:'fork',dorsal:'std',pat:stripes('#ffd23f',1,true)});
  fish('leuchtkalmar','Leuchtkalmar','Firefly squid','m','meer','S','nacht',3,1000,'Er funkelt blau wie ein Sternenhimmel.','It sparkles blue like a starry sky.','Im Frühling leuchten in einer Bucht in Japan Millionen Leuchtkalmare. Das Wasser funkelt dann blau.','In spring, millions of firefly squid glow in a bay in Japan. The water then sparkles blue.',{H:.12,L:.5,back:'#5a6aa8',belly:'#a8b8ff',tail:'spade',dorsal:'none',anal:false,pect:false,eye:.06,arms:8,armL:.6,pat:glowDots('#7ab8ff')});
  fish('mondscheinsepiole','Mondschein-Sepiole','Bobtail squid','f','meer','S','nacht',4,2000,'Sie leuchtet so sanft wie der Mond.','It glows as softly as the moon.','Die Sepiole hat leuchtende Bakterien im Bauch. Ihr Licht passt sie dem Mondlicht an, so wirft sie keinen Schatten.','The bobtail squid has glowing bacteria in its belly. It matches their light to the moonlight, so it casts no shadow.',{H:.26,L:.35,W:1.1,back:'#e8a080',belly:'#fff0e8',tail:'none',dorsal:'none',anal:false,ps:1.4,eye:.08,arms:8,armL:.5});
  bug('ligusterschwaermer','Ligusterschwärmer','Privet hawk-moth','m','luft','nacht',3,920,'Er ist rosa gestreift und ganz schön gross.','It has pink stripes and is pretty big.','Der Ligusterschwärmer ist einer der grössten Falter bei uns. Er trinkt Nektar mit einem langen Rüssel.','The privet hawk-moth is one of the biggest moths around here. It drinks nectar with a long tongue.',['bf','#8a7a6a','#ff8ab0','#4a3a3a',{fs:.55,hs:.36,raise:.3}]);
  bug('ordensband','Blaues Ordensband','Clifden nonpareil','n','baum','nacht',4,2100,'Es hat ein blaues Band unter den grauen Flügeln.','It has a blue band under its grey wings.','Das Blaue Ordensband sieht von oben grau aus wie Rinde. Erst im Flug zeigt es sein blaues Band.','The Clifden nonpareil looks grey like bark from above. Only in flight does it show its blue band.',['bf','#9a9a90',x=>{x.fillStyle='#2a2a34';x.fillRect(0,-1,1,2);x.fillStyle='#5a8aff';x.fillRect(0,-.6,1,.25)},'#5a5a54',{fs:.5,hs:.44}]);
  bug('nachtigallgrashuepfer','Nachtigall-Grashüpfer','Bow-winged grasshopper','m','boden','tag',1,150,'Er singt wie ein kleiner Vogel.','It sings like a little bird.','Der Nachtigall-Grashüpfer singt besonders laut und schön. Er reibt dafür die Hinterbeine an den Flügeln.','The bow-winged grasshopper sings especially loudly and beautifully. It rubs its back legs against its wings.',['gr','#7a8a4a',{wing:'#ff8a3a'}]);
  bug('holunderspanner','Holunderspanner','Swallow-tailed moth','m','luft','nacht',2,380,'Er ist hellgelb wie eine Laterne.','It is pale yellow like a lantern.','Der Holunderspanner fliegt im Sommer nachts zu Lampen. Seine Hinterflügel haben kleine Schwänzchen.','The swallow-tailed moth flies to lamps on summer nights. Its hind wings have little tails.',['bf','#fff4b0','#fff0a0','#e8d890',{fs:.5,hs:.44}]);
  bug('taktgluehwurm','Takt-Glühwürmchen','Synchronous firefly','n','luft','nacht',4,2300,'Es blinkt im gleichen Takt wie alle anderen.','It blinks in time with all the others.','In manchen Wäldern blinken Tausende Glühwürmchen gleichzeitig im selben Takt. Wie sie das schaffen, wird noch erforscht.','In some forests, thousands of fireflies flash at exactly the same time. How they do it is still being studied.',['be','#3a3028',{s:.75,len:1.3,glow:'#fff06a'}]);
  bug('schnurfuesser','Schnurfüsser','Snake millipede','m','boden','nacht',1,140,'Er rollt sich zu einer Schnecke zusammen.','It rolls up into a spiral.','Schnurfüsser rollen sich bei Gefahr zu einer flachen Spirale zusammen. Ihr harter Panzer schützt sie.','Snake millipedes roll into a flat spiral when in danger. Their hard armour protects them.',['ra',['#2a2224','#3a3234'],9]);

  /* ================= Bauklotz ================= */
  planet('bauklotz');
  fish('schneckenbuntbarsch','Schneckenbuntbarsch','Shell-dwelling cichlid','m','teich','S','tag',2,400,'Er wohnt in einem leeren Schneckenhaus.','It lives in an empty snail shell.','Ein winziger Buntbarsch aus dem Tanganjikasee wohnt in leeren Schneckenhäusern und baut daraus ganze Siedlungen.','A tiny cichlid from Lake Tanganyika lives in empty snail shells and builds whole villages out of them.',{H:.18,L:.4,back:'#c8b890',belly:'#f4ecd8',tail:'round',dorsal:'long',pat:stripes('#8a7a5a',5)});
  fish('kieferfisch','Kieferfisch','Jawfish','m','meer','S','tag',2,420,'Er hat einen Kieselstein im Maul getragen.','It was carrying a pebble in its mouth.','Kieferfische bauen Höhlen im Sand und tragen dafür Steine mit dem Maul. Die Männchen halten die Eier im Maul.','Jawfish build burrows in the sand and carry stones in their mouths to do it. The males keep the eggs in their mouths.',{H:.15,L:.5,back:'#ffd23f',belly:'#fff8d8',tail:'round',dorsal:'long',eye:.07,pat:(x,w,h)=>{x.fillStyle='#45a0ff';x.fillRect(0,0,w*.18,h);x.fillRect(w*.82,0,w*.18,h)}});
  fish('steinbeisser','Steinbeisser','Spined loach','m','fluss','S','nacht',2,360,'Er hat sich im Sand eingegraben.','It had buried itself in the sand.','Steinbeisser graben sich in den Sand ein, bis nur noch die Augen herausschauen. Unter den Augen haben sie einen kleinen Stachel.','Spined loaches dig themselves into the sand until only their eyes peek out. They have a small spine under each eye.',{H:.1,L:.55,back:'#e8d8b0',belly:'#fff8e8',tail:'round',dorsal:'std',dz:.4,pat:dots('#6a5a3a',20,6)});
  fish('wuerfelqualle','Würfelqualle','Box jellyfish','f','meer','M','nacht',3,1000,'Sie ist eckig wie ein Würfel.','It is square like a dice.','Würfelquallen haben 24 Augen. Manche davon sehen sogar richtige Bilder.','Box jellyfish have 24 eyes. Some of them can even see real images.',{H:.3,L:.35,W:1,back:'#e8f8ff',belly:'#ffffff',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,gloss:1.8,arms:4,armL:1.1,armCol:'#e8f8ff',pat:grid('#a8d8ff',40)});
  fish('waechtergrundel','Wächtergrundel','Watchman goby','f','meer','S','tag',2,380,'Sie passt auf die Baustelle auf.','It is watching over the building site.','Die Wächtergrundel lebt mit einem Krebs zusammen. Der Krebs baut die Höhle, die Grundel passt auf Gefahren auf.','The watchman goby lives together with a shrimp. The shrimp builds the burrow, the goby watches out for danger.',{H:.14,L:.55,back:'#ffd890',belly:'#fff8e8',tail:'round',dorsal:'hi',pat:dots('#45a0ff',18,4)});
  fish('seepocke','Seepocke','Barnacle','f','meer','S','immer',1,120,'Sie hat sich mit dem Kopf an einen Stein geklebt.','It glued itself to a stone head first.','Seepocken kleben sich mit dem Kopf an Felsen fest und fangen dann Futter mit ihren Beinen.','Barnacles glue themselves to rocks head first and then catch food with their legs.',{H:.3,L:.35,W:1,back:'#e8e0d0',belly:'#f8f4ec',tail:'none',dorsal:'none',anal:false,pect:false,eye:.001,pat:stripes('#c8c0b0',6,true)});
  bug('wollbiene','Wollbiene','Wool carder bee','f','blume','tag',2,350,'Sie hat Pflanzenwolle zu einem Nest gebaut.','It built a nest out of plant wool.','Wollbienen schaben weiche Haare von Pflanzen ab und bauen daraus ihre Nester, wie mit Watte.','Wool carder bees scrape soft hairs off plants and build their nests with them, like cotton wool.',['hu','#2a2224','#ffd23f',{s:.85}]);
  bug('trichterwickler','Trichterwickler','Leaf-roller weevil','m','baum','tag',3,880,'Er hat ein Blatt wie eine Tüte aufgerollt.','It rolled up a leaf like a paper cone.','Trichterwickler rollen Blätter kunstvoll zu kleinen Tüten. Darin legen sie ihre Eier ab.','Leaf-roller weevils skilfully roll leaves into little cones. They lay their eggs inside.',['be','#3a6ad8',{horn:true,s:.75,len:1.2}]);
  bug('flossameise','Floss-Ameise','Fire ant','f','boden','tag',3,900,'Sie baut mit ihren Freundinnen ein Floss.','It builds a raft with its friends.','Bei Hochwasser halten sich Feuerameisen aneinander fest und bauen aus ihren Körpern ein schwimmendes Floss.','During floods, fire ants hold on to each other and build a floating raft out of their bodies.',['ke',['#c84a2a','#a83a2a','#c84a2a'],3,.06]);
  bug('tapezierspinne','Tapezierspinne','Purseweb spider','f','boden','nacht',3,860,'Sie wohnt in einer Röhre aus Seide.','It lives in a tube made of silk.','Die Tapezierspinne baut eine Röhre aus Seide, die wie eine Socke aus dem Boden ragt. Sie wartet darin auf Beute.','The purseweb spider builds a silk tube that sticks out of the ground like a sock. It waits inside for prey.',['sp','#3a2a44',{body:.12,leg:.18}]);
  bug('baumhummel','Baumhummel','Tree bumblebee','f','baum','tag',2,360,'Sie wohnt in einem Vogelhäuschen.','It lives in a birdhouse.','Baumhummeln nisten gern hoch oben, zum Beispiel in leeren Vogelhäuschen.','Tree bumblebees like to nest high up, for example in empty birdhouses.',['hu','#c87a3a','#2a2224',{s:.95}]);
  bug('pyramideneule','Pyramideneule','Copper underwing','f','luft','nacht',2,330,'Ihre Raupe hat einen Buckel wie eine Pyramide.','Its caterpillar has a hump like a pyramid.','Die Raupe der Pyramideneule hat am Ende einen Höcker, der aussieht wie eine kleine Pyramide.','The copper underwing caterpillar has a hump at the end that looks like a little pyramid.',['bf','#7a6a5a','#c8803a','#4a3a2a',{fs:.46,hs:.4}]);

  /* ================= Schoner ================= */
  planet('schoner');
  fish('halfterfisch','Halfterfisch','Moorish idol','m','meer','M','tag',3,1050,'Er hat eine lange weisse Fahne.','It has a long white banner.','Der Halfterfisch hat eine sehr lange Rückenflosse wie eine Fahne. Er frisst am liebsten Schwämme.','The Moorish idol has a very long back fin like a banner. It likes to eat sponges best.',{H:.32,L:.45,W:.45,back:'#fff4d8',belly:'#ffffff',fin:'#ffd23f',tail:'fork',dorsal:'sail',ds:1.8,beak:{len:.08,r:.03,col:'#ff8a3a'},pat:stripes('#1a1a24',2)});
  fish('blaupunktrochen','Blaupunktrochen','Bluespotted ray','m','meer','M','nacht',3,980,'Er hat leuchtend blaue Punkte wie Pixel.','It has bright blue spots like pixels.','Der Blaupunktrochen versteckt sich tagsüber unter Korallen. Seine blauen Punkte warnen andere Fische.','The bluespotted ray hides under corals during the day. Its blue spots warn other fish.',{H:.07,L:.6,W:2.4,back:'#c8a060',belly:'#f4ecd8',tail:'spade',dorsal:'none',anal:false,pat:dots('#2a8aff',24,7)});
  fish('segelflossendoktor','Gelber Segelflossendoktor','Yellow tang','m','meer','M','tag',2,440,'Er ist so gelb wie eine Zitrone.','It is as yellow as a lemon.','Doktorfische haben neben dem Schwanz eine scharfe Klinge wie ein Skalpell. Daher kommt ihr Name.','Surgeonfish have a sharp blade next to their tail like a scalpel. That is where their name comes from.',{H:.32,L:.45,W:.5,back:'#ffe020',belly:'#fff4a0',tail:'fork',dorsal:'sail',anal:'long',beak:{len:.06,r:.03,col:'#ffe020'}});
  fish('ammenhai','Ammenhai','Nurse shark','m','meer','XL','nacht',4,2600,'Er hat ein Nickerchen auf dem Grund gemacht.','It was taking a nap on the bottom.','Ammenhaie können still auf dem Grund liegen und dabei weiteratmen. Sie pumpen Wasser über ihre Kiemen.','Nurse sharks can lie still on the bottom and keep breathing. They pump water over their gills.',{H:.14,L:1.1,back:'#c8a070',belly:'#f4e8d0',tail:'spade',ts:1.3,dorsal:'std',dz:.3});
  fish('gaehngrundel','Gähn-Grundel','Yawning goby','f','teich','S','immer',1,130,'Sie hat gegähnt, als ich sie aufgeweckt habe.','It yawned when I woke it up.','Auch Fische gähnen. Sie reissen das Maul weit auf, oft wenn sie aufwachen.','Fish yawn too. They open their mouths wide, often when they wake up.',{H:.15,L:.5,back:'#a090c0',belly:'#f4f0ff',tail:'round',dorsal:'hi',eye:.06,pat:dots('#6a5a90',14,5)});
  fish('kometenfisch','Kometenfisch','Comet','m','meer','M','nacht',4,2000,'Er hat Punkte wie ein Sternenhimmel.','It has spots like a starry sky.','Der Kometenfisch hat einen Augenfleck am Schwanz. Steckt er den Kopf in eine Höhle, sieht sein Schwanz aus wie der Kopf einer Muräne.','The comet has an eyespot on its tail. When it hides its head in a cave, its tail looks like the head of a moray eel.',{H:.24,L:.5,back:'#1a1a3a',belly:'#2a2a4a',tail:'round',dorsal:'sail',anal:'long',pat:dots('#ffffff',40,3)});
  bug('schlafbiene','Schlafbiene','Sleeping bee','f','blume','nacht',2,340,'Sie schläft und hält sich mit dem Mund am Stängel fest.','It is sleeping, holding onto a stem with its mouth.','Manche Wildbienen-Männchen schlafen, indem sie sich mit den Kiefern an einem Stängel festbeissen.','Some male wild bees sleep by biting onto a stem with their jaws.',['hu','#3a3a44','#c8b090',{s:.75}]);
  bug('labyrinthspinne','Labyrinthspinne','Labyrinth spider','f','blume','nacht',2,360,'Ihr Netz ist ein richtiges Labyrinth.','Its web is a real maze.','Die Labyrinthspinne baut ein dichtes Netz mit einer Röhre. Hinten hat die Röhre einen Notausgang.','The labyrinth spider builds a dense web with a tube. At the back the tube has an emergency exit.',['sp','#8a7a5a',{body:.11,leg:.24}]);
  bug('fensterfliege','Fensterfliege','Window fly','f','luft','tag',1,120,'Sie sitzt immer am Fenster.','It always sits at the window.','Die Fensterfliege sitzt oft an Fensterscheiben. Ihre Larven fressen Larven von anderen Insekten.','The window fly often sits on window panes. Its larvae eat the larvae of other insects.',['li','#2a2224','#e8f4ff',{len:.28,ws:.11,two:true}]);
  bug('mohnbiene','Mohnbiene','Poppy bee','f','blume','tag',4,2000,'Ihr Nest ist mit roten Mohnblättern tapeziert.','Its nest is wallpapered with red poppy petals.','Die Mohnbiene kleidet ihr Nest im Boden mit roten Mohnblütenblättern aus, wie mit Tapete.','The poppy bee lines its nest in the ground with red poppy petals, like wallpaper.',['hu','#3a3a3a','#e8302a',{s:.8}]);
  bug('abendpfauenauge','Abendpfauenauge','Eyed hawk-moth','n','baum','nacht',3,950,'Es hat plötzlich zwei grosse Augen auf den Flügeln gezeigt!','It suddenly showed two big eyes on its wings!','Bei Gefahr zeigt das Abendpfauenauge zwei blaue Augenflecken auf den Hinterflügeln. Das erschreckt Vögel.','When in danger, the eyed hawk-moth shows two blue eyespots on its hind wings. That startles birds.',['bf','#a08a7a',x=>{x.fillStyle='#ff9ab0';x.fillRect(0,-1,1,2);x.fillStyle='#1a1a24';x.beginPath();x.arc(.55,-.5,.18,0,TAU);x.fill();x.fillStyle='#4a8aff';x.beginPath();x.arc(.55,-.5,.11,0,TAU);x.fill()},'#6a5a4a',{fs:.48,hs:.4}]);
  bug('roehrenspinne','Rote Röhrenspinne','Ladybird spider','f','boden','tag',4,2200,'Sie sieht aus wie ein Marienkäfer mit acht Beinen.','It looks like a ladybird with eight legs.','Die Männchen der Röhrenspinne sind rot mit schwarzen Punkten wie ein Marienkäfer. Sie sind sehr selten.','Male ladybird spiders are red with black spots like a ladybird. They are very rare.',['sp','#e8302a',{body:.13,leg:.16}]);

  /* ================= Honigwabe ================= */
  planet('honigwabe');
  fish('wabenkofferfisch','Waben-Kofferfisch','Honeycomb cowfish','m','meer','M','tag',3,960,'Sein Panzer ist gemustert wie eine Honigwabe.','Its armour is patterned like a honeycomb.','Kofferfische haben einen harten Panzer aus Knochenplatten. Beim Waben-Kofferfisch sehen die Platten aus wie Waben.','Cowfish have a hard shell of bony plates. On the honeycomb cowfish, the plates look like honeycomb.',{H:.26,L:.55,W:1,back:'#e8b040',belly:'#fff4c8',tail:'round',dorsal:'std',pat:(x,w,h)=>{x.strokeStyle='#8a5a1a';x.lineWidth=3;for(let j=0;j<9;j++)for(let i=0;i<9;i++){const cx=i*32+(j%2)*16,cy=j*28;x.beginPath();for(let k=0;k<6;k++){const a=k*PI/3;x.lineTo(cx+14*Math.cos(a),cy+14*Math.sin(a))}x.closePath();x.stroke()}}});
  fish('wabenmuraene','Waben-Muräne','Honeycomb moray','f','meer','L','nacht',3,1150,'Ihre Haut sieht aus wie ein Bienenstock.','Its skin looks like a beehive.','Die Waben-Muräne hat ein Netzmuster auf der Haut. Sie versteckt sich tagsüber in Felsspalten.','The honeycomb moray has a net pattern on its skin. It hides in rock cracks during the day.',{H:.09,L:1.05,back:'#ffd23f',belly:'#fff4c0',tail:'none',dorsal:'long',dz:.1,ds:2.4,anal:'long',pect:false,pat:grid('#4a3a1a',22)});
  fish('hummelgrundel','Hummelgrundel','Bumblebee goby','f','teich','S','tag',2,380,'Sie ist gestreift wie eine Hummel.','It is striped like a bumblebee.','Die Hummelgrundel ist nur so gross wie ein Finger. Sie hat gelb-schwarze Streifen wie eine Hummel.','The bumblebee goby is only as big as a finger. It has yellow and black stripes like a bumblebee.',{H:.15,L:.42,back:'#ffd23f',belly:'#fff4b0',tail:'round',dorsal:'hi',pat:stripes('#1a1a24',4)});
  fish('goldbarbe','Goldbarbe','Gold barb','f','teich','S','immer',1,150,'Sie glänzt wie ein Tropfen Honig.','It shines like a drop of honey.','Goldbarben sind friedliche Schwarmfische. Sie wühlen gern im Boden nach Futter.','Gold barbs are peaceful schooling fish. They like to dig in the bottom for food.',{H:.2,L:.48,back:'#ffc830',belly:'#fff4c0',fin:'#ff8a2a',tail:'fork',dorsal:'std',pat:dots('#2a2224',4,5)});
  fish('zitronensalmler','Zitronensalmler','Lemon tetra','m','teich','S','tag',1,140,'Er ist gelb wie eine Zitrone.','It is yellow like a lemon.','Zitronensalmler werden gelber, wenn sie viele bunte Futterpflanzen und Insekten fressen.','Lemon tetras get more yellow when they eat lots of colourful food.',{H:.24,L:.45,back:'#fff080',belly:'#fffcd8',fin:'#ffd23f',tail:'fork',dorsal:'std',anal:'long',gloss:1.4});
  fish('ruderfusskrebs','Ruderfusskrebs','Copepod','m','teich','S','immer',2,320,'Er paddelt mit seinen langen Fühlern.','It paddles with its long antennae.','Ruderfusskrebse sind winzig, aber es gibt unvorstellbar viele. Sie gehören zu den häufigsten Tieren der Erde.','Copepods are tiny, but there are unbelievably many of them. They are among the most common animals on Earth.',{H:.18,L:.4,W:.8,back:'#ffb8a0',belly:'#fff0e8',tail:'fork',dorsal:'none',anal:false,eye:.04,eyeY:.5,arms:2,armL:1.1,pat:stripes('#e8806a',5)});
  bug('seidenbiene','Seidenbiene','Plasterer bee','f','blume','tag',2,330,'Ihr Nest glänzt wie Seide.','Its nest shines like silk.','Seidenbienen streichen ihre Nester mit einem glänzenden Stoff aus, der wie Kunststoff wasserdicht ist.','Plasterer bees coat their nests with a shiny substance that is waterproof like plastic.',['hu','#8a7a5a','#f4e8c8',{s:.8}]);
  bug('sandbiene','Sandbiene','Mining bee','f','boden','tag',1,170,'Sie hat einen kleinen Sandhügel gebaut.','It built a little hill of sand.','Sandbienen graben ihre Nester in den Boden. Vor dem Eingang liegt ein kleiner Haufen Sand.','Mining bees dig their nests in the ground. A small heap of sand lies in front of the entrance.',['hu','#c87a3a','#8a4a2a',{s:.8}]);
  bug('hosenbiene','Hosenbiene','Pantaloon bee','f','blume','tag',3,900,'Sie trägt dicke gelbe Pollenhosen.','It wears thick yellow pollen trousers.','Die Hosenbiene hat sehr lange Haare an den Hinterbeinen. Wenn sie voller Pollen sind, sieht es aus wie dicke Hosen.','The pantaloon bee has very long hairs on its back legs. When they are full of pollen, it looks like baggy trousers.',['hu','#5a4a3a','#ffd23f',{s:.9}]);
  bug('hummelschwaermer','Hummelschwärmer','Bee hawk-moth','m','blume','tag',3,950,'Er schwirrt wie eine Hummel, ist aber ein Falter.','It buzzes like a bumblebee, but it is a moth.','Der Hummelschwärmer hat durchsichtige Flügel und einen pelzigen Körper. Er trinkt Nektar im Schwirrflug.','The bee hawk-moth has see-through wings and a furry body. It drinks nectar while hovering.',['hu','#c8a040','#5a8a3a',{s:1}]);
  bug('krabbenspinne','Krabbenspinne','Crab spider','f','blume','tag',2,400,'Sie hat die gleiche Farbe wie ihre Blüte.','It is the same colour as its flower.','Manche Krabbenspinnen können ihre Farbe ändern, damit sie zur Blüte passen, auf der sie sitzen.','Some crab spiders can change colour to match the flower they are sitting on.',['sp','#fff080',{body:.12,leg:.18}]);
  bug('bienenkaefer','Bienenkäfer','Bee beetle','m','blume','tag',3,880,'Er ist rot-blau gestreift und sitzt gern auf Blüten.','It has red and blue stripes and likes sitting on flowers.','Der Bienenkäfer sitzt gern auf Doldenblüten. Seine Larven leben in den Nestern von Wildbienen.','The bee beetle likes to sit on umbel flowers. Its larvae live in the nests of wild bees.',['be','#e8302a',{len:1.3,s:.8,key:'bienenkaefer',pat:stripes('#2a3a8a',3)}]);

  ARTEN3.done();
})();
