/* =====================================================================
   CYBORG-LABOR · arten4.js · Inhalte 2.0, zweiter Schub (Teil 2)
   Die acht Themen-Planeten (Urzeit, Dschungel, Metro, Wolkenarchipel,
   Bibliothek, Uhrwerk, Klang, Origami) bekommen je sieben Fische und
   sieben Insekten dazu, damit jeder Planet 12 und 12 hat.
   ===================================================================== */
(()=>{
  const{planet,fish,bug}=ARTEN3;const{stripes,dots,grid,patch,glowDots}=NH.A2;

  /* ================= Urzeit ================= */
  planet('urzeit');
  fish('pfeilschwanzkrebs','Pfeilschwanzkrebs','Horseshoe crab','m','meer','L','nacht',3,1200,'Er sieht aus wie ein Helm mit Schwanz.','It looks like a helmet with a tail.','Pfeilschwanzkrebse gab es schon vor den Dinosauriern. Ihr Blut ist blau.','Horseshoe crabs were around even before the dinosaurs. Their blood is blue.',{H:.1,L:.75,W:2.2,back:'#8a6a3a',belly:'#d8c090',tail:'none',dorsal:'none',anal:false,pect:false,pat:grid('#6a4a2a',40)});
  fish('loeffelstoer','Löffelstör','Paddlefish','m','meer','XL','tag',4,2600,'Seine Nase ist lang und platt wie ein Löffel.','Its nose is long and flat like a spoon.','Der Löffelstör spürt mit seiner langen Schnauze winzige elektrische Signale von Beutetieren im trüben Wasser.','The paddlefish senses tiny electric signals from prey in murky water with its long snout.',{H:.16,L:1.1,back:'#5a6a7a',belly:'#e0e4ea',tail:'fork',dorsal:'tri',beak:{len:.5,r:.07,flat:2.6}});
  fish('floesselhecht','Flösselhecht','Bichir','m','teich','M','nacht',3,950,'Auf seinem Rücken stehen viele kleine Segel.','It has lots of little sails on its back.','Flösselhechte haben Lungen und atmen auch Luft. Ihre Familie ist sehr, sehr alt.','Bichirs have lungs and also breathe air. Their family is very, very old.',{H:.1,L:.95,back:'#6a5a3a',belly:'#e8d8b0',tail:'round',dorsal:'spiky',dz:.3,ds:1.6,pat:dots('#3a2a1a',22,6)});
  fish('triops','Urzeitkrebs','Tadpole shrimp','m','teich','S','tag',2,380,'Er hat drei Augen auf dem Panzer.','It has three eyes on its shell.','Die Eier von Urzeitkrebsen überleben jahrelang im trockenen Boden. Kommt Regen, schlüpfen sie.','Tadpole shrimp eggs survive for years in dry ground. When the rain comes, they hatch.',{H:.12,L:.5,W:1.6,back:'#a08a5a',belly:'#e8dcc0',tail:'fork',dorsal:'none',anal:false,eyeY:.8});
  fish('kahlhecht','Kahlhecht','Bowfin','m','teich','M','immer',2,460,'Er hat eine lange Flosse über den ganzen Rücken.','It has a long fin along its whole back.','Der Kahlhecht kann Luft schlucken und so auch in warmem, sauerstoffarmem Wasser leben.','The bowfin can gulp air, so it can live in warm water with little oxygen.',{H:.17,L:.85,back:'#5a6a3a',belly:'#e0e8c0',tail:'round',dorsal:'long',dz:.15,ds:1.8,pat:dots('#2a3a1a',12,6)});
  fish('kragenhai','Kragenhai','Frilled shark','m','meer','L','nacht',4,2800,'Er trägt einen Kragen aus Rüschen.','It wears a collar of frills.','Der Kragenhai hat rund 300 Zähne in vielen Reihen. Er sieht noch fast so aus wie seine Vorfahren vor sehr langer Zeit.','The frilled shark has about 300 teeth in many rows. It looks almost like its ancestors from a very long time ago.',{H:.1,L:1.1,back:'#6a5a5a',belly:'#c8b8b8',tail:'spade',dorsal:'std',dz:.2,pat:stripes('#8a6a6a',4)});
  fish('ichthyosaurier','Ichthyosaurier-Spielzeug','Toy ichthyosaur','n','meer','XL','tag',5,5000,'Ein Meeressaurier aus Gummi, der quietscht!','A rubber sea reptile that squeaks!','Ichthyosaurier waren Meeresreptilien zur Zeit der Dinosaurier. Sie brachten ihre Jungen lebend im Wasser zur Welt.','Ichthyosaurs were sea reptiles at the time of the dinosaurs. They gave birth to live young in the water.',{H:.2,L:1.05,back:'#4a9ad8',belly:'#e8f4ff',tail:'moon',dorsal:'tri',eye:.09,gloss:1.4});
  bug('termite','Termite','Termite','f','boden','immer',1,150,'Sie wohnt in einem Turm aus Lehm.','It lives in a tower made of clay.','Termiten gab es schon zur Zeit der Dinosaurier. Manche bauen Türme, die viel grösser sind als ein Mensch.','Termites were around at the time of the dinosaurs. Some build towers much taller than a person.',['ke',['#f0e0c0','#e8d0a0','#f0e0c0'],3,.06]);
  bug('riesenwasserwanze','Riesenwasserwanze','Giant water bug','f','wasser','nacht',3,1100,'Sie ist so gross wie meine Hand.','It is as big as my hand.','Bei manchen Riesenwasserwanzen trägt der Vater die Eier auf dem Rücken, bis die Jungen schlüpfen.','In some giant water bugs, the father carries the eggs on his back until the young hatch.',['be','#6a5a3a',{len:1.4,s:1.2}]);
  bug('felsenspringer','Felsenspringer','Jumping bristletail','m','stein','nacht',2,330,'Er hüpft mit einem Satz über den Felsen.','It jumps over the rock in one leap.','Felsenspringer haben nie Flügel gehabt. Sie gehören zu den ältesten Insektengruppen überhaupt.','Jumping bristletails have never had wings. They are one of the oldest insect groups of all.',['gr','#8a8a90',{len:.26,ant:.35,wing:'#6a6a70'}]);
  bug('eintagsfliege','Eintagsfliege','Mayfly','f','luft','tag',2,300,'Sie hat drei lange Schwanzfäden.','It has three long tail threads.','Eintagsfliegen leben als Larve lange im Wasser. Als fliegendes Insekt leben sie oft nur einen Tag.','Mayflies live in the water as larvae for a long time. As flying insects they often live for just one day.',['li','#e8d8a0','#fffbe8',{len:.4,ws:.17,two:true,tail:true}]);
  bug('kamelhalsfliege','Kamelhalsfliege','Snakefly','f','baum','tag',3,850,'Sie hat einen langen Hals wie ein Kamel.','It has a long neck like a camel.','Kamelhalsfliegen haben einen langen Vorderkörper wie einen Hals. Es gab sie schon vor über 100 Millionen Jahren.','Snakeflies have a long front body like a neck. They were around more than 100 million years ago.',['li','#3a3a44','#f0f4ff',{len:.5,ws:.15}]);
  bug('stummelfuesser','Stummelfüsser','Velvet worm','m','boden','nacht',4,2000,'Er ist weich wie Samt.','It is soft like velvet.','Stummelfüsser spritzen klebrigen Schleim, um Beute zu fangen. Ihre Verwandten lebten schon vor 500 Millionen Jahren.','Velvet worms squirt sticky slime to catch prey. Their relatives lived 500 million years ago.',['ra',['#6a3a3a','#7a4a3a'],8]);
  bug('zikade17','Siebzehnjahr-Zikade','Periodical cicada','f','baum','tag',4,2400,'Sie hat 17 Jahre unter der Erde gewartet.','It waited underground for 17 years.','Manche Zikaden leben 17 Jahre als Larve unter der Erde. Dann schlüpfen Millionen auf einmal.','Some cicadas live underground as larvae for 17 years. Then millions hatch all at once.',['gr','#2a2a2a',{wing:'#ff8a3a',len:.24}]);

  /* ================= Dschungel ================= */
  planet('dschungel');
  fish('suesswasserrochen','Süsswasserrochen','River stingray','m','fluss','L','nacht',3,1300,'Er ist rund wie ein Teller mit Punkten.','It is round like a plate with spots.','Süsswasserrochen leben in Flüssen in Südamerika. Sie liegen gern halb im Sand vergraben.','River stingrays live in rivers in South America. They like to lie half buried in the sand.',{H:.08,L:.7,W:2.6,back:'#6a5a3a',belly:'#f0e8d8',tail:'spade',dorsal:'none',anal:false,pat:dots('#f0c060',20,9)});
  fish('arowana','Arowana','Arowana','m','fluss','L','tag',3,1250,'Sie ist aus dem Wasser gesprungen, um eine Fliege zu fangen!','It leapt out of the water to catch a fly!','Arowanas springen aus dem Wasser und schnappen Insekten von Ästen über dem Fluss.','Arowanas jump out of the water and snap insects off branches above the river.',{H:.15,L:1,back:'#c0c8c0',belly:'#f4f8f0',tail:'round',dorsal:'long',dz:.15,anal:'long',pat:grid('#e0e8e0',22)});
  fish('pacu','Pacu','Pacu','m','fluss','L','immer',2,520,'Er hat Zähne, die fast aussehen wie meine!','It has teeth that look almost like mine!','Der Pacu ist ein Verwandter der Piranhas. Er hat breite Zähne, mit denen er Nüsse und Früchte knackt.','The pacu is a relative of piranhas. It has broad teeth for cracking nuts and fruit.',{H:.3,L:.75,back:'#6a6a7a',belly:'#e8603a',tail:'fork',dorsal:'std'});
  fish('gluehlichtsalmler','Glühlichtsalmler','Glowlight tetra','m','teich','S','nacht',1,170,'Über seinen Körper läuft ein leuchtender Streifen.','A glowing stripe runs along its body.','Glühlichtsalmler schwimmen in grossen Schwärmen. So sind sie vor Räubern besser geschützt.','Glowlight tetras swim in large schools. That keeps them safer from predators.',{H:.17,L:.45,back:'#c8b0a0',belly:'#fff4ec',tail:'fork',dorsal:'std',pat:stripes('#ff6a3a',1,true)});
  fish('panzerwels','Panzerwels','Corydoras','m','teich','S','tag',1,160,'Er hat einen Panzer wie eine kleine Ritterrüstung.','It has armour like a tiny knight.','Panzerwelse haben harte Knochenplatten statt Schuppen. Sie wühlen am Boden nach Futter.','Corydoras have hard bony plates instead of scales. They rummage on the bottom for food.',{H:.2,L:.5,back:'#a09070',belly:'#f4ecd8',tail:'fork',dorsal:'tri',pat:dots('#4a3a2a',18,5)});
  fish('vieraugenfisch','Vieraugenfisch','Four-eyed fish','m','fluss','M','tag',3,880,'Er guckt gleichzeitig über und unter das Wasser.','It looks above and below the water at the same time.','Die Augen des Vieraugenfischs sind zweigeteilt. Er sieht damit über und unter Wasser zugleich.','The four-eyed fish has eyes split in two. It can see above and below the water at the same time.',{H:.13,L:.75,back:'#a0a080',belly:'#f4f4e8',tail:'round',dorsal:'std',dz:.25,eye:.08,eyeY:.7});
  fish('messerfisch','Schwarzer Messerfisch','Black ghost knifefish','m','fluss','M','nacht',4,2000,'Er schwimmt rückwärts genauso gut wie vorwärts.','It swims backwards just as well as forwards.','Der Messerfisch baut ein schwaches elektrisches Feld um sich auf. Damit findet er nachts sein Futter.','The knifefish makes a weak electric field around itself. It uses it to find food at night.',{H:.12,L:.95,back:'#1a1a24',belly:'#3a3a44',tail:'none',dorsal:'none',anal:'long',as:2.2,az:.15,pat:stripes('#f4f4f4',2)});
  bug('glasfluegelfalter','Glasflügelfalter','Glasswing butterfly','m','luft','tag',3,950,'Durch seine Flügel kann ich hindurchschauen.','I can see right through its wings.','Die Flügel des Glasflügelfalters sind fast ganz durchsichtig. So ist er für Vögel schwer zu sehen.','The glasswing butterfly has almost completely see-through wings. That makes it hard for birds to spot.',['bf','rgba(240,250,255,.35)','rgba(240,250,255,.35)','#3a2a2a']);
  bug('prachtbiene','Prachtbiene','Orchid bee','f','blume','tag',3,900,'Sie glänzt grün wie Metall.','It shines green like metal.','Männchen der Prachtbiene sammeln Duftstoffe aus Orchideen und mischen sich daraus ein eigenes Parfüm.','Male orchid bees collect scents from orchids and mix their own perfume from them.',['hu','#2ac87a','#1a8a5a',{s:.85}]);
  bug('goliathspinne','Goliath-Vogelspinne','Goliath birdeater','f','boden','nacht',5,4000,'Sie ist so gross wie ein Teller, aber ganz ruhig.','It is as big as a plate, but very calm.','Die Goliath-Vogelspinne ist die schwerste Spinne der Welt. Bei Gefahr streift sie feine Härchen ab.','The Goliath birdeater is the heaviest spider in the world. When in danger, it flicks off fine hairs.',['sp','#6a4a3a',{body:.15,leg:.32}]);
  bug('dornzikade','Dornzikade','Thorn bug','f','baum','tag',2,420,'Ich dachte zuerst, sie wäre ein Dorn.','At first I thought it was a thorn.','Dornzikaden sehen aus wie Dornen an einem Zweig. So übersehen Vögel sie.','Thorn bugs look like thorns on a twig. That way, birds overlook them.',['be','#5a8a3a',{horn:true,len:1,s:.9}]);
  bug('orchideenmantis','Orchideenmantis','Orchid mantis','f','blume','tag',4,2200,'Sie sieht aus wie eine rosa Blüte.','It looks like a pink flower.','Die Orchideenmantis sieht aus wie eine Blüte. Insekten, die Nektar suchen, kommen ihr ganz nah.','The orchid mantis looks like a flower. Insects looking for nectar come very close to it.',['gr','#ffc8e0',{arms:true,wing:'#ffe0ee',len:.22}]);
  bug('helikopterlibelle','Helikopterlibelle','Helicopter damselfly','f','luft','tag',4,2100,'Ihre Flügel drehen sich wie ein Propeller.','Its wings spin like a propeller.','Die Helikopterlibelle hat die grössten Flügel aller Kleinlibellen. Sie fängt Spinnen direkt aus dem Netz.','The helicopter damselfly has the largest wings of any damselfly. It catches spiders right out of their webs.',['li','#2a4ad8','#e8f0ff',{len:.7,ws:.26}]);
  bug('wandelndesblatt','Wandelndes Blatt','Leaf insect','n','baum','immer',3,1050,'Es sieht aus wie ein Blatt mit Beinen.','It looks like a leaf with legs.','Das Wandelnde Blatt schaukelt beim Gehen hin und her, wie ein Blatt im Wind.','The leaf insect rocks back and forth as it walks, like a leaf in the wind.',['be','#7ac83a',{len:1.5,s:1.1,key:'blatt',pat:(x,w,h)=>{x.strokeStyle='#4a8a2a';x.lineWidth=3;x.beginPath();x.moveTo(w/2,0);x.lineTo(w/2,h);for(let i=1;i<6;i++){x.moveTo(w/2,i*h/6);x.lineTo(w*.15,i*h/6-12);x.moveTo(w/2,i*h/6);x.lineTo(w*.85,i*h/6-12)}x.stroke()}}]);

  /* ================= Metro ================= */
  planet('metro');
  fish('doebel','Döbel','Chub','m','meer','M','immer',1,170,'Er hat ein grosses Maul und frisst fast alles.','It has a big mouth and eats almost anything.','Döbel fressen fast alles: Insekten, Pflanzen, Krebse und sogar Kirschen, die ins Wasser fallen.','Chub eat almost anything: insects, plants, crayfish and even cherries that fall into the water.',{H:.18,L:.7,back:'#5a6a6a',belly:'#f0f0e8',fin:'#e86a4a',tail:'fork',dorsal:'std',pat:grid('#7a8a8a',20)});
  fish('flussbarbe','Flussbarbe','Barbel','f','meer','M','nacht',2,420,'Sie hat vier Barteln wie einen Schnurrbart.','It has four barbels like a moustache.','Barben haben vier Barteln am Maul. Damit suchen sie nachts zwischen den Steinen nach Futter.','Barbels have four whiskers on their mouth. They use them to search for food between stones at night.',{H:.14,L:.8,back:'#7a6a4a',belly:'#f0e8d0',tail:'fork',dorsal:'tri'});
  fish('ukelei','Ukelei','Bleak','m','teich','S','tag',1,120,'Er glitzert silbern wie Lametta.','It glitters silver like tinsel.','Aus den glänzenden Schuppen des Ukelei hat man früher Farbe für künstliche Perlen gemacht.','The shiny scales of the bleak were once used to make paint for artificial pearls.',{H:.13,L:.55,back:'#7a8a9a',belly:'#ffffff',tail:'fork',dorsal:'std',gloss:1.6});
  fish('kaulbarsch','Kaulbarsch','Ruffe','m','meer','S','nacht',1,150,'Er hat einen stacheligen Rücken.','It has a prickly back.','Kaulbarsche haben grosse Sinneszellen am Kopf. Sie finden ihr Futter auch in trübem Wasser und im Dunkeln.','Ruffes have large sense cells on their head. They find food even in murky water and in the dark.',{H:.2,L:.5,back:'#8a7a4a',belly:'#f0e8c8',tail:'fork',dorsal:'spiky',pat:dots('#4a3a2a',16,4)});
  fish('rapfen','Rapfen','Asp','m','meer','L','tag',3,1050,'Er jagt wie ein Blitz an der Oberfläche.','It hunts like lightning at the surface.','Der Rapfen ist der einzige Karpfenfisch bei uns, der andere Fische jagt. Er schlägt mit dem Schwanz auf das Wasser.','The asp is the only carp fish in our rivers that hunts other fish. It slaps the water with its tail.',{H:.17,L:.9,back:'#5a6a7a',belly:'#f4f4f4',tail:'fork',dorsal:'tri'});
  fish('graskarpfen','Graskarpfen','Grass carp','m','teich','L','immer',2,480,'Er hat bestimmt gerade Salat gegessen.','It must have just eaten some salad.','Graskarpfen fressen sehr viele Wasserpflanzen. Man setzt sie in Teiche, damit sie nicht zuwachsen.','Grass carp eat lots of water plants. People put them in ponds to stop them getting overgrown.',{H:.17,L:.95,back:'#6a7a5a',belly:'#f0f0e0',tail:'fork',dorsal:'std',pat:grid('#4a5a3a',26)});
  fish('brassen','Brassen','Bream','m','meer','M','nacht',2,380,'Er ist hoch und flach wie ein Teller.','It is tall and flat like a plate.','Brassen wühlen im Schlamm nach Futter. An den Luftblasen auf dem Wasser sieht man, wo sie gerade suchen.','Bream dig in the mud for food. You can tell where they are searching by the bubbles on the water.',{H:.32,L:.65,W:.5,back:'#8a7a5a',belly:'#e8dcc0',tail:'fork',dorsal:'hi',anal:'long'});
  bug('zitterspinne','Zitterspinne','Cellar spider','f','stein','immer',1,140,'Sie hat ganz dünne, lange Beine.','It has very thin, long legs.','Die Zitterspinne lässt ihr Netz schnell hin und her wackeln, wenn sie gestört wird. Dann ist sie kaum zu sehen.','When disturbed, the cellar spider shakes its web quickly back and forth. Then it is hard to see.',['sp','#c8b090',{body:.07,leg:.4}]);
  bug('stubenfliege','Stubenfliege','Housefly','f','luft','immer',1,90,'Sie hat sich die Füsse geputzt, bevor ich kam.','It was cleaning its feet when I came.','Fliegen schmecken mit ihren Füssen. Darum laufen sie erst über das Essen, bevor sie probieren.','Flies taste with their feet. That is why they walk over food before they try it.',['li','#4a4a54','#e8f0ff',{len:.25,ws:.12,two:true}]);
  bug('admiral','Admiral','Red admiral','m','blume','tag',2,380,'Er hat rote Streifen wie eine Uniform.','It has red stripes like a uniform.','Der Admiral fliegt im Herbst über die Alpen nach Süden. Im Frühling kommen neue Falter zurück.','In autumn the red admiral flies south over the Alps. In spring new butterflies come back.',['bf',x=>{x.fillStyle='#2a2224';x.fillRect(0,-1,1,2);x.fillStyle='#e8402a';x.fillRect(.38,-1,.16,2);x.fillStyle='#f4f0e8';for(const[a,b]of[[.75,.7],[.85,.55],[.68,.82]]){x.beginPath();x.arc(a,b,.05,0,TAU);x.fill()}},x=>{x.fillStyle='#2a2224';x.fillRect(0,-1,1,2);x.fillStyle='#e8402a';x.fillRect(.55,-1,.2,2)},'#2a2224']);
  bug('heimchen','Heimchen','House cricket','n','boden','nacht',1,170,'Es zirpt wie ein kleiner Wecker.','It chirps like a tiny alarm clock.','Heimchen lebten früher gern in warmen Häusern neben dem Ofen. Daher kommt ihr Name.','House crickets used to like living in warm houses next to the stove. That is where their name comes from.',['gr','#c8a060',{wing:'#a08040'}]);
  bug('feldwespe','Feldwespe','Paper wasp','f','blume','tag',2,350,'Sie baut ihr Nest aus Papier.','It builds its nest out of paper.','Feldwespen kauen Holz zu einem Brei und bauen daraus ein Nest aus Papier.','Paper wasps chew wood into a pulp and use it to build a nest out of paper.',['li','#ffd23f','#fff4c8',{len:.42,ws:.13,two:true}]);
  bug('mondvogel','Mondvogel','Buff-tip moth','m','luft','nacht',3,820,'Er sieht aus wie ein abgebrochenes Zweiglein.','It looks like a broken little twig.','Der Mondvogel faltet seine Flügel so, dass er aussieht wie ein abgebrochener Birkenzweig.','The buff-tip folds its wings so that it looks like a broken birch twig.',['bf','#b8b0a0','#d8d0c0','#e8d890',{fs:.4,hs:.34}]);
  bug('pflasterameise','Pflasterameise','Pavement ant','f','stein','tag',1,120,'Sie wohnt unter den Pflastersteinen.','It lives under the paving stones.','Pflasterameisen bauen ihre Nester unter Steinen und Gehwegplatten. Manchmal streiten zwei Völker um den Platz.','Pavement ants build their nests under stones and paving slabs. Sometimes two colonies argue over the space.',['ke',['#5a3a2a','#6a4a3a','#5a3a2a'],3,.055]);

  /* ================= Wolkenarchipel ================= */
  planet('wolkenarchipel');
  fish('sterngucker','Sterngucker','Stargazer','m','meer','M','nacht',3,900,'Seine Augen schauen immer nach oben zu den Sternen.','Its eyes always look up at the stars.','Der Sterngucker gräbt sich im Sand ein. Nur seine Augen oben auf dem Kopf schauen heraus.','The stargazer buries itself in the sand. Only its eyes on top of its head peek out.',{H:.18,L:.6,W:1.1,back:'#8a7a6a',belly:'#e8e0d8',tail:'round',dorsal:'std',eyeY:.9,eye:.065,pat:dots('#f4f0e8',24,4)});
  fish('neonregenbogenfisch','Neon-Regenbogenfisch','Neon rainbowfish','m','teich','S','tag',2,360,'Er schillert in allen Farben.','It shimmers in every colour.','Regenbogenfische zeigen ihre schönsten Farben am Morgen, wenn die Sonne aufgeht.','Rainbowfish show their brightest colours in the morning when the sun comes up.',{H:.24,L:.5,back:'#4a8ad8',belly:'#e8f4ff',fin:'#ff6a3a',tail:'fork',dorsal:'long',anal:'long',gloss:1.4});
  fish('himmelsgucker','Himmelsgucker','Celestial eye goldfish','m','teich','S','immer',2,420,'Er schaut die ganze Zeit in den Himmel.','It looks up at the sky the whole time.','Der Himmelsgucker ist ein gezüchteter Goldfisch. Seine Augen zeigen nach oben.','The celestial eye is a bred goldfish. Its eyes point upwards.',{H:.24,L:.5,back:'#ff8a3a',belly:'#ffd8a0',tail:'fancy',dorsal:'none',eye:.08,eyeY:.9,ts:1.3});
  fish('meerengel','Meerengel','Angel shark','m','meer','L','nacht',4,2300,'Er ist flach wie ein Teppich mit Flügeln.','It is flat like a rug with wings.','Der Meerengel ist ein flacher Hai. Er liegt versteckt im Sand und wartet auf Fische.','The angel shark is a flat shark. It lies hidden in the sand and waits for fish.',{H:.08,L:.95,W:2.2,back:'#a09070',belly:'#f0e8d8',tail:'fork',dorsal:'std',dz:.25,ps:2,pat:dots('#6a5a40',24,5)});
  fish('segelfisch','Segelfisch','Sailfish','m','meer','XL','tag',5,4600,'Er hat ein riesiges Segel auf dem Rücken.','It has a huge sail on its back.','Segelfische gehören zu den schnellsten Fischen im Meer. Beim Jagen klappen sie ihr Segel auf.','Sailfish are among the fastest fish in the sea. They raise their sail when hunting.',{H:.15,L:1.1,back:'#2a4a8a',belly:'#e8f0ff',tail:'moon',dorsal:'sail',ds:2,beak:{len:.38,r:.025},pat:stripes('#6a9ad8',8)});
  fish('wimpelfisch','Wimpelfisch','Pennant coralfish','m','meer','M','tag',2,440,'Er hat eine lange Fahne auf dem Rücken.','It has a long flag on its back.','Wimpelfische schwimmen oft in Paaren oder kleinen Gruppen durch das Riff.','Pennant coralfish often swim through the reef in pairs or small groups.',{H:.32,L:.5,W:.45,back:'#f4f4f0',belly:'#ffffff',fin:'#ffd23f',tail:'round',dorsal:'sail',ds:1.5,pat:stripes('#1a1a24',2)});
  fish('adlerrochen','Adlerrochen','Spotted eagle ray','m','meer','XL','tag',4,2700,'Er ist aus dem Wasser gesprungen wie ein Vogel.','It leapt out of the water like a bird.','Gefleckte Adlerrochen springen manchmal hoch aus dem Wasser. Warum, weiss niemand genau.','Spotted eagle rays sometimes leap high out of the water. Nobody knows exactly why.',{H:.08,L:.8,W:2.8,back:'#2a3a5a',belly:'#ffffff',tail:'spade',dorsal:'none',anal:false,pat:dots('#ffffff',30,5)});
  bug('schwalbenschwanz','Schwalbenschwanz','Swallowtail','m','luft','tag',3,900,'Seine Flügel haben Zipfel wie ein Schwalbenschwanz.','Its wings have points like a swallow\'s tail.','Schwalbenschwänze fliegen gern auf Hügelkuppen. Dort treffen sich die Falter.','Swallowtails like to fly up to hilltops. That is where the butterflies meet.',['bf','#ffe060','#ffd040','#1a1a24']);
  bug('segelfalter','Segelfalter','Scarce swallowtail','m','luft','tag',3,950,'Er segelt durch die Luft, fast ohne zu flattern.','It sails through the air almost without flapping.','Der Segelfalter gleitet oft weite Strecken, ohne mit den Flügeln zu schlagen, wie ein Segelflieger.','The scarce swallowtail often glides a long way without flapping, like a glider.',['bf','#f4f0d8','#f0e8c8','#2a2a2a',{fs:.55,hs:.45}]);
  bug('blaeuling','Himmelblauer Bläuling','Adonis blue','m','blume','tag',2,380,'Er ist so blau wie der Himmel.','It is as blue as the sky.','Die Raupen vieler Bläulinge werden von Ameisen beschützt. Dafür geben sie den Ameisen süssen Saft.','Many blue butterfly caterpillars are protected by ants. In return they give the ants a sweet juice.',['bf','#4ab8ff','#6ac8ff','#2a2a3a',{fs:.4,hs:.34}]);
  bug('kleinerfuchs','Kleiner Fuchs','Small tortoiseshell','m','blume','tag',1,170,'Er ist orange wie ein Fuchs.','It is orange like a fox.','Der Kleine Fuchs überwintert gern auf Dachböden und kommt im Frühling als einer der ersten Falter heraus.','The small tortoiseshell likes to spend winter in attics and is one of the first butterflies out in spring.',['bf','#ff7a2a','#e86a2a','#2a2224']);
  bug('tanzmuecke','Tanzmücke','Dancing midge','f','luft','nacht',1,110,'Sie tanzt in einer kleinen Wolke mit ihren Freundinnen.','It dances in a little cloud with its friends.','Zuckmücken tanzen abends in grossen Schwärmen. Sie stechen nicht.','Non-biting midges dance in big swarms in the evening. They do not bite.',['li','#8a9a7a','#f0fff0',{len:.22,ws:.08,two:true}]);
  bug('feuerlibelle','Feuerlibelle','Scarlet darter','f','luft','tag',2,420,'Sie leuchtet rot wie ein Feuer.','It glows red like a fire.','Die Feuerlibelle kommt aus dem Süden. Weil es wärmer wird, lebt sie jetzt auch weiter im Norden.','The scarlet darter comes from the south. Because it is getting warmer, it now lives further north too.',['li','#ff3a2a','#fff0e8']);
  bug('maikaefer','Maikäfer','Cockchafer','m','baum','nacht',2,400,'Er brummt laut wie ein kleines Flugzeug.','It buzzes loudly like a little airplane.','Maikäfer-Larven leben drei bis vier Jahre unter der Erde, bevor sie als Käfer herauskommen.','Cockchafer larvae live underground for three to four years before they come out as beetles.',['be','#a0602a',{key:'mai',ant:.1,pat:(x,w,h)=>{x.fillStyle='#f4f0e8';for(let i=0;i<5;i++){x.beginPath();x.moveTo(0,i*h/5+10);x.lineTo(16,i*h/5+18);x.lineTo(0,i*h/5+26);x.fill();x.beginPath();x.moveTo(w,i*h/5+10);x.lineTo(w-16,i*h/5+18);x.lineTo(w,i*h/5+26);x.fill()}}}]);

  /* ================= Bibliothek ================= */
  planet('bibliothek');
  fish('sepia','Sepia','Cuttlefish','f','meer','M','nacht',3,1000,'Sie hat mir einen Tintenklecks geschenkt.','It gave me a splash of ink.','Sepien wechseln blitzschnell ihre Farbe. Aus ihrer Tinte hat man früher braune Zeichenfarbe gemacht.','Cuttlefish change colour in a flash. Their ink was once used to make brown drawing paint.',{H:.18,L:.6,W:1.2,back:'#c8a080',belly:'#f4e8d8',tail:'none',dorsal:'none',anal:false,pect:false,eye:.07,arms:8,armL:.7,pat:stripes('#8a6040',9)});
  fish('kalmar','Kalmar','Squid','m','meer','M','nacht',3,950,'Er hat lange Arme und ist ganz schnell.','It has long arms and is very fast.','Kalmare haben drei Herzen und blaues Blut. Sie schwimmen mit einem Wasserstrahl wie eine Rakete.','Squid have three hearts and blue blood. They swim with a jet of water like a rocket.',{H:.12,L:.85,back:'#f0c8c8',belly:'#fff0f0',tail:'spade',ts:1.3,dorsal:'none',anal:false,pect:false,eye:.07,arms:10,pat:dots('#c87a7a',30,4)});
  fish('papierboot','Papierboot','Paper nautilus','n','meer','M','tag',4,2100,'Sein Haus ist dünn wie Papier.','Its shell is as thin as paper.','Das Papierboot ist eigentlich ein Krake. Das Weibchen baut sich eine hauchdünne Schale für seine Eier.','The paper nautilus is really an octopus. The female builds a wafer-thin shell for her eggs.',{H:.3,L:.45,W:.6,back:'#fff8ec',belly:'#ffffff',tail:'none',dorsal:'none',anal:false,pect:false,pat:stripes('#e8dcc0',8,true)});
  fish('seenadel','Seenadel','Pipefish','f','meer','S','tag',2,360,'Sie ist so dünn wie ein Bleistift.','It is as thin as a pencil.','Bei Seenadeln trägt der Vater die Eier in einer Bauchtasche, genau wie beim Seepferdchen.','In pipefish, the father carries the eggs in a belly pouch, just like a seahorse.',{H:.05,L:.9,back:'#8a9a5a',belly:'#e8f0c8',tail:'round',ts:.6,dorsal:'std',ds:.6,anal:false,pect:false,pat:stripes('#5a6a3a',12)});
  fish('bleistiftfisch','Bleistiftfisch','Pencilfish','m','teich','S','immer',1,140,'Er hat einen Streifen wie ein Bleistiftstrich.','It has a stripe like a pencil line.','Bleistiftfische ändern nachts ihr Muster. Dann haben sie Flecken statt Streifen.','Pencilfish change their pattern at night. Then they have spots instead of stripes.',{H:.1,L:.5,back:'#c8b090',belly:'#fff8ec',tail:'fork',dorsal:'std',pat:stripes('#2a2a2a',1,true)});
  fish('schriftbarsch','Schriftbarsch','Painted comber','m','meer','M','tag',2,420,'Auf seinem Kopf stehen Buchstaben.','There are letters written on its head.','Der Schriftbarsch hat feine blaue Linien am Kopf. Sie sehen aus wie Schrift.','The painted comber has fine blue lines on its head. They look like writing.',{H:.2,L:.6,back:'#c87a4a',belly:'#fff0e0',tail:'round',dorsal:'spiky',pat:(x,w,h)=>{x.strokeStyle='#3a6ad8';x.lineWidth=2;for(let i=0;i<8;i++){x.beginPath();x.moveTo(8,20+i*14);x.bezierCurveTo(30,10+i*14,40,30+i*14,60,18+i*14);x.stroke();x.beginPath();x.moveTo(w-8,20+i*14);x.bezierCurveTo(w-30,10+i*14,w-40,30+i*14,w-60,18+i*14);x.stroke()}}});
  fish('sandkreiskugelfisch','Sandkreis-Kugelfisch','Sand-circle pufferfish','m','meer','S','nacht',4,1900,'Er hat ein Bild in den Sand gemalt.','It drew a picture in the sand.','Ein kleiner Kugelfisch in Japan malt mit seinen Flossen grosse Kreise mit Mustern in den Sand.','A small pufferfish in Japan draws big circles with patterns in the sand with its fins.',{H:.26,L:.42,W:1,back:'#a09080',belly:'#f4f0e8',tail:'round',dorsal:'std',pat:dots('#5a4a3a',20,4)});
  bug('buecherskorpion','Bücherskorpion','Book scorpion','m','boden','nacht',3,880,'Er wohnt zwischen alten Büchern.','It lives between old books.','Der Bücherskorpion ist winzig und harmlos. Er frisst Staubläuse und Milben in alten Büchern.','The book scorpion is tiny and harmless. It eats booklice and mites in old books.',['kr','#a06a3a',{claw:.06}]);
  bug('buecherlaus','Bücherlaus','Booklouse','f','boden','immer',1,100,'Sie ist so klein wie ein i-Punkt.','It is as small as the dot on an i.','Bücherläuse fressen winzige Schimmelpilze auf altem Papier. Für Menschen sind sie harmlos.','Booklice eat tiny moulds on old paper. They are harmless to people.',['ke',['#f0e8d8','#e8dcc8'],2,.05]);
  bug('brotkaefer','Brotkäfer','Drugstore beetle','m','boden','tag',1,150,'Er riecht ein bisschen nach Zwieback.','It smells a little bit like rusks.','Brotkäfer knabbern an trockenen Dingen wie Mehl, Gewürzen und manchmal sogar an Büchern.','Drugstore beetles nibble dry things like flour, spices and sometimes even books.',['be','#a0602a',{s:.8,len:1.1}]);
  bug('klopfkaefer','Klopfkäfer','Deathwatch beetle','m','baum','nacht',2,380,'Er klopft wie jemand an der Tür.','It knocks like someone at the door.','Dieser Käfer klopft mit dem Kopf gegen Holz, um andere Käfer zu rufen. Das klingt wie eine tickende Uhr.','This beetle taps its head against wood to call other beetles. It sounds like a ticking clock.',['be','#7a5a3a',{s:.9}]);
  bug('buchdrucker','Buchdrucker','Bark beetle','m','baum','tag',2,340,'Er hat Muster unter die Rinde gebohrt.','It drilled patterns under the bark.','Der Buchdrucker frisst Gänge unter die Rinde von Fichten. Die Gänge sehen aus wie Schrift in einem Buch.','The bark beetle eats tunnels under the bark of spruce trees. The tunnels look like writing in a book.',['be','#4a3a2a',{s:.8,len:1.2}]);
  bug('federmotte','Federmotte','Plume moth','f','luft','nacht',2,360,'Ihre Flügel sind wie kleine Federn.','Its wings are like little feathers.','Federmotten haben Flügel, die in feine Federn aufgeteilt sind. In Ruhe rollen sie sie zusammen.','Plume moths have wings split into fine feathers. When resting, they roll them up.',['li','#f4f0e8','#ffffff',{len:.4,ws:.18}]);
  bug('cfalter','C-Falter','Comma butterfly','m','blume','tag',2,400,'Unter seinem Flügel steht ein weisses C.','There is a white C under its wing.','Der C-Falter hat auf der Unterseite der Flügel ein kleines weisses Zeichen, das aussieht wie ein C.','The comma has a small white mark on the underside of its wings that looks like a C.',['bf','#e87a2a','#d86a2a','#3a2a24']);

  /* ================= Uhrwerk ================= */
  planet('uhrwerk');
  fish('prachtgrundkaerpfling','Prachtgrundkärpfling','Killifish','m','teich','S','tag',3,880,'Er glänzt türkis und orange.','It shines turquoise and orange.','Manche Prachtkärpflinge leben nur eine Regenzeit lang. Ihre Eier warten im trockenen Schlamm auf den nächsten Regen.','Some killifish live for just one rainy season. Their eggs wait in the dry mud for the next rain.',{H:.17,L:.5,back:'#3ac8c0',belly:'#e8fff8',fin:'#ff7a3a',tail:'round',dorsal:'long',anal:'long',pat:dots('#ff7a3a',20,4)});
  fish('saegefisch','Sägefisch','Sawfish','m','meer','XL','nacht',5,4400,'Seine Nase ist eine lange Säge.','Its nose is a long saw.','Sägefische spüren mit ihrer Säge Beute im Sand auf. Ihre Säge hat Zähne an beiden Seiten.','Sawfish find prey in the sand with their saw. The saw has teeth on both sides.',{H:.1,L:1.15,W:1.4,back:'#8a7a5a',belly:'#f0e8d8',tail:'fork',dorsal:'tri',beak:{len:.6,r:.06,flat:2.4,saw:true}});
  fish('schwertfisch','Schwertfisch','Swordfish','m','meer','XL','tag',4,3200,'Er hat ein Schwert statt einer Nase.','It has a sword instead of a nose.','Schwertfische können ihre Augen aufwärmen. So sehen sie auch im kalten, tiefen Wasser gut.','Swordfish can warm up their eyes. That helps them see well in cold, deep water.',{H:.16,L:1.1,back:'#3a4a6a',belly:'#e8eef4',tail:'moon',dorsal:'tri',ds:1.4,beak:{len:.65,r:.035}});
  fish('drueckerfisch','Drückerfisch','Triggerfish','m','meer','M','tag',2,460,'Er klappt einen Stachel hoch wie einen Hebel.','It flips up a spine like a lever.','Drückerfische können ihren Rückenstachel aufstellen und feststellen, wie mit einem Abzug.','Triggerfish can raise their back spine and lock it in place, like with a trigger.',{H:.28,L:.6,back:'#3a4ad8',belly:'#ffd23f',tail:'fancy',dorsal:'tri',pat:patch(['#ffd23f','#ff6fa5','#45e0ff'])});
  fish('spiegelkarpfen','Spiegelkarpfen','Mirror carp','m','teich','L','immer',2,520,'Er hat nur ein paar grosse Schuppen wie Spiegel.','It has just a few big scales like mirrors.','Spiegelkarpfen sind gezüchtete Karpfen mit nur wenigen, sehr grossen glänzenden Schuppen.','Mirror carp are bred carp with only a few very large, shiny scales.',{H:.24,L:.85,back:'#a08a4a',belly:'#f4e8c0',tail:'fork',dorsal:'long',gloss:1.5,pat:(x,w,h)=>{x.fillStyle='rgba(255,250,220,.7)';for(let i=0;i<6;i++){x.beginPath();x.arc(w*(.3+(i%3)*.1),h*(.25+Math.floor(i/3)*.3),16,0,TAU);x.arc(w*(.7-(i%3)*.1),h*(.25+Math.floor(i/3)*.3),16,0,TAU);x.fill()}}});
  fish('rotbarsch','Rotbarsch','Redfish','m','meer','M','nacht',3,960,'Er ist rot wie eine Tomate.','It is red like a tomato.','Rotbarsche wachsen sehr langsam und können über 50 Jahre alt werden.','Redfish grow very slowly and can live for more than 50 years.',{H:.22,L:.7,back:'#e8402a',belly:'#ffd0c0',tail:'fork',dorsal:'spiky',eye:.07});
  fish('putzerfisch','Putzerfisch','Cleaner wrasse','m','meer','S','tag',2,380,'Er wollte mir die Zähne putzen.','It wanted to clean my teeth.','Putzerfische haben feste Putzstationen im Riff. Grosse Fische kommen vorbei und lassen sich säubern.','Cleaner wrasses have regular cleaning stations on the reef. Big fish stop by to get cleaned.',{H:.12,L:.5,back:'#4a8ad8',belly:'#f4f8ff',tail:'round',dorsal:'long',pat:stripes('#1a1a24',1,true)});
  bug('zahnradzikade','Zahnrad-Zikade','Gear planthopper','f','blume','tag',4,2200,'An ihren Beinen sitzen echte Zahnräder.','It has real gears on its legs.','Die Larven einer kleinen Zikade haben echte Zahnräder an den Hinterbeinen. So springen beide Beine genau gleichzeitig.','The young of a small planthopper have real gears on their back legs. That makes both legs jump at exactly the same time.',['gr','#8a7a4a',{len:.18,wing:'#c8a060'}]);
  bug('schnellkaefer','Schnellkäfer','Click beetle','m','boden','tag',1,170,'Er schnippt sich mit einem Klick in die Luft.','It flips itself into the air with a click.','Liegt ein Schnellkäfer auf dem Rücken, schnellt er sich mit einem lauten Klick hoch und landet wieder auf den Beinen.','If a click beetle lands on its back, it flips itself up with a loud click and lands on its feet again.',['be','#5a4a3a',{len:1.4,s:.8}]);
  bug('messingeule','Messingeule','Burnished brass moth','f','luft','nacht',3,900,'Ihre Flügel glänzen wie poliertes Messing.','Its wings shine like polished brass.','Die Messingeule hat Flügel mit Flecken, die golden glänzen wie Metall.','The burnished brass moth has wings with patches that shine gold like metal.',['bf','#c8a040','#a08a50','#6a5a3a',{fs:.42,hs:.36}]);
  bug('goldwespe','Goldwespe','Jewel wasp','f','blume','tag',3,950,'Sie funkelt wie ein Schmuckstück.','It sparkles like a piece of jewellery.','Goldwespen glänzen grün, blau und rot wie Metall. Bei Gefahr rollen sie sich zu einer Kugel zusammen.','Jewel wasps shine green, blue and red like metal. When in danger, they roll up into a ball.',['hu','#2ac8a0','#e8402a',{s:.7}]);
  bug('kupferglucke','Kupferglucke','Lappet moth','f','baum','nacht',3,860,'Sie sieht aus wie ein Bündel trockener Blätter.','It looks like a bundle of dry leaves.','Die Kupferglucke sieht in Ruhe aus wie ein Häufchen welker Blätter. So bleibt sie unentdeckt.','When resting, the lappet moth looks like a little pile of dead leaves. That way it stays hidden.',['bf','#a0502a','#8a4020','#5a3020',{fs:.46,hs:.4}]);
  bug('spannerraupe','Spannerraupe','Inchworm','f','baum','tag',1,140,'Sie misst den Ast aus wie ein Lineal.','It measures the branch like a ruler.','Spannerraupen machen beim Laufen einen Buckel. Es sieht aus, als würden sie den Weg ausmessen.','Inchworms hump their back when they walk. It looks as if they are measuring the way.',['ra',['#8ac83a','#7ab82a'],6]);
  bug('dukatenfalter','Dukatenfalter','Scarce copper','m','blume','tag',2,420,'Er glänzt wie eine Goldmünze.','It shines like a gold coin.','Die Männchen des Dukatenfalters glänzen leuchtend kupfer-orange. Die Weibchen sind gefleckt.','Male scarce coppers shine bright copper-orange. The females are spotted.',['bf','#ff8a1a','#ff9a2a','#3a2a24',{fs:.38,hs:.32}]);

  /* ================= Klang ================= */
  planet('klang');
  fish('knurrhahn','Knurrhahn','Gurnard','m','meer','M','tag',2,440,'Er hat mich angeknurrt!','It growled at me!','Der Knurrhahn knurrt mit seiner Schwimmblase. Er läuft auf fingerartigen Flossen über den Meeresgrund.','The gurnard growls with its swim bladder. It walks across the sea floor on finger-like fins.',{H:.18,L:.75,back:'#e8603a',belly:'#fff0e0',tail:'fork',dorsal:'spiky',ps:2,pat:dots('#c8402a',14,5)});
  fish('bootsmannfisch','Bootsmannfisch','Midshipman','m','meer','M','nacht',3,880,'Er brummt wie ein tiefes Horn.','It hums like a deep horn.','Das Männchen des Bootsmannfischs summt nachts so laut, dass man es in Hausbooten hören kann.','The male midshipman hums so loudly at night that people can hear it in houseboats.',{H:.15,L:.75,back:'#6a5a4a',belly:'#e8dcc0',tail:'round',dorsal:'long',dz:.15,anal:'long',pat:glowDots('#c8f0ff')});
  fish('pistolenkrebs','Pistolenkrebs','Pistol shrimp','m','meer','S','immer',3,950,'Er hat mit seiner Schere laut geknallt.','It made a loud bang with its claw.','Der Pistolenkrebs schliesst seine Schere so schnell, dass eine Blase entsteht, die laut knallt.','The pistol shrimp snaps its claw shut so fast that it makes a bubble that pops with a loud bang.',{H:.16,L:.5,W:.8,back:'#e8603a',belly:'#fff0e8',tail:'fork',dorsal:'none',pect:true,ps:2.2});
  fish('grunzer','Grunzer','Grunt','m','meer','M','tag',1,190,'Er grunzt wie ein kleines Schwein.','It grunts like a little pig.','Grunzer reiben ihre Zähne im Hals aneinander. Dabei entsteht ein grunzendes Geräusch.','Grunts rub teeth in their throat together. That makes a grunting sound.',{H:.24,L:.6,back:'#ffd23f',belly:'#fff8d8',tail:'fork',dorsal:'spiky',pat:stripes('#4a8ad8',6,true)});
  fish('geigenrochen','Geigenrochen','Guitarfish','m','meer','L','nacht',3,1200,'Er sieht aus wie eine Geige.','It looks like a violin.','Geigenrochen sind Rochen mit einem langen Körper. Von oben sehen sie aus wie eine Gitarre oder Geige.','Guitarfish are rays with a long body. From above they look like a guitar or a violin.',{H:.08,L:1,W:1.8,back:'#c8a070',belly:'#f4ece0',tail:'fork',dorsal:'std',dz:.35,ps:1.8});
  fish('blubberhering','Blubber-Hering','Bubble herring','m','meer','S','nacht',1,150,'Er macht lustige Blubbergeräusche.','It makes funny bubbling noises.','Heringe lassen Luftblasen aus dem Hinterteil. Das Pupsgeräusch hilft ihnen, sich im Schwarm im Dunkeln zu finden.','Herring let out air bubbles from their bottoms. The tooting sound may help the school find each other in the dark.',{H:.15,L:.6,back:'#3a6a8a',belly:'#f4f8ff',tail:'fork',dorsal:'std',gloss:1.5});
  fish('schallplattenscholle','Schallplatten-Scholle','Record plaice','f','meer','M','tag',2,400,'Sie ist rund und flach wie eine Schallplatte.','It is round and flat like a record.','Junge Schollen schwimmen wie andere Fische. Später wandert ein Auge auf die andere Seite und sie legen sich flach auf den Boden.','Young plaice swim like other fish. Later one eye moves to the other side and they lie flat on the bottom.',{H:.06,L:.65,W:2.4,back:'#8a7a5a',belly:'#f4f0e8',tail:'round',dorsal:'long',dz:.2,anal:'long',eyeY:.9,pat:dots('#ff7a3a',16,6)});
  bug('maulwurfsgrille','Maulwurfsgrille','Mole cricket','f','boden','nacht',3,900,'Sie hat Schaufeln an den Vorderbeinen.','It has shovels on its front legs.','Maulwurfsgrillen graben ihren Gang wie einen Trichter. Das macht ihr Zirpen viel lauter, wie ein Lautsprecher.','Mole crickets dig their burrow shaped like a funnel. That makes their chirping much louder, like a loudspeaker.',['gr','#8a6a3a',{arms:true,len:.26,wing:'#6a4a2a'}]);
  bug('ruderwanze','Ruderwanze','Water boatman','f','wasser','tag',2,380,'Sie ist winzig, aber singt ganz laut.','It is tiny but sings very loudly.','Eine winzige Ruderwanze singt so laut, dass man sie am Teichufer hören kann. Für ihre Grösse ist sie eines der lautesten Tiere.','A tiny water boatman sings so loudly that you can hear it on the pond bank. For its size, it is one of the loudest animals.',['be','#8a7a5a',{len:1.2,s:.8}]);
  bug('schnarrschrecke','Schnarrschrecke','Rattle grasshopper','f','boden','tag',2,360,'Beim Fliegen schnarrt sie wie eine Rassel.','When it flies, it rattles like a shaker.','Die Schnarrschrecke macht beim Fliegen ein lautes Schnarren. Dabei leuchten ihre roten Hinterflügel auf.','The rattle grasshopper makes a loud rattling sound when it flies. Its red hind wings flash as it does.',['gr','#6a6a5a',{wing:'#e8402a'}]);
  bug('trommelspinne','Trommelspinne','Drumming wolf spider','f','boden','nacht',2,340,'Sie trommelt mit den Beinen auf ein Blatt.','It drums on a leaf with its legs.','Manche Wolfspinnen-Männchen trommeln auf trockene Blätter, damit die Weibchen sie hören.','Some male wolf spiders drum on dry leaves so the females can hear them.',['sp','#5a4a3a',{eyes:true}]);
  bug('glockenbiene','Glockenblumen-Biene','Bellflower bee','f','blume','tag',2,320,'Sie schläft in einer Glockenblume.','It sleeps inside a bellflower.','Die Glockenblumen-Scherenbiene sammelt nur an Glockenblumen. Die Männchen schlafen sogar in den Blüten.','The bellflower bee only gathers from bellflowers. The males even sleep inside the flowers.',['hu','#3a3a44','#5a5a64',{s:.75}]);
  bug('feldgrille','Feldgrille','Field cricket','f','boden','nacht',1,160,'Sie hat vor ihrer Höhle ein Lied gespielt.','It played a song in front of its burrow.','Feldgrillen sitzen vor ihrer Erdhöhle und zirpen. Bei Gefahr flitzen sie blitzschnell hinein.','Field crickets sit in front of their burrow and chirp. When in danger, they dash inside in a flash.',['gr','#1a1a1a',{wing:'#c8a040'}]);
  bug('geigenkaefer','Geigenkäfer','Violin beetle','m','baum','nacht',4,2400,'Er sieht aus wie eine flache Geige.','It looks like a flat violin.','Der Geigenkäfer ist ganz flach. So passt er in die Ritzen zwischen Baumpilzen.','The violin beetle is completely flat. That lets it fit into the gaps between bracket fungi.',['be','#6a4a2a',{len:1.6,s:1.1,key:'geige',pat:(x,w,h)=>{x.fillStyle='#4a3020';x.beginPath();x.ellipse(w/2,h*.35,w*.35,h*.18,0,0,TAU);x.ellipse(w/2,h*.7,w*.42,h*.2,0,0,TAU);x.fill()}}]);

  /* ================= Origami ================= */
  planet('origami');
  fish('fliegenderknurrhahn','Fliegender Knurrhahn','Flying gurnard','m','meer','M','tag',3,920,'Er breitet seine Flossen aus wie Flügel aus Papier.','It spreads its fins like paper wings.','Der Flatterfisch kann nicht fliegen. Er klappt seine riesigen Brustflossen auf, um Feinde zu erschrecken.','The flying gurnard cannot fly. It opens its huge chest fins to scare off enemies.',{H:.15,L:.7,back:'#8a7a6a',belly:'#f0e8d8',fin:'#4ab8ff',tail:'fork',dorsal:'std',ps:3});
  fish('seefledermaus','Seefledermaus','Batfish','f','meer','M','nacht',4,2000,'Sie läuft auf ihren Flossen über den Boden.','It walks across the bottom on its fins.','Seefledermäuse schwimmen nicht gern. Sie laufen lieber auf ihren Flossen über den Meeresgrund.','Batfish do not like swimming much. They prefer to walk across the sea floor on their fins.',{H:.16,L:.5,W:1.8,back:'#c8605a',belly:'#f4e0d8',tail:'round',dorsal:'none',ps:1.6,pat:dots('#8a3a3a',16,5)});
  fish('faltflunder','Falt-Flunder','Folded flounder','f','meer','M','immer',2,400,'Sie ist so flach, als wäre sie gefaltet.','It is so flat, it looks folded.','Flundern können ihre Farbe dem Boden anpassen, auf dem sie liegen. So sind sie fast unsichtbar.','Flounders can change their colour to match the ground they lie on. That makes them almost invisible.',{H:.06,L:.6,W:2.3,back:'#e8dcc8',belly:'#ffffff',tail:'round',dorsal:'long',anal:'long',eyeY:.9,pat:grid('#c8b8a0',32)});
  fish('faltboothecht','Faltboot-Hecht','Paper boat pike','m','teich','L','tag',3,1050,'Er lauert ganz still wie ein Papierboot.','It lies in wait as still as a paper boat.','Hechte stehen ganz still zwischen Wasserpflanzen. Dann schiessen sie blitzschnell nach vorn.','Pike stay perfectly still among water plants. Then they shoot forward in a flash.',{H:.12,L:1,back:'#c8d0b8',belly:'#ffffff',tail:'fork',dorsal:'std',dz:.2,beak:{len:.14,r:.05,flat:1.4},pat:grid('#a8b098',30)});
  fish('faecherguppy','Fächerschwanz-Guppy','Fantail guppy','m','teich','S','tag',1,150,'Sein Schwanz ist ein bunter Papierfächer.','Its tail is a colourful paper fan.','Guppy-Männchen sind bunt und haben grosse Schwanzflossen. Die Weibchen sind meist schlicht grau.','Male guppies are colourful with big tail fins. The females are usually plain grey.',{H:.15,L:.42,back:'#ff6fa5',belly:'#fff0f6',tail:'fan',ts:1.6,dorsal:'std',pat:dots('#45a0ff',10,6)});
  fish('origamigoldfisch','Origami-Goldfisch','Origami goldfish','m','teich','S','immer',1,140,'Er ist aus rotem Papier gefaltet.','It is folded from red paper.','Goldfische stammen von einer Karausche aus China ab. Dort hat man sie vor über tausend Jahren gezüchtet.','Goldfish come from a carp in China. People there started breeding them more than a thousand years ago.',{H:.24,L:.48,back:'#ff5a2a',belly:'#ffd0a0',tail:'fancy',dorsal:'hi',pat:grid('#e84a1a',28)});
  fish('papiermanta','Papier-Manta','Paper manta','m','meer','XL','tag',5,4800,'Er segelt durchs Wasser wie ein grosser Papierdrachen.','It sails through the water like a big paper kite.','Mantarochen haben im Verhältnis zum Körper das grösste Gehirn aller Fische.','For their body size, manta rays have the biggest brain of any fish.',{H:.08,L:.7,W:3.2,back:'#2a2a3a',belly:'#ffffff',tail:'spade',dorsal:'none',anal:false,pat:grid('#4a4a5a',36)});
  bug('faltenwespe','Faltenwespe','Wasp','f','blume','tag',2,330,'Sie faltet ihre Flügel wie Papier.','It folds its wings like paper.','Faltenwespen falten ihre Flügel in Ruhe der Länge nach zusammen. Daher kommt ihr Name.','Wasps of this family fold their wings lengthways when resting. That is where their name comes from.',['li','#ffd23f','#fff8d8',{len:.4,ws:.12,two:true}]);
  bug('blattschneiderbiene','Blattschneiderbiene','Leafcutter bee','f','blume','tag',2,360,'Sie schneidet runde Stücke aus Blättern.','It cuts round pieces out of leaves.','Blattschneiderbienen schneiden runde Stücke aus Blättern und bauen daraus kleine Röhren für ihre Eier.','Leafcutter bees cut round pieces from leaves and build little tubes for their eggs out of them.',['hu','#5a5a5a','#c8a060',{s:.8}]);
  bug('papierdrachenfalter','Papierdrachen-Falter','Paper kite butterfly','m','luft','tag',3,920,'Er schwebt langsam wie ein Papierdrachen.','It floats slowly like a paper kite.','Der Papierdrachen-Falter fliegt sehr langsam und schwebt fast wie ein Blatt Papier im Wind.','The paper kite butterfly flies very slowly, floating almost like a sheet of paper in the wind.',['bf','#fffdf4','#fff8e8','#2a2a2a',{fs:.55,hs:.48}]);
  bug('kurzfluegler','Kurzflügler','Rove beetle','m','boden','nacht',2,330,'Er hat ganz kurze Flügeldecken.','It has very short wing covers.','Kurzflügler falten ihre langen Flügel wie Origami unter ganz kleine Flügeldecken.','Rove beetles fold their long wings like origami under very small wing covers.',['ke',['#2a2a34','#e8402a','#2a2a34','#2a2a34'],4,.06]);
  bug('faecherschrecke','Fächer-Heuschrecke','Fan grasshopper','f','boden','tag',1,160,'Ihre Flügel klappen auf wie ein Fächer.','Its wings open up like a fan.','Heuschrecken falten ihre Hinterflügel wie einen Fächer unter die Vorderflügel.','Grasshoppers fold their hind wings like a fan under their front wings.',['gr','#c8b080',{wing:'#45a0ff'}]);
  bug('schmetterlingshaft','Schmetterlingshaft','Owlfly','m','luft','tag',4,2000,'Er sieht aus wie ein Schmetterling mit Libellenkörper.','It looks like a butterfly with a dragonfly body.','Der Schmetterlingshaft hat lange Fühler mit Knöpfen wie ein Falter und fängt Insekten im Flug wie eine Libelle.','The owlfly has long, knobbed antennae like a butterfly and catches insects in flight like a dragonfly.',['li','#1a1a24','#ffe060',{len:.5,ws:.2}]);
  bug('ameisenjungfer','Ameisenjungfer','Antlion lacewing','f','luft','nacht',3,860,'Ihre Flügel sind fein wie Seidenpapier.','Its wings are as fine as tissue paper.','Aus dem Ameisenlöwen wird später die Ameisenjungfer, ein zartes Insekt mit vier durchsichtigen Flügeln.','The antlion later turns into the antlion lacewing, a delicate insect with four see-through wings.',['li','#5a5a4a','#f4f4ec',{len:.6,ws:.2}]);

  ARTEN3.done();
})();
