/* =====================================================================
   CYBORG-LABOR · arten3.js · Inhalte 2.0, zweiter Schub
   Jeder Planet bekommt ein volles Set: 12 Fische und 12 Insekten.
   Jedes Tier ist echt (oder ein Spielzeug-Verwandter eines echten Tieres)
   und hat einen wahren, kindgerechten Fakt. Die englischen Texte stehen
   direkt daneben und kommen über I18N.extend ins Sprachpaket.
   ===================================================================== */
const ARTEN3=(()=>{
  const{F,B,fishMeta,bugMeta,fishT,butterfly,legs,feelers,bugFace,shade}=NH;
  const{stripes,dots,grid,patch,glowDots,beetle,libelle,grille,kette,spinne,schnecke}=NH.A2;
  const EN={};const IDS=[];let nF=0,nB=0;
  const ART={m:'einen',f:'eine',n:'ein'};
  const an=w=>/^(?:[aeio]|u(?!ly|ni|ra))/i.test(w)?'an':'a';
  const PROPER=/^(Greenland|Ulysses|Arctic|Atlantic|Amazon|Nile|Japanese|Chinese|African|Indian|Pacific|Mexican|European|Siamese|Goliath|Hercules|Atlas)\b/;
  const low=w=>PROPER.test(w)?w:w.charAt(0).toLowerCase()+w.slice(1);
  /* Fang-Satz und Fakt auf Deutsch und Englisch */
  function texts(de,en,g,xde,xen,fde,fen){const acc=g==='m'?de.replace(/^(\S+)er (?=\S)/,'$1en '):de;const tde=`Ich hab ${ART[g]} ${acc} gefangen! ${xde}`,ten=`I caught ${an(en)} ${low(en)}! ${xen}`;
    EN[de]=en;EN[tde]=ten;EN[fde]=fen;return[tde,fde]}
  /* ---------- weitere Körper ---------- */
  function krabbe(g,m,col,o){o=o||{};const b=m.c(col,{gloss:.9,rim:.5});P(g,G.s(.16),b,[0,.12,0],null,[1.25,.5,.9]);
    both(s=>{P(g,G.tu([[s*.15,.1,.08],[s*.24,.14,.18],[s*.2,.14,.26]],.03,.025),b);P(g,G.s(o.claw||.07),b,[s*.2,.15,.29],null,[1,.8,1.3]);
      for(let i=0;i<3;i++)P(g,G.tu([[s*.16,.1,.02-i*.07],[s*.3,.16,.0-i*.08],[s*.36,.01,-.02-i*.09]],.018,.012),b);
      P(g,G.cy(.012,.012,.1,6),b,[s*.05,.2,.1]);P(g,G.s(.03),m.c('#1a1a24',{gloss:1.6}),[s*.05,.26,.1])})}
  function hummel(g,m,c1,c2,o){o=o||{};const t=m.tex('a3-hu-'+c1+c2,ctex('a3-hu-'+c1+c2,64,64,(x,w,h)=>{x.fillStyle=c1;x.fillRect(0,0,w,h);x.fillStyle=c2;x.fillRect(0,20,w,10);x.fillRect(0,44,w,8)}),{gloss:.4,rim:.8});
    P(g,G.s(.16*(o.s||1)),t,[0,.24,-.04],[PI/2,0,0],[1,1.25,1]);P(g,G.s(.1*(o.s||1)),m.c(c2,{gloss:.4}),[0,.26,.17]);bugFace(g,m,[0,.26,.2],.1,.6,{mouth:false});
    const wm=m.c('#e8f6ff',{opacity:.5});both(s=>{const w=P(g,G.s(.13),wm,[s*.14,.38,0],null,[1,.05,.5]);w.userData.noOutline=true});
    const k=m.c('#2a2438');legs(g,k,[[.1,.2,.05,.03],[0,.22,0,.03],[-.1,.2,-.05,.03]],.15,.014);feelers(g,k,k,[.04,.3,.24],.1,.06)}
  function raupe(g,m,cols,n){kette(g,m,cols,n||6,.065)}
  const K={be:beetle,li:libelle,gr:grille,ke:kette,sp:spinne,sn:schnecke,kr:krabbe,hu:hummel,ra:raupe};
  /* Fisch: id, Name, Name-en, Geschlecht (m/f/n), wo, Grösse, Zeit, Seltenheit, Preis, Zusatz de/en, Fakt de/en, Aussehen */
  function fish(id,de,en,g,wh,sz,tm,r,pr,xde,xen,fde,fen,o){const pl=CUR;const[t,f]=texts(de,en,g,xde,xen,fde,fen);nF++;IDS.push(id);
    F(id,fishMeta(de,pl,wh,sz,tm,r,pr,t,f),(gg,m)=>{const R=fishT(gg,m,Object.assign({id},o));extras(gg,m,R,o)})}
  /* Schnauze (Schwert, Säge, Löffel) und Arme (Kalmar, Sepia) */
  function extras(g,m,R,o){const b=o.beak;if(b){const mat=m.c(b.col||shade(o.back,.9),{gloss:.9,rim:.5});const L=b.len||.4,r=b.r||.03;
      P(g,G.co(r,L,10),mat,[0,b.y||0,R.nz+L/2-.02],[PI/2,0,0],[b.flat||1,1,b.flat?.35:1]);
      if(b.saw)for(let i=1;i<8;i++){const z=R.nz+L*i/8.5;const w=r*(b.flat||1)*(1-i/8.5)+.012;both(s=>P(g,G.co(.012,.05,5),m.c('#f4f0e8'),[s*w,b.y||0,z],[0,0,-s*PI/2]))}}
    if(o.arms){const am=m.c(o.armCol||shade(o.back,.95),{gloss:.8,rim:.5});for(let i=0;i<o.arms;i++){const a=i/o.arms*TAU,x=Math.cos(a)*R.H*.45,y=Math.sin(a)*R.H*.45,len=(i<2?.42:.26)*(o.armL||1);
      P(g,G.tu([[x,y,R.nz-.03],[x*1.3,y*1.3-.02,R.nz+len*.5],[x*1.1,y*1.1-.06,R.nz+len]],.022,.01),am)}}}
  /* Insekt: …, Körper als [Bausatz, Argumente…]; 'bf' = Schmetterling */
  function bug(id,de,en,g,wh,tm,r,pr,xde,xen,fde,fen,b){const pl=CUR;const[t,f]=texts(de,en,g,xde,xen,fde,fen);nB++;IDS.push(id);
    B(id,bugMeta(de,pl,wh,tm,r,pr,t,f),(gg,m)=>{const[k,...a]=b;if(k==='bf')butterfly(gg,m,id,...a);else K[k](gg,m,...a)})}
  let CUR='';const planet=p=>{CUR=p};

  /* ================= Kompost ================= */
  planet('kompost');
  fish('rotfeder','Rotfeder','Rudd','f','teich','S','tag',1,160,'Ihre Flossen leuchten rot wie Kirschen.','Its fins glow red like cherries.','Rotfedern fressen gern Wasserpflanzen. Sie schwimmen meist knapp unter der Oberfläche.','Rudd like to eat water plants. They usually swim just below the surface.',{H:.2,L:.6,back:'#7a8a5a',belly:'#f4ecc8',fin:'#e8503a',tail:'fork',dorsal:'std'});

  /* ================= Schrott ================= */
  planet('schrott');
  fish('schaltkreisschmerle','Schaltkreis-Schmerle','Circuit loach','f','kuehlwasser','S','nacht',2,420,'Auf ihrem Rücken laufen Leiterbahnen entlang.','Circuit lines run along its back.','Schmerlen haben Barteln am Maul. Damit tasten und schmecken sie am Boden nach Futter.','Loaches have barbels around their mouth. They use them to feel and taste for food on the bottom.',{H:.11,L:.7,back:'#2a6a4a',belly:'#c8f0d0',tail:'round',dorsal:'std',dz:.45,pat:grid('#9affc0',24)});
  bug('schraubenschnecke','Schrauben-Schnecke','Screw snail','f','schrott','immer',1,150,'Ihr Haus ist gedreht wie eine Schraube.','Its shell is twisted like a screw.','Schnecken haben eine Raspelzunge mit Tausenden winzigen Zähnchen. Damit schaben sie ihr Futter ab.','Snails have a rasping tongue with thousands of tiny teeth. They use it to scrape off their food.',['sn','#9aa4b0','#5a6470']);
  bug('drahtspinne','Draht-Spinne','Wire spider','f','schrott','nacht',2,380,'Ihr Netz glänzt wie feiner Draht.','Its web shines like fine wire.','Spinnenseide ist für ihr Gewicht sehr reissfest, fester als ein gleich dünner Stahlfaden.','For its weight, spider silk is very strong, stronger than a steel thread of the same thickness.',['sp','#c87a3a',{leg:.26}]);
  bug('rostwanze','Rost-Wanze','Rust bug','f','schrott','tag',1,170,'Sie ist rot-schwarz wie alter Rost.','It is red and black like old rust.','Feuerwanzen sitzen oft in grossen Gruppen in der Sonne, gern am Fuss von Linden.','Firebugs often sit together in big groups in the sun, especially at the foot of linden trees.',['be','#d8402a',{key:'rost',len:1,pat:(x,w,h)=>{x.fillStyle='#1a1a24';x.beginPath();x.arc(w*.3,h*.5,14,0,TAU);x.arc(w*.7,h*.5,14,0,TAU);x.fill();x.fillRect(w/2-3,0,6,h)}}]);
  bug('funkenzirpe','Funken-Zirpe','Spark cricket','f','schrott','nacht',3,820,'Wenn sie zirpt, knistert es wie ein Funke.','When it chirps, it crackles like a spark.','Grillen hören mit Ohren an den Vorderbeinen. Die sitzen gleich unter dem Knie.','Crickets hear with ears on their front legs, just below the knee.',['gr','#4a4a5a',{wing:'#ffb030'}]);

  /* ================= Korallen ================= */
  planet('korallen');
  fish('feuerfisch','Feuerfisch','Lionfish','m','meer','M','nacht',3,1200,'Seine Flossen sehen aus wie Federn.','Its fins look like feathers.','Feuerfische haben lange Flossenstrahlen mit Stacheln. Andere Fische halten deshalb lieber Abstand.','Lionfish have long fin rays with spines, so other fish prefer to keep their distance.',{H:.2,L:.6,back:'#e8603a',belly:'#fff0e0',tail:'fancy',dorsal:'spiky',ds:1.6,ps:1.8,pat:stripes('#fff4e8',8)});
  bug('geisterkrabbe','Geisterkrabbe','Ghost crab','f','boden','nacht',2,400,'Sie ist so schnell, dass man sie kaum sieht.','It is so fast you can hardly see it.','Geisterkrabben rennen sehr schnell seitwärts über den Strand. Sie kommen vor allem nachts heraus.','Ghost crabs run very fast sideways across the beach. They mostly come out at night.',['kr','#f0e4c8',{claw:.06}]);
  bug('palmendieb','Palmendieb','Coconut crab','m','baum','nacht',4,2400,'Er klettert ganz allein auf die Palme.','It climbs the palm tree all by itself.','Der Palmendieb ist die grösste Krabbe, die an Land lebt. Er kann auf Palmen klettern.','The coconut crab is the largest crab that lives on land. It can climb palm trees.',['kr','#4a6ad8',{claw:.1}]);
  bug('kaurischnecke','Kaurischnecke','Cowrie','f','boden','tag',2,350,'Ihr Haus glänzt wie Porzellan.','Its shell shines like porcelain.','Kaurischnecken haben glatte, glänzende Häuser. An manchen Orten hat man sie früher als Geld benutzt.','Cowries have smooth, shiny shells. In some places people once used them as money.',['sn','#f4e0c0','#c88a5a']);
  bug('ulyssesfalter','Ulyssesfalter','Ulysses butterfly','m','luft','tag',3,1000,'Er blitzt leuchtend blau in der Sonne.','It flashes bright blue in the sun.','Der Ulyssesfalter lebt im tropischen Regenwald. Von oben ist er leuchtend blau, von unten braun und gut versteckt.','The Ulysses butterfly lives in the tropical rainforest. From above it is bright blue, from below brown and well hidden.',['bf','#1a8aff','#1a6ad8','#1a1a24']);
  bug('palmenruessler','Palmenrüssler','Palm weevil','m','baum','tag',2,330,'Er hat eine lange Nase wie ein Rüssel.','It has a long nose like a trunk.','Rüsselkäfer haben ihr Maul ganz vorn an der Spitze des Rüssels. Es gibt sehr viele verschiedene Arten.','Weevils have their mouth right at the tip of their snout. There are a huge number of different kinds.',['be','#a03a2a',{horn:true,len:1.3}]);
  bug('wanderlibelle','Wanderlibelle','Globe skimmer','f','luft','tag',3,900,'Sie ist schon übers ganze Meer geflogen.','It has flown across the whole sea.','Die Wanderlibelle fliegt mit dem Wind Tausende Kilometer weit, sogar über Ozeane.','The globe skimmer rides the wind for thousands of kilometres, even across oceans.',['li','#ffb030','#fff4d8']);

  /* ================= Frost ================= */
  planet('frost');
  fish('saibling','Saibling','Arctic char','m','eissee','M','tag',2,420,'Sein Bauch leuchtet orange wie ein Sonnenuntergang.','Its belly glows orange like a sunset.','Der Saibling lebt weiter im Norden als fast jeder andere Süsswasserfisch.','The Arctic char lives further north than almost any other freshwater fish.',{H:.18,L:.75,back:'#3a5a7a',belly:'#ff8a3a',tail:'fork',dorsal:'std',pat:dots('#f4f8ff',22,5)});
  fish('groenlandhai','Grönlandhai','Greenland shark','m','eissee','XL','nacht',5,4200,'Er schwimmt gemütlich und ganz langsam.','It swims along slowly and comfortably.','Grönlandhaie schwimmen sehr langsam und werden älter als jedes andere Wirbeltier, das man kennt: mehrere hundert Jahre.','Greenland sharks swim very slowly and live longer than any other known animal with a backbone: several hundred years.',{H:.17,L:1.15,back:'#5a6470',belly:'#c8d0d8',tail:'moon',dorsal:'tri',ds:.7});
  fish('polardorsch','Polardorsch','Polar cod','m','eissee','S','immer',1,180,'Er ist kalt wie ein Eiswürfel und trotzdem munter.','It is as cold as an ice cube and still lively.','Viele Polarfische haben einen Frostschutz im Blut. So gefrieren sie im eiskalten Wasser nicht.','Many polar fish have a kind of antifreeze in their blood, so they do not freeze in icy water.',{H:.15,L:.6,back:'#8a9aa8',belly:'#f4f8ff',tail:'fork',dorsal:'long',pat:dots('#5a6a7a',14,4)});
  fish('seehase','Seehase','Lumpsucker','m','eissee','M','tag',3,950,'Er saugt sich an meinem Finger fest.','It sucks onto my finger.','Der Seehase hat am Bauch eine Saugscheibe. Damit hält er sich an Steinen fest, wenn die Wellen kommen.','The lumpsucker has a sucker disc on its belly. It holds on to rocks with it when the waves come.',{H:.28,L:.5,W:.9,back:'#5a8a6a',belly:'#e8f0c8',tail:'round',dorsal:'hi',pat:dots('#3a6a4a',16,7)});
  bug('winterlibelle','Winterlibelle','Winter damselfly','f','luft','tag',3,850,'Sie fliegt sogar im Schnee herum.','It flies around even in the snow.','Winterlibellen überwintern als fertige Libelle. Im Frühling fliegen sie als erste Libellen des Jahres.','Winter damselflies spend the winter as adults. In spring they are the first damselflies of the year.',['li','#a08a6a','#f0f8ff',{len:.45,ws:.15}]);
  bug('frostspanner','Frostspanner','Winter moth','m','luft','nacht',2,380,'Er flattert mitten im Winter.','It flutters around in the middle of winter.','Frostspanner fliegen im Winter. Die Weibchen haben fast keine Flügel und krabbeln die Bäume hoch.','Winter moths fly in winter. The females have almost no wings and crawl up the trees.',['bf','#c8bca0','#d8ccb0','#8a7a6a',{fs:.42,hs:.36}]);
  bug('winterhaft','Winterhaft','Snow scorpionfly','m','stein','tag',3,900,'Er hüpft über den Schnee wie ein Floh.','It hops over the snow like a flea.','Winterhafte sind nur wenige Millimeter gross und krabbeln im Winter über den Schnee.','Snow scorpionflies are only a few millimetres long and crawl over the snow in winter.',['gr','#3a3a4a',{wing:'#6a7a8a',ant:.2}]);
  bug('polarwolfspinne','Polar-Wolfspinne','Arctic wolf spider','f','stein','immer',2,360,'Sie trägt ihre Babys auf dem Rücken.','It carries its babies on its back.','Wolfspinnen-Mütter tragen ihre Jungen auf dem Rücken herum, bis sie gross genug sind.','Wolf spider mothers carry their young around on their back until they are big enough.',['sp','#6a5a4a',{eyes:true,body:.12}]);
  bug('polarhummel','Polarhummel','Arctic bumblebee','f','blume','tag',3,880,'Sie hat einen dicken Pelz gegen die Kälte.','It has a thick fur coat against the cold.','Hummeln wärmen sich auf, indem sie ihre Flugmuskeln zittern lassen. So fliegen sie auch bei Kälte.','Bumblebees warm up by shivering their flight muscles, so they can fly even when it is cold.',['hu','#ffd23f','#2a2438',{s:1.1}]);
  bug('eiswurm','Eiswurm','Ice worm','m','boden','nacht',4,1900,'Er wohnt mitten im Gletschereis.','It lives right inside the glacier ice.','Eiswürmer leben im Eis von Gletschern. Wird es ihnen zu warm, verkriechen sie sich tiefer ins Eis.','Ice worms live inside glaciers. If it gets too warm for them, they wriggle deeper into the ice.',['ra',['#3a3a4a','#4a4a5a'],7]);

  /* ================= Wüste ================= */
  planet('wueste');
  fish('hoehlensalmler','Höhlensalmler','Blind cave fish','m','oase','S','nacht',3,880,'Er hat keine Augen und findet trotzdem den Weg.','It has no eyes and still finds its way.','Der Höhlensalmler lebt in dunklen Höhlen. Er spürt seine Umgebung mit einem Sinnesorgan an der Seite, dem Seitenlinienorgan.','The blind cave fish lives in dark caves. It senses its surroundings with an organ along its side called the lateral line.',{H:.17,L:.55,back:'#f4c8c0',belly:'#fff0ec',tail:'fork',dorsal:'std',eye:.001});
  fish('wuestengrundel','Wüstengrundel','Desert goby','f','oase','S','tag',2,360,'Sie liegt gemütlich auf dem Grund.','It lies comfortably on the bottom.','Die Wüstengrundel hält sehr warmes und salziges Wasser aus, in dem andere Fische nicht überleben.','The desert goby can cope with very warm and salty water where other fish cannot survive.',{H:.14,L:.55,back:'#c8a060',belly:'#fff4d8',tail:'round',dorsal:'hi',pat:dots('#8a6a3a',14,5)});
  fish('schuetzenfisch','Schützenfisch','Archerfish','m','oase','M','tag',3,1050,'Er hat mir Wasser ins Gesicht gespritzt!','It squirted water in my face!','Schützenfische spritzen einen Wasserstrahl auf Insekten über dem Wasser. Die Insekten fallen herunter und werden gefressen.','Archerfish shoot a jet of water at insects above the water. The insects fall down and get eaten.',{H:.22,L:.6,back:'#c8c8a0',belly:'#fffff0',tail:'round',dorsal:'std',dz:.35,pat:stripes('#2a2a2a',5)});
  fish('schlammspringer','Schlammspringer','Mudskipper','m','oase','M','immer',2,480,'Er ist mir aus dem Eimer gehüpft!','It hopped right out of my bucket!','Schlammspringer können an Land laufen. Sie stützen sich dabei auf ihre kräftigen Brustflossen.','Mudskippers can walk on land. They prop themselves up on their strong chest fins.',{H:.16,L:.7,back:'#8a7a5a',belly:'#e8dcc0',tail:'round',dorsal:'sail',dz:.5,eyeY:.7,eye:.07,ps:1.6,pat:dots('#4a8ad8',18,4)});
  fish('fadenfisch','Mosaik-Fadenfisch','Pearl gourami','m','oase','S','tag',2,400,'Er hat lange Fäden statt Bauchflossen.','It has long threads instead of belly fins.','Fadenfische können Luft von der Oberfläche atmen. Die Männchen bauen Nester aus Schaumblasen.','Gouramis can breathe air from the surface. The males build nests out of foam bubbles.',{H:.24,L:.55,back:'#c8b8a0',belly:'#ffd8b0',tail:'round',dorsal:'long',pat:dots('#fff8f0',30,4)});
  bug('ameisenloewe','Ameisenlöwe','Antlion','m','boden','tag',2,400,'Er hat sich in einem Sandtrichter versteckt.','It was hiding in a sand funnel.','Die Larve des Ameisenlöwen gräbt einen Trichter in den Sand. Rutscht eine Ameise hinein, wird sie gefangen.','The antlion larva digs a funnel in the sand. If an ant slides in, it gets caught.',['be','#a08060',{len:.9,s:.9,ant:.05}]);
  bug('nebeltrinker','Nebeltrinker-Käfer','Fog-basking beetle','m','boden','nacht',3,1100,'Auf seinem Rücken glitzern Wassertropfen.','Water drops sparkle on its back.','Ein Käfer in der Namib-Wüste stellt sich in den Nebel. Die Tropfen sammeln sich auf seinem Rücken und laufen ihm ins Maul.','A beetle in the Namib desert stands in the fog. Drops collect on its back and run into its mouth.',['be','#2a2a34',{key:'nebel',pat:(x,w,h)=>{x.fillStyle='#c8e8ff';for(let i=0;i<14;i++){x.beginPath();x.arc((i*37)%w,(i*53)%h,4,0,TAU);x.fill()}}}]);
  bug('wuestenameise','Wüstenameise','Desert ant','f','boden','tag',2,320,'Sie flitzt auf langen Beinen über den heissen Sand.','It zooms across the hot sand on long legs.','Wüstenameisen finden ihr Nest mit Hilfe der Sonne. Sie zählen sogar ihre Schritte.','Desert ants find their nest using the sun. They even count their steps.',['ke',['#2a2420','#3a302a','#2a2420'],3,.065]);
  bug('distelfalter','Distelfalter','Painted lady','m','blume','tag',2,380,'Er kommt von ganz weit her geflogen.','It has flown here from very far away.','Distelfalter fliegen jedes Jahr aus Afrika bis nach Europa. Die Reise schaffen mehrere Generationen nacheinander.','Painted ladies fly from Africa to Europe every year. It takes several generations, one after the other, to finish the trip.',['bf','#ff8a3a','#e8703a','#2a2420']);
  bug('sandwespe','Sandwespe','Sand wasp','f','boden','tag',3,820,'Sie gräbt schneller als eine Schaufel.','It digs faster than a shovel.','Sandwespen graben ihre Nester in sandigen Boden. Für jedes Ei bauen sie eine eigene kleine Kammer.','Sand wasps dig their nests in sandy ground. They build a small chamber of its own for each egg.',['li','#ffd23f','#fff4c8',{len:.4,ws:.14,two:true}]);

  /* ================= Pilz ================= */
  planet('pilz');
  fish('schlammpeitzger','Schlammpeitzger','Weatherfish','m','sumpf','M','nacht',3,900,'Er zappelt, als käme gleich ein Gewitter.','It wriggles as if a storm were coming.','Der Schlammpeitzger wird unruhig, wenn sich das Wetter ändert. Darum heisst er auf Englisch Wetterfisch.','The weatherfish gets restless when the weather changes. That is how it got its name.',{H:.11,L:.85,back:'#8a6a3a',belly:'#e8d8b0',tail:'round',dorsal:'std',dz:.35,pat:stripes('#4a3a20',3,true)});
  fish('hundsfisch','Hundsfisch','Mudminnow','m','sumpf','S','tag',2,340,'Er schnappt an der Oberfläche nach Luft.','It gulps air at the surface.','Der Hundsfisch kann Luft schlucken. So überlebt er in Mooren, in denen wenig Sauerstoff im Wasser ist.','The mudminnow can swallow air. That is how it survives in bogs with little oxygen in the water.',{H:.18,L:.55,back:'#6a5a3a',belly:'#e0d4b0',tail:'round',dorsal:'std',dz:.4,pat:dots('#3a2a1a',14,5)});
  fish('mooraal','Moor-Aal','Bog eel','m','sumpf','L','nacht',4,2100,'Er ist lang und glitschig wie ein Seil.','It is long and slippery like a rope.','Aale wandern zum Eierlegen viele tausend Kilometer weit bis in die Sargassosee im Atlantik.','Eels travel thousands of kilometres to the Sargasso Sea in the Atlantic to lay their eggs.',{H:.08,L:1.1,back:'#4a4a2a',belly:'#d8d0a0',tail:'none',dorsal:'long',dz:.15,ds:2.2,anal:'long'});
  fish('bachneunauge','Bachneunauge','Brook lamprey','n','sumpf','M','tag',3,800,'Es sieht aus, als hätte es neun Augen.','It looks as if it has nine eyes.','Das Neunauge hat ein Auge, eine Nasenöffnung und sieben Kiemenlöcher auf jeder Seite. Zusammen sieht das aus wie neun Augen.','The lamprey has one eye, one nostril and seven gill holes on each side. Together they look like nine eyes.',{H:.08,L:.95,back:'#7a7a6a',belly:'#e8e4d0',tail:'none',dorsal:'long',dz:.2,pect:false,anal:false,pat:(x,w,h)=>{x.fillStyle='#2a2a24';for(let i=0;i<7;i++){x.beginPath();x.arc(w*.2+i*6,h*.5,2.5,0,TAU);x.arc(w*.8-i*6,h*.5,2.5,0,TAU);x.fill()}}});
  bug('leuchtmuecke','Leuchtmücke','Glow-worm gnat','f','luft','nacht',3,950,'Ihr Hinterteil leuchtet blau wie ein Sternenhimmel.','Its tail glows blue like a starry sky.','In Höhlen in Neuseeland hängen Leuchtmücken-Larven an der Decke und leuchten wie ein Sternenhimmel.','In caves in New Zealand, glow-worm larvae hang from the ceiling and shine like a starry sky.',['li','#4a4a5a','#c8f0ff',{len:.4,ws:.13}]);
  bug('schwammkaefer','Schwammkäfer','Fungus beetle','m','baum','immer',1,180,'Er knabbert am liebsten an Pilzen.','It likes to nibble on mushrooms best.','Pilzkäfer leben auf Baumpilzen und fressen sie. Viele sind bunt gemustert.','Fungus beetles live on bracket fungi and eat them. Many have colourful patterns.',['be','#ff8a3a',{key:'schwamm',pat:(x,w,h)=>{x.fillStyle='#1a1a24';x.fillRect(0,h*.3,w,12);x.fillRect(0,h*.65,w,12)}}]);
  bug('tigerschnegel','Tigerschnegel','Leopard slug','m','boden','nacht',2,330,'Er ist gefleckt wie ein Tiger, nur ohne Haus.','It is spotted like a tiger, just without a shell.','Nacktschnecken sind Schnecken ohne Haus. Der Tigerschnegel frisst gern Pilze und welke Pflanzen.','Slugs are snails without a shell. The leopard slug likes to eat mushrooms and wilted plants.',['ra',['#c8b090','#8a6a4a','#c8b090','#8a6a4a'],6]);
  bug('springschwanz','Springschwanz','Springtail','m','boden','immer',1,140,'Hupps, er ist mir fast weggesprungen!','Whoops, it almost jumped away!','Springschwänze haben eine Sprunggabel unter dem Bauch. Damit schnellen sie sich weg wie eine Feder.','Springtails have a jumping fork under their belly. They use it to fling themselves away like a spring.',['gr','#8a6ad8',{len:.16,wing:'#6a4ab8'}]);
  bug('moosjungfer','Moosjungfer','Whiteface darter','f','wasser','tag',3,880,'Ihr Gesicht ist weiss wie ein Pilzhut.','Its face is white like a mushroom cap.','Libellenlarven leben bis zu mehreren Jahren im Wasser, bevor sie als Libelle schlüpfen.','Dragonfly larvae can live in the water for several years before they hatch as dragonflies.',['li','#c83a3a','#f4f0e8']);

  /* ================= Riesengarten ================= */
  planet('riesengarten');
  fish('dreistachler','Stichling','Stickleback','m','teich','S','tag',1,150,'Auf seinem Rücken hat er drei Stacheln.','It has three spines on its back.','Das Stichling-Männchen baut ein Nest aus Pflanzen und bewacht die Eier ganz allein.','The male stickleback builds a nest out of plants and guards the eggs all by itself.',{H:.18,L:.45,back:'#5a7a5a',belly:'#e8503a',tail:'fork',dorsal:'spiky',ds:.8});
  fish('wasserfloh','Wasserfloh','Water flea','m','teich','S','immer',1,110,'Hier im Riesengarten ist er so gross wie meine Hand.','Here in the giant garden it is as big as my hand.','Wasserflöhe sind winzige Krebse. Man kann durch ihren Körper hindurch das Herz schlagen sehen.','Water fleas are tiny crustaceans. You can see their heart beating through their body.',{H:.3,L:.4,W:.6,back:'#e8c8a0',belly:'#fff4e0',tail:'spade',dorsal:'none',anal:false,gloss:1.4});
  fish('gruendling','Gründling','Gudgeon','m','teich','S','tag',1,140,'Er schnüffelt mit seinen Barteln am Boden.','It sniffs the bottom with its barbels.','Gründlinge suchen mit ihren Barteln am Grund nach kleinen Tieren. Sie schwimmen gern in Gruppen.','Gudgeons search the bottom for small animals with their barbels. They like to swim in groups.',{H:.14,L:.55,back:'#8a8060',belly:'#f4f0e0',tail:'fork',dorsal:'std',pat:dots('#4a4030',10,7)});
  fish('rotauge','Rotauge','Roach','n','teich','S','immer',1,130,'Es hat rote Augen, aber es weint nicht.','It has red eyes, but it is not crying.','Rotaugen haben eine rote Iris. Sie gehören zu den häufigsten Fischen in Seen und Teichen.','Roach have a red iris. They are among the most common fish in lakes and ponds.',{H:.22,L:.55,back:'#5a6a7a',belly:'#f4f4f0',fin:'#e86a4a',tail:'fork',dorsal:'std'});
  fish('posthornschnecke','Posthornschnecke','Ramshorn snail','f','teich','S','tag',2,300,'Ihr Haus ist aufgerollt wie ein Posthorn.','Its shell is coiled up like a post horn.','Posthornschnecken haben rotes Blut. Darin ist, wie bei uns, ein roter Stoff, der Sauerstoff trägt.','Ramshorn snails have red blood. Like ours, it contains a red substance that carries oxygen.',{H:.3,L:.4,W:1.2,back:'#a0502a',belly:'#e8a070',tail:'none',dorsal:'none',anal:false,pect:false,pat:stripes('#6a2a1a',6,true)});
  fish('teichmolch','Teichmolch','Smooth newt','m','teich','M','nacht',3,850,'Er hat einen Kamm auf dem Rücken wie ein kleiner Drache.','It has a crest on its back like a little dragon.','Molche können verlorene Beine und sogar Teile des Herzens wieder nachwachsen lassen.','Newts can regrow lost legs and even parts of their heart.',{H:.1,L:.85,back:'#7a6a4a',belly:'#ff8a3a',tail:'spade',dorsal:'long',dz:.1,ds:1.8,anal:'long',pat:dots('#2a2420',20,5)});
  fish('bachflohkrebs','Bachflohkrebs','Freshwater shrimp','m','teich','S','nacht',2,280,'Er schwimmt auf der Seite, ganz schön lustig.','It swims on its side, which looks really funny.','Bachflohkrebse leben nur in sauberem Wasser. Wo es viele gibt, ist der Bach gesund.','Freshwater shrimp only live in clean water. Where there are many, the stream is healthy.',{H:.18,L:.5,W:.5,back:'#c8a080',belly:'#f4e4d0',tail:'fork',dorsal:'none',pat:stripes('#a07a5a',7)});
  bug('wegameise','Wegameise','Black garden ant','f','boden','tag',1,120,'Sie trägt einen Krümel, der grösser ist als sie selbst.','It is carrying a crumb bigger than itself.','Wegameisen beschützen Blattläuse und bekommen dafür süssen Honigtau, fast wie Bauern mit ihren Kühen.','Garden ants protect aphids and get sweet honeydew in return, almost like farmers with their cows.',['ke',['#1a1a24','#2a2a34','#1a1a24'],3,.06]);
  bug('kohlweissling','Kohlweissling','Cabbage white','m','blume','tag',1,150,'Er ist weiss wie ein Blatt Papier.','It is white like a sheet of paper.','Die Raupen des Kohlweisslings fressen am liebsten Kohl. Darum heisst der Falter so.','Cabbage white caterpillars love to eat cabbage. That is how the butterfly got its name.',['bf','#f8f8f0','#f0f0e0','#3a3a44']);
  bug('schaumzikade','Schaumzikade','Froghopper','f','blume','tag',2,320,'Sie wohnte in einem kleinen Schaumhäufchen.','It was living in a little heap of foam.','Die Larven der Schaumzikade bauen sich ein Versteck aus Schaum. Man nennt es Kuckucksspeichel.','Froghopper larvae build a hiding place out of foam. People call it cuckoo spit.',['gr','#8a6a3a',{len:.16,wing:'#c8a060',ant:.1}]);
  bug('streifenwanze','Streifenwanze','Striped shield bug','f','blume','tag',2,300,'Sie trägt einen rot-schwarz gestreiften Pullover.','It wears a red and black striped jumper.','Streifenwanzen sitzen gern auf Doldenblüten wie wilder Möhre. Ihre Streifen warnen Vögel.','Striped shield bugs like to sit on umbel flowers such as wild carrot. Their stripes warn birds.',['be','#e8302a',{key:'streifen',len:1,pat:stripes('#1a1a24',4)}]);
  bug('heupferd','Grünes Heupferd','Great green bush-cricket','n','baum','nacht',3,820,'Es ist grün wie ein Blatt und sehr lang.','It is as green as a leaf and very long.','Das Grüne Heupferd hört mit Ohren an den Vorderbeinen und kann sehr laut zirpen.','The great green bush-cricket hears with ears on its front legs and can chirp very loudly.',['gr','#5ac83a',{len:.3,ant:.42,wing:'#3aa02a'}]);
  bug('steinlaeufer','Steinläufer','Stone centipede','m','boden','nacht',2,280,'Er saust auf ganz vielen Beinen davon.','It zooms away on lots of legs.','Hundertfüsser haben an jedem Körperring ein Beinpaar, Tausendfüsser dagegen zwei.','Centipedes have one pair of legs on each body segment, millipedes have two.',['ra',['#a0502a','#b8602a'],8]);

  /* englische Texte ins Sprachpaket (jede Datei ruft das am Ende auf) */
  function done(){try{if(typeof I18N!=='undefined'&&I18N.extend)I18N.extend('en',EN)}catch(e){}}
  done();
  return{EN,IDS,get count(){return{fish:nF,bugs:nB}},planet,fish,bug,done};
})();
