/* =====================================================================
   CYBORG-LABOR · funde2.js · Fundstücke für alle Planeten
   Viele Planeten hatten nur zwei oder drei Fundstücke zum Ausgraben.
   Jetzt hat jeder Planet mindestens sechs, jeder kleine Mond drei. Jedes
   Stück hat einen wahren, kindgerechten Fakt auf Deutsch und Englisch.
   ===================================================================== */
(()=>{
  const{REL,relMeta}=NH;const EN={};
  const F=(id,pl,kind,rar,price,de,en,tde,ten,fde,fen,b)=>{EN[de]=en;EN[tde]=ten;EN[fde]=fen;if(!RELICS.some(r=>r.id===id))REL(id,relMeta(de,pl,kind,rar,price,tde,fde),b)};
  /* Bausteine */
  const jar=(g,m,h,inner)=>{P(g,G.cy(.17,.17,h,Q(16)),m.c('#e8f8ff',{opacity:.35,gloss:1.4}),[0,h/2,0]);P(g,G.cy(.18,.18,.06,Q(16)),m.c('#8a5a3a'),[0,h+.03,0]);if(inner)inner()};
  const stand=(g,m,col)=>P(g,G.cy(.22,.25,.06,Q(16)),m.c(col||'#6a4a3a'),[0,.03,0]);
  const coin=(g,m,col,r,y,rot)=>P(g,G.cy(r,r,.03,Q(20)),m.c(col,{gloss:1.4}),[0,y,0],rot||[PI/2,0,0]);

  /* ================= Frost ================= */
  F('schneeflocke_glas','frost','natur',2,700,'Schneeflocke im Glas','Snowflake in a jar','Eine Schneeflocke, die nie schmilzt. Sie hat genau sechs Arme.','A snowflake that never melts. It has exactly six arms.','Schneeflocken haben fast immer sechs Arme. Das liegt daran, wie sich Wasserteilchen beim Gefrieren aneinanderhängen.','Snowflakes almost always have six arms. That comes from the way water particles link up when they freeze.',(g,m)=>jar(g,m,.4,()=>{for(let i=0;i<3;i++)P(g,G.bx(.2,.02,.02),m.glow('#dff4ff',1.3),[0,.2,0],[0,0,i*PI/3])}));
  F('knochenschlittschuh','frost','alltag',2,900,'Knochen-Schlittschuh','Bone ice skate','Ein Schlittschuh aus Knochen, mit Lederbändern festgebunden.','An ice skate made of bone, tied on with leather straps.','Die ersten Schlittschuhe waren aus Tierknochen. Menschen sind damit schon vor mehreren tausend Jahren über das Eis geglitten.','The first ice skates were made of animal bones. People glided over the ice on them several thousand years ago.',(g,m)=>{P(g,G.ca(.06,.45),m.c('#f0e6d0'),[0,.07,0],[0,0,PI/2]);P(g,G.bx(.4,.12,.18,.04),m.c('#8a5a3a'),[0,.18,0]);for(const x of[-.12,.12])P(g,G.to(.1,.015),m.c('#5a3a2a'),[x,.22,0],[0,PI/2,0])});
  F('polarlichtflasche','frost','kunst',3,1500,'Polarlicht-Flasche','Northern lights bottle','In der Flasche tanzen grüne und violette Lichter.','Green and purple lights dance inside the bottle.','Polarlichter entstehen, wenn winzige Teilchen von der Sonne auf die Luft hoch über der Erde treffen. Dann leuchtet die Luft grün, rot oder violett.','Northern lights appear when tiny particles from the Sun hit the air high above the Earth. Then the air glows green, red or purple.',(g,m)=>{P(g,G.s(.2),m.c('#e8f8ff',{opacity:.3,gloss:1.4}),[0,.22,0]);P(g,G.cy(.06,.06,.15,Q(10)),m.c('#e8f8ff',{opacity:.3}),[0,.45,0]);P(g,G.cy(.07,.07,.05,Q(10)),m.c('#8a5a3a'),[0,.54,0]);for(const[c,y]of[['#7fffb0',.18],['#c87aff',.27]])P(g,G.to(.11,.02,PI*1.4),m.glow(c,1.6),[0,y,0],[PI/2,0,y*9])});

  /* ================= Wüste ================= */
  F('sanduhr','wueste','alltag',2,800,'Alte Sanduhr','Old hourglass','Der Sand rieselt genau drei Minuten lang.','The sand trickles for exactly three minutes.','Sanduhren wurden früher auf Schiffen benutzt, um die Zeit zu messen. Man drehte sie immer wieder um.','Hourglasses were once used on ships to measure time. People turned them over again and again.',(g,m)=>{for(const y of[.02,.5])P(g,G.cy(.18,.18,.04,Q(12)),m.c('#8a5a3a'),[0,y,0]);for(const x of[-.14,.14])P(g,G.cy(.015,.015,.48),m.c('#8a5a3a'),[x,.26,0]);P(g,G.co(.13,.22,Q(16)),m.c('#e8f8ff',{opacity:.35}),[0,.37,0],[PI,0,0]);P(g,G.co(.13,.22,Q(16)),m.c('#e8f8ff',{opacity:.35}),[0,.15,0]);P(g,G.co(.1,.1,Q(12)),m.c('#e8c070'),[0,.09,0])});
  F('fulgurit','wueste','natur',3,1400,'Blitzröhre','Lightning tube','Eine Röhre aus Glas, mitten im Sand gefunden.','A tube of glass, found right in the sand.','Wenn ein Blitz in Sand einschlägt, schmilzt der Sand zu Glas. So entstehen hohle Glasröhren, die Fulgurite heissen.','When lightning strikes sand, the sand melts into glass. That makes hollow glass tubes called fulgurites.',(g,m)=>{P(g,G.tu([[0,.02,0],[.06,.18,.02],[-.03,.34,-.02],[.04,.5,.01]],.05,.025),m.c('#c8b890',{gloss:.8}));for(const[y,x]of[[.15,.07],[.3,-.06]])P(g,G.co(.025,.1,5),m.c('#c8b890'),[x,y,0],[0,0,x>0?-1.2:1.2])});
  F('kamelglocke','wueste','kunst',2,700,'Kamelglocke','Camel bell','Eine Messingglocke. Sie klingt tief und warm.','A brass bell. It rings low and warm.','Kamele können tagelang ohne zu trinken laufen. In ihrem Höcker speichern sie aber kein Wasser, sondern Fett.','Camels can walk for days without drinking. But their hump does not store water, it stores fat.',(g,m)=>{P(g,G.co(.18,.3,Q(16)),m.c('#c89a40',{gloss:1.3}),[0,.17,0]);P(g,G.s(.05),m.c('#8a6a3a'),[0,.03,0]);P(g,G.to(.06,.015),m.c('#c89a40',{gloss:1.3}),[0,.36,0]);P(g,G.tu([[0,.4,0],[.1,.5,0],[.2,.45,0]],.015),m.c('#c83a3a'))});

  /* ================= Pilz ================= */
  F('sporenabdruck','pilz','kunst',2,600,'Sporenbild','Spore print','Ein Bild aus feinem Pilzstaub, wie ein Stern gemalt.','A picture made of fine mushroom dust, painted like a star.','Legt man einen Pilzhut über Nacht auf Papier, fallen die Sporen heraus und malen ein Muster. Das nennt man Sporenabdruck.','If you leave a mushroom cap on paper overnight, its spores fall out and draw a pattern. That is called a spore print.',(g,m)=>{P(g,G.bx(.5,.02,.4,.01),m.c('#fffdf4'),[0,.01,0]);for(let i=0;i<16;i++){const a=i/16*TAU;P(g,G.bx(.13,.005,.01),m.c('#6a4a5a'),[Math.cos(a)*.08,.025,Math.sin(a)*.08],[0,-a,0])}P(g,G.cy(.03,.03,.01,Q(10)),m.c('#6a4a5a'),[0,.03,0])});
  F('hexenringstein','pilz','natur',2,700,'Hexenring-Stein','Fairy ring stone','Ein runder Stein mit einem Ring aus kleinen Pilzen darauf.','A round stone with a ring of little mushrooms on top.','Pilze wachsen manchmal in einem Kreis auf der Wiese. Man nennt das Hexenring. Der Pilz wächst unter der Erde von der Mitte nach aussen.','Mushrooms sometimes grow in a circle on a meadow. This is called a fairy ring. The fungus grows underground from the middle outwards.',(g,m)=>{P(g,G.cy(.28,.3,.08,Q(18)),m.c('#8a8a7a'),[0,.04,0]);for(let i=0;i<8;i++){const a=i/8*TAU;P(g,G.cy(.012,.015,.06,Q(6)),m.c('#fff4e6'),[Math.cos(a)*.2,.11,Math.sin(a)*.2]);P(g,G.hs(.035),m.c('#e8a070'),[Math.cos(a)*.2,.14,Math.sin(a)*.2])}});
  F('leuchtpilzlaterne','pilz','natur',3,1300,'Leuchtpilz-Laterne','Glowing mushroom lantern','Ein Glas mit Pilzen, die im Dunkeln grün leuchten.','A jar of mushrooms that glow green in the dark.','Es gibt Pilze, die im Dunkeln grün leuchten. Rund hundert solche Arten sind bekannt.','There are mushrooms that glow green in the dark. Around a hundred such species are known.',(g,m)=>jar(g,m,.42,()=>{for(const[x,h]of[[-.06,.14],[.05,.2],[0,.1]]){P(g,G.cy(.012,.012,h,Q(6)),m.c('#e8fff0'),[x,h/2,0]);P(g,G.hs(.04),m.glow('#8aff8a',1.5),[x,h,0])}}));
  F('goldtrueffel','pilz','schatz',3,2000,'Goldene Trüffel','Golden truffle','Eine knubbelige Trüffel aus Gold. Sie duftet trotzdem nach Wald.','A knobbly truffle made of gold. It still smells like the forest.','Trüffel wachsen unter der Erde. Früher halfen Schweine beim Suchen, heute meist Hunde mit feiner Nase.','Truffles grow underground. Pigs used to help find them, today it is mostly dogs with a fine nose.',(g,m)=>{stand(g,m);P(g,G.ico(.15,1),m.c('#e8b830',{gloss:1.4}),[0,.2,0])});

  /* ================= Dschungel ================= */
  F('kakaobohne_gold','dschungel','schatz',3,1800,'Goldene Kakaobohne','Golden cocoa bean','Eine Kakaobohne aus Gold, so gross wie eine Faust.','A cocoa bean made of gold, as big as a fist.','Schokolade wird aus Kakaobohnen gemacht. Die Bohnen wachsen in grossen Früchten direkt am Stamm des Kakaobaums.','Chocolate is made from cocoa beans. The beans grow in big fruits right on the trunk of the cocoa tree.',(g,m)=>{stand(g,m);P(g,G.s(.16),m.c('#e8b830',{gloss:1.4}),[0,.2,0],[0,0,.3],[1,.6,.75])});
  F('riesenseerosenblatt','dschungel','natur',2,900,'Riesen-Seerosenblatt','Giant water lily leaf','Ein riesiges, rundes Blatt mit hochgebogenem Rand.','A huge round leaf with a turned-up edge.','Die Blätter der Riesenseerose können über zwei Meter breit werden. Sie tragen sogar ein kleines Gewicht, ohne unterzugehen.','The leaves of the giant water lily can grow more than two metres wide. They can even carry a small weight without sinking.',(g,m)=>{P(g,G.cy(.4,.4,.03,Q(24)),m.c('#5aa83a'),[0,.03,0]);P(g,G.to(.4,.03),m.c('#c83a5a'),[0,.06,0],[PI/2,0,0]);for(let i=0;i<8;i++)P(g,G.bx(.38,.005,.01),m.c('#4a8a2a'),[0,.05,0],[0,i*PI/8,0])});

  /* ================= Metro ================= */
  F('alte_fahrkarte','metro','alltag',2,600,'Alte Fahrkarte','Old ticket','Eine Fahrkarte aus Pappe mit einem Loch drin.','A cardboard ticket with a hole punched in it.','Die erste U-Bahn der Welt fuhr 1863 in London. Damals zogen noch Dampflokomotiven die Wagen.','The world\'s first underground railway opened in London in 1863. Back then, steam engines pulled the carriages.',(g,m)=>{P(g,G.bx(.4,.02,.22,.01),m.c('#f4e0b0'),[0,.06,0],[0,0,.1]);P(g,G.bx(.3,.005,.03),m.c('#8a3a3a'),[0,.075,-.05],[0,0,.1]);P(g,G.cy(.025,.025,.03,Q(8)),m.c('#3a3a44'),[.14,.06,.06]);stand(g,m,'#3a3a44')});
  F('jazzschallplatte','metro','musik',2,900,'Jazz-Schallplatte','Jazz record','Eine schwarze Platte mit einem goldenen Etikett.','A black record with a golden label.','Auf einer Schallplatte ist der Ton in einer einzigen langen Rille gespeichert. Eine Nadel fährt die Rille entlang und spürt jede kleine Welle.','On a record, the sound is stored in one single long groove. A needle runs along the groove and feels every tiny wave.',(g,m)=>{P(g,G.cy(.3,.3,.015,Q(32)),m.c('#1a1a24',{gloss:1.2}),[0,.2,0],[PI/2-.2,0,0]);P(g,G.cy(.1,.1,.018,Q(20)),m.c('#e8b04a'),[0,.2,0],[PI/2-.2,0,0]);P(g,G.bx(.5,.04,.2,.02),m.c('#6a4a3a'),[0,.02,-.02])});

  /* ================= Riesengarten ================= */
  F('riesensamen','riesengarten','natur',3,1400,'Riesen-Samenkorn','Giant seed','Ein Samen so gross wie ein Kopf. Was wohl daraus wächst?','A seed as big as a head. What might grow from it?','Der grösste Samen der Welt gehört der Seychellenpalme. Er kann über 15 Kilogramm wiegen.','The largest seed in the world belongs to the sea coconut palm. It can weigh more than 15 kilograms.',(g,m)=>{for(const s of[-1,1])P(g,G.s(.18),m.c('#6a4a2a',{gloss:.6}),[s*.1,.17,0],null,[.8,1,1])});
  F('alte_giesskanne','riesengarten','alltag',2,700,'Alte Giesskanne','Old watering can','Eine verbeulte Giesskanne. In ihr ist noch ein bisschen Regen.','A dented watering can. There is still a little rain inside.','Pflanzen trinken über ihre Wurzeln. Das Wasser wandert bis in die Blätter und verdunstet dort.','Plants drink through their roots. The water travels up into the leaves and evaporates there.',(g,m)=>{P(g,G.cy(.16,.18,.3,Q(16)),m.c('#5a9a8a',{gloss:.8}),[0,.15,0]);P(g,G.cy(.02,.035,.35,Q(8)),m.c('#5a9a8a'),[.25,.25,0],[0,0,-1]);P(g,G.cy(.05,.04,.04,Q(10)),m.c('#5a9a8a'),[.39,.36,0],[0,0,-1]);P(g,G.to(.12,.02,PI),m.c('#5a9a8a'),[-.05,.3,0],[0,0,.2])});
  F('sonnenblumenkern','riesengarten','schatz',2,1000,'Goldener Sonnenblumenkern','Golden sunflower seed','Ein Sonnenblumenkern aus Gold, gestreift wie ein echter.','A sunflower seed made of gold, striped like a real one.','Junge Sonnenblumen drehen ihre Knospe tagsüber mit der Sonne mit. Erwachsene Blüten schauen dann meist nach Osten.','Young sunflowers turn their buds with the Sun during the day. Grown-up flowers then mostly face east.',(g,m)=>{stand(g,m);P(g,G.s(.12),m.c('#e8b830',{gloss:1.4}),[0,.18,0],null,[.6,1.3,.35]);for(const x of[-.03,.03])P(g,G.bx(.01,.24,.005),m.c('#8a6a2a'),[x,.18,.045])});

  /* ================= Wolkenarchipel ================= */
  F('regenbogenprisma','wolkenarchipel','kunst',3,1300,'Regenbogen-Prisma','Rainbow prism','Ein Glaskeil. Hält man ihn ins Licht, malt er einen Regenbogen.','A glass wedge. Hold it in the light and it paints a rainbow.','Ein Glasprisma teilt weisses Licht in alle Regenbogenfarben auf. So hat Isaac Newton gezeigt, dass Sonnenlicht aus vielen Farben besteht.','A glass prism splits white light into all the colours of the rainbow. Isaac Newton used one to show that sunlight is made of many colours.',(g,m)=>{P(g,G.cy(.18,.18,.35,3),m.c('#e8f8ff',{opacity:.45,gloss:1.6}),[0,.18,0],[PI/2,0,0]);['#ff5a5a','#ffb03a','#ffe060','#6ad85a','#4ab8ff','#9a6aff'].forEach((c,i)=>P(g,G.bx(.4,.004,.025),m.glow(c,1.2),[.35,.006,(i-2.5)*.026],[0,.2,0]))});
  F('wolkenflasche','wolkenarchipel','natur',2,800,'Wolke in der Flasche','Cloud in a bottle','Eine kleine weisse Wolke schwebt in der Flasche.','A little white cloud floats inside the bottle.','Eine Wolke besteht aus winzigen Wassertröpfchen. Eine grosse Wolke kann so schwer sein wie hundert Elefanten.','A cloud is made of tiny water droplets. A big cloud can be as heavy as a hundred elephants.',(g,m)=>jar(g,m,.45,()=>{for(const[x,y,r]of[[0,.25,.08],[-.06,.23,.06],[.06,.22,.06]])P(g,G.s(r),m.c('#ffffff',{rim:.9}),[x,y,0])}));
  F('alter_drachen','wolkenarchipel','spielzeug',2,900,'Alter Drachen','Old kite','Ein Drachen aus Seide und Bambus, mit einem langen Schwanz.','A kite made of silk and bamboo, with a long tail.','Drachen zum Steigenlassen gibt es seit über 2000 Jahren. Sie wurden wahrscheinlich in China erfunden.','Kites have existed for more than 2000 years. They were probably invented in China.',(g,m)=>{const q=grp(g,[0,.35,0],[-.3,0,0]);P(q,G.cy(.3,.3,.01,4),m.c('#ff6f91'),[0,0,0],[PI/2,0,0],[1,1.4,1]);P(q,G.bx(.02,.84,.02),m.c('#d8c080'),[0,0,.01]);P(q,G.bx(.6,.02,.02),m.c('#d8c080'),[0,.1,.01]);for(let i=0;i<4;i++)P(g,G.bx(.06,.04,.01),m.c(['#ffd23f','#45a0ff'][i%2]),[0,.1-i*.02,.15+i*.08],[0,0,i])});

  /* ================= Bibliothek ================= */
  F('tintenfass','bibliothek','alltag',2,700,'Tintenfass mit Feder','Inkwell and quill','Ein Tintenfass. Die Feder steckt noch drin.','An inkwell. The quill is still standing in it.','Früher schrieb man mit Federn von Gänsen. Man tauchte sie immer wieder in Tinte.','People used to write with goose feathers. They dipped them in ink again and again.',(g,m)=>{P(g,G.cy(.12,.14,.14,Q(14)),m.c('#2a2a4a',{gloss:1.2}),[0,.07,0]);P(g,G.cy(.05,.05,.04,Q(10)),m.c('#c89a40'),[0,.16,0]);P(g,G.s(.1),m.c('#fffdf4'),[.08,.4,0],[0,0,-.4],[.3,1.8,.1]);P(g,G.cy(.006,.006,.3),m.c('#d8d0c0'),[.05,.28,0],[0,0,-.4])});
  F('papyrusrolle','bibliothek','kunst',3,1200,'Papyrus-Rolle','Papyrus scroll','Eine alte Rolle mit Zeichen, die wie kleine Bilder aussehen.','An old scroll with signs that look like little pictures.','Papyrus wurde im alten Ägypten aus einer Pflanze gemacht, die am Nil wuchs. Die Streifen wurden kreuzweise gelegt und gepresst.','Papyrus was made in ancient Egypt from a plant that grew along the Nile. The strips were laid crosswise and pressed together.',(g,m)=>{for(const x of[-.2,.2])P(g,G.cy(.06,.06,.3,Q(12)),m.c('#e8d8a8'),[x,.06,0],[PI/2,0,0]);P(g,G.bx(.4,.005,.28),m.c('#f0e0b0'),[0,.06,0]);for(let i=0;i<5;i++)P(g,G.bx(.05,.004,.05),m.c('#8a5a3a'),[-.12+i*.06,.065,(i%2)*.06-.03])});
  F('goldenes_lesezeichen','bibliothek','schatz',3,1700,'Goldenes Lesezeichen','Golden bookmark','Ein Lesezeichen aus Gold. Es steckt in einem Buch ohne Ende.','A bookmark made of gold. It is tucked in a book with no ending.','In der grössten Bibliothek der Welt gibt es über 170 Millionen Dinge, darunter Bücher, Landkarten und Noten.','The largest library in the world holds more than 170 million items, including books, maps and sheet music.',(g,m)=>{P(g,G.bx(.4,.12,.3,.02),m.c('#8E6BD1'),[0,.06,0]);P(g,G.bx(.38,.1,.28,.01),m.c('#fffdf4'),[.01,.06,0]);P(g,G.bx(.06,.02,.25,.005),m.c('#e8b830',{gloss:1.4}),[.05,.13,.12])});

  /* ================= Uhrwerk ================= */
  F('mini_sonnenuhr','uhrwerk','technik',2,800,'Mini-Sonnenuhr','Tiny sundial','Eine Sonnenuhr für den Tisch. Bei Wolken macht sie Pause.','A sundial for the table. When it is cloudy, it takes a break.','Eine Sonnenuhr zeigt die Zeit mit einem Schatten. Weil die Sonne über den Himmel wandert, wandert auch der Schatten.','A sundial shows the time with a shadow. Because the Sun moves across the sky, the shadow moves too.',(g,m)=>{P(g,G.cy(.28,.3,.06,Q(24)),m.c('#d8d0c0'),[0,.03,0]);for(let i=0;i<12;i++){const a=i/12*TAU;P(g,G.bx(.02,.01,.06),m.c('#3a3a44'),[Math.cos(a)*.22,.065,Math.sin(a)*.22],[0,-a,0])}P(g,G.cy(.18,.18,.01,3,1,false,0,PI/2),m.c('#c89a40',{gloss:1.2}),[0,.065,0],[0,0,PI/2])});
  F('messingpendel','uhrwerk','technik',2,900,'Messing-Pendel','Brass pendulum','Ein Pendel, das noch immer sanft hin und her schwingt.','A pendulum that still swings gently back and forth.','Ein Pendel braucht für jeden Schwung fast genau gleich lang, auch wenn es weniger weit ausschlägt. Darum hat man es in Uhren eingebaut.','A pendulum takes almost exactly the same time for each swing, even when it swings less far. That is why it was built into clocks.',(g,m)=>{P(g,G.bx(.5,.04,.2,.01),m.c('#6a4a3a'),[0,.02,0]);for(const x of[-.2,.2])P(g,G.cy(.015,.015,.55),m.c('#6a4a3a'),[x,.3,0]);P(g,G.cy(.015,.015,.4),m.c('#6a4a3a'),[0,.57,0],[0,0,PI/2]);P(g,G.cy(.006,.006,.35),m.c('#c89a40'),[.03,.4,0],[0,0,.15]);P(g,G.cy(.07,.07,.02,Q(16)),m.c('#c89a40',{gloss:1.4}),[.055,.22,0],[PI/2,0,0])});
  F('taschenuhr','uhrwerk','schatz',3,1900,'Goldene Taschenuhr','Golden pocket watch','Eine Taschenuhr an einer Kette. Sie tickt ganz leise.','A pocket watch on a chain. It ticks very quietly.','Früher trug man Uhren an einer Kette in der Westentasche. Armbanduhren wurden erst vor etwa hundert Jahren beliebt.','People used to carry watches on a chain in their waistcoat pocket. Wristwatches only became popular about a hundred years ago.',(g,m)=>{stand(g,m);P(g,G.cy(.16,.16,.05,Q(24)),m.c('#e8b830',{gloss:1.4}),[0,.22,0],[PI/2-.3,0,0]);P(g,G.cy(.13,.13,.055,Q(24)),m.c('#fff8e8'),[0,.22,.005],[PI/2-.3,0,0]);P(g,G.to(.04,.012),m.c('#e8b830',{gloss:1.4}),[0,.4,-.05])});

  /* ================= Klang ================= */
  F('stimmgabel','klang','musik',2,700,'Stimmgabel','Tuning fork','Schlägt man sie an, summt sie einen ganz reinen Ton.','Strike it and it hums one very pure note.','Eine Stimmgabel klingt immer genau gleich hoch. Musikerinnen und Musiker stimmen damit ihre Instrumente.','A tuning fork always sounds at exactly the same pitch. Musicians use it to tune their instruments.',(g,m)=>{stand(g,m);P(g,G.cy(.02,.02,.15),m.c('#c8c8d8',{gloss:1.4}),[0,.13,0]);for(const x of[-.05,.05])P(g,G.bx(.025,.3,.025),m.c('#c8c8d8',{gloss:1.4}),[x,.36,0]);P(g,G.bx(.125,.025,.025),m.c('#c8c8d8',{gloss:1.4}),[0,.21,0])});
  F('knochenfloete','klang','musik',3,1600,'Knochenflöte','Bone flute','Eine uralte Flöte mit fünf Löchern. Sie spielt noch!','An ancient flute with five holes. It still plays!','Die ältesten bekannten Musikinstrumente sind Flöten aus Vogelknochen. Sie sind über 40000 Jahre alt.','The oldest known musical instruments are flutes made from bird bones. They are more than 40,000 years old.',(g,m)=>{P(g,G.cy(.035,.04,.5,Q(10)),m.c('#f0e6d0'),[0,.05,0],[0,0,PI/2]);for(let i=0;i<5;i++)P(g,G.cy(.012,.012,.02,Q(6)),m.c('#5a4a3a'),[-.12+i*.06,.09,0])});
  F('muschelhorn','klang','musik',2,1000,'Muschelhorn','Conch horn','Bläst man hinein, tönt es wie eine Trompete.','Blow into it and it sounds like a trumpet.','Wenn man in eine grosse Meeresschnecke bläst, tönt sie wie eine Trompete. Auf vielen Inseln rief man so die Leute zusammen.','If you blow into a big sea snail shell, it sounds like a trumpet. On many islands, this was how people were called together.',(g,m)=>{P(g,G.co(.16,.45,Q(14)),m.c('#f4c8a8'),[0,.14,0],[0,0,PI/2]);for(let i=0;i<4;i++)P(g,G.to(.15-i*.03,.025),m.c('#e8a888'),[-.12+i*.08,.14,0],[0,PI/2,0]);P(g,G.s(.09),m.c('#ffd8e8'),[.22,.14,0],null,[.3,1,1])});

  try{if(typeof I18N!=='undefined'&&I18N.extend)I18N.extend('en',EN)}catch(e){}
})();
