/* =====================================================================
   CYBORG-LABOR · funde3.js · Fundstücke, zweiter Teil
   Die Themen-Planeten von der Neon-Arkade bis zur Honigwabe und die
   fünf kleinen Monde. Gleiches Muster wie funde2.js.
   ===================================================================== */
(()=>{
  const{REL,relMeta}=NH;const EN={};
  const F=(id,pl,kind,rar,price,de,en,tde,ten,fde,fen,b)=>{EN[de]=en;EN[tde]=ten;EN[fde]=fen;if(!RELICS.some(r=>r.id===id))REL(id,relMeta(de,pl,kind,rar,price,tde,fde),b)};
  const jar=(g,m,h,inner)=>{P(g,G.cy(.17,.17,h,Q(16)),m.c('#e8f8ff',{opacity:.35,gloss:1.4}),[0,h/2,0]);P(g,G.cy(.18,.18,.06,Q(16)),m.c('#8a5a3a'),[0,h+.03,0]);if(inner)inner()};
  const stand=(g,m,col)=>P(g,G.cy(.22,.25,.06,Q(16)),m.c(col||'#6a4a3a'),[0,.03,0]);
  const GOLD={gloss:1.4};

  /* ================= Neon-Arkade ================= */
  F('goldene_spielmarke','neonarkade','schatz',3,1600,'Goldene Spielmarke','Golden token','Eine Spielmarke aus Gold. Kein Automat nimmt sie an, so wertvoll ist sie.','A token made of gold. No machine will take it, it is far too precious.','Die ersten Spielautomaten mit Bildschirm gab es in den 1970er-Jahren. Davor spielte man Flipper.','The first arcade games with a screen appeared in the 1970s. Before that, people played pinball.',(g,m)=>{stand(g,m,'#3b3450');P(g,G.cy(.16,.16,.04,Q(24)),m.c('#e8b830',GOLD),[0,.24,0],[PI/2,0,0]);P(g,G.star(.08,.035,5,.02),m.c('#fff0a0',GOLD),[0,.24,.025])});
  F('pixelkristall','neonarkade','elektro',2,900,'Pixel-Kristall','Pixel crystal','Ein Kristall aus lauter kleinen Würfeln in Rot, Grün und Blau.','A crystal made of little cubes in red, green and blue.','Ein Bildschirm besteht aus vielen kleinen Punkten, den Pixeln. Jeder Pixel mischt seine Farbe aus Rot, Grün und Blau.','A screen is made of many tiny dots called pixels. Each pixel mixes its colour from red, green and blue.',(g,m)=>{const c=['#ff3a5a','#3aff7a','#3a8aff'];let i=0;for(let y=0;y<4;y++)for(let x=-(3-y);x<=3-y;x+=2){P(g,G.bx(.08,.08,.08),m.glow(c[i++%3],1.2),[x*.045,.04+y*.085,0])}});
  F('alter_joystick','neonarkade','elektro',2,800,'Alter Joystick','Old joystick','Ein roter Knauf auf einem schwarzen Kasten. Er wackelt in alle Richtungen.','A red knob on a black box. It wobbles in every direction.','Das Wort Joystick gab es schon bei Flugzeugen, lange bevor es Videospiele gab.','The word joystick was used for aeroplanes long before video games existed.',(g,m)=>{P(g,G.bx(.4,.1,.3,.03),m.c('#2a2a3a'),[0,.05,0]);P(g,G.cy(.02,.02,.22),m.c('#c8c8d8'),[0,.2,0],[.2,0,0]);P(g,G.s(.07),m.c('#ff3a5a',GOLD),[0,.32,.02]);P(g,G.cy(.03,.03,.02,Q(10)),m.c('#ffd23f'),[.13,.11,.06])});
  F('highscoreband','neonarkade','kunst',2,700,'Highscore-Band','High score ribbon','Ein Band mit drei Buchstaben und einer sehr langen Zahl.','A ribbon with three letters and a very long number.','Viele alte Spielautomaten speicherten nur drei Buchstaben für den Namen. Darum stehen in Highscore-Listen oft Kürzel.','Many old arcade machines only saved three letters for a name. That is why high score lists are often full of initials.',(g,m)=>{P(g,G.cy(.14,.14,.03,Q(20)),m.c('#45e0ff'),[0,.3,0],[PI/2,0,0]);P(g,G.star(.09,.04,5,.02),m.c('#ffd23f',GOLD),[0,.3,.02]);for(const s of[-1,1])P(g,G.bx(.07,.25,.01),m.c('#ff6fd8'),[s*.05,.12,0],[0,0,s*.2])});

  /* ================= Plüsch ================= */
  F('erster_teddy','pluesch','schatz',3,2200,'Der allererste Teddy','The very first teddy','Ein alter Teddy mit Knopfaugen. Ein Ohr wurde schon einmal geflickt.','An old teddy with button eyes. One ear has already been mended.','Der Teddybär ist nach einem amerikanischen Präsidenten benannt: Theodore Roosevelt, genannt Teddy.','The teddy bear is named after an American president: Theodore Roosevelt, known as Teddy.',(g,m)=>{const c=m.c('#b8804a',{rim:.8});P(g,G.s(.15),c,[0,.15,0],null,[1,1.1,.9]);P(g,G.s(.11),c,[0,.35,0]);for(const s of[-1,1]){P(g,G.s(.045),c,[s*.08,.44,0]);P(g,G.s(.05),c,[s*.13,.18,.04]);P(g,G.cy(.015,.015,.01,Q(8)),m.c('#2a2224'),[s*.04,.37,.1],[PI/2,0,0])}P(g,G.s(.04),m.c('#f4d8b0'),[0,.33,.1])});
  F('goldener_knopf','pluesch','schatz',2,1100,'Goldener Knopf','Golden button','Ein riesiger Knopf aus Gold mit vier Löchern.','A huge golden button with four holes.','Knöpfe gab es schon vor Tausenden von Jahren. Lange Zeit waren sie nur Schmuck und nicht zum Zuknöpfen da.','Buttons existed thousands of years ago. For a long time they were only decoration and not used for fastening.',(g,m)=>{stand(g,m,'#ff8fb8');P(g,G.cy(.17,.17,.05,Q(24)),m.c('#e8b830',GOLD),[0,.24,0],[PI/2,0,0]);for(const[x,y]of[[-.04,-.04],[.04,-.04],[-.04,.04],[.04,.04]])P(g,G.cy(.018,.018,.06,Q(8)),m.c('#8a6a2a'),[x,.24+y,0],[PI/2,0,0])});
  F('knochennadel','pluesch','alltag',3,1300,'Uralte Nähnadel','Ancient sewing needle','Eine Nadel aus Knochen, mit einem kleinen Öhr.','A needle made of bone, with a little eye.','Die ältesten Nähnadeln sind aus Knochen und über 40000 Jahre alt.','The oldest sewing needles are made of bone and are more than 40,000 years old.',(g,m)=>{P(g,G.bx(.4,.03,.25,.01),m.c('#ff8fb8'),[0,.015,0]);P(g,G.cy(.012,.004,.35,Q(8)),m.c('#f0e6d0'),[0,.05,0],[0,0,PI/2]);P(g,G.tu([[-.17,.05,0],[-.1,.08,.05],[0,.06,.08],[.1,.05,.04]],.006),m.c('#9ab8ff'))});
  F('regenbogenwolle','pluesch','alltag',2,700,'Regenbogen-Wollknäuel','Rainbow ball of wool','Ein Wollknäuel in allen Farben. Der Faden ist ganz weich.','A ball of wool in every colour. The yarn is very soft.','Wolle kommt meistens vom Schaf. Ein Schaf wird etwa einmal im Jahr geschoren, das tut ihm nicht weh.','Wool mostly comes from sheep. A sheep is sheared about once a year, and it does not hurt.',(g,m)=>{P(g,G.s(.17),m.c('#ff8fb8',{rim:.8}),[0,.17,0]);['#ffd23f','#7fd34a','#45a0ff','#c87aff'].forEach((c,i)=>P(g,G.to(.172,.015),m.c(c),[0,.17,0],[i*.8,i*.5,0]));P(g,G.tu([[.15,.08,0],[.3,.02,.05],[.4,.02,-.05]],.012),m.c('#ff8fb8'))});

  /* ================= Dino-Fabrik ================= */
  F('blech_dinoei','dinofabrik','spielzeug',2,1000,'Blech-Dinoei','Tin dino egg','Ein Ei aus Blech mit Nieten. Drinnen tickt es leise.','An egg made of tin with rivets. Something inside ticks quietly.','Dinosaurier legten Eier, genau wie Vögel heute. Vögel sind sogar die nächsten Verwandten der Dinosaurier.','Dinosaurs laid eggs, just like birds do today. Birds are even the closest living relatives of the dinosaurs.',(g,m)=>{P(g,G.s(.17),m.c('#a8b8c8',GOLD),[0,.22,0],null,[1,1.3,1]);for(let i=0;i<8;i++){const a=i/8*TAU;P(g,G.s(.015),m.c('#6a7a8a'),[Math.cos(a)*.17,.22,Math.sin(a)*.17])}P(g,G.to(.17,.012),m.c('#6a7a8a'),[0,.22,0],[PI/2,0,0])});
  F('aufziehschluessel','dinofabrik','spielzeug',2,800,'Aufzieh-Schlüssel','Wind-up key','Ein grosser Schlüssel zum Aufziehen. Für welches Spielzeug wohl?','A big wind-up key. Which toy could it be for?','Aufziehspielzeug läuft mit einer Feder. Beim Aufziehen spannt man die Feder, beim Loslassen treibt sie das Spielzeug an.','Wind-up toys run on a spring. Winding it up tightens the spring, and when you let go it drives the toy.',(g,m)=>{stand(g,m,'#5a6a7a');P(g,G.cy(.02,.02,.25),m.c('#c89a40',GOLD),[0,.18,0]);for(const s of[-1,1])P(g,G.to(.07,.02),m.c('#c89a40',GOLD),[s*.08,.36,0])});
  F('dino_bauplan','dinofabrik','kunst',2,900,'Dino-Bauplan','Dino blueprint','Ein blauer Plan mit weissen Linien. Er zeigt, wie man einen Dino baut.','A blue plan with white lines. It shows how to build a dino.','Forschende bauen Dino-Skelette oft aus vielen Fundstücken zusammen. Fehlende Knochen werden nachgebildet.','Researchers often put dinosaur skeletons together from many finds. Missing bones are modelled to fill the gaps.',(g,m)=>{P(g,G.bx(.5,.01,.36),m.c('#2a5aaa'),[0,.06,0]);for(const x of[-.25,.25])P(g,G.cy(.03,.03,.38,Q(10)),m.c('#2a5aaa'),[x,.06,0],[PI/2,0,0]);P(g,G.s(.06),m.c('#ffffff'),[-.05,.07,0],null,[1.6,.05,.8]);P(g,G.tu([[.03,.07,0],[.12,.07,-.06],[.18,.07,-.02]],.006),m.c('#ffffff'));P(g,G.tu([[-.13,.07,0],[-.18,.07,.05]],.006),m.c('#ffffff'))});
  F('goldenes_zahnrad','dinofabrik','schatz',3,1700,'Goldenes Zahnrad','Golden cog','Ein Zahnrad aus Gold. Es dreht sich ganz von selbst ein kleines Stück.','A cog made of gold. It turns a little bit all by itself.','Greifen zwei Zahnräder ineinander, drehen sie sich in entgegengesetzte Richtungen.','When two cogs mesh together, they turn in opposite directions.',(g,m)=>{stand(g,m,'#5a6a7a');const q=grp(g,[0,.26,0]);P(q,G.cy(.15,.15,.05,Q(20)),m.c('#e8b830',GOLD),[0,0,0],[PI/2,0,0]);for(let i=0;i<10;i++){const a=i/10*TAU;P(q,G.bx(.05,.05,.05),m.c('#e8b830',GOLD),[Math.cos(a)*.17,Math.sin(a)*.17,0],[0,0,a])}P(q,G.cy(.04,.04,.06,Q(10)),m.c('#8a6a2a'),[0,0,0],[PI/2,0,0])});

  /* ================= Kaufhaus ================= */
  F('mini_kasse','kaufhaus','technik',2,900,'Alte Registrierkasse','Old cash register','Eine kleine Kasse mit runden Tasten. Sie klingelt beim Öffnen.','A little till with round keys. It rings when it opens.','Die Registrierkasse wurde 1879 erfunden. Sie sollte helfen, das Geld im Laden richtig zu zählen.','The cash register was invented in 1879. It was meant to help count the money in a shop correctly.',(g,m)=>{P(g,G.bx(.4,.2,.3,.03),m.c('#c89a40',GOLD),[0,.1,0]);P(g,G.bx(.4,.06,.3,.02),m.c('#8a6a3a'),[0,.03,.02]);P(g,G.bx(.25,.12,.04,.02),m.c('#fff8e8'),[0,.27,-.08]);for(let i=0;i<6;i++)P(g,G.cy(.022,.022,.02,Q(8)),m.c('#fffdf4'),[-.1+(i%3)*.1,.21,.03+Math.floor(i/3)*.07])});
  F('rolltreppenstufe','kaufhaus','technik',2,700,'Rolltreppen-Stufe','Escalator step','Eine einzelne Metallstufe mit gelbem Rand.','A single metal step with a yellow edge.','Eine Rolltreppe ist ein Band aus Stufen, das im Kreis läuft. Oben verschwinden die Stufen nach unten und kommen unten wieder hervor.','An escalator is a loop of steps that runs round and round. At the top the steps fold away underneath and come back out at the bottom.',(g,m)=>{P(g,G.bx(.45,.12,.3,.01),m.c('#a8b0b8',GOLD),[0,.06,0]);for(let i=0;i<8;i++)P(g,G.bx(.43,.02,.012),m.c('#6a7078'),[0,.125,-.13+i*.037]);P(g,G.bx(.45,.02,.03),m.c('#ffd23f'),[0,.13,.14])});
  F('goldener_einkaufskorb','kaufhaus','schatz',3,1600,'Goldener Einkaufskorb','Golden shopping basket','Ein kleiner Einkaufskorb aus Gold. Drin liegt ein goldener Apfel.','A little golden shopping basket. Inside is a golden apple.','Der Einkaufswagen wurde 1937 in Amerika erfunden. Vorher trug man alles in Körben.','The shopping trolley was invented in America in 1937. Before that, people carried everything in baskets.',(g,m)=>{P(g,G.bx(.36,.18,.24,.02),m.c('#e8b830',GOLD),[0,.09,0]);P(g,G.bx(.32,.18,.2,.01),m.c('#8a6a2a'),[0,.1,0]);P(g,G.to(.15,.015,PI),m.c('#e8b830',GOLD),[0,.18,0]);P(g,G.s(.07),m.c('#e8b830',GOLD),[.05,.2,0])});
  F('altes_preisschild','kaufhaus','kunst',2,600,'Altes Preisschild','Old price tag','Ein Preisschild aus Pappe. Der Preis ist nicht mehr zu lesen.','A cardboard price tag. The price can no longer be read.','Früher hatten viele Dinge im Laden keinen festen Preis. Man handelte aus, wie viel man bezahlt.','In the past many things in shops had no fixed price. People haggled over how much to pay.',(g,m)=>{stand(g,m,'#ff6fa5');P(g,G.bx(.28,.18,.01,.01),m.c('#f4e0b0'),[0,.24,0],[0,0,.15]);P(g,G.to(.025,.008),m.c('#8a6a3a'),[-.11,.3,.01]);P(g,G.bx(.15,.02,.005),m.c('#8a3a3a'),[.02,.24,.01],[0,0,.15])});

  /* ================= Funkturm ================= */
  F('morsetaste','funkturm','elektro',2,900,'Morsetaste','Morse key','Drückt man darauf, piept es: kurz, kurz, lang.','Press it and it beeps: short, short, long.','Beim Morsen besteht jeder Buchstabe aus kurzen und langen Tönen. SOS heisst: drei kurz, drei lang, drei kurz.','In Morse code every letter is made of short and long sounds. SOS is three short, three long, three short.',(g,m)=>{P(g,G.bx(.4,.05,.24,.02),m.c('#6a4a3a'),[0,.025,0]);P(g,G.bx(.3,.025,.05,.01),m.c('#c89a40',GOLD),[0,.09,0],[0,0,.08]);P(g,G.cy(.04,.04,.04,Q(12)),m.c('#1a1a24'),[.13,.12,0]);P(g,G.cy(.02,.02,.06,Q(8)),m.c('#c89a40',GOLD),[-.05,.07,0])});
  F('radioroehre','funkturm','elektro',2,800,'Radioröhre','Radio valve','Eine Glasröhre mit Drähten drin. Sie glüht noch ein bisschen.','A glass tube with wires inside. It still glows a little.','Alte Radios hatten Glasröhren, die beim Einschalten warm wurden und leuchteten. Darum dauerte es eine Weile, bis sie spielten.','Old radios had glass valves that got warm and glowed when switched on. That is why they took a while before they played.',(g,m)=>{P(g,G.cy(.08,.08,.06,Q(14)),m.c('#3a3a44'),[0,.03,0]);P(g,G.ca(.07,.22),m.c('#e8f8ff',{opacity:.35,gloss:1.4}),[0,.24,0]);P(g,G.cy(.03,.03,.15,Q(10)),m.glow('#ff9a4a',1.3),[0,.22,0]);for(const x of[-.03,.03])P(g,G.cy(.004,.004,.15),m.c('#c8c8d8'),[x,.15,0])});
  F('kristallempfaenger','funkturm','elektro',3,1300,'Kristall-Empfänger','Crystal radio','Ein Radio mit einem glitzernden Stein. Es braucht keine Batterie.','A radio with a sparkling stone. It needs no battery.','Ein einfaches Kristallradio braucht keinen Strom aus der Steckdose. Es nutzt nur die Energie der Funkwellen.','A simple crystal radio needs no power from a socket. It only uses the energy of the radio waves.',(g,m)=>{P(g,G.bx(.45,.04,.3,.01),m.c('#8a5a3a'),[0,.02,0]);P(g,G.cy(.07,.07,.22,Q(14)),m.c('#c8702a'),[-.1,.08,0],[0,0,PI/2]);P(g,G.ico(.04,0),m.c('#9ab8c8',GOLD),[.12,.08,0]);P(g,G.tu([[.12,.12,0],[.1,.18,0],[.08,.15,0]],.005),m.c('#c89a40'))});
  F('goldene_antennenspitze','funkturm','schatz',3,1600,'Goldene Antennenspitze','Golden antenna tip','Die Spitze eines Funkturms, aus Gold. Sie fängt jedes Signal.','The tip of a radio tower, made of gold. It catches every signal.','Funkwellen sind unsichtbar und bewegen sich so schnell wie das Licht.','Radio waves are invisible and travel as fast as light.',(g,m)=>{stand(g,m,'#e8402a');P(g,G.co(.05,.4,Q(8)),m.c('#e8b830',GOLD),[0,.26,0]);P(g,G.s(.04),m.glow('#ff5a5a',1.5),[0,.48,0]);for(const y of[.15,.25])P(g,G.bx(.15,.015,.015),m.c('#e8b830',GOLD),[0,y,0])});

  /* ================= Magnetbahn ================= */
  F('hufeisenmagnet','magnetbahn','technik',2,700,'Hufeisen-Magnet','Horseshoe magnet','Ein roter Magnet. An ihm hängen noch drei Büroklammern.','A red magnet. Three paper clips are still stuck to it.','Jeder Magnet hat einen Nord- und einen Südpol. Gleiche Pole stossen sich ab, verschiedene ziehen sich an.','Every magnet has a north and a south pole. Like poles push each other away, unlike poles pull together.',(g,m)=>{P(g,G.to(.13,.05,PI),m.c('#ff4a5a',GOLD),[0,.3,0],[0,0,0]);for(const s of[-1,1]){P(g,G.cy(.05,.05,.15,Q(12)),m.c('#ff4a5a',GOLD),[s*.13,.22,0]);P(g,G.cy(.051,.051,.05,Q(12)),m.c('#e6ecf5',GOLD),[s*.13,.13,0])}for(let i=0;i<3;i++)P(g,G.to(.025,.005),m.c('#c8c8d8'),[-.13+i*.01,.08-i*.03,0],[0,PI/2,0],[1,1.6,1])});
  F('kompass','magnetbahn','technik',2,800,'Messing-Kompass','Brass compass','Ein Kompass. Die rote Nadel zeigt immer nach Norden.','A compass. The red needle always points north.','Eine Kompassnadel ist ein kleiner Magnet. Sie zeigt nach Norden, weil die Erde selbst wie ein riesiger Magnet ist.','A compass needle is a little magnet. It points north because the Earth itself works like a giant magnet.',(g,m)=>{P(g,G.cy(.18,.18,.06,Q(24)),m.c('#c89a40',GOLD),[0,.03,0]);P(g,G.cy(.15,.15,.065,Q(24)),m.c('#fff8e8'),[0,.035,0]);P(g,G.co(.025,.12,4),m.c('#e8402a'),[0,.07,-.06],[-PI/2,0,0]);P(g,G.co(.025,.12,4),m.c('#3a3a44'),[0,.07,.06],[PI/2,0,0]);P(g,G.cy(.16,.16,.005,Q(24)),m.c('#e8f8ff',{opacity:.35}),[0,.08,0])});
  F('magnetstein','magnetbahn','natur',2,900,'Magnetstein','Lodestone','Ein dunkler Stein. Kleine Eisenkrümel halten sich an ihm fest.','A dark stone. Little iron crumbs cling to it.','Magnetit ist ein Stein, der von selbst magnetisch sein kann. So haben Menschen den Magnetismus entdeckt.','Magnetite is a stone that can be magnetic all by itself. That is how people discovered magnetism.',(g,m)=>{P(g,G.ico(.17,1),m.c('#3a3a44'),[0,.15,0],null,[1.2,.9,1]);for(let i=0;i<14;i++){const a=i*2.4,b=(i%5)/5*1.4;P(g,G.co(.008,.04,4),m.c('#8a8a98'),[Math.cos(a)*Math.cos(b)*.21,.15+Math.sin(b)*.16,Math.sin(a)*Math.cos(b)*.18],[b,a,0])}});
  F('schwebewagen_modell','magnetbahn','spielzeug',3,1400,'Schwebewagen-Modell','Maglev model','Ein kleiner Zug, der eine Fingerbreite über der Schiene schwebt.','A little train that floats a finger\'s width above the track.','Magnetschwebebahnen berühren die Schiene nicht. Sie schweben ein kleines Stück darüber und sind darum sehr leise.','Maglev trains do not touch the track. They float a little above it, which makes them very quiet.',(g,m)=>{P(g,G.bx(.6,.04,.12,.01),m.c('#8a8a98'),[0,.02,0]);P(g,G.ca(.06,.4),m.c('#ffffff',GOLD),[0,.14,0],[0,0,PI/2],[1,1,1.3]);P(g,G.bx(.3,.03,.13,.01),m.c('#ff4a5a'),[0,.13,0]);for(let i=0;i<3;i++)P(g,G.bx(.07,.03,.01,.01),m.c('#2a3a6a'),[-.1+i*.1,.17,.078])});

  /* ================= Rechenzentrum ================= */
  F('lochkarte','rechenzentrum','elektro',2,700,'Lochkarte','Punched card','Eine Karte voller kleiner rechteckiger Löcher.','A card full of little rectangular holes.','Frühe Computer lasen ihre Befehle von Karten mit Löchern. Jedes Loch stand für eine Information.','Early computers read their instructions from cards with holes. Each hole stood for a piece of information.',(g,m)=>{stand(g,m,'#3b3450');P(g,G.bx(.4,.18,.01,.005),m.c('#f4e8c0'),[0,.2,0],[-.2,0,0]);for(let i=0;i<14;i++)P(g,G.bx(.015,.03,.012),m.c('#3b3450'),[-.17+i*.026,.2+((i*7)%5-2)*.025,.004],[-.2,0,0])});
  F('holzmaus','rechenzentrum','elektro',3,1500,'Holz-Computermaus','Wooden computer mouse','Ein Holzkästchen mit einem Knopf und einem Kabel als Schwanz.','A little wooden box with one button and a cable for a tail.','Die erste Computermaus war aus Holz. Sie wurde in den 1960er-Jahren gebaut.','The first computer mouse was made of wood. It was built in the 1960s.',(g,m)=>{P(g,G.bx(.22,.1,.3,.03),m.c('#b8885a'),[0,.05,0]);P(g,G.bx(.08,.02,.06,.01),m.c('#c83a3a'),[0,.11,-.08]);P(g,G.tu([[0,.05,-.15],[0,.03,-.3],[.1,.02,-.4]],.012),m.c('#3a3a44'))});
  F('ringkernspeicher','rechenzentrum','elektro',2,1000,'Ringkern-Speicher','Core memory','Ein Gitter aus Drähten mit winzigen Ringen an jeder Kreuzung.','A grid of wires with tiny rings at every crossing.','Alte Computer speicherten Daten in winzigen Eisenringen, die auf Drähte aufgefädelt waren.','Old computers stored data in tiny iron rings threaded onto wires.',(g,m)=>{stand(g,m,'#3b3450');const q=grp(g,[0,.25,0]);P(q,G.bx(.34,.34,.02,.01),m.c('#2a6a4a'),[0,0,-.02]);for(let i=0;i<5;i++)for(let k=0;k<5;k++)P(q,G.to(.015,.006),m.c('#3a3a44'),[-.12+i*.06,-.12+k*.06,0],[0,0,.8])});
  F('goldener_chip','rechenzentrum','schatz',3,1800,'Goldener Chip','Golden chip','Ein Computerchip mit goldenen Beinchen. Er glänzt wie ein Käfer.','A computer chip with golden legs. It shines like a beetle.','Ein Computerchip enthält Milliarden winziger Schalter. Sie sind so klein, dass man sie nur mit besonderen Mikroskopen sieht.','A computer chip contains billions of tiny switches. They are so small that you can only see them with special microscopes.',(g,m)=>{stand(g,m,'#3b3450');P(g,G.bx(.2,.04,.2,.01),m.c('#2a2a3a'),[0,.09,0]);for(let i=0;i<5;i++)for(const s of[-1,1]){P(g,G.bx(.02,.01,.05),m.c('#e8b830',GOLD),[-.08+i*.04,.075,s*.12]);P(g,G.bx(.05,.01,.02),m.c('#e8b830',GOLD),[s*.12,.075,-.08+i*.04])}P(g,G.bx(.08,.005,.08),m.c('#e8b830',GOLD),[0,.112,0])});

  /* ================= Tiefsee ================= */
  F('leuchtkoralle','tiefsee','natur',2,900,'Leuchtkoralle','Glowing coral','Eine Koralle, deren Spitzen blau leuchten.','A coral whose tips glow blue.','Viele Tiere in der Tiefsee leuchten selbst. Das hilft ihnen, im Dunkeln Futter zu finden oder einander zu treffen.','Many deep-sea animals make their own light. It helps them find food in the dark or find each other.',(g,m)=>{P(g,G.cy(.12,.15,.06,Q(12)),m.c('#8a8a7a'),[0,.03,0]);for(let i=0;i<5;i++){const a=i*1.26,x=Math.cos(a)*.08,z=Math.sin(a)*.08;P(g,G.tu([[0,.05,0],[x,.18,z],[x*1.8,.32,z*1.8]],.02,.012),m.c('#c87aff'));P(g,G.s(.025),m.glow('#7ab8ff',1.6),[x*1.8,.33,z*1.8])}});
  F('kupferhelm','tiefsee','kunst',3,1700,'Alter Taucherhelm','Old diving helmet','Ein Kupferhelm mit drei runden Fenstern.','A copper helmet with three round windows.','Früher trugen Taucher schwere Kupferhelme. Durch einen Schlauch wurde Luft von oben hinuntergepumpt.','Divers used to wear heavy copper helmets. Air was pumped down to them through a hose.',(g,m)=>{P(g,G.cy(.18,.2,.06,Q(18)),m.c('#a8703a',GOLD),[0,.03,0]);P(g,G.s(.2),m.c('#c8803a',GOLD),[0,.24,0]);for(const a of[0,1.3,-1.3]){P(g,G.cy(.07,.07,.02,Q(16)),m.c('#9ad8f8',{opacity:.6}),[Math.sin(a)*.19,.24,Math.cos(a)*.19],[PI/2,a,0],[1,1,1]);P(g,G.to(.07,.012),m.c('#c89a40',GOLD),[Math.sin(a)*.2,.24,Math.cos(a)*.2],[0,a,0])}});
  F('sanddollar','tiefsee','natur',2,700,'Sanddollar','Sand dollar','Eine flache, runde Scheibe mit einem Blumenmuster.','A flat round disc with a flower pattern.','Ein Sanddollar ist ein flacher Seeigel. Das Muster auf seinem Rücken sieht aus wie eine Blume.','A sand dollar is a flat sea urchin. The pattern on its back looks like a flower.',(g,m)=>{stand(g,m,'#2a5a9a');const q=grp(g,[0,.24,0],[1.1,0,0]);P(q,G.cy(.18,.18,.03,Q(24)),m.c('#f0e6d0'),[0,0,0]);for(let i=0;i<5;i++){const a=i/5*TAU;P(q,G.s(.035),m.c('#c8b898'),[Math.cos(a)*.08,.018,Math.sin(a)*.08],[0,-a,0],[1.4,.2,.45])}P(g,G.cy(.015,.015,.15),m.c('#8a8a98'),[0,.1,0])});
  F('flaschenpost','tiefsee','alltag',2,800,'Flaschenpost','Message in a bottle','Eine Flasche mit einem gerollten Brief. Er beginnt mit «Hallo, wer das findet».','A bottle with a rolled-up letter. It begins with "Hello, whoever finds this".','Manche Flaschenposten sind jahrzehntelang über das Meer getrieben, bevor jemand sie gefunden hat.','Some messages in bottles drifted across the sea for decades before anyone found them.',(g,m)=>{P(g,G.ca(.08,.25),m.c('#a8e8c8',{opacity:.5,gloss:1.4}),[0,.09,0],[0,0,PI/2]);P(g,G.cy(.035,.04,.08,Q(10)),m.c('#a8e8c8',{opacity:.5}),[.22,.09,0],[0,0,PI/2]);P(g,G.cy(.03,.03,.04,Q(8)),m.c('#a07a4a'),[.27,.09,0],[0,0,PI/2]);P(g,G.cy(.04,.04,.2,Q(10)),m.c('#f4e8c0'),[-.02,.09,0],[0,0,PI/2])});

  /* ================= Wetterwerk ================= */
  F('riesenhagelkorn','wetterwerk','natur',2,800,'Riesen-Hagelkorn','Giant hailstone','Ein Hagelkorn aus Glas, so gross wie ein Tennisball. Man sieht die Schichten.','A glass hailstone as big as a tennis ball. You can see the layers.','Hagelkörner wachsen in Gewitterwolken. Sie werden immer wieder hochgewirbelt und bekommen jedes Mal eine neue Eisschicht.','Hailstones grow inside thunderclouds. They are tossed up again and again and get a new layer of ice each time.',(g,m)=>{stand(g,m,'#2fb5d9');for(let i=0;i<3;i++)P(g,G.s(.14-i*.04),m.c(['#e8f8ff','#c8e8ff','#ffffff'][i],{opacity:.45+i*.2,gloss:1.4}),[0,.22,0])});
  F('regenmesser','wetterwerk','technik',2,700,'Regenmesser','Rain gauge','Ein Glas mit Strichen. Es ist bis zur Mitte voll.','A glass with lines on it. It is filled halfway.','Mit einem Regenmesser misst man, wie viel Regen fällt. Ein Millimeter Regen heisst: ein Liter Wasser auf einem Quadratmeter.','A rain gauge measures how much rain falls. One millimetre of rain means one litre of water on one square metre.',(g,m)=>{P(g,G.cy(.08,.08,.45,Q(14)),m.c('#e8f8ff',{opacity:.35,gloss:1.4}),[0,.23,0]);P(g,G.cy(.075,.075,.2,Q(14)),m.c('#4ab8ff',{opacity:.7}),[0,.11,0]);P(g,G.co(.14,.1,Q(14),1,true),m.c('#c8c8d8'),[0,.48,0],[PI,0,0]);for(let i=0;i<5;i++)P(g,G.bx(.04,.006,.005),m.c('#3a3a44'),[0,.08+i*.08,.08])});
  F('wetterhaeuschen','wetterwerk','kunst',3,1300,'Wetterhäuschen','Weather house','Ein Häuschen mit zwei Türen. Bei Sonne kommt die eine Figur heraus, bei Regen die andere.','A little house with two doors. One figure comes out when it is sunny, the other when it rains.','Ein Wetterhäuschen zeigt die Luftfeuchtigkeit an. Ein Faden darin wird bei feuchter Luft länger und dreht die Figuren.','A weather house shows how damp the air is. A thread inside gets longer in damp air and turns the figures.',(g,m)=>{P(g,G.bx(.4,.3,.2,.02),m.c('#f4e0b0'),[0,.15,0]);P(g,G.co(.32,.2,4),m.c('#c86a3a'),[0,.4,0],[0,PI/4,0]);for(const s of[-1,1]){P(g,G.bx(.1,.16,.01),m.c('#3a2a24'),[s*.1,.12,.1]);P(g,G.ca(.03,.06),m.c(s<0?'#ffd23f':'#45a0ff'),[s*.1,.12,.12])}});
  F('leidener_flasche','wetterwerk','elektro',3,1400,'Leidener Flasche','Leyden jar','Ein Glas mit Metall innen und aussen. Oben ragt ein Stab mit Kugel heraus.','A jar with metal inside and out. A rod with a ball sticks out of the top.','In einer Leidener Flasche konnte man vor fast 300 Jahren zum ersten Mal Elektrizität sammeln und aufheben.','Almost 300 years ago, the Leyden jar let people collect and store electricity for the first time.',(g,m)=>{P(g,G.cy(.14,.14,.32,Q(16)),m.c('#e8f8ff',{opacity:.35,gloss:1.4}),[0,.16,0]);P(g,G.cy(.141,.141,.16,Q(16)),m.c('#c8c8d8',GOLD),[0,.09,0]);P(g,G.cy(.15,.15,.03,Q(16)),m.c('#6a4a3a'),[0,.33,0]);P(g,G.cy(.012,.012,.2),m.c('#c89a40'),[0,.43,0]);P(g,G.s(.04),m.c('#c89a40',GOLD),[0,.54,0])});

  /* ================= Origami ================= */
  F('kranichkette_gold','origami','schatz',3,1700,'Tausend Kraniche','A thousand cranes','Eine lange Kette aus winzigen Papierkranichen in allen Farben.','A long string of tiny paper cranes in every colour.','In Japan faltet man manchmal tausend Papierkraniche für einen Herzenswunsch, zum Beispiel für schnelle Genesung.','In Japan, people sometimes fold a thousand paper cranes for a heartfelt wish, such as getting well soon.',(g,m)=>{stand(g,m,'#8E6BD1');P(g,G.cy(.01,.01,.5),m.c('#8a5a3a'),[0,.3,0]);for(let i=0;i<8;i++){const c=['#ff6fa5','#45a0ff','#ffd23f','#7fd34a'][i%4];P(g,G.co(.035,.08,4),m.c(c),[0,.12+i*.05,0],[0,i,PI/2])}});
  F('papierfrosch','origami','spielzeug',2,500,'Spring-Papierfrosch','Jumping paper frog','Ein grüner Papierfrosch. Drückt man hinten, hüpft er davon.','A green paper frog. Press its back and it hops away.','Ein gefalteter Papierfrosch kann wirklich springen, wenn man hinten auf ihn drückt und schnell loslässt.','A folded paper frog really can jump if you press on its back and let go quickly.',(g,m)=>{P(g,G.co(.16,.25,4),m.c('#7fd34a'),[0,.08,0],[-PI/2+.3,PI/4,0],[1,1,.45]);for(const s of[-1,1])P(g,G.co(.04,.12,3),m.c('#5aa83a'),[s*.1,.04,-.1],[-PI/2,0,s*.6])});
  F('schoepfsieb','origami','alltag',2,800,'Papier-Schöpfsieb','Papermaking screen','Ein Holzrahmen mit einem feinen Sieb. Darauf liegt ein frisches Blatt.','A wooden frame with a fine mesh. A fresh sheet of paper lies on it.','Papier wird aus Pflanzenfasern gemacht. Die Fasern werden mit Wasser vermischt und mit einem Sieb geschöpft.','Paper is made from plant fibres. The fibres are mixed with water and scooped up with a screen.',(g,m)=>{for(const[x,z,w,d]of[[0,-.15,.5,.04],[0,.15,.5,.04],[-.23,0,.04,.34],[.23,0,.04,.34]])P(g,G.bx(w,.05,d,.01),m.c('#a07a4a'),[x,.03,z]);P(g,G.bx(.42,.01,.26),m.c('#fffdf4'),[0,.05,0])});

  /* ================= Nachtmarkt ================= */
  F('sternkarte','nachtmarkt','kunst',2,900,'Sternkarte','Star chart','Eine dunkelblaue Karte mit goldenen Sternbildern.','A dark blue chart with golden constellations.','Die Sterne am Himmel sind in Sternbilder eingeteilt. Es gibt 88 offizielle Sternbilder.','The stars in the sky are grouped into constellations. There are 88 official constellations.',(g,m)=>{P(g,G.cy(.06,.06,.5,Q(12)),m.c('#3a3a8a'),[0,.06,-.14],[0,0,PI/2]);P(g,G.bx(.5,.005,.3),m.c('#2a2a6a'),[0,.03,.02]);for(let i=0;i<9;i++)P(g,G.s(.012),m.glow('#ffe86a',1.5),[-.2+((i*37)%40)/100,.04,-.1+((i*53)%25)/100])});
  F('mondstein','nachtmarkt','natur',2,1000,'Mondstein','Moonstone','Ein milchiger Stein, der bläulich schimmert, wenn man ihn dreht.','A milky stone that shimmers blue when you turn it.','Mondstein schimmert bläulich, weil das Licht an vielen dünnen Schichten im Stein gestreut wird.','Moonstone shimmers blue because light is scattered by many thin layers inside the stone.',(g,m)=>{stand(g,m,'#2a2a5a');P(g,G.s(.13),m.c('#e8f0ff',{opacity:.85,gloss:1.6,rim:1.2,rimColor:'#9ab8ff'}),[0,.2,0],null,[1.2,.8,1])});
  F('kerzenlaterne','nachtmarkt','alltag',2,700,'Kerzen-Laterne','Candle lantern','Eine Laterne mit einer Kerze, die nie ausgeht.','A lantern with a candle that never goes out.','Kerzen gibt es seit über 2000 Jahren. Früher machte man sie aus Bienenwachs oder Tierfett.','Candles have existed for more than 2000 years. They used to be made from beeswax or animal fat.',(g,m)=>{P(g,G.bx(.22,.04,.22,.01),m.c('#2a2224'),[0,.02,0]);P(g,G.bx(.2,.3,.2,.01),m.c('#ffe8b0',{opacity:.4}),[0,.19,0]);P(g,G.co(.16,.1,4),m.c('#2a2224'),[0,.39,0],[0,PI/4,0]);P(g,G.cy(.035,.035,.12,Q(10)),m.c('#fffdf4'),[0,.1,0]);P(g,G.s(.025),m.glow('#ffb84a',1.8),[0,.18,0],null,[1,1.5,1])});
  F('meteorit','nachtmarkt','schatz',3,2100,'Kleiner Meteorit','Small meteorite','Ein schwerer, dunkler Stein mit glänzenden Flecken. Er kam vom Himmel.','A heavy dark stone with shiny spots. It fell from the sky.','Meteoriten sind Steine aus dem Weltall, die auf die Erde gefallen sind. Viele sind so alt wie unser Sonnensystem.','Meteorites are stones from space that fell to Earth. Many are as old as our solar system.',(g,m)=>{stand(g,m,'#2a2a5a');P(g,G.ico(.14,1),m.c('#4a4048'),[0,.2,0],null,[1.2,1,.9]);for(let i=0;i<5;i++)P(g,G.s(.02),m.c('#c8c8d8',GOLD),[Math.cos(i*1.3)*.15,.2+Math.sin(i*2)*.08,Math.sin(i*1.3)*.12])});

  /* ================= Bauklotz ================= */
  F('erster_bauklotz','bauklotz','schatz',3,1600,'Der erste Baustein','The first building block','Ein abgegriffener Holzwürfel mit einem goldenen Rand.','A well-worn wooden cube with a golden edge.','Vor fast 200 Jahren erfand der Lehrer Friedrich Fröbel Spielbausteine für Kinder. Er hat auch das Wort Kindergarten erfunden.','Almost 200 years ago, the teacher Friedrich Fröbel invented building blocks for children. He also invented the word kindergarten.',(g,m)=>{stand(g,m);P(g,G.bx(.22,.22,.22,.03),m.c('#d8b080'),[0,.17,0],[0,.4,0]);P(g,G.bx(.23,.02,.23),m.c('#e8b830',GOLD),[0,.28,0],[0,.4,0])});
  F('wackelturm','bauklotz','kunst',2,800,'Wackel-Turm','Wobbly tower','Ein Turm aus Klötzchen. Er wackelt, aber er fällt nie um.','A tower of blocks. It wobbles but never falls down.','Ein Turm steht stabiler, wenn unten die schweren und breiten Teile liegen.','A tower stands more steadily when the heavy, wide pieces are at the bottom.',(g,m)=>{const c=['#ff5a5a','#45a0ff','#ffd23f','#7fd34a','#c87aff'];for(let i=0;i<5;i++){const w=.3-i*.04;P(g,G.bx(w,.1,w,.02),m.c(c[i]),[(i%2)*.02-.01,.05+i*.1,0],[0,i*.3,0])}});
  F('holzkreisel','bauklotz','spielzeug',2,600,'Holzkreisel','Wooden spinning top','Ein bunter Kreisel. Er dreht sich so lange, bis du blinzelst.','A colourful spinning top. It spins until you blink.','Ein Kreisel fällt nicht um, solange er sich schnell genug dreht.','A spinning top does not fall over as long as it spins fast enough.',(g,m)=>{P(g,G.co(.17,.2,Q(16)),m.c('#ff5a5a'),[0,.12,0],[PI,0,0]);P(g,G.cy(.17,.17,.06,Q(16)),m.c('#ffd23f'),[0,.25,0]);P(g,G.cy(.02,.02,.12),m.c('#8a5a3a'),[0,.33,0])});
  F('glasmurmel','bauklotz','spielzeug',2,500,'Riesen-Glasmurmel','Giant marble','Eine Murmel mit einer bunten Spirale in der Mitte.','A marble with a colourful swirl in the middle.','Murmeln gehören zu den ältesten Spielzeugen der Welt. Man hat sie sogar in alten Gräbern in Ägypten gefunden.','Marbles are among the oldest toys in the world. They have even been found in ancient tombs in Egypt.',(g,m)=>{stand(g,m);P(g,G.s(.15),m.c('#e8f8ff',{opacity:.4,gloss:1.6}),[0,.21,0]);P(g,G.to(.06,.02,PI*1.6),m.c('#ff5a5a'),[0,.21,0],[.6,0,0]);P(g,G.to(.06,.02,PI*1.6),m.c('#45a0ff'),[0,.21,0],[-.6,1,0])});

  /* ================= Bildschirmschoner ================= */
  F('wandernder_punkt','schoner','elektro',2,700,'Wandernder Leuchtpunkt','Wandering dot of light','Ein Lichtpunkt in einem Kästchen. Er läuft immer im Zickzack.','A dot of light in a little box. It always moves in a zigzag.','Bildschirmschoner wurden erfunden, weil alte Bildschirme ein Bild einbrennen konnten, wenn es zu lange stillstand.','Screensavers were invented because old screens could get an image burned in if it stayed still for too long.',(g,m)=>{P(g,G.bx(.36,.28,.2,.04),m.c('#e8e0d0'),[0,.14,0]);P(g,G.bx(.28,.2,.01,.01),m.c('#0a0a2a'),[0,.15,.1]);P(g,G.s(.02),m.glow('#7affff',2),[.05,.18,.11]);P(g,G.bx(.15,.004,.004),m.glow('#7affff',1.2),[-.02,.14,.11],[0,0,.6])});
  F('diskette','schoner','elektro',2,600,'Diskette','Floppy disk','Ein flaches Quadrat mit Metallschieber. Darauf steht: «Wichtig!».','A flat square with a metal shutter. It says "Important!".','Auf eine Diskette passten früher nur etwa 1,4 Megabyte. Das reicht heute nicht einmal für ein einziges Handyfoto.','A floppy disk could only hold about 1.4 megabytes. Today that is not even enough for a single phone photo.',(g,m)=>{stand(g,m,'#3b3450');P(g,G.bx(.25,.25,.015,.01),m.c('#3a5aaa'),[0,.22,0],[-.15,0,0]);P(g,G.bx(.12,.07,.017),m.c('#c8c8d8',GOLD),[.02,.31,-.01],[-.15,0,0]);P(g,G.bx(.18,.09,.017),m.c('#fffdf4'),[0,.16,.01],[-.15,0,0])});
  F('kugelmaus','schoner','elektro',2,700,'Kugelmaus','Ball mouse','Eine graue Maus. Unten rollt eine Gummikugel.','A grey mouse. A rubber ball rolls underneath.','Ältere Computermäuse hatten unten eine Gummikugel. Wenn sie rollte, bewegte sich der Zeiger auf dem Bildschirm.','Older computer mice had a rubber ball underneath. When it rolled, the pointer moved on the screen.',(g,m)=>{P(g,G.s(.14),m.c('#d8d8e0'),[0,.07,0],null,[.8,.55,1.2]);P(g,G.bx(.005,.02,.12),m.c('#8a8a98'),[0,.14,-.08]);P(g,G.s(.04),m.c('#3a3a44'),[0,.02,.02]);P(g,G.tu([[0,.06,-.16],[0,.03,-.3],[.08,.02,-.4]],.01),m.c('#d8d8e0'))});
  F('goldener_cursor','schoner','schatz',3,1500,'Goldener Mauszeiger','Golden cursor','Ein Pfeil aus Gold. Er zeigt immer auf das Wichtigste.','An arrow made of gold. It always points at what matters most.','Das Wort Cursor kommt aus dem Lateinischen und heisst Läufer.','The word cursor comes from Latin and means runner.',(g,m)=>{stand(g,m,'#1a1a3a');const sh=new THREE.Shape();sh.moveTo(0,.2);sh.lineTo(-.1,-.04);sh.lineTo(-.03,-.02);sh.lineTo(-.05,-.14);sh.lineTo(.02,-.12);sh.lineTo(.03,-.02);sh.lineTo(.1,-.04);sh.lineTo(0,.2);P(g,new THREE.ExtrudeGeometry(sh,{depth:.04,bevelEnabled:false}),m.c('#e8b830',GOLD),[0,.27,-.02],[0,0,.4])});

  /* ================= Honigwabe ================= */
  F('weiselzelle','honigwabe','natur',2,900,'Königinnen-Zelle','Queen cell','Eine lange Wachszelle, in der eine Bienenkönigin heranwächst.','A long wax cell where a queen bee grows up.','Eine Bienenkönigin legt im Sommer bis zu 2000 Eier an einem einzigen Tag.','In summer a queen bee can lay up to 2000 eggs in a single day.',(g,m)=>{P(g,G.bx(.4,.08,.25,.02),m.c('#e8a030'),[0,.04,0]);P(g,G.ca(.06,.16),m.c('#e8c070'),[0,.2,0],[0,0,0],[1,1,1]);for(let i=0;i<4;i++)P(g,G.to(.06,.008),m.c('#c89a40'),[0,.14+i*.04,0],[PI/2,0,0])});
  F('pollenhoeschen','honigwabe','natur',2,600,'Pollenhöschen','Pollen baskets','Zwei kleine gelbe Kügelchen aus Blütenstaub.','Two little yellow balls of pollen.','Bienen sammeln Blütenstaub in kleinen Körbchen an ihren Hinterbeinen. Man nennt das Pollenhöschen.','Bees collect pollen in little baskets on their back legs. These are called pollen baskets.',(g,m)=>{stand(g,m,'#3b3450');for(const s of[-1,1])P(g,G.s(.08),m.c(s<0?'#ffd23f':'#ffb030'),[s*.08,.14,0],null,[1,1.2,1])});
  F('bienentanzkarte','honigwabe','kunst',2,800,'Bienentanz-Karte','Bee dance map','Eine Karte mit Pfeilen in Form einer Acht.','A map with arrows in the shape of a figure eight.','Bienen zeigen einander mit einem Tanz, wo Blumen sind. Die Richtung des Tanzes zeigt die Richtung zur Futterstelle.','Bees show each other where flowers are with a dance. The direction of the dance points the way to the food.',(g,m)=>{stand(g,m);P(g,G.bx(.36,.26,.01,.01),m.c('#fff4d0'),[0,.25,0],[-.15,0,0]);for(const s of[-1,1])P(g,G.to(.06,.008),m.c('#c86a3a'),[s*.06,.25,.008],[-.15,0,0]);P(g,G.bx(.01,.12,.005),m.c('#c86a3a'),[0,.25,.01],[-.15,0,0])});
  F('honigloeffel','honigwabe','alltag',2,600,'Honiglöffel','Honey dipper','Ein Holzstab mit Rillen. Honig tropft langsam herunter.','A wooden stick with grooves. Honey drips slowly off it.','Honig verdirbt fast nie. Forschende haben in alten Gräbern Honig gefunden, der Tausende Jahre alt war.','Honey almost never goes bad. Researchers have found honey thousands of years old in ancient tombs.',(g,m)=>{P(g,G.cy(.14,.12,.18,Q(16)),m.c('#ffb030',{opacity:.8,gloss:1.4}),[0,.09,0]);P(g,G.cy(.012,.012,.4),m.c('#b8885a'),[.06,.3,0],[0,0,-.3]);for(let i=0;i<3;i++)P(g,G.to(.035,.012),m.c('#b8885a'),[.02+i*.015,.18+i*.035,0],[PI/2,0,-.3])});

  /* ================= Monde ================= */
  F('goldene_eichel','keim','schatz',2,1200,'Goldene Eichel','Golden acorn','Eine Eichel aus Gold. Sie ist noch keimfähig, sagt man.','An acorn made of gold. People say it could still sprout.','Aus einer kleinen Eichel kann eine Eiche wachsen, die viele hundert Jahre alt wird.','A little acorn can grow into an oak tree that lives for many hundreds of years.',(g,m)=>{stand(g,m);P(g,G.s(.1),m.c('#e8b830',GOLD),[0,.2,0],null,[1,1.3,1]);P(g,G.hs(.105),m.c('#8a6a2a'),[0,.27,0],null,[1,.6,1]);P(g,G.cy(.012,.012,.06),m.c('#8a6a2a'),[0,.34,0])});
  F('samentresorschluessel','keim','alltag',2,900,'Tresor-Schlüssel','Vault key','Ein schwerer Schlüssel mit einem Samenkorn als Griff.','A heavy key with a seed for a handle.','Auf der Insel Spitzbergen gibt es einen Samen-Tresor im kalten Berg. Dort lagern Samenproben von über einer Million Pflanzen.','On the island of Svalbard there is a seed vault deep in a cold mountain. It stores seed samples from more than a million plants.',(g,m)=>{P(g,G.cy(.02,.02,.4),m.c('#a8b0b8',GOLD),[0,.04,0],[0,0,PI/2]);P(g,G.s(.07),m.c('#c8a060'),[-.22,.04,0],null,[1,.5,1.3]);for(const x of[.12,.17])P(g,G.bx(.03,.02,.07),m.c('#a8b0b8',GOLD),[x,.04,.04])});
  F('musikkassette','kassette','elektro',2,700,'Musikkassette','Music cassette','Eine Kassette mit einer handgeschriebenen Liste der Lieder.','A cassette with a handwritten list of songs.','Auf einer Musikkassette ist der Ton auf einem dünnen Magnetband gespeichert.','On a music cassette, the sound is stored on a thin magnetic tape.',(g,m)=>{stand(g,m,'#3b3450');P(g,G.bx(.3,.19,.03,.01),m.c('#2a2a3a'),[0,.2,0],[-.15,0,0]);P(g,G.bx(.24,.07,.032),m.c('#fffdf4'),[0,.24,.002],[-.15,0,0]);for(const x of[-.06,.06])P(g,G.cy(.025,.025,.035,Q(10)),m.c('#8a6a4a'),[x,.17,.005],[PI/2-.15,0,0])});
  F('alter_kopfhoerer','kassette','elektro',2,800,'Alter Kopfhörer','Old headphones','Ein Kopfhörer mit runden Polstern aus Schaumstoff.','Headphones with round foam pads.','Die ersten Kopfhörer wurden vor über 100 Jahren gebaut, zum Beispiel für Leute, die Telefongespräche verbanden.','The first headphones were built more than 100 years ago, for example for people who connected telephone calls.',(g,m)=>{P(g,G.to(.18,.02,PI),m.c('#c8c8d8'),[0,.12,0]);for(const s of[-1,1]){P(g,G.cy(.08,.08,.06,Q(14)),m.c('#3a3a44'),[s*.18,.1,0],[0,0,PI/2]);P(g,G.cy(.075,.075,.03,Q(14)),m.c('#ff9a45'),[s*.14,.1,0],[0,0,PI/2])}});
  F('gluehwurmglas','gluehwurm','natur',2,700,'Glühwürmchen-Glas','Firefly jar','Ein Glas mit kleinen grünen Lichtern. Morgens lässt man sie frei.','A jar of little green lights. In the morning you let them go.','Glühwürmchen sind eigentlich Käfer. Sie leuchten, um einander im Dunkeln zu finden.','Fireflies are actually beetles. They glow so they can find each other in the dark.',(g,m)=>jar(g,m,.38,()=>{for(let i=0;i<5;i++)P(g,G.s(.022),m.glow('#d8ff6a',1.8),[Math.sin(i*1.7)*.08,.08+i*.06,Math.cos(i*1.7)*.08])}));
  F('mottenfluegel','gluehwurm','natur',2,800,'Nachtfalter-Flügel','Moth wing','Ein weicher, silbriger Flügel mit einem Auge darauf.','A soft silvery wing with an eye pattern on it.','Nachtfalter fliegen nachts. Mit ihren feinen Fühlern finden sie den Duft von Blüten.','Moths fly at night. With their fine antennae they find the scent of flowers.',(g,m)=>{stand(g,m,'#2a2a5a');P(g,G.s(.16),m.c('#c8c0d8',{rim:.6}),[0,.22,0],[0,0,.3],[1,.7,.06]);P(g,G.cy(.04,.04,.015,Q(14)),m.c('#6a4a8a'),[.03,.23,.012],[PI/2,0,0]);P(g,G.cy(.02,.02,.017,Q(10)),m.c('#ffd23f'),[.03,.23,.014],[PI/2,0,0])});
  F('drachenschwanz','drachen','spielzeug',2,600,'Drachenschwanz','Kite tail','Ein langer Schwanz aus bunten Schleifen.','A long tail made of colourful bows.','Der Schwanz eines Drachens hält ihn ruhig in der Luft, damit er sich nicht wild dreht.','A kite\'s tail keeps it steady in the air so that it does not spin wildly.',(g,m)=>{P(g,G.tu([[-.25,.03,0],[-.1,.06,.08],[.05,.03,-.04],[.25,.05,.05]],.006),m.c('#8a5a3a'));for(let i=0;i<5;i++){const x=-.22+i*.11;for(const s of[-1,1])P(g,G.co(.03,.07,3),m.c(['#ff6fa5','#45a0ff','#ffd23f','#7fd34a','#c87aff'][i]),[x+s*.03,.05,0],[0,0,s*PI/2])}});
  F('windraedchen','drachen','spielzeug',2,500,'Windrädchen','Pinwheel','Ein Windrädchen aus Papier. Schon ein Hauch bringt es zum Drehen.','A paper pinwheel. Even a breath makes it spin.','Wind entsteht, weil die Sonne die Luft an manchen Stellen stärker erwärmt als an anderen.','Wind happens because the Sun warms the air more in some places than in others.',(g,m)=>{stand(g,m);P(g,G.cy(.012,.012,.4),m.c('#f4f0e8'),[0,.25,0]);for(let i=0;i<4;i++)P(g,G.co(.08,.16,3),m.c(['#ff6fa5','#45a0ff','#ffd23f','#7fd34a'][i]),[Math.cos(i*PI/2)*.07,.45+Math.sin(i*PI/2)*.07,.02],[0,0,i*PI/2])});
  F('pixelherz','pixelmond','kunst',2,700,'Pixel-Herz','Pixel heart','Ein Herz aus roten Klötzchen. Es pocht ganz leise.','A heart made of red blocks. It beats very softly.','Frühe Videospiele hatten nur wenige Farben. Figuren wurden aus groben Klötzchen gezeichnet, den Pixeln.','Early video games had only a few colours. Characters were drawn from chunky blocks called pixels.',(g,m)=>{const H=['.XX.XX.','XXXXXXX','XXXXXXX','.XXXXX.','..XXX..','...X...'];H.forEach((row,y)=>[...row].forEach((ch,x)=>{if(ch==='X')P(g,G.bx(.05,.05,.05),m.glow('#ff3a5a',1.1),[(x-3)*.05,.33-y*.05,0])}));stand(g,m,'#1a1a3a')});
  F('lichtkachel','pixelmond','elektro',2,800,'Licht-Kachel','Light tile','Eine Kachel, die beim Antippen an- und ausgeht.','A tile that switches on and off when you tap it.','Ein Computer rechnet nur mit zwei Zuständen: an und aus. Daraus baut er alle Zahlen, Bilder und Töne.','A computer only works with two states: on and off. From these it builds every number, picture and sound.',(g,m)=>{P(g,G.bx(.3,.06,.3,.02),m.c('#2a2a3a'),[0,.03,0]);P(g,G.bx(.24,.02,.24,.01),m.glow('#7affc8',1.3),[0,.07,0])});

  /* ================= je ein Stück mehr, damit überall sechs liegen ================= */
  F('eisbohrkern','frost','natur',3,1300,'Eisbohrkern','Ice core','Eine lange Eisstange mit Schichten und winzigen Luftbläschen.','A long rod of ice with layers and tiny air bubbles.','Forschende bohren tief ins Eis der Antarktis. In den Bläschen im Eis steckt Luft von vor Hunderttausenden Jahren.','Researchers drill deep into the ice of Antarctica. The bubbles in the ice hold air from hundreds of thousands of years ago.',(g,m)=>{P(g,G.cy(.08,.08,.5,Q(16)),m.c('#dff4ff',{opacity:.7,gloss:1.4}),[0,.08,0],[0,0,PI/2]);for(let i=0;i<5;i++)P(g,G.cy(.081,.081,.01,Q(16)),m.c('#a8c8e8'),[-.2+i*.1,.08,0],[0,0,PI/2]);for(let i=0;i<8;i++)P(g,G.s(.01),m.c('#ffffff'),[-.22+i*.06,.08+((i*3)%5-2)*.02,.06])});
  F('kaktusbluete','wueste','natur',2,800,'Kaktusblüte im Glas','Cactus flower in a jar','Eine grosse weisse Blüte, die nie verwelkt.','A big white flower that never wilts.','Manche Kakteen blühen nur eine einzige Nacht lang. Am Morgen ist die Blüte schon wieder zu.','Some cacti bloom for just one single night. By morning the flower has closed again.',(g,m)=>jar(g,m,.42,()=>{P(g,G.cy(.04,.05,.12,Q(10)),m.c('#5a9a4a'),[0,.06,0]);for(let i=0;i<8;i++){const a=i/8*TAU;P(g,G.s(.05),m.c('#fffdf4'),[Math.cos(a)*.06,.2,Math.sin(a)*.06],[0,-a,.6],[1.6,.3,.7])}P(g,G.s(.03),m.c('#ffe060'),[0,.21,0])}));
  F('kuckucksfigur','uhrwerk','kunst',2,900,'Kuckucks-Figur','Cuckoo figure','Der kleine Holzvogel aus einer Kuckucksuhr. Er ruft noch immer.','The little wooden bird from a cuckoo clock. It still calls out.','Der echte Kuckuck legt seine Eier in fremde Nester. Andere Vögel brüten sie dann aus.','The real cuckoo lays its eggs in other birds\' nests. The other birds then hatch them.',(g,m)=>{stand(g,m);P(g,G.s(.1),m.c('#8a5a3a'),[0,.18,0],null,[1,.9,1.3]);P(g,G.s(.07),m.c('#8a5a3a'),[0,.28,.08]);P(g,G.co(.025,.08,6),m.c('#ffb030'),[0,.28,.17],[PI/2,0,0]);P(g,G.bx(.04,.02,.14),m.c('#6a4a2a'),[0,.2,-.15],[.4,0,0]);for(const s of[-1,1])P(g,G.s(.012),m.c('#1a1a24'),[s*.04,.3,.13])});
  F('spieluhr','klang','musik',2,1000,'Spieluhr','Music box','Ein Kästchen mit Kurbel. Dreht man sie, klimpert eine Melodie.','A little box with a crank. Turn it and a tune tinkles out.','In einer Spieluhr dreht sich eine Walze mit kleinen Stiften. Die Stifte zupfen an Metallzungen, so entsteht die Melodie.','Inside a music box a cylinder with little pins turns. The pins pluck metal teeth, and that makes the tune.',(g,m)=>{P(g,G.bx(.36,.16,.24,.02),m.c('#c86a8a'),[0,.08,0]);P(g,G.cy(.04,.04,.24,Q(14)),m.c('#c89a40',GOLD),[0,.2,0],[0,0,PI/2]);P(g,G.bx(.24,.02,.08),m.c('#c8c8d8',GOLD),[0,.17,.07]);P(g,G.cy(.01,.01,.1),m.c('#c89a40'),[.22,.2,0],[0,0,PI/2]);P(g,G.cy(.01,.01,.08),m.c('#c89a40'),[.27,.24,0]);P(g,G.s(.02),m.c('#fffdf4'),[.27,.28,0])});
  F('filzherz','pluesch','kunst',2,600,'Filz-Herz','Felt heart','Ein dickes, weiches Herz aus Filz mit Stichen am Rand.','A thick soft heart made of felt, with stitches around the edge.','Filz entsteht, wenn man Wolle mit warmem Wasser und Seife reibt. Die Fasern verhaken sich dann fest ineinander.','Felt is made by rubbing wool with warm water and soap. The fibres then hook firmly into each other.',(g,m)=>{stand(g,m,'#b89af0');for(const s of[-1,1])P(g,G.s(.09),m.c('#ff6fa5',{rim:.8}),[s*.065,.3,0],null,[1,1,.5]);P(g,G.co(.13,.18,Q(12)),m.c('#ff6fa5',{rim:.8}),[0,.18,0],[PI,0,0],[1,1,.4])});
  F('abakus','rechenzentrum','technik',2,800,'Abakus','Abacus','Ein Rahmen mit bunten Kugeln auf Stäben.','A frame with colourful beads on rods.','Der Abakus ist eine der ältesten Rechenhilfen. Mit verschiebbaren Kugeln kann man schnell zusammenzählen.','The abacus is one of the oldest counting tools. With its sliding beads you can add up quickly.',(g,m)=>{for(const x of[-.22,.22])P(g,G.bx(.03,.32,.08,.01),m.c('#8a5a3a'),[x,.16,0]);for(const y of[.015,.31])P(g,G.bx(.47,.03,.08,.01),m.c('#8a5a3a'),[0,y,0]);const c=['#ff5a5a','#ffd23f','#7fd34a','#45a0ff'];for(let k=0;k<4;k++){const y=.07+k*.065;P(g,G.cy(.006,.006,.42),m.c('#c8c8d8'),[0,y,0],[0,0,PI/2]);for(let i=0;i<5;i++)P(g,G.s(.022),m.c(c[k]),[-.17+i*.045+(k%2)*.1,y,0],null,[.7,1,1])}});
  F('mini_fernrohr','nachtmarkt','technik',3,1300,'Messing-Fernrohr','Brass telescope','Ein kleines Fernrohr. Durch es sieht man vier Pünktchen neben einem hellen Stern.','A little telescope. Through it you can see four tiny dots beside a bright star.','Mit einem einfachen Fernrohr entdeckte Galileo Galilei vor über 400 Jahren die vier grossen Monde des Jupiters.','With a simple telescope, Galileo Galilei discovered the four big moons of Jupiter more than 400 years ago.',(g,m)=>{for(let i=0;i<3;i++){const a=i/3*TAU;P(g,G.cy(.01,.01,.28),m.c('#6a4a3a'),[Math.cos(a)*.06,.13,Math.sin(a)*.06],[Math.sin(a)*.25,0,-Math.cos(a)*.25])}P(g,G.cy(.04,.05,.4,Q(14)),m.c('#c89a40',GOLD),[0,.32,0],[0,0,PI/2-.4]);P(g,G.cy(.052,.052,.02,Q(14)),m.c('#2a2224'),[.18,.4,0],[0,0,PI/2-.4])});
  F('dominostein','bauklotz','spielzeug',2,500,'Dominostein','Domino','Ein schwarzer Stein mit weissen Punkten. Er möchte umfallen.','A black tile with white dots. It wants to fall over.','Fällt ein Dominostein, stösst er den nächsten an. So kann eine lange Reihe ganz von allein umfallen.','When one domino falls, it knocks over the next. That way a long row can topple all by itself.',(g,m)=>{for(let i=0;i<3;i++){P(g,G.bx(.1,.22,.03,.01),m.c('#1a1a24'),[-.12+i*.12,.11,0],[0,0,-i*.25]);for(const y of[.05,.15])P(g,G.cy(.012,.012,.032,Q(8)),m.c('#ffffff'),[-.12+i*.12+Math.sin(-i*.25)*(y-.11)*-1,y,0],[PI/2,0,0])}P(g,G.bx(.04,.004,.22),m.c('#e8402a'),[0,.004,0],[0,PI/2,0])});

  try{if(typeof I18N!=='undefined'&&I18N.extend)I18N.extend('en',EN)}catch(e){}
})();
