/* =====================================================================
   CYBORG-LABOR · tiere2.js · Inhalte 2.0: Tiere
   Jeder Planet bekommt mindestens sechs Tiere. Jedes ist ein echtes Tier
   oder ein Spielzeug-Verwandter davon, mit wahrem, kindgerechtem Fakt.
   Körper kommen aus Vorlagen (Hase, Katze, Vogel …), Farben je Tier.
   Englische Texte stehen daneben und kommen über I18N.extend dazu.
   ===================================================================== */
(()=>{
  if(typeof FAUNA==='undefined')return;
  const EN={};
  /* ---------- Körper-Vorlagen ---------- */
  const PRE={
    hase:{body:[.3,.28,.36],head:{r:.24,p:[0,.48,.28]},snout:{type:'muzzle',col:'#ffffff'},ears:{type:'long',len:.6},legs:{n:4,len:.1,r:.07},tail:{type:'puff',r:.1},gait:'hop'},
    maus:{body:[.28,.24,.34],head:{r:.22,p:[0,.38,.3]},snout:{type:'long'},ears:{type:'round',x:.6,y:.6},legs:{n:4,len:.08,r:.05},tail:{type:'long',len:1.2,r:.025,curl:.4},gait:'fast'},
    hamster:{body:[.32,.3,.34],head:{r:.25,p:[0,.42,.26]},snout:{type:'muzzle',len:.5},ears:{type:'round',x:.55,y:.65},legs:{n:4,len:.06,r:.05},tail:{type:'puff',r:.05},gait:'waddle'},
    katze:{body:[.3,.28,.46],head:{r:.27,p:[0,.62,.42]},snout:{type:'muzzle',len:.6},ears:{type:'pointy',len:.4},legs:{n:4,len:.22,r:.07},tail:{type:'long',len:1.2,r:.05,curl:1.3},gait:'walk'},
    hund:{body:[.32,.3,.5],head:{r:.28,p:[0,.66,.44]},snout:{type:'muzzle',len:1},ears:{type:'floppy',len:.5},legs:{n:4,len:.24,r:.08},tail:{type:'long',len:.8,r:.05,curl:1.6},gait:'fast'},
    fuchs:{body:[.3,.28,.5],head:{r:.26,p:[0,.62,.46]},snout:{type:'muzzle',len:1.3},ears:{type:'pointy',len:.55},legs:{n:4,len:.24,r:.06},tail:{type:'bushy',len:1.3},gait:'fast'},
    baer:{body:[.45,.42,.55],head:{r:.33,p:[0,.85,.52]},snout:{type:'muzzle',len:.8},ears:{type:'round'},legs:{n:4,len:.25,r:.12},tail:{type:'puff',r:.08},gait:'waddle'},
    schaf:{body:[.38,.36,.5],head:{r:.24,p:[0,.78,.5]},snout:{type:'muzzle',len:.7},ears:{type:'floppy',len:.4},legs:{n:4,len:.3,r:.07},tail:{type:'puff',r:.08},gait:'walk'},
    vogel:{body:[.26,.26,.3],head:{r:.2,p:[0,.55,.2]},snout:{type:'beak',len:.5},ears:{type:'none'},legs:{n:2,len:.14,r:.03},wings:{},tail:{type:'fan'},gait:'hop'},
    eule:{body:[.3,.36,.3],head:{r:.28,p:[0,.75,.08]},snout:{type:'beak',len:.28},eyes:{r:.14,x:.42,y:.12},ears:{type:'pointy',len:.25,y:.85},legs:{n:2,len:.1,r:.04},wings:{},tail:{type:'fan'},gait:'hop'},
    ente:{body:[.3,.26,.38],head:{r:.2,p:[0,.55,.32]},snout:{type:'bill'},ears:{type:'none'},legs:{n:2,len:.1,r:.04},wings:{},tail:{type:'fan'},gait:'waddle'},
    pinguin:{body:[.3,.42,.3],head:{r:.22,p:[0,.85,.1]},snout:{type:'beak',len:.4},ears:{type:'none'},legs:{n:2,len:.06,r:.05},flippers:{up:.9},tail:{type:'none'},gait:'waddle'},
    frosch:{body:[.4,.24,.38],head:{r:.28,p:[0,.38,.24],sc:[1.2,.8,1]},snout:{type:'wide'},eyes:{r:.11,x:.5,y:.55},ears:{type:'none'},legs:{n:4,len:.1,r:.08},tail:{type:'none'},gait:'hop'},
    kroete:{body:[.36,.22,.36],head:{r:.25,p:[0,.32,.24],sc:[1.2,.8,1]},snout:{type:'wide'},eyes:{r:.1,x:.5,y:.55},ears:{type:'none'},legs:{n:4,len:.08,r:.07},tail:{type:'none'},gait:'hop'},
    schildkroete:{body:[.34,.2,.4],head:{r:.16,p:[0,.3,.5]},snout:{type:'dot'},ears:{type:'none'},legs:{n:4,len:.08,r:.07},tail:{type:'lizard',r:.04},gait:'waddle'},
    igel:{body:[.3,.24,.36],head:{r:.19,p:[0,.3,.36]},snout:{type:'long'},ears:{type:'round',x:.5,y:.5},legs:{n:4,len:.06,r:.05},tail:{type:'none'},gait:'waddle'},
    echse:{body:[.18,.13,.42],head:{r:.15,p:[0,.24,.5],sc:[1,.75,1.3]},snout:{type:'dot'},ears:{type:'none'},legs:{n:4,len:.08,r:.045},tail:{type:'lizard',r:.06},gait:'fast'},
    schlange:{body:[.13,.12,.55],by:.13,head:{r:.15,p:[0,.18,.6],sc:[1.1,.7,1.3]},snout:{type:'dot'},ears:{type:'none'},legs:{n:0},tail:{type:'lizard',r:.1},cheeks:false,gait:'slither'},
    schnecke:{body:[.16,.12,.42],by:.12,head:{r:.13,p:[0,.2,.42]},snout:{type:'none'},ears:{type:'none'},legs:{n:0},tail:{type:'none'},stalkEyes:true,gait:'slither'},
    robbe:{body:[.34,.3,.6],by:.3,head:{r:.26,p:[0,.55,.55]},snout:{type:'muzzle',len:.6},ears:{type:'none'},legs:{n:0},flippers:{back:true},tail:{type:'none'},gait:'slither'},
    krabbe:{body:[.4,.16,.3],by:.22,head:{r:.001,p:[0,.2,.3]},snout:{type:'none'},ears:{type:'none'},cheeks:false,legs:{n:6,type:'crab',len:.2,r:.05},stalkEyes:true,tail:{type:'none'},gait:'fast'}
  };
  /* Tier anlegen: id, Planet, Vorlage, Aussehen, Name de/en, Biome, mag, Produkt, Fakt de/en, Extras */
  function T(id,pl,pre,look,de,en,bio,likes,prod,fde,fen,o){o=o||{};if(FAUNA.S[id])return;
    const base=PRE[pre];const a=Object.assign({},base,look);for(const k of['head','snout','ears','legs','tail','eyes','wings'])if(base[k]&&look[k])a[k]=Object.assign({},base[k],look[k]);
    FAUNA.S[id]=Object.assign({n:de,planet:pl,biomes:bio,count:o.count||3,size:o.size||.7,speed:o.speed||1,gait:a.gait,voice:o.voice||['mrr','prr','hm'],pitch:o.pitch||360,likes,product:prod,names:o.names||['Pip','Flocke','Kiko','Mo'],fact:fde,a},o.flags||{});
    EN[de]=en;EN[fde]=fen}
  const W={water:true},NIGHT={night:true},SHY={shy:true},HERD={herd:true};

  /* ===== ältere Planeten auffüllen ===== */
  T('dachs','kompost','baer',{col:'#8a8a8a',belly:'#3a3a3a',head:{r:.26,col:'#f4f4f0'},stripes:{col:'#2a2a2a',n:2},body:[.38,.3,.5]},'Dachs','Badger',['wald','herbstwald'],['apfel','beeren','champignon'],'champignon','Dachse graben grosse Baue mit vielen Zimmern. Manche Baue werden über viele Generationen bewohnt.','Badgers dig big burrows with many rooms. Some burrows are lived in for many generations.',{size:.75,speed:.8,voice:['grummel','schnauf','hmpf'],pitch:240,flags:NIGHT,names:['Grauling','Brummel','Streifi']});
  T('blechigel','schrott','igel',{col:'#a0a8b0',extra:{spikes:'#c8d0d8'}},'Blech-Igel','Tin hedgehog',['schrottebene','kristallfeld'],['schraube','kabelrest'],'schraube','Ein Igel hat rund 7000 Stacheln. Bei Gefahr rollt er sich zu einer stacheligen Kugel zusammen.','A hedgehog has about 7000 spines. When in danger, it rolls up into a prickly ball.',{size:.55,speed:.8,voice:['klirr','schnuff','pfff'],pitch:420,flags:SHY});
  T('drahtspatz','schrott','vogel',{col:'#8a7a5a',belly:'#e8dcc8',head:{col:'#6a5a4a'}},'Draht-Spatz','Wire sparrow',['schrottebene','gluehwald'],['beeren','schraube'],'kabelrest','Spatzen baden gern im Sand oder Staub. So halten sie ihr Gefieder sauber.','Sparrows like to bathe in sand or dust. That keeps their feathers clean.',{size:.45,speed:1.4,voice:['tschilp','zirp','piep'],pitch:900,flags:HERD});
  T('riffschildkroete','korallen','schildkroete',{col:'#7ab86a',extra:{shell:'#4a8a5a',plate:'#8ac87a'},legs:{n:4,len:.06,r:.09}},'Meeresschildkröte','Sea turtle',[],['muschel','seeglas'],'seeglas','Meeresschildkröten kehren zum Eierlegen an den Strand zurück, an dem sie selbst geschlüpft sind.','Sea turtles return to lay eggs on the beach where they themselves hatched.',{size:.95,speed:.5,voice:['blubb','hmm','pff'],pitch:180,flags:W});
  T('pelikan','korallen','vogel',{col:'#f4f4f0',belly:'#ffffff',snout:{type:'beak',len:1.3,col:'#ffb040'},body:[.34,.32,.4],legs:{n:2,len:.16,r:.04}},'Pelikan','Pelican',['strand','riffstrand','felsinsel'],['muschel','kokosnuss'],'feder','Pelikane fangen Fische mit dem grossen Hautsack unter ihrem Schnabel, wie mit einem Kescher.','Pelicans catch fish with the big skin pouch under their beak, like with a net.',{size:.95,speed:.7,voice:['krah','gack','hrr'],pitch:220,flags:HERD});
  T('schneeeule','frost','eule',{col:'#f8f8f4',belly:'#ffffff',spots:{col:'#3a3a3a',n:8,s:.4}},'Schnee-Eule','Snowy owl',['schneefeld','polarhuegel','tannenwald'],['kiefernzapfen','beeren'],'fellbueschel','Schnee-Eulen jagen auch am Tag. Im arktischen Sommer geht die Sonne nämlich gar nicht unter.','Snowy owls also hunt during the day. In the Arctic summer, the sun does not set at all.',{size:.75,speed:1,voice:['huu','hu-hu','krrr'],pitch:300,flags:SHY});
  T('wuestenschildkroete','wueste','schildkroete',{col:'#c8a070',extra:{shell:'#a07a4a',plate:'#c89a60'}},'Wüsten-Schildkröte','Desert tortoise',['duenen','kakteenfeld','canyon'],['kaktusfrucht','unkraut'],'kaktusfrucht','Wüsten-Schildkröten graben Höhlen, um sich vor der Hitze zu schützen. Sie können Wasser lange in ihrem Körper speichern.','Desert tortoises dig burrows to shelter from the heat. They can store water in their body for a long time.',{size:.7,speed:.35,voice:['hmm','pff','schnauf'],pitch:160});
  T('trueffelmaus','pilz','maus',{col:'#a08060',belly:'#f4e8d8',cap:'#e8402a'},'Trüffel-Maus','Truffle mouse',['pilzwald','moorwiese'],['champignon','morchel'],'champignon','Mäuse fressen gern Pilze und verbreiten dabei ihre Sporen im Wald. So helfen sie neuen Pilzen beim Wachsen.','Mice like to eat mushrooms and spread their spores through the forest. That helps new mushrooms grow.',{size:.45,speed:1.5,voice:['piep','fiep','quiek'],pitch:1100,flags:SHY});
  T('waldkauz','pilz','eule',{col:'#8a6a4a',belly:'#c8a880',ears:{type:'none'}},'Waldkauz','Tawny owl',['pilzwald','sporensumpf'],['champignon','leuchtspore'],'leuchtspore','Das bekannte «Huhuuu» in der Nacht ist der Ruf des Waldkauz-Männchens.','The famous hooting at night is the call of the male tawny owl.',{size:.7,voice:['huhuu','kuwitt','hu'],pitch:280,flags:NIGHT});
  T('gartenigel','riesengarten','igel',{col:'#8a6a4a',extra:{spikes:'#5a4a3a'}},'Garten-Igel','Garden hedgehog',['gemuesebeet','rasenwald','kleefeld'],['erbse','beeren'],'tautropfen','Igel fressen Schnecken, Käfer und Würmer. Darum freuen sich viele Gärtner über einen Igel im Garten.','Hedgehogs eat snails, beetles and worms. That is why many gardeners are happy to have a hedgehog in the garden.',{size:1.4,speed:.8,voice:['schnuff','fff','pfff'],pitch:340,flags:NIGHT});
  T('stadtkraehe','metro','vogel',{col:'#2a2a34',belly:'#3a3a44',snout:{type:'beak',len:.6,col:'#2a2a2a'}},'Stadt-Krähe','City crow',['gehweg','stadtpark','hafenkai'],['hotdog','beeren'],'zeitung','Krähen sind sehr schlau. Sie können sich die Gesichter von Menschen merken.','Crows are very clever. They can remember people\'s faces.',{size:.6,speed:1.2,voice:['krah','kraa','kroa'],pitch:260});
  T('gleithoernchen','wolkenarchipel','maus',{col:'#c8b8d8',belly:'#ffffff',tail:{type:'bushy',len:1},flippers:{s:1.6,up:.1,col:'#b0a0c8'}},'Wolken-Gleithörnchen','Cloud flying squirrel',['nebelwald','regenbogenhain'],['beeren','regenbogensplitter'],'windfeder','Gleithörnchen haben eine Flughaut zwischen Armen und Beinen. Damit segeln sie von Baum zu Baum.','Flying squirrels have a skin flap between their arms and legs. They use it to glide from tree to tree.',{size:.5,speed:1.5,voice:['tschk','fiep','prr'],pitch:900,flags:NIGHT});
  T('lesezeichenschnecke','bibliothek','schnecke',{col:'#d8c8a8',extra:{snailShell:'#a0603a'}},'Lesezeichen-Schnecke','Bookmark snail',['papierwiese','lesegarten'],['papierseite','beeren'],'papierseite','Weinbergschnecken verschliessen ihr Haus im Winter mit einem Deckel aus Kalk und schlafen bis zum Frühling.','Roman snails seal their shell in winter with a lid of chalk and sleep until spring.',{size:.6,speed:.25,voice:['...','schlurp','hm'],pitch:500});
  T('zahnradigel','uhrwerk','igel',{col:'#c89a40',extra:{spikes:'#e8c060'}},'Zahnrad-Igel','Cog hedgehog',['messingheide','federwiese'],['zahnrad','beeren'],'zahnrad','Igel halten einen Winterschlaf. Dabei schlägt ihr Herz viel langsamer, nur wenige Male in der Minute.','Hedgehogs hibernate in winter. Their heart then beats much more slowly, only a few times a minute.',{size:.55,voice:['tick','schnuff','klick'],pitch:460,flags:NIGHT});
  T('leierschwanz','klang','vogel',{col:'#8a6a4a',belly:'#c8a880',tail:{type:'fan',col:'#c8a060'},body:[.28,.28,.34]},'Leierschwanz','Lyrebird',['harfenwald','echoufer'],['beeren','glockenstaub'],'glockenstaub','Der Leierschwanz kann fast jedes Geräusch nachmachen, sogar Kameras und Autoalarme.','The lyrebird can copy almost any sound, even cameras and car alarms.',{size:.7,voice:['tirili','klick','trrr'],pitch:700});
  T('faltschwan','origami','ente',{col:'#fffdf4',belly:'#ffffff',snout:{type:'bill',col:'#ff8a3a'},body:[.34,.28,.44],head:{r:.18,p:[0,.75,.4]}},'Falt-Schwan','Paper swan',[],['buntpapier','papierkoi'],'buntpapier','Schwäne bleiben oft ein Leben lang mit demselben Partner zusammen.','Swans often stay with the same partner for their whole life.',{size:.9,speed:.6,voice:['hrr','tröt','hmm'],pitch:240,flags:W});

  /* ===== Neon-Arkade ===== */
  T('arcadewaschbaer','neonarkade','katze',{col:'#8a8a9a',belly:'#e8e8f0',head:{col:'#c8c8d8'},tail:{type:'bushy',len:1.1,col:'#6a6a7a'},stripes:{col:'#ff6fd8',n:3}},'Arcade-Waschbär','Arcade raccoon',['neonwiese','chromklippen'],['spielmarke_klein','kabelrest'],'spielmarke_klein','Waschbären tasten ihr Futter mit den Vorderpfoten ab, oft im Wasser. Ihre Pfoten sind sehr feinfühlig.','Raccoons feel their food with their front paws, often in water. Their paws are very sensitive.',{size:.7,speed:1.1,voice:['tschirp','grrm','kekek'],pitch:520,flags:NIGHT,names:['Joy','Coin','Pixel']});
  T('neonflamingo','neonarkade','vogel',{col:'#ff6fd8',belly:'#ffb8ec',legs:{n:2,len:.45,r:.03,col:'#ff6fd8'},body:[.28,.28,.34],head:{r:.17,p:[0,1.0,.3]},snout:{type:'beak',len:.6,col:'#2a2a34'}},'Neon-Flamingo','Neon flamingo',['kabelufer','neonwiese'],['pixelstaub','pixelkaefer'],'pixelstaub','Flamingos sind rosa, weil ihr Futter, kleine Krebse und Algen, rote Farbstoffe enthält.','Flamingos are pink because their food, small shrimp and algae, contains red colouring.',{size:1,speed:.8,voice:['gack','honk','krr'],pitch:330,flags:HERD});
  T('bonusgecko','neonarkade','echse',{col:'#7fff6a',spots:{col:'#ff6fd8',n:8,s:.5}},'Bonus-Gecko','Bonus gecko',['chromklippen','pixelwueste'],['pixelkaefer','pixelstaub'],'pixelstaub','Geckos können an Wänden und sogar an Glas hochlaufen. An ihren Zehen sitzen Millionen winziger Härchen.','Geckos can run up walls and even glass. Their toes are covered in millions of tiny hairs.',{size:.55,speed:1.6,voice:['geck-o','tock','zirp'],pitch:800,flags:SHY});
  T('tastenigel','neonarkade','igel',{col:'#7a3aff',extra:{spikes:'#45e0ff'}},'Tasten-Igel','Button hedgehog',['knopfwald','neonwiese'],['spielmarke_klein','pixelkaefer'],'spielmarke_klein','Igel haben eine sehr gute Nase. Sie finden Käfer und Würmer sogar unter dem Laub.','Hedgehogs have a very good nose. They can even find beetles and worms under leaves.',{size:.55,voice:['bip','schnuff','pling'],pitch:600,flags:NIGHT});

  /* ===== Plüsch ===== */
  T('kuschelbaer','pluesch','baer',{col:'#c8905a',belly:'#f4d8b0',snout:{type:'muzzle',col:'#f4d8b0'}},'Kuschelbär','Cuddle bear',['kissenhuegel','pomponwald'],['flausch','flausch'],'wollfaden','Viele Bären halten im Winter eine lange Ruhe in ihrer Höhle. Die Jungen kommen dabei zur Welt.','Many bears rest for a long time in their den in winter. Their cubs are born during that time.',{size:1,speed:.7,voice:['brumm','hmm','grrr'],pitch:180,names:['Teddy','Knuddel','Honig']});
  T('pomponpudel','pluesch','hund',{col:'#ffb8d0',extra:{wool:'#ffd0e0'}},'Pompon-Pudel','Pompom poodle',['kuschelwiese','sockengipfel'],['knopf_klein','flausch'],'wollfaden','Pudel haben Locken, die immer weiter wachsen. Sie verlieren kaum Haare.','Poodles have curls that keep on growing. They hardly shed any hair.',{size:.7,speed:1.3,voice:['wuff','wau','jip'],pitch:480});
  T('filzpinguin','pluesch','pinguin',{col:'#3a3a54',belly:'#f4f0e8',snout:{type:'beak',col:'#ff9a3a'}},'Filz-Pinguin','Felt penguin',['filzufer','sockengipfel'],['knopf_klein','sockenfisch'],'knopf_klein','Kaiserpinguine kuscheln sich im Winter eng aneinander. Wer aussen steht, darf bald wieder in die warme Mitte.','Emperor penguins huddle close together in winter. Those on the outside soon get a turn in the warm middle.',{size:.75,speed:.6,voice:['kwäk','quiek','trööt'],pitch:400,flags:HERD});
  T('sockenalpaka','pluesch','schaf',{col:'#f4e8d8',extra:{wool:'#fff4e8'},head:{r:.2,p:[0,1.15,.5]},ears:{type:'pointy',len:.5}},'Socken-Alpaka','Sock alpaca',['kuschelwiese','kissenhuegel'],['flausch','flausch'],'wollfaden','Alpakas summen leise, um sich zu verständigen. Ihre Wolle ist sehr weich und warm.','Alpacas hum softly to talk to each other. Their wool is very soft and warm.',{size:1.05,speed:.8,voice:['hmmm','mmh','summ'],pitch:300,flags:HERD});

  /* ===== Bernstein ===== */
  T('bernsteingecko','bernstein','echse',{col:'#e8a040',spots:{col:'#a0602a',n:8,s:.5}},'Bernstein-Gecko','Amber gecko',['harzwald','bernsteinbruch'],['harzmuecke','harztropfen'],'harztropfen','Man hat Geckos in Bernstein gefunden, die vor rund 100 Millionen Jahren gelebt haben.','Geckos have been found in amber that lived about 100 million years ago.',{size:.5,speed:1.5,voice:['tock','zirp','geck'],pitch:760,flags:SHY});
  T('saebelzahnkaetzchen','bernstein','katze',{col:'#e8b070',belly:'#f8e8c8',spots:{col:'#a07040',n:6}},'Säbelzahn-Kätzchen','Sabre-tooth kitten',['farnlichtung','goldduenen'],['zapfen_klein','harztropfen'],'zapfen_klein','Säbelzahnkatzen lebten in der Eiszeit. Ihre langen Eckzähne waren über 20 Zentimeter lang.','Sabre-toothed cats lived in the Ice Age. Their long fangs were over 20 centimetres long.',{size:.75,voice:['miau','grrr','mrau'],pitch:420});
  T('ammonitenschnecke','bernstein','schnecke',{col:'#d8b890',extra:{snailShell:'#c88a40'}},'Ammoniten-Schnecke','Ammonite snail',['fossilstrand','harzwald'],['harztropfen','beeren'],'harztropfen','Ammoniten waren Meerestiere mit gedrehtem Gehäuse. Ihre Versteinerungen findet man überall auf der Welt.','Ammonites were sea creatures with coiled shells. Their fossils are found all over the world.',{size:.6,speed:.25,voice:['...','hm','schlurp'],pitch:500});
  T('urpferdchen','bernstein','hund',{col:'#a07a4a',belly:'#e8d8b8',ears:{type:'pointy',len:.45},tail:{type:'long',len:.6,r:.06,curl:.3},stripes:{col:'#c8a070',n:4}},'Urpferdchen','Dawn horse',['farnlichtung','goldduenen'],['zapfen_klein','beeren'],'zapfen_klein','Das Urpferdchen lebte vor über 50 Millionen Jahren und war nur so gross wie ein Fuchs.','The dawn horse lived more than 50 million years ago and was only as big as a fox.',{size:.8,speed:1.4,voice:['hihi','pfrr','wieh'],pitch:500,flags:HERD});

  /* ===== Dino-Fabrik ===== */
  T('spielzeugparasaurolophus','dinofabrik','echse',{col:'#ff9a45',belly:'#ffe0b0',body:[.28,.3,.55],head:{r:.2,p:[0,.78,.62],sc:[1,.9,1.3]},horns:'#ffd23f',legs:{n:4,len:.28,r:.08},tail:{type:'lizard',r:.1},spots:{col:'#45a0ff',n:6}},'Spielzeug-Parasaurolophus','Toy parasaurolophus',['fabrikwiese','gusswald'],['granulat','schraube_klein'],'granulat','Der Parasaurolophus hatte einen hohlen Kamm auf dem Kopf. Damit konnte er wahrscheinlich laute, tiefe Töne machen.','Parasaurolophus had a hollow crest on its head. It could probably make loud, deep sounds with it.',{size:.7,speed:.8,voice:['tröt','huu','tuut'],pitch:200});
  T('aufziehschildkroete','dinofabrik','schildkroete',{col:'#7ad84a',extra:{shell:'#ff6fa5',plate:'#ffd23f'},tail:{type:'magnet'}},'Aufzieh-Schildkröte','Wind-up turtle',['fabrikwiese','farbufer'],['granulat','badeente'],'schraube_klein','Schildkröten können sehr alt werden. Manche Riesenschildkröten leben über 150 Jahre.','Turtles can live a very long time. Some giant tortoises live for more than 150 years.',{size:.6,speed:.4,voice:['klick','surr','tick'],pitch:420});
  T('gummikrokodil','dinofabrik','echse',{col:'#5ac83a',belly:'#e8ffb0',body:[.24,.16,.6],head:{r:.18,p:[0,.26,.66],sc:[1,.6,1.8]},extra:{spikes:'#3aa02a'}},'Gummi-Krokodil','Rubber crocodile',['farbufer','granulatduenen'],['badeente','granulat'],'granulat','Krokodile können sehr lange ohne Futter auskommen, manchmal monatelang.','Crocodiles can go a very long time without food, sometimes for months.',{size:1,speed:.7,voice:['quietsch','grrr','schnapp'],pitch:200,flags:{nearWater:true}});
  T('spritzgusspinguin','dinofabrik','pinguin',{col:'#45a0ff',belly:'#ffffff',snout:{type:'beak',col:'#ffd23f'}},'Spritzguss-Pinguin','Moulded penguin',['farbufer','schlotberge'],['granulat','quietschfisch'],'granulat','Pinguine können nicht fliegen, aber unter Wasser «fliegen» sie mit ihren Flügeln sehr schnell.','Penguins cannot fly, but under water they "fly" very fast with their wings.',{size:.65,speed:.7,voice:['quiek','kwäk','trööt'],pitch:420,flags:HERD});

  /* ===== Kaufhaus ===== */
  T('kaufhaushamster','kaufhaus','hamster',{col:'#e8b070',belly:'#fff4e0'},'Kaufhaus-Hamster','Shop hamster',['atrium','parkdeck'],['kassenbon','parkchip'],'kassenbon','Hamster tragen Futter in ihren Backentaschen nach Hause. Da passt erstaunlich viel hinein.','Hamsters carry food home in their cheek pouches. An amazing amount fits inside.',{size:.45,speed:1.1,voice:['fiep','quiek','mümmel'],pitch:1000,flags:NIGHT});
  T('wellensittich','kaufhaus','vogel',{col:'#7ad84a',belly:'#ffe060',head:{col:'#ffe060'},stripes:{col:'#2a2a2a',n:3}},'Wellensittich','Budgie',['palmenpassage','dachgarten'],['parkchip','beeren'],'kassenbon','Wellensittiche können einzelne Wörter nachsprechen. In der Natur leben sie in grossen Schwärmen in Australien.','Budgies can repeat single words. In the wild they live in big flocks in Australia.',{size:.45,speed:1.3,voice:['tschirp','piep','hallo'],pitch:1100,flags:HERD});
  T('atriumschildkroete','kaufhaus','schildkroete',{col:'#8ac86a',extra:{shell:'#5a8a4a',plate:'#a8d080'},head:{col:'#8ac86a'}},'Atrium-Schildkröte','Atrium turtle',[],['brunnenkoi','parkchip'],'knopfbatterie','Schildkröten haben keine Zähne. Sie beissen mit einem harten Hornschnabel.','Turtles have no teeth. They bite with a hard beak made of horn.',{size:.6,speed:.4,voice:['blubb','hm','pff'],pitch:200,flags:W});
  T('mops','kaufhaus','hund',{col:'#e8d0a8',belly:'#f8ecd8',snout:{type:'muzzle',len:.35,col:'#3a2a24'},ears:{type:'floppy',len:.3,col:'#3a2a24'},tail:{type:'long',len:.4,r:.05,curl:2}},'Mops','Pug',['atrium','palmenpassage'],['kassenbon','parkchip'],'knopfbatterie','Möpse haben eine kurze Schnauze. Darum schnarchen sie oft beim Schlafen.','Pugs have a short snout. That is why they often snore while sleeping.',{size:.6,speed:.8,voice:['wuff','schnarch','grunz'],pitch:360});

  /* ===== Funkturm ===== */
  T('funkelster','funkturm','vogel',{col:'#1a1a24',belly:'#f4f4f0',tail:{type:'long',len:1.2,r:.04,curl:0},wings:{col:'#2a4a8a'}},'Funk-Elster','Radio magpie',['drahtwald','gipfelstation'],['kupferdraht','funkgrille'],'quarz','Elstern erkennen sich selbst im Spiegel. Das können nur wenige Tiere.','Magpies recognise themselves in a mirror. Only a few animals can do that.',{size:.6,speed:1.2,voice:['schäk','krr','tschak'],pitch:620});
  T('kupferechse','funkturm','echse',{col:'#c87a3a',belly:'#f4c8a0',stripes:{col:'#ffd890',n:3}},'Kupfer-Echse','Copper lizard',['kupferufer','schuesselfeld'],['funkgrille','kupferdraht'],'kupferdraht','Manche Echsen können bei Gefahr ihren Schwanz abwerfen. Er wächst danach wieder nach.','Some lizards can drop their tail when in danger. It grows back afterwards.',{size:.5,speed:1.6,voice:['zisch','tock','zirp'],pitch:700,flags:SHY});
  T('drahthaarfuchs','funkturm','fuchs',{col:'#c86a2a',belly:'#f4f0e8',tail:{type:'bushy',tip:'#ffffff'}},'Drahthaar-Fuchs','Wire-haired fox',['wellenwiese','drahtwald'],['kupferdraht','schuesselblume'],'kupferdraht','Füchse hören Mäuse unter dem Schnee rascheln. Dann springen sie hoch und landen mit der Nase voran.','Foxes can hear mice rustling under the snow. Then they leap up and land nose first.',{size:.75,speed:1.4,voice:['kek','wau','jiep'],pitch:560,flags:SHY});
  T('schuesselschnecke','funkturm','schnecke',{col:'#c8c0b0',extra:{snailShell:'#8a8a9a'}},'Schüssel-Schnecke','Dish snail',['schuesselfeld','kupferufer'],['schuesselblume','beeren'],'quarz','Schnecken haben vier Fühler. Auf den beiden langen sitzen die Augen.','Snails have four feelers. Their eyes sit on the two long ones.',{size:.6,speed:.25,voice:['...','hm','schlurp'],pitch:500});

  /* ===== Magnetbahn ===== */
  T('kompassschildkroete','magnetbahn','schildkroete',{col:'#6aa8c8',extra:{shell:'#3a6a8a',plate:'#e8402a'}},'Kompass-Schildkröte','Compass turtle',[],['eisenspan','kompassblume'],'magnetstein','Meeresschildkröten spüren das Magnetfeld der Erde. Damit finden sie über Tausende Kilometer ihren Weg.','Sea turtles can sense the Earth\'s magnetic field. They use it to find their way across thousands of kilometres.',{size:.9,speed:.5,voice:['blubb','hmm','pff'],pitch:180,flags:W});
  T('magnetfuchs','magnetbahn','fuchs',{col:'#8a8a9a',belly:'#f4f4f8',tail:{type:'bushy',tip:'#e8402a'}},'Magnet-Fuchs','Magnet fox',['ringwiese','spulenwald'],['eisenspan','magnetstein'],'eisenspan','Forschende vermuten, dass Füchse beim Mäusefangen das Magnetfeld der Erde zum Zielen nutzen. Sie springen oft in Richtung Nordosten.','Scientists think foxes might use the Earth\'s magnetic field to aim when catching mice. They often leap towards the north-east.',{size:.75,speed:1.4,voice:['kek','wau','jiep'],pitch:560,flags:SHY});
  T('polpinguin','magnetbahn','pinguin',{col:'#2a2a3a',belly:'#ffffff',head:{col:'#2a2a3a'},snout:{type:'beak',col:'#ffa040'}},'Pol-Pinguin','Pole penguin',['polkappe','polufer'],['magnetstein','pol_scholle'],'magnetstein','Pinguine leben fast nur auf der Südhalbkugel der Erde, viele davon rund um den Südpol.','Penguins live almost only in the southern half of the Earth, many around the South Pole.',{size:.7,speed:.6,voice:['kwäk','trööt','quiek'],pitch:400,flags:HERD});
  T('brieftaube','magnetbahn','vogel',{col:'#a0a8b8',belly:'#d8dce8',head:{col:'#6a8a7a'}},'Brieftaube','Homing pigeon',['ringwiese','eisenspanfeld'],['eisenspan','beeren'],'eisenspan','Brieftauben finden aus Hunderten Kilometern Entfernung nach Hause. Dabei helfen ihnen Sonne und Magnetfeld.','Homing pigeons find their way home from hundreds of kilometres away. The sun and the magnetic field help them.',{size:.5,speed:1.2,voice:['gurr','ruckedigu','grr'],pitch:340,flags:HERD});

  /* ===== Rechenzentrum ===== */
  T('serverkatze','rechenzentrum','katze',{col:'#4a4a54',belly:'#c8c8d0',spots:{col:'#7aff8a',n:5,s:.4}},'Server-Katze','Server cat',['rankenhalle','lueftungsfeld'],['computermotte','ledkaefer'],'luefterschraube','Katzen schlafen sehr viel, oft 15 Stunden am Tag. Am liebsten an warmen Orten.','Cats sleep a lot, often 15 hours a day. They like warm places best.',{size:.65,voice:['miau','mrrp','schnurr'],pitch:620});
  T('kabelnatter','rechenzentrum','schlange',{col:'#2a8a4a',belly:'#c8f0c8',stripes:{col:'#ffd23f',n:5}},'Kabel-Natter','Cable snake',['rankenhalle','kuehlwasserufer'],['ledkaefer','computermotte'],'ranke_stueck','Schlangen riechen mit ihrer Zunge. Sie züngeln, um Duftstoffe aus der Luft einzufangen.','Snakes smell with their tongue. They flick it to catch scents from the air.',{size:.8,speed:.8,voice:['zzz','tss','hsss'],pitch:400,flags:SHY});
  T('moosschildkroete','rechenzentrum','schildkroete',{col:'#6a8a5a',extra:{shell:'#4a7a3a',plate:'#7ab84a'}},'Moos-Schildkröte','Moss turtle',['kuehlwasserufer','rankenhalle'],['ledbeere','ranke_stueck'],'ranke_stueck','Auf dem Panzer mancher Wasserschildkröten wachsen Algen. Das tarnt sie zwischen Pflanzen.','Algae grow on the shells of some water turtles. That camouflages them among plants.',{size:.6,speed:.4,voice:['blubb','hmm','pff'],pitch:200,flags:{nearWater:true}});
  T('platinenfrosch','rechenzentrum','frosch',{col:'#2a8a4a',belly:'#c8f0c8',spots:{col:'#ffd23f',n:8,s:.4}},'Platinen-Frosch','Circuit frog',['kuehlwasserufer','platinenwald'],['ledkaefer','computermotte'],'luefterschraube','Frösche trinken nicht mit dem Maul. Sie nehmen Wasser über ihre Haut auf.','Frogs do not drink with their mouth. They take in water through their skin.',{size:.5,speed:1.2,voice:['quak','bip','quaak'],pitch:300,flags:{nearWater:true}});

  /* ===== Tiefsee ===== */
  T('seeelefant','tiefsee','robbe',{col:'#8a7a6a',belly:'#c8b8a8',snout:{type:'long',col:'#8a7a6a'}},'See-Elefant','Elephant seal',[],['leuchtalge','tiefseefloh'],'perle_klein','See-Elefanten tauchen über tausend Meter tief und bleiben bis zu zwei Stunden unter Wasser.','Elephant seals dive more than a thousand metres deep and stay under water for up to two hours.',{size:1.2,speed:.5,voice:['röhr','blubb','grunz'],pitch:150,flags:W});
  T('riesenkrabbe','tiefsee','krabbe',{col:'#e87a4a',belly:'#f4c8a8',legs:{n:6,type:'crab',len:.5,r:.06}},'Japanische Riesenkrabbe','Japanese spider crab',['tiefseeboden','tiefgraben'],['leuchtalge','tiefseefloh'],'perle_klein','Die Japanische Riesenkrabbe hat die längsten Beine aller Krebse. Von Spitze zu Spitze messen sie über drei Meter.','The Japanese spider crab has the longest legs of any crab. From tip to tip they measure more than three metres.',{size:1,speed:.6,voice:['klack','knack','blubb'],pitch:260});
  T('meeresnacktschnecke','tiefsee','schnecke',{col:'#9a5aff',spots:{col:'#ffd23f',n:10,s:.5},stalkEyes:false,feelers:true,glowTips:'#ff8a3a'},'Meeres-Nacktschnecke','Sea slug',['leuchtriff','sandgrund'],['leuchtalge'],'leuchtalge','Meeres-Nacktschnecken gehören zu den buntesten Tieren der Welt. Die Farben warnen Fische, dass sie nicht schmecken.','Sea slugs are among the most colourful animals in the world. The colours warn fish that they taste bad.',{size:.6,speed:.3,voice:['...','blubb','hm'],pitch:500});
  T('lederschildkroete','tiefsee','schildkroete',{col:'#3a3a44',extra:{shell:'#2a2a34',plate:'#6a6a7a'},spots:{col:'#f4f4f0',n:10,s:.3}},'Lederschildkröte','Leatherback turtle',[],['leuchtalge','perle_klein'],'perle_klein','Die Lederschildkröte ist die grösste Schildkröte der Welt und taucht über tausend Meter tief.','The leatherback is the largest turtle in the world and dives more than a thousand metres deep.',{size:1.1,speed:.5,voice:['blubb','hmm','pff'],pitch:170,flags:W});

  /* ===== Wetterwerk ===== */
  T('regenschwalbe','wetterwerk','vogel',{col:'#2a3a6a',belly:'#f4f0e8',head:{col:'#2a3a6a'},tail:{type:'long',len:.8,r:.03,curl:0}},'Regen-Schwalbe','Rain swallow',['windwiese','regenhain'],['gewitterfliege','wasserlaeufer'],'wetterfeder','Vor Regen fliegen Schwalben oft tief. Dann fliegen auch die Insekten tief, die sie jagen.','Before rain, swallows often fly low. That is because the insects they hunt fly low then too.',{size:.45,speed:1.5,voice:['zwit','tschirp','wit'],pitch:1000,flags:HERD});
  T('regenbogenschnecke','wetterwerk','schnecke',{col:'#e8d8c8',extra:{snailShell:'#7a5aff'}},'Regenbogen-Schnecke','Rainbow snail',['regenhain','windwiese'],['regentropfen_glas','beeren'],'regentropfen_glas','Schnecken lieben Regen. Ihre Haut trocknet in der Sonne leicht aus, darum sind sie bei feuchtem Wetter unterwegs.','Snails love rain. Their skin dries out easily in the sun, so they come out in damp weather.',{size:.6,speed:.25,voice:['...','hm','schlurp'],pitch:500});
  T('wolkenlama','wetterwerk','schaf',{col:'#f4f4f8',extra:{wool:'#ffffff'},head:{r:.2,p:[0,1.15,.5]},ears:{type:'pointy',len:.55}},'Wolken-Lama','Cloud llama',['windwiese','sonnendeck'],['windradblume','wetterfeder'],'wetterfeder','Lamas spucken manchmal, wenn sie sich ärgern. Meistens spucken sie aber nur andere Lamas an.','Llamas sometimes spit when they are annoyed. But mostly they only spit at other llamas.',{size:1.05,speed:.8,voice:['hmmm','mäh','summ'],pitch:300,flags:HERD});
  T('gewitterkroete','wetterwerk','kroete',{col:'#5a6a7a',belly:'#c8d0d8',spots:{col:'#ffd23f',n:6}},'Gewitter-Kröte','Thunder toad',['regenhain','blitzfelsen'],['gewitterfliege','wasserlaeufer'],'regentropfen_glas','Kröten kommen vor allem bei Regen aus ihren Verstecken. Dann ist ihre Haut schön feucht.','Toads mostly come out of their hiding places when it rains. Then their skin stays nice and damp.',{size:.55,speed:.8,voice:['unk','quaak','grumm'],pitch:180,flags:NIGHT});

  /* ===== Nachtmarkt ===== */
  T('laterneneule','nachtmarkt','eule',{col:'#c8a070',belly:'#f4e8c8',ears:{type:'none'},spots:{col:'#ff8a3a',n:6,s:.4}},'Laternen-Eule','Lantern owl',['lampionhain','nachtgipfel'],['kerzenwachs','weinhaehnchen'],'kerzenwachs','Eulen fliegen fast lautlos. Ihre Federn haben weiche, fransige Ränder, die das Fluggeräusch dämpfen.','Owls fly almost silently. Their feathers have soft, fringed edges that muffle the sound of flight.',{size:.7,voice:['huu','hu-hu','krrr'],pitch:300,flags:NIGHT});
  T('mondkatze','nachtmarkt','katze',{col:'#3a3a54',belly:'#c8c8e0',spots:{col:'#fff4b0',n:4,s:.5}},'Mond-Katze','Moon cat',['marktgasse','mondwiese'],['mondblume','sternsplitter'],'sternsplitter','Katzen sehen im Dunkeln viel besser als wir. Hinter ihren Augen liegt eine Schicht, die Licht zurückwirft.','Cats see much better in the dark than we do. Behind their eyes is a layer that reflects light.',{size:.65,voice:['miau','mrrp','schnurr'],pitch:620,flags:NIGHT});
  T('lampiongecko','nachtmarkt','echse',{col:'#7aa0d8',spots:{col:'#ff8a3a',n:10,s:.5}},'Lampion-Gecko','Lantern gecko',['lampionhain','marktgasse'],['weinhaehnchen','kerzenwachs'],'kerzenwachs','Manche Geckos rufen nachts laut «Geck-o». Daher kommt ihr Name.','Some geckos call out loudly at night: "geck-o". That is where their name comes from.',{size:.5,speed:1.5,voice:['geck-o','tock','zirp'],pitch:760,flags:NIGHT});
  T('roterpanda','nachtmarkt','fuchs',{col:'#c8502a',belly:'#2a2224',head:{col:'#e8803a'},snout:{type:'muzzle',len:.6,col:'#ffffff'},ears:{type:'pointy',len:.35,col:'#ffffff'},tail:{type:'bushy',len:1.2}},'Roter Panda','Red panda',['lampionhain','nachtgipfel'],['mondblume','beeren'],'sternsplitter','Der Rote Panda wickelt sich zum Schlafen in seinen buschigen Schwanz ein, wie in eine Decke.','The red panda wraps itself in its bushy tail to sleep, like a blanket.',{size:.7,speed:.9,voice:['quiek','huff','zwitscher'],pitch:600,flags:SHY});

  /* ===== Bauklotz ===== */
  T('kloetzchenbiber','bauklotz','baer',{col:'#a0703a',belly:'#c8a070',body:[.36,.3,.48],head:{r:.26},tail:{type:'flat',col:'#5a4030'}},'Klötzchen-Biber','Block beaver',['bauufer','kegelwald'],['holzperle','steckblume'],'bauklotz','Biber bauen Dämme aus Ästen und Schlamm. So stauen sie das Wasser zu einem Teich.','Beavers build dams out of branches and mud. That holds back the water to make a pond.',{size:.75,speed:.6,voice:['brumm','klopf','schnauf'],pitch:240,flags:{nearWater:true}});
  T('holzspecht','bauklotz','vogel',{col:'#2a2a34',belly:'#f4f4f0',head:{col:'#e8302a'},snout:{type:'beak',len:.8,col:'#3a3a3a'}},'Holz-Specht','Wooden woodpecker',['kegelwald','klotzgipfel'],['holzperle','stapelameise'],'holzperle','Spechte haben eine sehr lange Zunge, die sich im Kopf um den Schädel wickelt.','Woodpeckers have a very long tongue that wraps around inside their head.',{size:.5,speed:1.1,voice:['tok-tok','kjück','tock'],pitch:700});
  T('steckschildkroete','bauklotz','schildkroete',{col:'#ffd23f',extra:{shell:'#45a0ff',plate:'#ff6fa5'}},'Steck-Schildkröte','Peg turtle',['klotzwiese','noppenfeld'],['steckblume','holzperle'],'holzperle','Schildkröten können sich nicht aus ihrem Panzer ausziehen. Er ist mit ihrer Wirbelsäule verwachsen.','Turtles cannot take off their shell. It is grown together with their backbone.',{size:.6,speed:.4,voice:['klack','hmm','pff'],pitch:200});
  T('nachziehdackel','bauklotz','hund',{col:'#c8502a',belly:'#e8803a',body:[.26,.24,.62],legs:{n:4,len:.1,r:.07},ears:{type:'floppy',len:.6}},'Nachzieh-Dackel','Pull-along dachshund',['klotzwiese','bauufer'],['bauklotz','holzperle'],'bauklotz','Dackel wurden früher gezüchtet, um in Dachsbaue zu kriechen. Darum haben sie so kurze Beine.','Dachshunds were once bred to crawl into badger burrows. That is why they have such short legs.',{size:.65,speed:1.1,voice:['wuff','wau','klapper'],pitch:460});

  /* ===== Schoner ===== */
  T('schlummerhamster','schoner','hamster',{col:'#c8b8e8',belly:'#f4f0ff'},'Schlummer-Hamster','Snooze hamster',['mystifywiese','sternfeld'],['diskette_klein','cursorkaefer'],'pixelstaub','Hamster schlafen am Tag und werden erst am Abend munter. In der Nacht laufen sie weite Strecken.','Hamsters sleep during the day and wake up in the evening. At night they run long distances.',{size:.45,speed:1.1,voice:['fiep','gähn','quiek'],pitch:1000,flags:NIGHT});
  T('koala','schoner','baer',{col:'#a0a0a8',belly:'#e8e8f0',body:[.36,.36,.36],head:{r:.3},ears:{type:'round',col:'#e8e8f0'},snout:{type:'muzzle',len:.4,col:'#3a3a44',nose:'#2a2a34'}},'Koala','Koala',['rohrwald','sternfeld'],['pixelstaub','diskette_klein'],'pixelstaub','Koalas schlafen bis zu 20 Stunden am Tag. Ihr Futter, Eukalyptusblätter, gibt nur wenig Kraft.','Koalas sleep up to 20 hours a day. Their food, eucalyptus leaves, gives them only a little energy.',{size:.65,speed:.4,voice:['grunz','brumm','gähn'],pitch:180,flags:SHY});
  T('mystifynatter','schoner','schlange',{col:'#45e0ff',belly:'#c8f8ff',stripes:{col:'#c83aff',n:5}},'Mystify-Natter','Mystify snake',['mystifywiese','labyrinthgipfel'],['cursorkaefer','diskette_klein'],'diskette_klein','Schlangen haben keine Augenlider. Ihre Augen sind von einer durchsichtigen Schuppe geschützt.','Snakes have no eyelids. Their eyes are protected by a see-through scale.',{size:.8,speed:.8,voice:['zzz','tss','hsss'],pitch:420,flags:SHY});
  T('schlaeferschnecke','schoner','schnecke',{col:'#d8d0f0',extra:{snailShell:'#4a4a8a',glow:'#c8f0ff'}},'Schläfer-Schnecke','Sleeper snail',['aquariumufer','sternfeld'],['sternenbarbe','beeren'],'pixelstaub','Schnecken können bei Trockenheit wochenlang schlafen. Kommt Regen, wachen sie wieder auf.','Snails can sleep for weeks when it is dry. When rain comes, they wake up again.',{size:.6,speed:.25,voice:['...','gähn','schlurp'],pitch:500});

  /* ===== Honigwabe ===== */
  T('honigdachs','honigwabe','baer',{col:'#2a2a2a',belly:'#2a2a2a',head:{r:.24,col:'#e8e8e0'},body:[.36,.26,.5],legs:{n:4,len:.14,r:.08}},'Honigdachs','Honey badger',['honigufer','lavendelfeld'],['wachskruemel','nektartropfen'],'wachskruemel','Der Honigdachs liebt Honig und Bienenlarven. Er gilt als eines der mutigsten Tiere der Welt.','The honey badger loves honey and bee larvae. It is known as one of the bravest animals in the world.',{size:.7,speed:1,voice:['grrr','hmpf','schnauf'],pitch:280});
  T('bienenfresser','honigwabe','vogel',{col:'#2ac8a0',belly:'#45a0ff',head:{col:'#c8602a'},tail:{type:'long',len:.8,r:.03,curl:0}},'Bienenfresser','Bee-eater',['bluetenhain','wabenwiese'],['nektartropfen','riesenbluete'],'nektartropfen','Bienenfresser schlagen Bienen auf einen Ast, bis der Stachel herausfällt. Erst dann fressen sie sie.','Bee-eaters bash bees on a branch until the stinger falls out. Only then do they eat them.',{size:.45,speed:1.4,voice:['prrüt','tschürr','pip'],pitch:900,flags:HERD});
  T('malaienbaer','honigwabe','baer',{col:'#2a2224',belly:'#2a2224',head:{r:.3,col:'#2a2224'},snout:{type:'muzzle',len:.7,col:'#e8b070'},stripes:{col:'#ffb040',n:1}},'Malaienbär','Sun bear',['bluetenhain','honigufer'],['nektartropfen','wachskruemel'],'nektartropfen','Der Malaienbär hat eine sehr lange Zunge. Damit holt er Honig aus Bienennestern in Baumhöhlen.','The sun bear has a very long tongue. It uses it to get honey out of bee nests in hollow trees.',{size:.9,speed:.7,voice:['brumm','hmm','grrr'],pitch:200,flags:SHY});
  T('bluetenschnecke','honigwabe','schnecke',{col:'#f4e8d0',extra:{snailShell:'#ffb040'}},'Blüten-Schnecke','Blossom snail',['lavendelfeld','bluetenhain'],['nektartropfen','kleeblume'],'wachskruemel','Schnecken kriechen auf einer Schleimspur. Darauf können sie sogar über eine Messerklinge kriechen, ohne sich zu verletzen.','Snails crawl on a trail of slime. On it they can even crawl along a knife edge without getting hurt.',{size:.6,speed:.25,voice:['...','hm','schlurp'],pitch:500});

  try{if(typeof I18N!=='undefined'&&I18N.extend)I18N.extend('en',EN)}catch(e){}
})();
